### ISSUE TITLE
选中一篇文章后，按"delete"没有反应

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#10]
我在文章列表栏中，如果想删除一篇文档，只能在右键菜单中选"move to trash"。

能否提供另外一种选择：按"delete"，提示是否删除，确定后删除？

**Comment by oulvhai** [comment]
快捷键是 `CMD + Delete`

**Comment by freewind** [comment]
为什么不直接支持直接按`delete`呢？

**Comment by oulvhai** [comment]
避免误操作。:D 
因为删除文档很不经常用呀，你想，我辛苦写的文档，总不会轻易删除的。对于不经常用而且是删除文档的功能，就是要设计成麻烦一点。
