### ISSUE TITLE
【建议】无法对文档库的文件夹进行排序

### ISSUE THREAD

**Issue by qzz0518** [oulvhai/MWeb-issues#1000]
无法对文档库中的文件夹进行排序，并且当一个文档库的文件夹拖拽到另一个文件夹成为子文件夹后，无论如何都不能再拖拽出来让他成为父文件夹的同级文件夹。

**Comment by oulvhai** [comment]
文档库是叫分类，是可以拖拽排序的，如果不能，那就是有 bug，另外一个也是可以的，拖拽时鼠标跟同级的垂直对齐即可，或者过一点点。如果不行，也是 bug， 请邮件联系我： coderforart@gmail.com 因为我现在测试是没问题的。
