### ISSUE TITLE
可以整合Grammarly语法检查么？

### ISSUE THREAD

**Issue by xunuo** [oulvhai/MWeb-issues#1003]
平日写英文文档较多，非常希望能在mweb中用上。

**Comment by oulvhai** [comment]
可是 https://www.grammarly.com/native/mac 这家公司？ 他们没提供 API 呀，而且也有自身的 Mac App 了。

**Comment by xunuo** [comment]
是的，它的chrome插件很好用，能研究一下么？

**Comment by xunuo** [comment]
比如我在输入框输入：

![image](https://user-images.githubusercontent.com/698455/42446953-c969d7c0-8380-11e8-9875-493f8da9041a.png)

**Comment by oulvhai** [comment]
如果他不提供 API，然后你用他的功能，是不合规则的。如果是在国外，可能会有法律风险。
