### ISSUE TITLE
编辑器中代码块背景色的处理

### ISSUE THREAD

**Issue by pzgz** [oulvhai/MWeb-issues#1009]
编辑器中代码块可以在样式内设置背景色，但设置了对于用```包围的全行代码块来说，背景色并没有充满全行，而仅仅只在有文字的地方出现，如图所示，感觉如果对于全行的代码块来说，背景色能够覆盖全行看上去会舒服很多。

![qq20180711-032600](https://user-images.githubusercontent.com/529486/42532774-80cfcb42-84ba-11e8-8f9c-b092055b0791.png)

**Comment by oulvhai** [comment]
目前还不支持这个用法 。等我计划中的编辑器功能更新吧  😂

这次新版只是个开始的感觉。。。
