### ISSUE TITLE
工具栏超链接按钮，【插入/取消连结】错别字

### ISSUE THREAD

**Issue by Geocld** [oulvhai/MWeb-issues#1010]
[![q9BIG.png](https://s1.ax2x.com/2018/07/11/q9BIG.png)](https://simimg.com/i/q9BIG)

**Comment by hstdt** [comment]
设置中还有一处类似的

![image](https://user-images.githubusercontent.com/10215098/42607353-f5f595be-85b4-11e8-873c-0774f1b941d7.png)

**Comment by ghost** [comment]
@Geocld @hstdt 好细心哦

**Comment by oulvhai** [comment]
3.1.5 已修

**Comment by ghost** [comment]
那能不能顺便优化链接这快呢
可以参考Ulysses
![image](https://user-images.githubusercontent.com/16393951/42920815-37c4c91a-8b4b-11e8-95cd-b669b3436f77.png)
![image](https://user-images.githubusercontent.com/16393951/42920838-4fe3d446-8b4b-11e8-919b-9e10cf524fe6.png)
像现在这样，在编辑模式下，把链接直接放出来，挺丑的

**Comment by ghost** [comment]
@oulvhai 如上，谢谢

**Comment by oulvhai** [comment]
@bbbran 目前 MWeb 还在坚持显示原始文本，仅是为了方便增加了显示图片的选项。但是图片的 markdown 还是保留。这个优点缺点不好说，但是暂时还不考虑改动。
