### ISSUE TITLE
请 MWeb 3 加上标题栏,像 2 一样。习惯,方便拖动

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#1012]
如图,
MWeb 3 把标题栏去掉了。
最主要是不习惯,
没有原来 MWeb 2 **醒目**, 显示当前文档标题。
另一方面,
不好**拖动**,
也是个问题。

标题是大多数软件的**传统**,
还是保留吧。

![15313307118657](https://user-images.githubusercontent.com/8175652/42589701-72481b78-8574-11e8-98c2-c9b0c2964a0c.jpg)

**Comment by ghost** [comment]
我觉得没必要呀

**Comment by linfeng365** [comment]
@bbbran 不必要的理由是?

**Comment by oulvhai** [comment]
@linfeng365 加上后太丑了，不知道怎么优化让他好看。

**Comment by ghost** [comment]
@oulvhai 对对对，加上真的是太丑了！
