### ISSUE TITLE
快速笔记Mac自带中文输入选择提示条消失

### ISSUE THREAD

**Issue by daboxu** [oulvhai/MWeb-issues#1016]
![bug](https://user-images.githubusercontent.com/3971919/42660007-bc0494f2-85de-11e8-838f-52ef9d1c0ec3.gif)

macOS High Sierra Version 10.13.6 (17G65)

**Comment by marsxxl** [comment]
我这里是正常的，macOS 10.13.6 (17G65)，MWeb 版本：3.1.4 输入法：自带中文
![](https://ws4.sinaimg.cn/large/006tKfTcly1ft83drsb4fj30uc0pctbc.jpg)

**Comment by oulvhai** [comment]
macOS 10.13.5 也正常。

**Comment by oulvhai** [comment]
或者可以试试重启 macOS 试试。我先关。

**Comment by daboxu** [comment]
@xinxiaoliang @oulvhai 谢谢confirm。发现是个神奇的问题，购买的是App Store版本。因为电脑保留了旧版本没删除先，所以苹果自动放在了Application/MWeb/localization/路径下。删除旧版本和该路径之下的新版本，再从App Store重新下载，这次自动存放在Application下问题就消失了。可能像我这样migrate过来的比较少吧，就留在这FYI。

**Comment by oulvhai** [comment]
@daboxu 旧版本是有这个问题，后来新版本修正了。可能是这个原因。
