### ISSUE TITLE
MWeb 3 点击任务列表时应用崩溃

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#1020]
假设我有如下的内容：

\### 界面
\* 创建底部完成按钮。

当光标位于“\* 创建底部完成按钮。”最右的时候，按工具栏的“任务列表/取消任务列表”。整行内容都会被删除。

当光标位于“\* 创建底部完成按钮。”中间的时候，整行内容会被删，MWeb会卡住一会儿，然后提示应用已崩溃。

MWeb 3.1.4
macOS Mojave 10.14 Beta (18A326h)

**Comment by oulvhai** [comment]
3.1.5 已修正，如果还有问题，再开。
