### ISSUE TITLE
外部模式下点击右上角本地图片传至图床卡死

### ISSUE THREAD

**Issue by cikichen** [oulvhai/MWeb-issues#1026]
外部模式下点击右上角本地图片传至图床卡死
![image](https://user-images.githubusercontent.com/1478821/42755600-76ecd46a-892b-11e8-9811-4fd74477571f.png)
必现

补充：文档库模式也一样卡死，操作就是点击本地图片传至图床，试过不配置任何图床，或者配置一个七牛，都会卡死

**Comment by oulvhai** [comment]
可否提供样例文档？感觉应该是个别文档问题。
然后如果你的 MWeb 没有升级到 3.1.4，可以升级再试试。如果已升级了，可否提供样例文档？

**Comment by cikichen** [comment]
@oulvhai 更新3.1.4后不会卡死了，但是点击上传本地图片按钮没效果，配置了七牛

**Comment by oulvhai** [comment]
参考一下帮助： https://zh.mweb.im/15303740497765.html
