### ISSUE TITLE
MWeb3快速笔记功能突然失效

### ISSUE THREAD

**Issue by xwzy** [oulvhai/MWeb-issues#1028]
前几天使用的时候，快速笔记正常并可以自动生成。

今天使用就发现点击确认后，文字消失，但是在我选择的文件夹中没有出现新的笔记。

我设置的是7天产生新的笔记。

不知道这个问题要怎么解决

**Comment by oulvhai** [comment]
可以看看偏好设置中是不是还是你原来选择的分类。
