### ISSUE TITLE
3.1.4版本本地图片上传功能有问题

### ISSUE THREAD

**Issue by cikichen** [oulvhai/MWeb-issues#1029]
![image](https://user-images.githubusercontent.com/1478821/42854741-eb1d29e4-8a6f-11e8-89e1-ae21869084a1.png)

如图，上传成功后远程地址不正确，点击复制markdown会把整个文档的复制下来

**Comment by oulvhai** [comment]
明显是没有设置域名，可以参考：https://zh.mweb.im/how_to_use_qiniu_url.html
