### ISSUE TITLE
想要调整预览时文字的大小，可是找不到入口

### ISSUE THREAD

**Issue by leonerd42** [oulvhai/MWeb-issues#103]
目前只看到sample-css.css，这个可以调整它的font-size
但是其他几个不行

**Comment by oulvhai** [comment]
其他几个是系统自带的 css,不能修改，你可以用导出 html 或者从 MWeb 包里（MWeb.app/Contents/Resources/PreviewAsset/previewCSS） 获得系统自带的 css，然后把它放到 sample-css 同一文件夹里（注意文件名不要和系统自带相同），然后在设置里点 reload。
