### ISSUE TITLE
[建议] 添加修改 UI 字体大小的功能

### ISSUE THREAD

**Issue by dong4j** [oulvhai/MWeb-issues#1030]
没人觉得 3.0 UI 的字体太大了吗? 
还有快速笔记里面的字体也不能调整, 字体非常大, 一页显示不了多少信息.
置顶功能倒是好用
最后希望快速笔记能增加调整大小的功能

**Comment by oulvhai** [comment]
主要是苹果的设计都建议都是字体偏大，所以就不知不觉调大了。
已有计划做些 UI 定制方面的功能，感谢建议，先关。
