### ISSUE TITLE
MWEB3下外部模式搜索建议

### ISSUE THREAD

**Issue by xunuo** [oulvhai/MWeb-issues#1031]
现在可以用cmd+o打开一个搜索浮层，但是没有以前好用，因为不能分区域搜索了。

另外搜索后能否点击某个tab，左侧目录可以自动定位到某一级文件夹及高亮当前文件，这样就知道我改的这个文件位于哪个位置。

**Comment by oulvhai** [comment]
如果想搜索某区域，更新到最新版本，然后选择某文件夹或者某文件，就会搜索当前引入的文件夹了。
另外的功能可以用菜单：标签 - 在导航中显示当前文档的位置 或者  Shift + CMD +J

**Comment by xunuo** [comment]
这个每次都要点一下。。。能自动么？

**Comment by oulvhai** [comment]
@xunuo 左边的只是导航，自动会跳来跳去的。
