### ISSUE TITLE
建议加入锁定标签的功能。

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#1041]
具体样式参考Safari标签右键的“固定标签页”。这个标签页会一直锁定，不会被删除。

**Comment by linfeng365** [comment]
文档,编辑后是用了查看,浏览。
设计向浏览器靠近,是自然而然的。

**Comment by oulvhai** [comment]
Safari 的网页有图标，固定了变小好识别，MWeb 的没有这个优势。
