### ISSUE TITLE
Could you make the current tab has a highlighted underline line, especially for the dark theme

### ISSUE THREAD

**Issue by 181** [oulvhai/MWeb-issues#1042]
![screen shot 2018-07-22 at 9 20 10 pm](https://user-images.githubusercontent.com/6262815/43045093-a5dca77c-8df5-11e8-9839-b38dc05cde44.png)

**Comment by linfeng365** [comment]
相关:
请 MWeb 3 加上标题栏,像 2 一样。习惯,方便拖动 · Issue #1012

**Comment by oulvhai** [comment]
This is another style for tab.
