### ISSUE TITLE
快速笔记功能，能否支持Markdown预览

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#1044]
希望可以快速查看markdown是否正确编写了，因此需要在这里的预览功能(仅支持快捷键都可以)。

![image](https://user-images.githubusercontent.com/10215098/43068466-0ce34726-8e9d-11e8-8804-522b46fa54b8.png)

**Comment by oulvhai** [comment]
感觉不需要呀，这个快速笔记的概念是随意记下，等什么时候再去整理，这样。
