### ISSUE TITLE
建议增加导出html时的侧边栏TOC功能

### ISSUE THREAD

**Issue by nameryan** [oulvhai/MWeb-issues#1045]
尽管目前已经可以使用 [TOC] 语法来生成目录，但更好看一点的方式是放在侧边栏，像gitbook这种。
找到了一种替代方案：https://github.com/i5ting/i5ting_ztree_toc
每次可以手动处理生成html，是否可以考虑将此方案集成到mweb中，在导出的时候自动生成？

**Comment by oulvhai** [comment]
加个选项应该可以。

**Comment by hedame** [comment]
+1

**Comment by hedame** [comment]
最好【大纲可折叠】  @oulvhai 

![image](https://user-images.githubusercontent.com/10413331/44615118-57eac600-a864-11e8-91df-7477756b0d88.png)

**Comment by nameryan** [comment]
@oulvhai 选项？so结论是？
