### ISSUE TITLE
改进建议：分类仅包含自身的文章，而不包含子类的文章

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#1048]
假设我有一个网站，格式类似

* foo.com
  * index.html
  * help.html
  * catalog1
    * 1.html
    * 2.html
  * catalog2
    * 1.html
    * 2.html
...

现在打开foo.com这个分类，就会显示里面所有的文件，而非只显示index.html和help.html。这实际上是一种混乱。

希望能改进为只显示各自分类下的内容，而非所有子分类的内容。

或者加一个可以这么做的选项也好。

目前的话，开启按照分类分组，可以部分解决这个问题。

MWeb 3.1.6。

**Comment by oulvhai** [comment]
分组足够了吧，仅显示先中的分类，用户会觉得怎么文档找不到了。
