### ISSUE TITLE
子分类不能单独设置排序

### ISSUE THREAD

**Issue by ucaime** [oulvhai/MWeb-issues#105]
在实际使用的时候，有时候会遇到需要某个资料库中子目录按照名称排列，有一部分又需要按照时间排列的情况。现在的根目录可以设置但子目录不可以，希望能够实现子目录排序规则设置。

**Comment by oulvhai** [comment]
子目录支持会有点太乱，会考虑加个快速设置排序的功能，比如说右键直接可以修改排序方式。

**Comment by cnfi** [comment]
非常需要这个功能！
比如按照创建时间或者修改时间的排序，会有非常大的用处。这样基本可以代替evernote了
