### ISSUE TITLE
MWeb iOS 的bug

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#1051]
Bug反馈：

iOS版MWeb目录顺序和mac版MWeb的目录顺序不一致

**Comment by oulvhai** [comment]
iOS 准备改 UI，到时一并修。

**Comment by chenzz** [comment]
我还以为都是先改bug，再close issue的。

**Comment by chenzz** [comment]
@oulvhai 建议重新打开这个issue，等修复之后再close

**Comment by randomatom** [comment]
@oulvhai 我发现500+个open 的issue里，好多几年前的问题，或者已经修复，或者到现在已经没意义了。
估计起码可以关闭300个，这样看起来清爽，也有成就感哈哈

**Comment by oulvhai** [comment]
@randomatom :D 正想有空处理一下。。

**Comment by oulvhai** [comment]
iOS 改 UI 这个未能达到理想，这个忘记改了，iOS 下个版本修。

**Comment by chenzz** [comment]
难以置信作者回复了，还以为作者失联了。。

**Comment by oulvhai** [comment]
@chenzz 失联了一段时间。目前打算明确每条 issue 将在那个版本解决，用来冶我本身的毛病。

**Comment by oulvhai** [comment]
手头上的版本 3.0.4 已修正。
