### ISSUE TITLE
【排序】所有文档 和 最近使用 有什么区别？

### ISSUE THREAD

**Issue by randomatom** [oulvhai/MWeb-issues#1059]
设置排序：「最新在前」或者「最新修改在前」。
「所有文档」 和 「最近使用」，**无法分别设置排序方式**。

这样「所有文档」 和 「最近使用」这**两项内容几乎是一样的**。
那就没有区分的意义了。

建议：
*  针对两者，排序方式「最新在前」或者「最新修改在前」可以分别设置；
* 「所有文档」默认排序为：「最新在前」
*  「最近使用」默认排序为：「最新修改在前」

**Comment by oulvhai** [comment]
有道理.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16393951/43560236-135078c8-9644-11e8-8138-dfacd9428743.png)
还有这个问题
所有文档的数量居然要比最近使用的要少？
而且最近使用的，会存最近多少天的呢？
如果全部都算最近使用，只是用排序规则来划分，那和全部文档也没啥区别吧？
建议：
要么指保留最近一段时间的，
要么直接把最近使用这个文件夹去掉
@oulvhai

**Comment by oulvhai** [comment]
@bbbran 应该不是实时更新的，感谢反馈。最近使用还是有必要的。跟所有文档不一样。

**Comment by oulvhai** [comment]
3.1.8 版本已实现此功能。
