### ISSUE TITLE
能否支持更多的UML 语法

### ISSUE THREAD

**Issue by crayygy** [oulvhai/MWeb-issues#1060]
目前仅支持 flow chart 和 sequence chart? 有点不太方便，如果能支持更多的UML的语法并且渲染就更好了，考虑一下
[mermaidjs](https://mermaidjs.github.io/)

谢谢

**Comment by crayygy** [comment]
sorry，因为我是 MWeb 2.0 用户，刚刚才发现 3.0 上已经支持了这个功能，请忽略。
另： Mac App Store 2.0 用户升级新版本必须重新购买？ 能否通过订单邮件申请一个 discount 呢？ 
谢谢。

**Comment by oulvhai** [comment]
@crayygy 2.x 版本也是支持的，应该是更强大，具体请看： https://zh.mweb.im/14689205256580.html 
另外，非常抱歉，目前没有 3.0 版本的 discount。2.x 版本将继续维护 2 到 3 年。

**Comment by crayygy** [comment]
好的， 谢谢。
