### ISSUE TITLE
MWeb 3.1.6 CPU 不断 100%

### ISSUE THREAD

**Issue by IMBlues** [oulvhai/MWeb-issues#1062]
OS：10.13.6 (17G65)
MWeb： 3.1.6

在打开侧边栏的情况下，CPU会经常跑到100%，然后恢复，然后再跑满

影响正常使用，望解决

**Comment by oulvhai** [comment]
可否再具体一点？我一直是打开侧边栏使用，没有发现这个情况。

**Comment by IMBlues** [comment]
这个现象今天下午刚出现。我不确定出现的条件是什么，我这里打开了两个mweb窗口，一个是 LiLibrary，一个是 Folder，现在关掉 Folder 的窗口，暂时无法复现出来了。我记得有一次崩溃日志，我找下，不知道是否对你排查有帮助。

**Comment by IMBlues** [comment]
![image](https://user-images.githubusercontent.com/4225292/43457432-6fce9518-94f9-11e8-848e-58300d679567.png)

基本能够确定和External Mode 相关，在 Library Mode 下 CMD + E，然后就会像上图一样CPU 跑到 100 %

External Mode 我是打开的一个 jekyll 的静态站，文件量不算大

**Comment by oulvhai** [comment]
好像未能重现，看看其他人有没有遇到过。
感谢！

**Comment by IMBlues** [comment]
好的，感谢回复 😬。

想知道是否有类似DEBUG模式，或者可以发送某些运行日志，应该会比手动复现更准确一些，毕竟每个人的系统环境差异太大了。

**Comment by oulvhai** [comment]
@IMBlues 我先研究一下。

**Comment by Tbabm** [comment]
OS：10.13.6 (17G65)
MWeb： 3.1.6

同样遇到这个问题。文档库模式没有问题，一切正常。但是在使用外部文档模式的时候：

1. 打开会卡住，CPU飙升到100%，然后正常。
2. 在双栏模式下，打开新文件，无论是在新的标签打开还是在新的窗口中打开都会先正常一两秒钟，然后卡住几秒钟， CPU飙升到100%左右，然后恢复正常。
3. 单栏模式下通过command + o打开外部文件也会出现这样的问题。

已经把MWeb2删除，并且重装过MWeb3。

目前在我的macbook上能够稳定重现，只要在在外部文档模式打开文件就一定卡住。

**Comment by oulvhai** [comment]
@Tbabm 你的引入的文件夹的情况是怎么样的？我试试能否重现。

感谢反馈。

**Comment by Tbabm** [comment]
@oulvhai 我发现我之前不小心引入了一个包含好几个大型Java项目源码（比如，Hadoop的源码）的文件夹。当我把这个文件夹移出外部模式之后，此问题就没有出现了。

**Comment by IMBlues** [comment]
@oulvhai 

我也怀疑是由于外部文件过多引起的，我打开的是一个 jekyll 站点，相较于普通的 md 目录，不论是层级还是文件肯定有点多

**Comment by IMBlues** [comment]
3.1.8 版本这个问题没有出现了，close
