### ISSUE TITLE
增加图床服务后拖拽图片至编辑器，在MWeb预览窗口中无法预览。生成的链接copy到浏览器中可以预览

### ISSUE THREAD

**Issue by julyCodeGo** [oulvhai/MWeb-issues#1064]
使用版本号3.1.6（440）
设备版本号：macOS High Sierra 10.13.6(17G65)

编辑器内的内容：
![2018-08-01 09 50 52](https://user-images.githubusercontent.com/4662685/43496531-6dd0a2ca-9570-11e8-9ffc-b39ec12b98f9.png)

预览窗口中的内容：
![2018-08-01 09 50 54](https://user-images.githubusercontent.com/4662685/43496536-71f54086-9570-11e8-9e0c-dd6c53379e8e.png)

上传图床后的生成的图片链接：

7xkl0t.com1.z0.glb.clouddn.com/15330878049278.png

7xkl0t.com1.z0.glb.clouddn.com/2018-08-01-15330878924741.png

使用图床：七牛云。并且点击验证按钮后 提示成功。
![2018-08-01 09 52 35](https://user-images.githubusercontent.com/4662685/43496585-ae501312-9570-11e8-9349-c057727f1392.png)

求助！

**Comment by uclort** [comment]
加前缀 `http` or` https`
*例如*
http://7xkl0t.com1.z0.glb.clouddn.com/15330878049278.png

> MWeb 里添加图床的时候绑定域名那里填写 `http://7xkl0t.com1.z0.glb.clouddn.com/`

**Comment by julyCodeGo** [comment]
@mTerminal  Hi,我尝试了下，可以预览了。谢谢你！
