### ISSUE TITLE
在 2018  rMBP 上能 100% 重现窗口花屏现象

### ISSUE THREAD

**Issue by jinleili** [oulvhai/MWeb-issues#1065]
现象：只要有某个软件的窗口在 MWeb 之上，MWeb 的编辑窗口及侧边样列表就会出现花屏现象
运行环境：2018  rMBP， macOS Hight Sierra 10.13.6

**Comment by oulvhai** [comment]
感觉比较有可能是 2018 rmbp 的驱动 bug。

**Comment by jinleili** [comment]
今天苹果针对 2018 版发布了更新了，确实没有再现花屏现象了

**Comment by hktalent** [comment]
2018mac pro真多非常垃圾啊，我也遇到若干的问题，但是家里其他的老款的air就没有问题
