### ISSUE TITLE
bug: 七牛传图 copy 到的地址有误

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#1068]
七牛传图 `copy` 到的地址:
`15101411852817.jpghttp://ovtzx06ib.bkt.clouddn.com/`

正确应该是:
http://ovtzx06ib.bkt.clouddn.com/15101411852817.jpg

**Comment by oulvhai** [comment]
看情况是配置错误 ，感觉是把域名填到处理代码那里了。 配置检查一下。
