### ISSUE TITLE
快捷键建议

### ISSUE THREAD

**Issue by iHTCboy** [oulvhai/MWeb-issues#1069]
希望可以增加一下快捷键，打开当前编辑的文档所在的目录！！！！程序员在这里先感谢！

**Comment by randomatom** [comment]
你可能是想 对当前文件做额外处理吧？
我在另外一个issue里，提了一个建议，增加「自定义命令」。作者说可能会加进去。
这应该可以对当前文档，扩展功能。

**Comment by oulvhai** [comment]
@iHTCboy 快捷键是 Shift + CMD + J 

在 Actions  这个菜单下面。

**Comment by iHTCboy** [comment]
@randomatom  对的，编辑完后，想把文档更新到git上啊

**Comment by iHTCboy** [comment]
@oulvhai 不是想定位到文档位置，是想打开文档所在位置，然后同步到git啊

**Comment by randomatom** [comment]
@iHTCboy 
mweb的目录是固定的。
我自己写了一个计划任务脚本，每天定时自动将docs目录所有变更提交到git。

**Comment by iHTCboy** [comment]
@randomatom 好想法，你提醒我了，脚本的重要性！能否共享一下你的脚本？

**Comment by randomatom** [comment]
```
cd /Users/xxx/Dropbox/Apps/mweb/v3/script
python opt_md.py  # 自己写的脚本，对md文件格式优化美化，去掉冗余
python opt_img.py # 优化图片大小

cd ../

git add -A docs/*

d=`date "+%d"`
h=`date "+%h"`
if [[ `expr $d % 2` -eq 0 && $h -gt 15 ]]; then
  git add mainlib.db  # mainlib.db 每次都会有变化，没必要都提交，两天才提交一次
fi

git commit -m "`date "+%Y/%m/%d %H:%M"`"
```

用 crontab 加入定时任务

**Comment by morethink** [comment]
我是直接把文档保存到iCloud上的
