### ISSUE TITLE
文档消失的问题

### ISSUE THREAD

**Issue by ChangLiuXYZ** [oulvhai/MWeb-issues#107]
有时文字会看不见：

![image](https://cloud.githubusercontent.com/assets/12593872/12235480/14eb8684-b8af-11e5-85e2-db771d7830d7.png)

上下文：我在文档中写了好多`objc`代码块，代码块中含有#ifdef等语句。当我继续输入时，发现文字颜色不对，本应是灰绿色的代码块变成了普通文字的灰蓝色，然后点击其他文档，就发现文字都看不到了。

**Comment by oulvhai** [comment]
这个是语法解析时的 Bug， 这个 Bug 会在月底的新版修正。 目前没有非常好的解决办法。 感谢反馈！

**Comment by oulvhai** [comment]
文档文字还在的， 你可以 CMD + A 然后 CMD + C 找回。
