### ISSUE TITLE
文件过多情况时，搜索报错

### ISSUE THREAD

**Issue by Baifann** [oulvhai/MWeb-issues#1071]
目前管理的文件将近2000左右，一搜索就会报错

版本: 3.16
系统版本: macOS 10.13.6

**Comment by Baifann** [comment]
![image](https://user-images.githubusercontent.com/9654844/44014767-25f8e93c-9f00-11e8-9ac9-1936112a3910.png)

**Comment by oulvhai** [comment]
搜索 bug 应该在 3.1.8 版本修正了。
