### ISSUE TITLE
[优化]有序列表自动补全逻辑

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#1072]
当我使用`1. 1. 1. 1.`来写有序列表时，会自动帮我转换成`1. 2. 3. 4.`的样式，同时当我删除一条时(比如3)，数字并不会发生改变(还是`1. 2. 4.`而不是`1. 2. 3.`)。

这样就会导致删除时需要重新排序，很麻烦。

所以建议2种方案：

1. 完善删除时的逻辑
2. 当检测到1. 1. 1. 1. 这种方式编写有序列表时，不要自动进行转换。继续补全 1.即可

**Comment by woaidangyang** [comment]
嗯，因为这个原因我基本不用数字列表...

**Comment by oulvhai** [comment]
我手头上的版本 3.1.9 已使用 1. 完善删除时的逻辑 这个方案。
