### ISSUE TITLE
如何取消网站地址自动加链接

### ISSUE THREAD

**Issue by sdjk** [oulvhai/MWeb-issues#1074]
在编辑框写一些假的演示链接地址，但会自动生成有链接的文本。
这个可以取消吗？

**Comment by oulvhai** [comment]
应该可以加个选项。

**Comment by ghost** [comment]
这个真的可以有～

**Comment by oulvhai** [comment]
3.1.9 版本中，偏好设置 - 主题 & 样式 - 启用自动链接(Autolink) 可以启用和取消。
