### ISSUE TITLE
主题样式设置是否可以再滑动栏的基础上增加输入框

### ISSUE THREAD

**Issue by imfuxiao** [oulvhai/MWeb-issues#1075]
![image](https://user-images.githubusercontent.com/6482586/43932781-9bf086a2-9c78-11e8-8ec4-bd4bebf927f4.png)
如截图显示, 这里滑动调节想要调节到自己想要的数字, 不好控制, 如编辑行最大宽度设置, 想要滑到1000, 滑动太难控制了, 建议加入input输入框, 通过数字调节.

**Comment by oulvhai** [comment]
3.1.8 版本已改成输入框的方式了。
