### ISSUE TITLE
能否单独分离出外部模式？

### ISSUE THREAD

**Issue by 9uest** [oulvhai/MWeb-issues#1076]
基本只使用外部模式，但是每次打开都需要打开两个窗口，切换又感觉卡，可否做个独立的外部模式

这样还能减少系统压力

**Comment by woaidangyang** [comment]
非常同意！我喜欢把所有的文章储存为单个文档，这样方便管理，也方便用其他编辑器编辑。

MWeb是一个优秀的markdown编辑器，非常优秀。

**Comment by oulvhai** [comment]
@9uest @woaidangyang 可以在 MWeb  偏好设置  - 通用设置 中勾选： 启动时默认打开外部模式 ，这样的话，如果你不主动打开文档库，是不会显示的。
