### ISSUE TITLE
rename能分配一个快捷键么？

### ISSUE THREAD

**Issue by xunuo** [oulvhai/MWeb-issues#1077]
![image](https://user-images.githubusercontent.com/698455/43944884-253f293a-9c89-11e8-83bc-f367727b271e.png)

**Comment by linfeng365** [comment]
还有 Outline 的选择也给个快捷键吧。

> `Ouline`焦点到OutLine 以便上下选择,`回车`回到正文。
![screen shot 2018-08-10 at 23 15 49](https://user-images.githubusercontent.com/8175652/43966009-555d4cb8-9cf3-11e8-865d-a67ffd947e28.jpg)

**Comment by backwind1233** [comment]
@linfeng365  我记得MWeb3刚开始的时候是支持的

**Comment by oulvhai** [comment]
rename 的快捷键为： cmd + shift + r
@linfeng365 目前可以上下箭头选择

应该是 3.1.9 版本才有。
