### ISSUE TITLE
導出為epub

### ISSUE THREAD

**Issue by jason820** [oulvhai/MWeb-issues#109]
目前有導出PDF、HTML等格式，導出效果很好，但想把筆記放到手機上看，能加一個把文檔導出為epub檔的功能嗎？

或是有什麼簡單的方法可以解決。

**Comment by oulvhai** [comment]
可以用 gitbook

**Comment by younglicode** [comment]
楼上正解

**Comment by bestony** [comment]
如果能够提供对应的导出功能会方便很多，同时还在用 Ulysses 就是因为此。

不过 Ulysses 对 Markdown 语法支持似乎不太好， MWeb 复制过去显示不完全。

**Comment by oulvhai** [comment]
最新版本已实现。
