### ISSUE TITLE
嵌入的图片不好删

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#11]
如果我在文档中嵌入了一个图片，然后把光标放在它的右边，这时按`delete`无效，表现为：删除成功但马上又还原，一闪一闪的。只能先把图片包括上面的`![](imgurl)`选中，同时删除才可以

**Comment by oulvhai** [comment]
是这样的，图片只是按 markdown 标记显示。

**Comment by freewind** [comment]
能否删除一个图片时，自动删除整个`![](imgurl)` ?

**Comment by oulvhai** [comment]
不能。显示图片这个概念是按 Markdown 定义来显示，我后边会重点说明一下这个。

**Comment by freewind** [comment]
不知道是内部是如何实现的，不过我看到如果有图片，光标是可以在图片左右移动的。这样的话，是否可以判断，如果光标在图片的右边并删了图片，则把光标左边的最后一个`![](...)`删掉？

![image](https://cloud.githubusercontent.com/assets/333781/7787355/5cba7e9c-023a-11e5-8438-7c6a0f0932f2.png)

**Comment by oulvhai** [comment]
好像是可行，尝试一下看看。

**Comment by oulvhai** [comment]
嗯应该还要考虑选择了图片和标记再删除等情况。。 我先加入下个版本需求列表好了。

**Comment by oulvhai** [comment]
1.7.1 版已支持
