### ISSUE TITLE
文件库备份没有导入恢复功能

### ISSUE THREAD

**Issue by morphinewan** [oulvhai/MWeb-issues#110]
现在的app有定期备份文件库到三个不同的地方，我的问题是，如果客户的机器崩溃需要重新安装系统。或者购买了新机器，并没有TimeMachine来恢复系统。

那么我怎么从这些备份的文件库完整的恢复到之前的使用状态呢？

**Comment by oulvhai** [comment]
目前要手动处理。

以下引自 http://zh.mweb.im/help.html

要恢复备份，只要用之前备份的文件夹下的 LocalData 文件夹换到
~/Library/Containers/com.coderforart.MWeb/Data/Documents/MWeb/LocalData
即可。方法：右键文档库标题可以快速转到这个位置，然后 CMD + Q 退出 MWeb，把备份的文件夹换上，再启动 MWeb 即可。

**Comment by morphinewan** [comment]
有可能的话，能在Preferences里面加个导入或者恢复按钮做这件事情

**Comment by ghost** [comment]
2.0新版目录名不再一致
