### ISSUE TITLE
文档移动到另一个分类下，不是剪切，而是复制且关联

### ISSUE THREAD

**Issue by cnfi** [oulvhai/MWeb-issues#111]
A分类下的a文档，移动到B分类下。发现A和B分类下都有a文档，而且删除任何一个，另一个分类下的这个文档也被删除。

我建议移动就是剪切，而不是复制且关联

**Comment by oulvhai** [comment]
文档库的分类 是用来组织和归类文档的，所以一个文档可以属于多个分类。
你可以理解成博客的形式：发一篇文章时可以选择多个分类。

**Comment by oulvhai** [comment]
可能你是说拖动文档到分类的情况，这个目前的确是增加分类的效果。 然后再次拖动到相同分类，会是移除分类的效果。

这个可能不大合习惯，我其实有计划修正一下。

**Comment by cnfi** [comment]
@oulvhai 这个“增加分类”效果的交互太隐藏了，而且不太主流。大多数人（包括我），会以windows的资源管理器的交互作为标准，希望你们能考虑哈~

**Comment by oulvhai** [comment]
的确是， 所以 1.9.5 版把拖动变成移动， 按住 CMD 拖动变成增加 按住 Option 拖动为 移除。
