### ISSUE TITLE
MWeb 3.1.6 如何代码语法高亮和显示行号？

### ISSUE THREAD

**Issue by JL1829** [oulvhai/MWeb-issues#1127]
刚刚开始使用MWeb 3.1.6，使用最简单的插入代码的方式：
```
print('Hello World!')
print('Hello again')
print('I like typing this.')
print('This is fun')
print('Yay! Printing')
print("I'd much rather you 'not'")
print('I "said" do not touch this.')
```

预览的时候并没有高亮，也没有显示行数，求赐教，如何高亮和显示行数。

**Comment by JL1829** [comment]
已经解决。
给后来的新手的提示： 在Preference --->Themes---> 勾选“Enable Code Block Line number" 
代码语法高亮： 
```python

**Comment by sailnorth** [comment]
> 已经解决。
> 给后来的新手的提示： 在Preference --->Themes---> 勾选“Enable Code Block Line number"
> 代码语法高亮：

如何代码语法高亮，表示还没有找到办法呀

**Comment by fcwork** [comment]
同求

**Comment by iXinXuan** [comment]
代码高亮直接

\```matlab
% matlab 代码即可
\```
