### ISSUE TITLE
发布到WordPass 报错，看不懂（本来就看不懂），只好来求助。

### ISSUE THREAD

**Issue by wclebb** [oulvhai/MWeb-issues#114]
错误有敏感信息，我已删除。

**Comment by oulvhai** [comment]
这个好像是上传图片时出错了。 如果重试不行的话，可以看看文档中图片的情况。

**Comment by wclebb** [comment]
OK，有时间参考一下文档。
只是觉得简单一下上传图片就成这样。
有问题在来发这里或新 issue。
谢谢帮忙删敏感信息。

**Comment by oulvhai** [comment]
不客气，敏感信息其实是你的email。
我的意思其实是你的文档中的图片是否特殊或者怎么样，如果可以的话，可以截图给我看看。因为我测试了有图文的文档是可以发出去的。

**Comment by wclebb** [comment]
![C9E5641B-7CEA-4041-B1CE-F707CA6C720E.png](https://ooo.0o0.ooo/2016/01/22/56a1c6a0c2bb9.png)
好像没什么特别的。
纯粹，拉过去，就变成图片那样。

然后点右上角的分享图标，点分享到 WordPass 按默认发送（或点分类、标签都报错）。
就这样了，刚安装的，所以不太清楚。

**Comment by oulvhai** [comment]
的确没什么特别的。
我也看不出来为啥会出错。 你可以重试，不行的话，重启 MWeb， 不行的话，就删除 Wordpress 发布服务再重加试试了。 

我有空多测试看看。非常感谢！

**Comment by wclebb** [comment]
我当然试过了7、8次，均报错。
然后 CMD+Q 重开，依然报错。
看来得删除再重加试试了。

晚上试试。

**Comment by wclebb** [comment]
那个，我又来了。
@oulvhai 

上次错误的是 iMac。
所以这次换到了 MacBook Air，安装，点 WordPress.com，登陆，输入 WordPress 的密码，过。
同意，然后输入自己网站账号和密码，过。
然后显示到「发布服务」里，看起来，像是成功的。

我以为可以了。
随便写测试发布内容，就像上面的图片一样。

依然，报错。

要发到你邮件吗？
