### ISSUE TITLE
七牛云存储上传bug-文件名中有空格上传出错

### ISSUE THREAD

**Issue by zminds** [oulvhai/MWeb-issues#117]
第一张图片没有处理，有空格，在上传界面显示不正常，第二张手动去掉空格就可以上传成功了
![image](https://cloud.githubusercontent.com/assets/1445705/12535489/05ed3ca2-c2c0-11e5-93e8-31de54f4e5e2.png)
![image](https://cloud.githubusercontent.com/assets/1445705/12535491/0f907238-c2c0-11e5-922f-3e3b2a997c0b.png)
![image](https://cloud.githubusercontent.com/assets/1445705/12535493/1b438782-c2c0-11e5-8ed8-7d0b4c8964e5.png)

**Comment by oulvhai** [comment]
感谢反馈，目前所知中文也会出错，将在下一版修正。
