### ISSUE TITLE
个人作品就是TM的靠不住，作者你天天在鼓捣什么

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#1176]
你知道你这软件有多少BUG和必须要enhancement的地方吗，我现在都懒得开issue给你贴出来，反正你都不修复，你这一年更新了几次你自己心里清楚，不知道的还以为该软件已经趋于稳定了。怎么着，从mweb2换成mweb3圈骗了波钱然后没本事了？ 不想维护了就赶紧说，老子提前把markdown文件搬家！

**Comment by oulvhai** [comment]
因为个人原因，这里的 issues 我变成只看不回了。
最近事几乎算完了，正准备捡起来继续处理，就先回你这个。

1. 这里的很多 bug 和 enhancement  大都不影响基本使用，有一些标记 very high 的，是我想马上修的，只是由于上面说的个人原因，mac 版本更新没有这么频繁了。有一些是我没办法修的，有一些是我不能重现的，找不到线索。对于软件是否趋于稳定就不用更新，这点肯定不是，我觉得个人作品更新的控制大部分是看作者个人的安排的。
2. 圈或者骗钱倒是不至于吧，虽然大部分软件购买了之后会有更新，但是都是用完觉得当前版本满足需求才购买的，最多是觉得不值得而已。关于有没有本事这点，的确是没本事，我点倒是有点清晰了解了的，下面会说说。
3. MWeb 肯定是会继续更新的，最近的更新在 2 个月前，而且是会一直维护的。

下面说说个人原因
这次一大部分原因是 mweb 3 发布后，做 iOS 大版本设计时，自我怀疑，挫败感等等各种情况，感觉到抑郁症可能会复发，当时就停止一些时间做别的事，最后慢慢认清自己的情况，大大降低期望，才慢慢恢复。

这个情况也可以看到，的确如你说的，个人作品风险比较大，能达到自己期望的是非常少的。
对于 MWeb 之后及未来的情况，我也会在按自身情况和 MWeb 的清晰定位，慢慢改进，希望 MWeb 用户不要期望过高了，也就是说，突然就变得很强是没有的事。

以上，就是真实的情况。

**Comment by hedame** [comment]
@oulvhai 加油，支持你

**Comment by RubiTree** [comment]
@oulvhai 不要着急，一点一点优化，慢慢来，就很快

**Comment by ileadall42** [comment]
@oulvhai 支持你，加油，icloud同步很赞！

**Comment by ltmsyvag** [comment]
@oulvhai 现在的 MWeb 完全能满足我个人的需求，并且在目前的 markdown 编辑器市场上没有任何其他一家可以替代，即使以后不再添加任何功能，只是更新适配最新 macOS，我也会一直用下去并第一时间支持您的任何收费版本或订阅.

**Comment by cn-src** [comment]
刚开始发现 MWeb 是惊喜，现在感觉是鸡肋，旧版新版都买了，一直用不起来。

很多功能还是不错的，但感觉定位不太好，无论是定位 markdown 编辑器，还是静态博客生成工具，都没太大优势。

我就想要一个强大的外部 markdown 文件管理工具。静态博客生成我更喜欢开源项目。

我觉得作者还是多在 markdown 文件管理和编辑上多下些功夫吧。
-----------------------------------------------------------------------
至于 issues，解不解决问题是一回事，关键是好歹处理下啊！
1. 该关 issues 的关
2. 新功能，不打算做的关掉，要么投票决定，最终做不做作者自己权衡
3 . bug 按优先级修复

但问题是，好不容易提供了个 issues ，结果你都不怎么鸟。
哪怕随便回复下也行啊，都不知道你是知道还是不知道。
这样谁知道这个项目是维护还是不维护，或者想起来就维护下。

**Comment by fmewtwo** [comment]
@oulvhai  你找什么借口啊，你连基础使用问题都不修复，你还谈“不影响基本使用”、“用户期望”问题

请所有人来围观一下这个再基础不过的问题#700， 关于不能在预览模式下搜索关键字的issue光我看到的就有六七个，被标注very high的也有好几次， 有个毛用？ 我最初给你提交这个问题应该是在2017年6月份，快两年了你解决不了？ 3个月前你更新的小版本和没更新没什么两样，再之前的更新估计就是5月份的mweb3，你2018年一共更新次数不超过8次，

在预览模式下搜索关键字定位不是基础功能？编辑模式与预览模式不同步你不知道？ **markdown是用来加速写作节省时间的**，光这一点就浪费别人多少时间，你平时看网页都是在源代码界面搜索的？我就问这是不是基本使用功能，两年，你都在干什么

**Comment by ifsc01** [comment]
加油，自己最重要，千万不要让抑郁症复发

**Comment by oulvhai** [comment]
@all 

不管怎么样，的确是失联了一段时间，然后之前处理 issue 的方式也有问题。现在暂时尝试做改进。我将多花时间在上面，希望今年能还给大家一个满意的 MWeb 吧。

**Comment by ppggff** [comment]
@oulvhai 请问2.x还会继续维护么？比如bug修复之类的

**Comment by oulvhai** [comment]
@ppggff 不会修 bug，会兼容今年的 macOS 版本。也就是说如果今年在新的 macOS 上用不了，就会发布兼容新系统的更新。
