### ISSUE TITLE
使用感受

### ISSUE THREAD

**Issue by jiangyuan** [oulvhai/MWeb-issues#118]
总体来说是我想要的 markdown 编辑器，但如果能有下面几点功能就更好了。
1. 支持 hexo 静态博客生成工具，至少可以把它海量的主题吸纳过来。
2. 保存到印象笔记等地方时，应该提供在 `MWeb` 打开功能，比如“马克飞象”就有这个功能。

**Comment by oulvhai** [comment]
这两个功能不考虑做了。
