### ISSUE TITLE
【建议】iOS版有没有考虑支持Git

### ISSUE THREAD

**Issue by alan-yeh** [oulvhai/MWeb-issues#1181]
支持Git的话，可以利用GitHub或GitLab的CI功能，完成一些事情，编辑完毕后提交即可。希望作者考虑一下，谢谢

**Comment by cn-src** [comment]
估计不太可能。
只要能加个文档被修改的标记，避免不小心误触，我就哦弥陀佛了。

**Comment by ifsc01** [comment]
没啥必要，交给专业工具做不好吗

**Comment by oulvhai** [comment]
iOS 3.0.3 版本已经可以引入 Working Copy 和其它第三方文件夹，github 需求建议用 Working Copy 协作。在 “网盘文档 - 新增文件夹(底部的按钮) - 增加第三方应用的文件夹” 即可增加。

**Comment by alan-yeh** [comment]
没发现working copy，我去试试，谢谢
