### ISSUE TITLE
無法上傳圖片到 Google photos

### ISSUE THREAD

**Issue by nate12** [oulvhai/MWeb-issues#1185]
按下上傳圖片後，出現「Request failed: bad request (400) 」。

<img width="532" alt="screen shot 2019-01-17 at 22 12 28" src="https://user-images.githubusercontent.com/319484/51324239-2ab5e300-1aa5-11e9-9f74-198211a6a3db.png">

**Comment by oulvhai** [comment]
Google Photos 目前确认无法做为图床，然后原来所用可以做为图床的 picasa-web API 已确认要关掉了，公告为：https://developers.google.com/picasa-web/ 。
MWeb 将删除 Google Photos 图床功能。
