### ISSUE TITLE
编辑器主题无法显示，编辑时的内容也不显示。

### ISSUE THREAD

**Issue by 9yearfish** [oulvhai/MWeb-issues#1187]
![image](https://user-images.githubusercontent.com/11186536/51401328-6cb65600-1b85-11e9-8d9a-df7bddf8f58a.png)

之前安装了试用版，然后又删除了，在安装就变成这样了，AppStore在下最新的也是这样。

**Comment by 9yearfish** [comment]
├── iChats -> ../../../../../Documents/iChats
└── themes
    ├── EditorThemes
    ├── PreviewCSS
    └── Site


是不是因为我这`主题`都是空的的原因？

**Comment by oulvhai** [comment]
@aoxiang594 感谢反馈，这个 bug 将在下个版本修正，目前可以直接复制： app 包里的主题（ /MWeb.app/Contents/Resources/v3setup/themes/EditorThemes ）到 ~/Library/Containers/com.coderforart.MWeb3/Data/Documents/themes/EditorThemes 。
