### ISSUE TITLE
「BUG」在一篇文章里的所有GIF全都变成一个了

### ISSUE THREAD

**Issue by zhouxl** [oulvhai/MWeb-issues#1188]
**我在一篇文章里插入了6种不同的GIF，最后都变成相同的一个GIF，文件命名640**
这是一个相当严重的问题，相当于我写很多的内容，最后**MWeb**把我写的东西给删除了，是我操作不对吗？ @oulvhai

**Comment by oulvhai** [comment]
目前是：在同一文章里，文件名一样的 gif，不管插入多少次都会是同一个。
之前其实是会重命名的，但是有用户反馈说建议同文章 插入一样的图片，覆盖原来的比较合理。

你看看是不是这个问题。

**Comment by zhouxl** [comment]
好像是的
右键复制gif，最后复制的是jpg的,名字是类似这样的15479777509354/15479784639922。
如果直接拖拽,不同的gif,都是同一个文件名![640](media/15479777509354/640.gif)，但是在编辑的时候显示的git图片是不一样的,比较费解

**Comment by zhouxl** [comment]
这个可能并不是Mweb的问题，和Mac系统有关
