### ISSUE TITLE
Failed to publish to Medium :bad request(401)

### ISSUE THREAD

**Issue by MarcSteven** [oulvhai/MWeb-issues#1192]
<img width="415" alt="2019-01-28 15 05 30" src="https://user-images.githubusercontent.com/13824297/51819769-86d2ff80-230e-11e9-9719-94fa66a561cc.png">
You can see the issue as the pic ,hope fix it as soon as possible ,I have a doubt -long time no update mweb  ,does it mean you will stop updating the mac application???

**Comment by oulvhai** [comment]
I check the Medium setting page: https://medium.com/me/settings  and found Medium remove to generate the `Integration Tokens`. Maybe Medium will drop the publish API.

PS: MWeb for macOS is update to version 3.2.0 in ago.

**Comment by MarcSteven** [comment]
@oulvhai  Yeah right ,thank for your reply ,any plan to add new feature for the product ?Long time no update

**Comment by MarcSteven** [comment]
So the medium had dropped the publish API ,so close the issue.Thank for reply...

**Comment by MarcSteven** [comment]
@oulvhai  so my tips is that remove the medium options out of the application ,or it can lead a wrong sign ...Happy new year ...
