### ISSUE TITLE
点击一个category后，能否自动显示其第一篇文档的内容？

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#12]
现在的行为是：点击了别的category后，第二栏文档列表中的内容变了，但是右边编辑区的内容还是以前的，感觉很奇怪。能否直接改为显示新category中第一篇的内容？

**Comment by oulvhai** [comment]
不会这样改。 左边两栏只是管理文档的功能。

**Comment by freewind** [comment]
目前这样存在一个问题：比如我正在编辑某个文档，然后点了其它的category，结果两边的右边的内容跟左边的文章列表脱节了。如果不是仔细回想，可能不记得它是哪个category下的哪篇文章了。

这样的话，能否提供一个功能：点我点击了别的分类，左右脱节的时候，点击编辑区会自动让左边的category和文章列表定位到正确的位置？

**Comment by oulvhai** [comment]
目前提供了 recent 的功能，可以看到最近用的文档。

因为 文档库的文档是可以多选分类或不选的，所以暂时不会做这个功能。越来越觉得外部模式合适你，外部模式可以这样优化一下。我也记下了。

**Comment by freewind** [comment]
谢谢，可能跟我之前一直用sublime+markdown插件写博客有关吧。我刚尝试了一下外部模式，感觉不错。你的程序太好了，加油

**Comment by oulvhai** [comment]
:D MWeb 做了两种模式也是希望一般情况下只用 MWeb 就能解决需求。
