### ISSUE TITLE
可否增加FTP发布站点

### ISSUE THREAD

**Issue by lvtao-net** [oulvhai/MWeb-issues#120]
生成的静态网站，不想使用云存储和一些其它站点的生成，而是有自己的FTP空间，有独立的域名，这样生成的站点能配置FTP自动上传上去不是更方便吗？

**Comment by oulvhai** [comment]
一个 App 集成功能越多， Bug 就越多，目前 MWeb 的功能已经算是多的了， FTP 同步部分就不做了，因为目前有非常好的专业的这类工具，比如说 GoodSync
