### ISSUE TITLE
渲染数学公式出现问题

### ISSUE THREAD

**Issue by ghost** [oulvhai/MWeb-issues#123]
![123](https://cloud.githubusercontent.com/assets/14837648/12828209/635184a0-cbbe-11e5-8c3a-b0b5599323c5.png)

**Comment by oulvhai** [comment]
原 markdown 文本 贴过来 我试试？所用预览 样式也可以说明一下， 现在看不出来是什么情况的。

**Comment by ghost** [comment]
我查找一下问题,是我的预览css出问题了，已经解决了，支持你的应用
