### ISSUE TITLE
发布到印象笔记报错

### ISSUE THREAD

**Issue by mouzwang** [oulvhai/MWeb-issues#1244]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "e" must be declared.}

发布到印象笔记时报如上的错，请问一下是为什么？

**Comment by grothen** [comment]
感觉跟我一样，包含本地文件链接的就会有问题，如果有的话你去掉试试看

**Comment by grothen** [comment]
如果解决起来的复杂的话可以先加个是否上传本地文件的选项

**Comment by mouzwang** [comment]
> 如果解决起来的复杂的话可以先加个是否上传本地文件的选项

好的，蟹蟹
