### ISSUE TITLE
MWeb的预览窗口问题

### ISSUE THREAD

**Issue by atone** [oulvhai/MWeb-issues#126]
使用Cmd+4快捷键打开的预览窗口绿色按钮是+号，无法全屏，也无法放到分屏模式中。
使用Cmd+R打开的预览窗口的绿色按钮可以全屏，也可以放到分屏模式中。
两种方式打开的预览窗口行为不一致，希望能够统一。

**Comment by oulvhai** [comment]
CMD + 4 预览 和 CMD + R 预览这类问题，目前正在做一个统一的、简单点的方案。月底估计能用上了。

**Comment by atone** [comment]
好的，感谢！
