### ISSUE TITLE
iPadOS / iOS13: Pick Up Folder from iCloud not possible

### ISSUE THREAD

**Issue by PhilKuer** [oulvhai/MWeb-issues#1264]
MWeb for iOS 3.1.2 build 462

Not able to pick a folder from iCloud or else where, while using Third Party Folder.

Folders are not selectable.

**Comment by Leeestephen** [comment]
Same problem in version 3.1.5 build 488 (on iPadOS)

[update] this problem is solved in version 3.1.6.

**Comment by Leeestephen** [comment]
Update: this problem is solved in version 3.1.6
