### ISSUE TITLE
一个问题和另外两个不知道是不是问题的问题

### ISSUE THREAD

**Issue by ghost** [oulvhai/MWeb-issues#128]
1. 用Mweb写博客，在文章中插入一张图片，渲染。后因种种原因删除换图，渲染，生成的博客文件里media图片并没有变化，仍然是原图片。手动删除原图片后重新build正常。
2. `<!-- more -->`这种代码一定要上下行空格才能有效吗？感觉心好累=。=！
3. 代码高亮能否支持自定义？有的语言好像不能完全支持出来，或者说显示的颜色我不喜欢。

**Comment by oulvhai** [comment]
1. 感谢反馈
2. `<!-- more -->` 是 HTML 的语法，MWeb 所用的解析库规定必须上下空行（只上空行也行）
3. 目前所用的是 http://highlightjs.org， 静态博客的模板中我并没有下载全部的语言支持，可以自行替换原来的。如果不喜欢，也可以换别的。

**Comment by ghost** [comment]
3.Solved.
thx~
