### ISSUE TITLE
希望可以有使用工作空间文件夹之类的机制

### ISSUE THREAD

**Issue by albertgh** [oulvhai/MWeb-issues#129]
多设备间协作不是很方便啊。

以工作空间管理的话，就可以通过 `Dropbox` 或者 `坚果云` 等同步盘服务来自行同步了。

现在的备份机制，只能说单设备单纯做个备份。

**Comment by oulvhai** [comment]
备份是这样，然后文档库不支持同步。 文档库目前是单设备的。同步请用外部模式引入 Dropbox 文件夹。
