### ISSUE TITLE
突然无法添加，修改及保存任何文件了

### ISSUE THREAD

**Issue by jinleili** [oulvhai/MWeb-issues#1291]
突然无法添加，修改及保存任何文件了，查看了文件的读写权限是有的,重启电脑也没效。
我用 vscode 去打开编辑这个文件也是能正常操作的，但是在 MWeb 修改了内容无保存就提示：您没有将文件“xxx.md”存储到文件夹“docs”中的权限。点击【+】按钮也没有任何反应，添加不了文件。
MWeb 版本： 3.3.3.
操作系统：macOS 10.15

**Comment by oulvhai** [comment]
可以试试把文档库复制到新地方，然后使用 偏好设置 - 文档库 - 选择现有文档库，选择新的地方试试。

**Comment by jinleili** [comment]
换个地方并重启电脑后好了，看来是 macOS  的 bug
