### ISSUE TITLE
能否增加一个copy html with inline style的功能？

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#13]
现在提供了一个`copy as html`的功能，它copy出来的内容是纯的html，没有样式信息。

能否提供一个功能 `copy as html with inline style`，把当前的样式信息（比如颜色、缩进）inline到每个html tag中？

我想要这样的功能是因为我们有时候要写一些文档，但是那边的在线编辑器不支持markdown（但可以插入html）。通过这个功能，我能把在这边编辑好的好看的效果直接粘过去。

为什么要`inline style`呢？是因为那种在线编辑器会过滤掉`<style>...</style>`标签，只接受inline的html tag，比如: `<p style="color:red">...</p>`

**Comment by oulvhai** [comment]
这个功能好像不大不好做 :D
