### ISSUE TITLE
在MWeb中直接点击连接, 跳转似乎有些问题

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#131]
直接上个例子

```
[MWeb-issues](https://github.com/oulvhai/MWeb-issues/issues "MWeb-issues")

[MWeb-issues][2]

[2]: https://github.com/oulvhai/MWeb-issues/issues "MWeb-issues"
```

![2016-02-23 9 33 08](https://cloud.githubusercontent.com/assets/12368943/13238788/76dfe25e-da10-11e5-99e3-2cf7e8292e18.png)
这两种写法, 在MWeb中直接点击MWeb-issue, 试图跳转到链接的时候, "MWeb-issues"以及前边的空格会被encode之后增加到链接后边, 变成这样`https://github.com/oulvhai/MWeb-issues/issues%20%22MWeb-issues%22`

---
### 试了下, 以下几种方法是OK的.

1 用尖括号将链接包起来

```
[2]: <https://github.com/oulvhai/MWeb-issues/issues> "MWeb-issues"
```

2 最后的title信息, 换到下一行

```
[2]: <https://github.com/oulvhai/MWeb-issues/issues>
"MWeb-issues"
```

看了下Markdown的语法, 不加尖括号也是可以的.

**Comment by oulvhai** [comment]
1.9.7 版已修正链接点击错误问题。
