### ISSUE TITLE
发布两三次之后，会消失

### ISSUE THREAD

**Issue by wclebb** [oulvhai/MWeb-issues#132]
或许又是我个人的个例，但还是说明一下。
发布后是成功的，再发布基本就是修改的状态。

然后两三次后再点发布，消失了。
几次下来也是没显示。
 MWeb 是发布状态的。

无奈只好上博客，发现内容是草稿状态。

额……

**Comment by oulvhai** [comment]
你这个是说发布到那？ Wordpress? Wordpress.com? Blogger ?

**Comment by wclebb** [comment]
哦不好意思，忘记补充了。
-个人博客，VPS，wordpress.com方式连上去。

**Comment by wclebb** [comment]
确认过，两三次后发布不了，怀疑我自己不小心改了草稿，但MWeb 依然是发布状态，不懂了……

**Comment by oulvhai** [comment]
那应该是 wordpress.org 这个吧。 .com 博客服务商的。我测试看这个。

**Comment by wclebb** [comment]
汗，不好意思……
是wordpress.org……

**Comment by wclebb** [comment]
刚去看了，是 org，com 跟你反馈过，连不上去，于是改用 org 了。

**Comment by oulvhai** [comment]
嗯嗯，
我刚刚测试过程和结果为：

发布状态为 发布，发布成功，再修改文档，再发布几次也是没问题，然后状态改为 草稿再发布，也是会正确进草稿。再试几次也是一样。 
我进后台修改文章为草稿，然后 MWeb 的状态为 发布，再发布，会变为发布状态，也就是说还是正确的。

我暂时没有测试出什么问题。等有时间我再研究研究了。

**Comment by wclebb** [comment]
哎，我这……哎。
用的是 com 发布。

——————————
我反复尝试复现。
发现正文好像不受影响，测试：正文写1、2、3、4、5……

然后标题并不是网站的问题，而是 MWeb 本身貌似获取的问题。
假设我之前写的是 Adobe CC 系列。
发现标题不达意，修改 Adobe CC PhotoShop。

发布时会获取第一#的标题。
但后来会时不时获取原有的标题，例如 Adobe CC 系列，这个在 MWeb 发布时发布框内标题会自动获取之前的标题，因为点发布按钮的 Wordpress，然后出来一瞬间能看到是 Adobe CC PhotoShop，然后不到一秒改为 Adobe CC 系列。

正文应该不受影响。
——————————————
发布后消失暂时没法复现，反复尝试没消失。摊手，不知道为什么。难道我那边MacBook 和 iMac 有不同的环境？……

**Comment by oulvhai** [comment]
经确认，好像 1.9.5 版及以下有这个 Bug，1.9.7 版修正了，所以才会有这个问题吧？ 感谢如此详细的测试！

**Comment by wclebb** [comment]
这样啊，我回去升级看看。谢谢你的回复。
