### ISSUE TITLE
MWeb 4.2.2  mathjax 的换行问题

### ISSUE THREAD

**Issue by lincolnred8** [oulvhai/MWeb-issues#1322]
![image](https://user-images.githubusercontent.com/31056595/145716304-67e299a1-a0ef-43ea-b70f-97c642a9ca00.png)

看过之前的 https://github.com/oulvhai/MWeb-issues/issues/558，但是在我的电脑上还是不好用。 

```
$$
  \begin{matrix}
   1 & 2 & 3  \\\
   4 & 5 & 6  \\\
   7 & 8 & 9  \\\
  \end{matrix} 
$$
```

同时 在 mathjax.org 上却好用。 

![image](https://user-images.githubusercontent.com/31056595/145716355-83fc909e-258e-4424-bb16-5ed4782c82b0.png)

**Comment by lincolnred8** [comment]
![image](https://user-images.githubusercontent.com/31056595/145716592-49803f45-7a58-46b8-93e3-3f48cf1863be.png)
![image](https://user-images.githubusercontent.com/31056595/145716595-22def656-da98-4488-9db5-2cad4c6a37ec.png)


我猜，是换行出现了问题了吗？

**Comment by oulvhai** [comment]
mweb 4.x 使用的是 mathjax v3，需要使用 \begin{align} \end{align}

```math
\begin{align}
a_{11}& =b_{11}\\\\
  a_{22}& =b_{22}+c_{22}
\end{align}
```

参考： https://github.com/mathjax/MathJax/issues/2312

**Comment by lincolnred8** [comment]
谢谢
