### ISSUE TITLE
iCloud 同步失效

### ISSUE THREAD

**Issue by VinceFanZ** [oulvhai/MWeb-issues#1325]
已经设置成存储到 iCloud 了，但是过几天再打开就不显示 iCloud 存储的内容。

<img width="937" alt="image" src="https://github.com/oulvhai/MWeb-issues/assets/7631809/8a32e361-9f58-422b-ae78-2f0403189197">

**Comment by oulvhai** [comment]
你当前显示的是外部文件夹模式的窗口，使用菜单：视图 - 打开文档库就可以了。
