### ISSUE TITLE
Gif导入和图片粘贴

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#135]
剪切板中的gif图,貌似无法快速导入进Mweb,只能另存为之后手动导入.提供的两种粘贴模式都无法粘贴成gif图.
另外,如果剪切板中是PNG图,command+v是jpg图,必须按command+shift+v,逻辑有点蛋疼,能否直接粘贴出来就是png格式的呢.(不过我还是挺喜欢这个功能,可以快速把各种类型的图快速转换成PNG图)

**Comment by oulvhai** [comment]
经研究，剪切板 gif 这个目前暂时无解。

**Comment by hstdt** [comment]
@oulvhai  
那么拖拽是否可行呢.目前可以拖拽chrome中的文字和超链接,但是无法拖拽过来图片(有+提示了,但是无效果)

**Comment by oulvhai** [comment]
@hstdt  经研究 拖拽的功能，竟然顺便把 chrome 和 Safari 中 CMD + V 粘贴 gif 也解决了。感谢反馈！
