### ISSUE TITLE
能否发布到自己写的博客应用中

### ISSUE THREAD

**Issue by cocbin** [oulvhai/MWeb-issues#136]
目前好像只看到一些比较有名的博客系统能使用，如果我的博客系统是自己写的，我能否发布到自己写的博客上，目前只能先导出为html，然后再发布

**Comment by oulvhai** [comment]
自己写的博客系统要支持 MetaWeblog API 才行。 
然后为什么只支持这个？ 是因为不知道博客除了 MetaWeblog API 外，还有什么发布的标准 API。
