### ISSUE TITLE
导出为docx的时格式问题

### ISSUE THREAD

**Issue by jealone** [oulvhai/MWeb-issues#138]
- 导出为docx的时候没有格式效果，建议导出到docx时候，导出为预览的效果
- 表格中建议能够解析todo list

**Comment by oulvhai** [comment]
1. docx 功能非常原始，然而改进的话，非常困难，所以长期可能都会这样。
2. Markdown 就是简单和易读易写，目前所用解析库是有标准的，不能随便改。
