### ISSUE TITLE
幻灯片模式

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#14]
经常需要给同事写幻灯片，能否提供这样的支持？

比如我写成：

```

# hello

---

println("Hello")

```

预览的时候就是一个两页的幻灯片，可以用方向键或者鼠标切换。

这个功能很实用，有很多开源的东西可以实现。最好能允许自定义样式，这样可以定义一个适合自己或自己公司的样式，长期使用。

**Comment by oulvhai** [comment]
这个我列表后期功能增强考虑。
暂时不会提供支持这个 :D 。

**Comment by oulvhai** [comment]
确认不考虑此功能，可借助其他工具。
