### ISSUE TITLE
发布到印象笔记之后TOC、顺序图、流程图等都没有显示

### ISSUE THREAD

**Issue by samposn** [oulvhai/MWeb-issues#140]
发布到印象笔记之后TOC、顺序图、流程图等都没有显示，下一个更新，能否增加这个功能啊！

**Comment by kamyuentse** [comment]
公式显示也不正常
<img width="744" alt="screen shot 2016-06-22 at 13 50 38" src="https://cloud.githubusercontent.com/assets/15538025/16255927/c8de89c4-3880-11e6-8d72-9a238538c08c.png">

**Comment by colorado666** [comment]
感谢作者开发出这么好的工具，支持，并安利同事们用啦。

有两个建议：
1、能否开发一个命令行工具，用来打开文件或者目录？
2、打开的目录浏览器能否做成树状的？ 现在的 mweb 是左边一栏是目录，右边一栏是文件下的内容，不够直观，而且挺占据屏幕空间的。

谢谢！

**Comment by oulvhai** [comment]
@shujun 
1. open -a MWeb doc.md  这样可以打开文件，打开目录不支持
2. 外部模式倒是可以做成这样，但是目前要跟文档库交互一致，所以暂时先三栏式了。
