### ISSUE TITLE
请问hugo静态网站生成器应该怎么设置？

### ISSUE THREAD

**Issue by laishulu** [oulvhai/MWeb-issues#141]
hugo（http://gohugo.io/）项目的目录结构如图所示
![hugo的目录结构](https://cloud.githubusercontent.com/assets/1224321/13530025/3a312a3c-e25a-11e5-80e0-972a02ebde13.png)
这种情况下应该如何设置mweb导入的外部文件夹呢？
是否有方法为**本地文件夹**和**url前缀**分别设置形成映射呢？

**Comment by oulvhai** [comment]
main 下有没有 docs 文件夹？ 我猜生成静态页时会把 main 下的 docs 或者其它不属于 gohugo 的文件夹都复制到 static 下，所以你现在的样子，加一张图片，然后生成一下试试。这时图片应该是保存在 main 下的 media 下，你就看看 media 文件夹会不会被复制到 static 下。 如果不是，那 docs 应该会被复制到 static 下的。 

反正具体规则时：main 下的文件夹，生成时如果会被复制到 static 下，那么就用这个文件夹做为 图片文件夹名称 即可。

**Comment by laishulu** [comment]
_main_ 是我的display name，项目里面叫 _content_，里面是纯粹的markdown，static目录是和它平行的目录。在编译的时候，markdown生成的网页，及static下面的所有文件会被copy到平行的public目录下面。
我现在暂且用 _软链接_ （将static/docs目录链接到 content下面）绕过了，但可能hugo在编译的时候针对docs目录下的文件非markdown会报错，我没试过，但总归不是个正常的方法。

**Comment by oulvhai** [comment]
这样就简单了，你按下图的设置即可。注意红线的设置。

![snip20160305_6](https://cloud.githubusercontent.com/assets/2174294/13547033/93d8d2e6-e2fb-11e5-8284-89b76fb03802.png)

这样 main 下的所有 markdown 文档如果插入图片，图片都会被复制到 static/docs 下，我亲测没问题的。你可以试试。

**Comment by laishulu** [comment]
问题在于：插入的url应该是 `/docs/some_image.jpg` 时hugo编译的页面才能正常工作。你给的方案里面是 `/static/docs/some_image.jpg`, 而且得注意是`/docs/....`,不是`docs/...`.

**Comment by oulvhai** [comment]
这倒是难了，目前 MWeb 不支持这种情况。
因为如果你 “保存插入的图片的文件夹名称” 设置为 docs 的话，docs 会在 main 下， 然后生成时 docs 又不会被复制到 public。
难道 main 下就没有被复制到 public 下的文件夹吗？ 或者不能配置？ 我对hugo 和 go 都不了解。如果没有，那就没办法了。

提示一下：如果插入的图片的保存位置如果设为：绝对位置，那么 url 就会是 /docs/...

**Comment by laishulu** [comment]
我那个work around反正如果不编译hugo仅仅在mweb中编辑的话是没问题的。
但如果mweb要官方支持的话，可以让 _保存投入的文件夹名称_ 支持 `../some_dir` 这样，并且可以定制 `url prefix`，那样就可以完成映射了。

**Comment by oulvhai** [comment]
做软件加功能一般是要考虑通用性，如果官方加这个支持，好像就只针对 hugo （不知道其他的静态博客使用方式如何）。 再就是：其实不能设置为 ../some_dir， 因为引入的文件夹之上的文件夹 MWeb 都是没有读写的权限的。

目前的这个问题，建议的方案是为 hugo 加个插件或配置，可以复制 main 下的某文件夹到 public。

**Comment by laishulu** [comment]
符号链接恰好不被hugo支持，直接skip了，所以没有任何问题 :-)

```
ERROR: 2016/03/05 Symbolic links for directories not supported, skipping '/Users/xxx/notes/main/content/docs'
```

**Comment by oulvhai** [comment]
:D 以后有人问 hugo ，我先直接丢这个网址，让他用你的方法了。
