### ISSUE TITLE
制表符渲染对齐异常

### ISSUE THREAD

**Issue by ficapy** [oulvhai/MWeb-issues#142]
**如下图:**
![](https://ficapy.b0.upaiyun.com/capture/2016_03_07_00_03_25.png)
![](https://ficapy.b0.upaiyun.com/capture/2016_03_07_00_04_37.png)

**Comment by oulvhai** [comment]
制表符用来对齐是不准的，可以勾选 偏好设置 - 通用设置 - 用 4 个空格代替 Tab 就会按你所想的样子了。
