### ISSUE TITLE
外部模式在某些情况下无法打开

### ISSUE THREAD

**Issue by dyx13** [oulvhai/MWeb-issues#143]
如果打开的窗口只有 Library 窗口，并且外部文件库中没有包含任何文件，在这种情况下似乎无法打开外部模式。

具体经过：今天第一次使用外部模式，无论用快捷键或者 View-Open External 都无法打开。后来使用 MWeb 打开了一个不在 Library 的文件后，外部模式才能打开。在外部模式中添加几个文件夹之后，即使没有打开的其它非 Library 文件的窗口，外部模式也能正常工作。

**Comment by gexiao** [comment]
哭晕，今天试了好久怎么都打不开外部模式，还以为是我自己操作问题，对文档理解有误。竟然真的是 bug。

**Comment by mrLuyao** [comment]
这个问题在3.1.6依然存在。第一次安装mweb 3之后，无论是用快捷键还是 视图-打开外部模式，抑或右键md文件用mweb打开，都无法启用外部模式。只有在mweb中，文件-打开 ，打开一个md文件之后才能正常使用外部模式。
