### ISSUE TITLE
待办任务, 打钩, md 源文件不会改变

### ISSUE THREAD

**Issue by fengqi** [oulvhai/MWeb-issues#144]
比如这个待办, 在预览状态, 如果给某一项打钩, 切换到源码状态, 觉得自动改为 `[x]` 会好点
![680fc6b8e0a9799bab100f1b23a3625f001](https://cloud.githubusercontent.com/assets/517708/13623923/1d169ade-e5e5-11e5-982d-14e26240a4f9.jpg)

版本 1.9.7 (196)

**Comment by oulvhai** [comment]
预览的 任务列表中的 打勾应该是要被禁用的。下个版本预览中的任务表示将不能打勾了。
MWeb 一切是以源文件为标准的。

感谢！

**Comment by fengqi** [comment]
嗯, 这样也行.
