### ISSUE TITLE
快捷键切换视图问题

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#145]
`Command+4`切换出预览视图之后, 再使用`Command+3`, `Command+2`, `Command+1`预览视图都会在

感觉不太对. 比如, `Command+1`在**视图**菜单里显示的是"仅显示编辑器"

**Comment by oulvhai** [comment]
CMD + 1 这个下个版本会修正为 仅显示编辑器
CMD + 2/3 的话，保留预览视图 是因为某些时候会需要如此（有些朋友屏幕大，可以用四栏视图）
感谢！
