### ISSUE TITLE
编辑器&预览视图的左右两栏有时发现不能位置正好对应

### ISSUE THREAD

**Issue by wtianyi** [oulvhai/MWeb-issues#147]
RT，相差接近一屏，还是蛮多的。这个文档里行比较长，可能是原因吧。
![screen-shot-2016-03-09-at-11 58 41-pm](https://cloud.githubusercontent.com/assets/5387775/13641712/7b58c0d0-e654-11e5-84d2-6233bf8bd2d4.png)

[文档地址](https://drive.google.com/file/d/0B7IQmDpGRquSOG9BMHJLYXdZX2s/view?usp=sharing)

**Comment by oulvhai** [comment]
好长的文档！
这个的确不太准的，我虽然很想优化这个，但是目前还无从下手 :D

**Comment by wtianyi** [comment]
啊酱_(:з」∠)_
好奇多问一下现在是怎么实现的？

**Comment by oulvhai** [comment]
两边高度对比一下，算出个 大概位置呗。
这种事原生的 Markdown 编辑器基本没有太好的办法做好的，但是 WebKit 类这方面可以做得非常好。

**Comment by wtianyi** [comment]
这样啊～

**Comment by selfboot** [comment]
@oulvhai  [markdown-scroll-sync](https://github.com/mark-hahn/markdown-scroll-sync) 这方面做的也很不错啊

**Comment by oulvhai** [comment]
@xuelangZF 这个是 JS 类的，无法用于 MWeb

**Comment by selfboot** [comment]
@oulvhai  不懂 JS，不知道它是用什么方法做到的，不过它的方法应该可以移植的吧。
