### ISSUE TITLE
上传至evernote报异常

### ISSUE THREAD

**Issue by Niclas3** [oulvhai/MWeb-issues#149]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo=0x610000460b40 {NSLocalizedDescription=Content of submitted note was malformed, parameter=Error processing document: Invalid a href attribute:}

**Comment by oulvhai** [comment]
这个错误是说： 你的 markdown 文档中有一个连结 (href) 的 网址不被 印象笔记支持。 通常是这个连结 不是以 http 开头。 比如说 `[连结](index.html)` 这种可能印象笔记就不支持。
