### ISSUE TITLE
文章列表栏中的标题能否去掉前面的#

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#15]
感觉有点奇怪，每次看到都要犹豫一下：这到底是标题还是正文

**Comment by oulvhai** [comment]
我倒是想去掉。

目前的问题是，去掉后一开始，光标会飞到最边上。目前还没有很好的解决办法，除非去掉打纯中文字不会跳动这个功能。

**Comment by oulvhai** [comment]
误解了，这个已修正。
