### ISSUE TITLE
能否提供带内联css的预览模式

### ISSUE THREAD

**Issue by dongxuanlb** [oulvhai/MWeb-issues#151]
如果我直接全选预览内容, 是没有css样式的, 生成的html文件css也是外联的.

期望能够复制内联css的, 可以方便我直接复制到邮件, word等地方.

**Comment by cnfi** [comment]
我也遇到这个问题，复制到外面，样式丢失

**Comment by oulvhai** [comment]
目前的解决办法是自定义一个预览样式，并用 JS 把样式都变为内联的（也就是 html 标签直接加 style 的）。 首先第一步是参考： http://zh.mweb.im/14689205256580.html 这个网址，自定义预览样式。
另外第二步是参考：https://github.com/cyhhao/html2enml 这个库的 transCssByAllStyle() 方法，把页面内的 `<style>` 去掉，并变成 内联 的样式。 要注意的是自定义样式时，样式都要写在 `<style>` 内，不要用 `<link>` 的方式引入。

这样的话，再用复制的方法复制这个预览样式时，应该会带样式了。

如果需要的是纯带样式的 html，可以在 预览的样式内加一个 `<textarea>` 和一个按钮，点按钮，就把 内联的样式的  html 显示在 textarea 中，这样就可以复制了。
