### ISSUE TITLE
（重要问题）删除了图片网站生成中还会出现

### ISSUE THREAD

**Issue by xunuo** [oulvhai/MWeb-issues#152]
（重要问题）删除了图片网站生成中还会出现，重要问题。

**Comment by oulvhai** [comment]
拖入的图片正确的删除方法是：点文章右上角 “扳手” 按钮，Media 那个标签，然后从里边删除图片。然后生成网站的时候要用：Clear & Rebuild Site 就不会有问题了。

**Comment by xunuo** [comment]
但是以前有些图片已经看不到了呃。

**Comment by xunuo** [comment]
哦 我知道如何使用了，谢谢！
