### ISSUE TITLE
如何一键切换成远程图片

### ISSUE THREAD

**Issue by cocbin** [oulvhai/MWeb-issues#155]
我将图片上传到图床上面了，我想要直接复制markdown用于发布博客，但是需要直接复制的markdown是用的本地图片

**Comment by oulvhai** [comment]
图床上传界面有个复制markdown按钮，点这个即可

**Comment by zminds** [comment]
@oulvhai  如果在外部模式下  移走当前引入的文件夹，到别的机器上用mweb重新引入，之前上传过七牛的那些图片地址信息应该还在吧，这个复制markdown按钮应该也还能用吧，感觉这些信息是存在.MwebMetaData里的data文件中的

**Comment by oulvhai** [comment]
是的，不过如果文件改名或者移动到另外的文件夹，就不行了。 而且 OS X 下暂时找不到除了文件路径外识别一个文件的方法。
