### ISSUE TITLE
双击文件项打开外部编辑器

### ISSUE THREAD

**Issue by laishulu** [oulvhai/MWeb-issues#156]
当前好像是双击重新打开一个窗口，请问。。。。这个有什么意义呢？
对程序员来说，很可能将mweb当成管理/预览及轻度编辑工具，但是重度编辑时会切换到vim等上面去。
双击文件项直接调用外部编辑器打开，会是个不错的选择，marked2/marboo这种预览工具都是这种操作方式。

**Comment by oulvhai** [comment]
双击打开新窗口其实是一些朋友的建议，外部编辑器支持会在之后的版本提供。感谢建议。

**Comment by laishulu** [comment]
issue的响应很迅速，
不愧好几个朋友在我的推荐下买了你的软件。
赞一个！

**Comment by oulvhai** [comment]
非常感谢支持！

**Comment by oulvhai** [comment]
2.0 版可以在编辑器内右键，选择外部编辑器打开。

**Comment by laishulu** [comment]
在2.0版中，是在编辑器内部右键，选择外部编辑器打开。
这对于想用外部编辑器来打开的人来说，需要经过：
1. 点击左边的列表栏，在mweb编辑中打开文件
2. 在mweb编辑器中右键，用外部编辑器打开

可否在列表栏中也增加 **打开方式** 选项呢？在一般的资源管理器中，比如windows的explorer，mac的finder中，也都有 **打开方式** 这个选项。

当然 **mweb编辑器中右键用外部编辑器打开** 可保留。免得在mweb编辑器中，遇到比较复杂的情况，想用别的编辑器打开，还得重新在左边列表栏中定位。

**Comment by oulvhai** [comment]
@chenhouwu 列表右键如果加上这个的话，好像会显得 MWeb 对自己的编辑器没有信心。。然后这个应该不是常用功能，有很多方式可以达到，比如说列表中先右键，在 finder 中显示，然后再打开。

**Comment by laishulu** [comment]
> 好像会显得 MWeb 对自己的编辑器没有信心

哈哈，你赢了

**Comment by gdshen** [comment]
是不是只有外部模式下可以使用外部编辑器，文档库模式下无法调用外部编辑器？
