### ISSUE TITLE
关于数据同步

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#157]
有个关于数据同步的想法.

现在`MWeb`并不支持不同设备之间的数据同步(传统那种同步到云端, 再从云端拉回)

那么, 可不可以像`MWeb`本身提供的发布服务一样, 提供一个用户可自定义的服务, 在点击发布之后, 将数据原样发送到指定服务的地址, 自行实现数据存储的功能. 当点击同步(pull)的时候, 再从配置的服务器端, 拉回数据, 覆盖相同ID的数据?

**Comment by oulvhai** [comment]
正在开发的 2.0 版将重写一下文档库的数据库，让它更小一点，然后支持自定义文档库的保存位置和打开其它文档库，这样就可以自由同步和使用了。

**Comment by KrabsWong** [comment]
赞~

**Comment by littledu** [comment]
坐等 2.0 更新，什么都好，就差同步了。
