### ISSUE TITLE
独立文档（非文档库，非外部目录）中插入图片不正常。

### ISSUE THREAD

**Issue by laishulu** [oulvhai/MWeb-issues#158]
使用场景：
1. 偶尔编辑单独的md文件。而不是项目式的文档库或外部目录式的管理。
2. 将mweb当成预览工具，代替marked2。

问题：
1. 如果原始md文件有个图片 `![](./result.png)`，其它的编辑器会从当前md文件所在目录下找出图片并正确显示。而mweb不能正常显示。
2. 如果我将当前md所在的目录下的 `result.png` 文件拖动到md文件中，则mweb会直接显示一个**完整的绝对路径名**，既不是 `![](./result.png)` 这种md标记，也不是**相对路径**，当文件拷贝到别处或者目录改名时，绝对路径很显然会出问题。

**Comment by oulvhai** [comment]
这个是由于 Sandbox 的原因，具体可以参考： http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html 开始那段。

**Comment by laishulu** [comment]
但是，marked2也是MAS版的，可以正常工作。
另外：即使mweb不能正常显示，也可以生成**相对路径**的md标记：`![](./result.png)`

**Comment by oulvhai** [comment]
有可能 marked 向 apple 请求了 读 documents 下的文档的权限，这个问题 MWeb 应该会用另外的方式解决。
另外的感谢建议！这的确可以优化更好！

**Comment by laishulu** [comment]
哦。刚才我重新测试了一下：
- marked2不是请求了documents目录，是任意目录。
- marked2第一次打开文档的时候，会弹出对话框，要求 **allow access**。

这个也是可以接受的，毕竟只要一次授权，以后就不用麻烦了。

**Comment by oulvhai** [comment]
原来如此，The Unarchiver 也是这样做的，MWeb 其实也正计划这样做。非常感谢测试！
