### ISSUE TITLE
流程图超过右边距生成图片不完整

### ISSUE THREAD

**Issue by allenzerg001** [oulvhai/MWeb-issues#159]
![如图所示](http://7xr00o.com1.z0.glb.clouddn.com/mweb_bug_report.png)

**Comment by oulvhai** [comment]
看不到图。
流程图是用第三方 JS 库画的，现在看来好像是久不维护了，下个版本将不建议使用。

**Comment by allenzerg001** [comment]
![](http://7xr00o.com1.z0.glb.clouddn.com/mweb_bug_report.png)
 不知道现在能不能看到
图片地址在这里：http://7xr00o.com1.z0.glb.clouddn.com/mweb_bug_report.png

**Comment by oulvhai** [comment]
能看到了，目前生成的图片大小是写死的，流程图太宽的确会被切掉。我再考虑一下要不要改为可以设置宽度或者先预览再生成。

**Comment by allenzerg001** [comment]
谢谢
