### ISSUE TITLE
调整文章的顺序

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#16]
有时候有这样的情况，比如我要写几篇文章跟同一个主题有关系，写了几篇，然后中间又插入了一篇别的，再接着上次的主题写，这样看起来就有点别扭了，比如:

```
hello world5
hello world4
中间插了一篇别的
hello world3
hello world2
hello world1
```

想调整一下位置，但不知道怎么调整，只能删了再新建一篇？

**Comment by oulvhai** [comment]
文档库中的话如图设置：
![image](https://cloud.githubusercontent.com/assets/2174294/7787380/8d21faa0-023b-11e5-9fa8-3518816740d4.png)
就可以拖动排序文档了。

外部模式可以设置成按名称排序。

![image](https://cloud.githubusercontent.com/assets/2174294/7787382/ae20fc92-023b-11e5-92d6-03330739c85e.png)

**Comment by freewind** [comment]
原来`custom`的意思是这个。。。谢谢

**Comment by callmewhy** [comment]
custom 模式有个 bug ，今天终于摸索清楚了。。。拖拽的时候必须先选定一个 title ，然后拖拽才有用，如果是 ABCDE ，选中 B ，然后把 C 拖到 D 下面，是没有反应的。。。而且会有一些奇怪的表现
