### ISSUE TITLE
新版本的回车换行符粘贴后错乱

### ISSUE THREAD

**Issue by tankery** [oulvhai/MWeb-issues#163]
最近刚刚更新的版本 `Version 1.9.9 (203)` 非常难用。某些编辑器复制过来的代码换行符（Unix 标准的`\n`），会变成`<U+2028>`，导致不显示换行。

而当我复制一串不包含换行的文字时，却自行添加了一个换行。

我使用的编辑器是Android Studio IDE 的编辑器。

下面是一些测试：
Sublime Text -> MWeb 正常
Android Studio -> Sublime Text 正常
Android Studio -> MWeb 回车错乱

**Comment by oulvhai** [comment]
这个之前有位朋友反馈过。
然后我用 1.9.8 之前的版本测试，也是会回车错乱。Android Studio 贴到 VIM 和 Sublime 3 都是会回车错乱。 虽然测试的跟你的不大一样，但是解决办法倒是有了。

就是**取消选中** Android Studio 的 Copy as rich text by default 这个选项。

PS: 1.9.8 版之上其实是小改了粘贴的行为，之前是先看是否有文本，有则贴入，现在是改成先判定是否有富文本，有则转成文本贴入。 目前已经改为原来的 1.9.7 版的行为了，但是要 2.0 版才会一并发布这个修正。

非常感谢！

**Comment by tankery** [comment]
好的，那目前只能暂时禁用富文本了。期待2.0！

**Comment by limao123** [comment]
你好，请问Xcode有禁用富文件的选项吗？如果有能否告知一下在哪里？

**Comment by lidinghao** [comment]
同样遇到了这个问题，代码复制过来，换行丢失了
