### ISSUE TITLE
请求显示行号的功能

### ISSUE THREAD

**Issue by zheeeng** [oulvhai/MWeb-issues#166]

**Comment by owenzhao** [comment]
这个是等待实现的功能吗？我今天也找了好久没找到。

**Comment by oulvhai** [comment]
@owenzhao enhancement 标签就是这个意思吧。

**Comment by owenzhao** [comment]
@oulvhai 3月底提的，现在都8月底了。希望能尽快实现！😂

**Comment by oulvhai** [comment]
@owenzhao 你看看有多少 enhancement 就知道了 :D， 很多都不会实现的。

**Comment by owenzhao** [comment]
我尝试自己解决这个问题，我使用的是octopress的模板。我在模板的`octopress.js`发现有这样一段代码。

``` js
function addCodeLineNumbers() {
  if (navigator.appName === 'Microsoft Internet Explorer') { return; }
  $('div.gist-highlight').each(function(code) {
    var tableStart = '<table><tbody><tr><td class="gutter">',
        lineNumbers = '<pre class="line-numbers">',
        tableMiddle = '</pre></td><td class="code">',
        tableEnd = '</td></tr></tbody></table>',
        count = $('.line', code).length;
    for (var i=1;i<=count; i++) {
      lineNumbers += '<span class="line-number">'+i+'</span>\n';
    }
    var table = tableStart + lineNumbers + tableMiddle + '<pre>'+$('pre', code).html()+'</pre>' + tableEnd;
    $(code).html(table);
  });
}
```

那是不是说插入的gist是有行号的？在MWeb里要用什么样的语法插入gist？

**Comment by owenzhao** [comment]
这里有提到如何插入行号的办法，我看不懂，你可以参考一下。

https://groups.google.com/forum/#!topic/highlightjs/0EgfCzhDdJs

**Comment by oulvhai** [comment]
@owenzhao 其实你那连结我看过，然而这并不是官方的方案，奇怪的是：我竟然没有找到比较好的第三方的解决方案。

markdown 支持 html，所以插入 gist 要用 gist 提供的 embed code， 好像是一行 js

**Comment by owenzhao** [comment]
highlightjs官方说不支持行号是故意的。因为它觉得自己这个就是语法加量的功能，没必要画蛇添足，而且他认为加行号的功能用别的方式实现更简单。

我之前在用的MacDown支持行号，但是它是用别的语法加量库。

**Comment by oulvhai** [comment]
@owenzhao 官方不支持可以理解，我奇怪的是，竟然没有一个关于这功能的第三方库。
Macdown 所用的库的确不同，其实你可以在自定义预览，然后不加 {{head}} 这个语法，这样 MWeb 就不会加上 MWeb 本身所用的高亮库了。

**Comment by oulvhai** [comment]
最新版本已实现。

**Comment by owenzhao** [comment]
> 最新版本已实现。

说是已经实现了。但是要如何使用呢？我升级到了最新的3.2.0版。但是生成的网站的代码还是没有行号的啊。

如果说已经实现的，是只有MWeb的预览里能看，这个早就在3.0里就可以了。
