### ISSUE TITLE
能否增加命令行模式？通过命令打开md文件或者目录，和sublime一样

### ISSUE THREAD

**Issue by zheeeng** [oulvhai/MWeb-issues#167]
增加软链:(/usr/local/bin 在$PATH下)
cd /usr/local/bin
ln -s /Applications/MWeb.app/Contents/XXXXXX/bin/mweb  mweb

打开文件或者目录（不需要额外options）
mweb ~/README.md
mweb ~/Diary

**Comment by oulvhai** [comment]
目前可以用 open -a MWeb doc.md  这种命令打开。
