### ISSUE TITLE
文档库模式下,md文件的互相跳转

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#169]
提一些想法,仅供参考.
文档库模式下:
md文件生成一个内部链接(比如MWeb://123456.md),点击之后,可以从文档A跳到文档B,用作文档之间的互相引用,然后还能有个前进后退按钮,在先后打开的几个文档之间进行快速切换

**Comment by oulvhai** [comment]
2.0 版可以用 编辑 - 复制文档连结，也可以在列表中多选，右键 - 复制文档连结

**Comment by gatspy** [comment]
找了好久这个问题的解决方法，终于找到了。感觉mweb好强大啊。好多功能都没发掘出来啊。
官方文档是不是要增强下啊。

**Comment by oulvhai** [comment]
@gatspy 的确是，早就想弄这个了，只是最近比较长的时间有另外的事，连正常更新都不能保证，好在快结束了。
