### ISSUE TITLE
可否支持icloud，或者怎么设置icloud，公司和家里怎么实现同步

### ISSUE THREAD

**Issue by xun404** [oulvhai/MWeb-issues#175]
非常好用，支持
家里公司各买一套正版，实在是太好用了
如果能支持云端备份（icloud或七牛等）就更棒了
谢谢

**Comment by xun404** [comment]
目前主要存在的问题是，恢复需要手动点，并且会互相覆盖，并不是增量

**Comment by oulvhai** [comment]
文档库目前不支持同步，2.0 版将使用可以自定文档库的位置的方法支持网盘同步。
目前同步需求建议使用外部模式 /

**Comment by kingzeus** [comment]
你可以把备份目录直接设置到 iCloud 目录，然后再恢复出来。

我是用 git 来管理目录

**Comment by hstdt** [comment]
目前我也是把MWeb的内容给群晖NAS的SVN插件进行管理,SVN服务器放在家里,想什么时候使用数据都行,而且不限电脑甚至操作系统(虽然也不用做到这个地步).

顺带也可以用群晖的Web服务器功能放MWeb建立的网站,自建网站.

**Comment by oulvhai** [comment]
2.0 中偏好设置 - 通用设置中 可以将文档库另存到指定的位置。
