### ISSUE TITLE
在列表中，敲击 Tab 键会换行？

### ISSUE THREAD

**Issue by ChangLiuXYZ** [oulvhai/MWeb-issues#178]
一个列表，比如：
- hello
- world

在 hello 后边敲击几次 Tab 键就会换行，可是并没有达到我的页面宽度。

**Comment by oulvhai** [comment]
Tab 的宽度的确不大准的，可以选中 偏好设置 - 通用设置中的 用 空格代替 Tab，这样就准确了。
