### ISSUE TITLE
“外部模式”下如何移动文件和目录？

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#18]
在Library模式下可以移动文件和目录，但是在外部模式下不支持。

能否提供该功能，因为在编写的过程中，对目录重新组织是很常见的需求，不然还得在finder里操作，太麻烦了

**Comment by oulvhai** [comment]
:D 自然会提供，具体看某版会提供了。

**Comment by freewind** [comment]
期待！

**Comment by oulvhai** [comment]
1.7.1 版已移动、重新组织目录等等。
