### ISSUE TITLE
集成 PlantUML

### ISSUE THREAD

**Issue by kingzeus** [oulvhai/MWeb-issues#181]
试了下流程图和顺序图，发现简单 demo 用着蛮好。但是一复杂就扛不住了。另外入股哦生成的图很大，预览也有问题。

后来，找了个画图的工具 plantUML ，用着蛮好。直接渲染成图片，而不是用 js 即时绘制的，兼容性会好很多。另外 plantUML 支持的类型更多，建议集成。

**Comment by oulvhai** [comment]
PlantUML 上上周我整合了一下，发现他生成图的速度太慢，满足不了边写边预览的需求，所以有可能会做成一个辅助的功能，也就是可以填入 PlantUML，然后生成图片，把图片插入 markdown 中。

**Comment by kingzeus** [comment]
我一直在用 android studio 的 plantuml 插件.也是实时预览的.好像没觉得特别慢

**Comment by oulvhai** [comment]
可能是我使用方式不对。 不过纯图更好兼容性，毕竟 iOS 不可能跑 plantuml 的。

**Comment by oulvhai** [comment]
请参考：http://zh.mweb.im/14689205256580.html
