### ISSUE TITLE
MAC下WORD文字复制，怎么变成图片贴过来了

### ISSUE THREAD

**Issue by SLTECH** [oulvhai/MWeb-issues#183]
Mac OSX EI Capitan 10.11.4
WORD为Office 365订阅，15.21.1（160411）
外部文档库模式，一粘贴自动变成图片了，还在media下生成这张图片……
呃，这个功能有时候挺有用的，但是经常我只是想贴点文字过来而已，不带这么歧视WORD的吧。囧。

**Comment by oulvhai** [comment]
下个版本我修正一下，非常感谢反馈！

**Comment by oulvhai** [comment]
暂时可以用 编辑 - 粘贴为纯文本

**Comment by smilehu2019** [comment]
我粘到其他word还是图片
