### ISSUE TITLE
能不能考虑加入清理media目录内的无用文件功能。

### ISSUE THREAD

**Issue by mu3517** [oulvhai/MWeb-issues#185]
在写作中经常替换或者更新图片。会导致media无限制扩大也没法手动清理。

**Comment by oulvhai** [comment]
可以用 右键图片 - 彻底删除图片 功能删除一下的吧？ 毕竟有些图片虽然没在正文用到，但是可以用在别的地方，比如说静态网站的生成上。所以整个全部清理就不好了。

**Comment by oulvhai** [comment]
不过可以考虑列出来的时候，标记一下那些图没在文档中引用到。
