### ISSUE TITLE
 不能自动保存文档

### ISSUE THREAD

**Issue by MarcSteven** [oulvhai/MWeb-issues#186]
写了一万字的东西，突然Dock崩溃，然后回来以后文档没有了，已哭晕在厕所，如果软件增加自动保存功能的话就比较好，Mac本上的备忘录都有自动保存功能，为何这款软件没有呢？难道是作者没有想到吗？？希望赶紧修复这个问题。。。。。。不然真的太致命。。。。

**Comment by oulvhai** [comment]
有自动保存的。正常使用的自动保存就不说了。
连用 CMD + N 新增，未保存到硬盘里。然后用 活动管理器 强制退出 MWeb 。然后再打开也会回来。

所以不知道你的用法是如何？

**Comment by MarcSteven** [comment]
反正不知是发生了什么奇怪的事情，东西反正是没有了，今天又出现了一个让人无法忍受的事情，之前编辑好的文档我用这个App尝试打开的时候被告知“MWeb打不开这种类型的文件”，我用Mac自带的文本编辑器是可以打开的，求解决。。。。。。。。。。。打扰您了。。。。

**Comment by oulvhai** [comment]
不像textedit，MWeb只持打开.txt .md .markdown 这几种扩展名的文档，其他或者无扩展名的都是不支持的。

**Comment by MarcSteven** [comment]
If it can support more formats of text,that's great.....When click ⬆️ and then press Weibo,finally post it.The pic MWeb created was so fuzzy....If you can improve the effective ,that's very good .Just my advice,sorry to disturb your job .....Good nite,learn  more from your info.....Good luck to you..........Now you can close it........

**Comment by oulvhai** [comment]
发到微薄图片模糊这个是用系统的 API，然后被强压缩了。这个暂时的解决方案是先导出为图片，然后再手动上传到 微薄。

**Comment by MarcSteven** [comment]
@oulvhai  Ok,I know the resolution to solve it ,but it's not the best choice.Now I have a doubt about it.....I wanna insert one pic into the document ,but the icon of inserting is gray,perhaps it's invalid ....How to deal with this issue.
Thank you so much......

**Comment by oulvhai** [comment]
直接用 CMD + N 新增或者直接打开的文档并不支持插入图片。

外部模式推荐的使用方式是支持的，具体可以参考 http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html 这个文章。

当然，文档库可以直接插入。

**Comment by MarcSteven** [comment]
Thank you so much,sorry to disturb your time.Have a good holiday.....
