### ISSUE TITLE
表格文本不换行

### ISSUE THREAD

**Issue by runfriends** [oulvhai/MWeb-issues#187]
表格单元格内文本太长，不会自动换行；导出成pdf，文本被截断了。
导出word表格没有了，只导出了表格内的文本

**Comment by qmkCamel** [comment]
遇到同样的问题，感觉列表不换行的话有点鸡肋。

**Comment by GerrieWell** [comment]
为何快一年了还没解决- -

**Comment by qmkCamel** [comment]
体谅下独立开发者吧

**Comment by GerrieWell** [comment]
需要这个功能可以用typora代替下先哈.排版还漂亮.

**Comment by oulvhai** [comment]
@GerrieWell 导出word表格 这功能目前还不知道要怎么做 :D，估计是不会出来了。下个版本尝试优化一下 PDF 表格试试。
@qmkCamel :D 感谢！
