### ISSUE TITLE
代码和有序列表混合预览显示错误

### ISSUE THREAD

**Issue by fengqi** [oulvhai/MWeb-issues#189]
比如这样:

```
1. item1
2. item2

code
code

3. item3
```

后面的 item3 就会从1开始显示, 而不是3

**Comment by oulvhai** [comment]
选中 code 部份，然后 按 Tab 键，就会得到你想要的结果。

**Comment by fengqi** [comment]
试过了, 也用过 ``` 这样 三个反向引号的, 主要问题不是 code 样式问题, 是有序列表问题, 前面的数字不对

**Comment by oulvhai** [comment]
请参考：

<img width="1118" alt="screen shot 2016-05-04 at 7 06 00" src="https://cloud.githubusercontent.com/assets/2174294/15012450/4bc4fbe2-122b-11e6-8d68-eb4e1b569b1f.png">

**Comment by fengqi** [comment]
出来了, 好像是就算用 三个 ` 包起来 也要用 tab 缩进下才行, 不包的话要缩进两次...这...

**Comment by oulvhai** [comment]
所用的库的语法是这样，其实 Markdown 都不建议这种复杂的写法，毕竟这种写法，各种库的支持都不同。:D
可以用 

```
### 1. item 1

### 2. item 2

### 3. item 3
```

这种稳定，全部都支持的写法。

**Comment by fengqi** [comment]
这实际上是化身为小标题了, 暂时能满足需求, 不过这个 bug 还算是存在的...

**Comment by oulvhai** [comment]
这个不是 bug，是所用的解析库 需求语法是这样写。

**Comment by KrabsWong** [comment]
这个应该算是`Markdown`语法的范畴了. 语法要求如此.

[Markdown列表](http://www.appinn.com/markdown/#list) 其中有对列表中使用`code`的说明

<img width="973" alt="2016-05-05 1 42 35" src="https://cloud.githubusercontent.com/assets/12368943/15036857/7a1a4c80-12c7-11e6-8892-2031a1459a10.png">

**Comment by fengqi** [comment]
Ok 明白了 还真没那么细致看
