### ISSUE TITLE
“双击目录”展开

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#19]
当前双击目录的行为是“编辑该目录”，比如重命名什么的。如果想展开，必须要去点左边的那个小三角，比较累。

考虑到展示目录是比较常见的需求，而重命名比较少，能否把重命名放到context menu里？而双击是展开？

**Comment by oulvhai** [comment]
暂时不考虑这个，因为 Lirbray 当初也是这样。然后修改会改变用户习惯，不修改也影响不大。

**Comment by freewind** [comment]
“小三角”点得太累了，另外我发现context menu里已经提供了Edit这个选项。

不过说到用户习惯，双击跳出“修改菜单”这个做法还是比较少的。我觉得可以问问其他的用户，也许不少人希望改呢。

**Comment by oulvhai** [comment]
还好吧，点一次就可以了，不要关就好。

双击在 OS X 中其实也很少用。
这个 issues 一直不关好了。有这需求就留言。

**Comment by freewind** [comment]
那有没有“展开全部”这样的功能？看我的目录结构，就知道我点得有多辛苦了：

![image](https://cloud.githubusercontent.com/assets/333781/7787526/d6b33a3c-0243-11e5-94df-5d80ab0ff116.png)

**Comment by oulvhai** [comment]
全部展开有规划到的。
外部模式引入文件夹现在是首次发布。
