### ISSUE TITLE
MathJax 公式没能实时更新

### ISSUE THREAD

**Issue by haoliplus** [oulvhai/MWeb-issues#190]
我在输入类似下面的公式时
$$
f(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}
$$

出现了下图这种情况，指数上的x没能更新。需要再输入些东西才能更新。我遇见的几次都是在输入指数时，不知是不是有关。
![](http://i.imgur.com/seJSaQo.png)

**Comment by oulvhai** [comment]
这部分的确是，还需要优化一下。
