### ISSUE TITLE
Chrome 浏览器无法正常预览生成网站。

### ISSUE THREAD

**Issue by haoliplus** [oulvhai/MWeb-issues#194]
测试了 Safari 没有问题。

Chrome 在之前没有打开浏览器时没问题，如果 Chrome本身是在运行，MWeb 选择预览时只会把Chrome打开到前台，而不是打开对应的网址。禁用所有插件后同样存在问题，所以与插件无关。

**Comment by ablipan** [comment]
这是 Chrome 的问题，当 Chrome 已打开时，无法用命令打开本地 html 文件，只能在浏览器中使用 `file:///` 或者将文件拖进 Chrome。

**Comment by haoliplus** [comment]
你好，
我想，你所说的并不是关键的原因。我测试了一下，在我的MWeb静态网站输出目录手动创建了一个test.html。然后用alfred的方式打开它（都是第三方文件，来模拟一下这个过程），是可以用Chrome打开的。而MWeb生成的文件还是打不开。

就我看来，两者唯一的区别在于MWeb生成的HTML文件有着@标记(用ls能看到)，似乎是增加了什么属性，我不是太清楚具体含义。但总之，我觉得这个问题应该是可以解决的。
下面的git是我录制下来的过程 ![](http://i.imgur.com/Hlzagud.gif)

On Wed, May 4, 2016 at 17:26, Lipan notifications@github.com wrote:
这是 Chrome 的问题，当 Chrome 已打开时，无法用命令打开本地 html 文件，只能在浏览器中使用 file:/// 或者将文件拖进 Chrome。

**Comment by haoliplus** [comment]
补一下图，邮件回复不支持Markdown
![](http://i.imgur.com/Hlzagud.gif)

**Comment by haoliplus** [comment]
另外，更直接点的话。如果我们把生成的静态网站的主页文件 index.html 替换为我们自己创建的文件，完全同样的内容 (除了没有@ 标记) 。然后用MWeb 跳过生成，直接预览，是能够在Chrome 里打开主页的。
所以，应该是 @ 标记的文件的某些属性影响了这个过程才对。

**Comment by oulvhai** [comment]
@ 标记是什么鬼，我从来未手动增加过什么。我用 ls 是也没看到 @ 标记，是要加什么参数？
然后我的常用浏览器就是 chrome，在我的机器用 chrome 是正常预览的。

目前预览这个功能是用 Apple 建议的 API 做的，alfred 不知道是不是用这个 API，或者也有可能 alfred 是非 sandbox 的原因。

**Comment by haoliplus** [comment]
是这种，我的MWeb生成的html都有呀...
![](http://i.imgur.com/Qbdo7fh.png)

API 应该是一样的，因为 Alfred 和 MWeb 的行为是一致的，只要文件属性里有 @ 就没能打开，只要没有就可以打开。

**Comment by oulvhai** [comment]
明白了，我研究看看，感谢啦！

**Comment by haoliplus** [comment]
@oulvhai 
只要index.html没有@可以打开。

清理重新生成也有，而且之前改掉没有@的index.html被替换成有@的了...

我刚刚查了下，有人说这是 OS X 的文件扩展信息，可以用xattr查看。
然后，这些MWeb生成的文件在xattr命令下显示的是

> com.apple.TextEncoding
> com.apple.quarantine

都是Apple家的。希望这有帮助。

**Comment by haoliplus** [comment]
写了一个 Alfred 3 的 [Workflow](https://github.com/DarryO/alfred3-mweb-workflow) 来暂时解决这个问题。

除了使用xattr删除@扩展属性，本地预览网站，同时还可以用来上传至 Git 服务器，以及搜索静态网站生成链接用来文章间的相互引用(#169)。

因为用了 Alfred 3 的一点特性，不兼容2，不过脚本很简单，很容易改。有相同需要的同学可以参考一下。

示例
![](http://i.imgur.com/S4ZXYAC.gif)

**Comment by oulvhai** [comment]
2.0 版好像是解决了，还有问题请重开。
