### ISSUE TITLE
导出到HTML和编辑模式的一点建议

### ISSUE THREAD

**Issue by jokemmy** [oulvhai/MWeb-issues#195]
1. 我平时都写一些文档会发给我同事看，一般内网使用。
   能不能给个选项将JS运行后最终的结果放到一个HTML中，而不是打开HTML再去加载第三方的JS库。
2. CMD + 1/2/3/4 记录下来，上次打开什么模式下次打开记住

**Comment by oulvhai** [comment]
1. 目前 高亮的 JS 是放到 HTML 内的。 流程图的不是， MathJax 只能用 线上的，也算是放在 一个 HTML 中。所以你不要用 流程图就可以了。
2. 目前应该只有 预览不会记一下，下个版本有计划修正这个。

**Comment by jokemmy** [comment]
我是前端程序员这个前端的东西我可能洁癖比较深呵呵，
作为程序员写文档流程图还是必不可少的，有时候装装B也是很有用的呵呵
流程图和MathJax的话，可以把预览生成后的SVG复制出来，，我稍微试了试应该没什么问题。

**Comment by oulvhai** [comment]
这个功能在计划中，只是还没有做。
