### ISSUE TITLE
到处html的模版能修改么？

### ISSUE THREAD

**Issue by xun404** [oulvhai/MWeb-issues#197]
想重新定制下导出html的格式，这个是通过模版生成的还是写死在代码里的？如果是模版，能给下具体的路径么？不是简单的修改css，谢谢啦

**Comment by oulvhai** [comment]
[github_new.zip](https://github.com/oulvhai/MWeb-issues/files/252051/github_new.zip)

上面这个就是定制导出 html 格式 的办法，把这个解压后放到 样式的文件夹，再到偏好设置里 reload 一下，就会生效了。还可以参考 http://zh.mweb.im/mweb-v1.2-release-zh.html 这个网址。

**Comment by oulvhai** [comment]
新版有修改，可以直接将旧的 文件夹移到自定预览上，然后删除同名的 css 即可。

新的可参考：http://zh.mweb.im/14689205256580.html
