### ISSUE TITLE
【EXTERNAL SOURCES】左下角 + 号功能有问题

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#2]
点击

```
+ New Floder
```

无反应
-  如图

![qq20150517-1 2x](https://cloud.githubusercontent.com/assets/2178683/7670531/1ac783f4-fcdb-11e4-9eda-bc25bdae7c09.png)
## PS
- 已知bug，请更新新版本以后close

**Comment by oulvhai** [comment]
github 好讚！！
