### ISSUE TITLE
Feature Request - Multiple Notes / Notes status support

### ISSUE THREAD

**Issue by xakraz** [oulvhai/MWeb-issues#20]
Hello @oulvhai !

First, thank you for you App, it's beautiful and exactly what I was looking for !

I don't know if it is the "best" (or the one you want) way to reach you about such things ...

So, I use your App a lot as note editor.
In my daily usage workflow, I may open multiple notes because they are related to the work I am doing.
And then I loose the context and the notes I was editing and forgot to save ...

I have multiple ideas on how to deal with it from a user point of view:
- Add a colored bullet on the Note Name in the dedicated pannel
- or Add Tabs support

**Comment by oulvhai** [comment]
I'll think about Tabs support.

Thanks!

**Comment by oulvhai** [comment]
Tabs support added in version 2.0
