### ISSUE TITLE
默认显示方式问题

### ISSUE THREAD

**Issue by Sir0xb** [oulvhai/MWeb-issues#202]
我现在使用的是外部模式，有没有能设置默认启动显示方式。我想启动的时候就是预览模式，编辑的时候在Cmd＋r

**Comment by oulvhai** [comment]
1. 偏好设置 - 通用设置 里有
2. 暂无

**Comment by yeafel** [comment]
需求：可设置，启动的时候默认是预览模式。
原因：需要经常查看预览模式的文档情况，编辑模式的MarkDown语法信息非常干扰阅读，因为目前我已经用MWeb做我的文档管理中心了，希望可以考虑。
