### ISSUE TITLE
「编辑器&预览」模式下两边不会同步滚动

### ISSUE THREAD

**Issue by iCasture** [oulvhai/MWeb-issues#203]
滚动左边的编辑器，右边的预览会同步滚动，但是反过来就不会。这是个 BUG 还是有意为之？

另外，帮助 - 发送建议 为啥不可用？点了啥反应都没有。

**Comment by oulvhai** [comment]
这个是有意为之，因为预览目前没有绝对准确，如果在不准确的情况下，会有需求滚动预览而编辑器要不动。 发送建议是已知 bug，感谢反馈！
