### ISSUE TITLE
连接七牛出现如此问题，反复尝试都是这样的结果。

### ISSUE THREAD

**Issue by evanzhu2013** [oulvhai/MWeb-issues#205]
<img width="407" alt="2016-05-18 21 05 31" src="https://cloud.githubusercontent.com/assets/7533756/15359662/f071ab74-1d3c-11e6-9db2-581b577354af.png">

已经购买正版支持开发者，比Ulysses功能丰富很多，而且便宜很多。Macbook上最好用的Markdown编辑器，特别是用来写博客。连接七牛，出现了如图的问题，一个医学生，不知道如何处理这种问题。

参照开发者配置说明建立了账号，还是尝试失败。

 系统： OSX EI Capitan 10.11.5 
配置： Macbook Pro 2013年末

**Comment by oulvhai** [comment]
unauthorized (401) 一般是 Access Key 和 Secret Key 两个填错。

**Comment by evanzhu2013** [comment]
Thx. Done.
