### ISSUE TITLE
目录可以生成在左侧吗

### ISSUE THREAD

**Issue by FoghostCn** [oulvhai/MWeb-issues#206]
目录随屏幕滚动不是太方便，可以选择把目录固定在左侧吗？

**Comment by oulvhai** [comment]
是说预览？

**Comment by FoghostCn** [comment]
导出为html的时候，
我现在用MWeb写文档，用起来很赞，就是目录在最上面不太方便

**Comment by potatoker** [comment]
@oulvhai 目录信息在右侧可以打开，可是不知道怎么关掉。。。求问怎么关掉啊。。。。

<img width="310" alt="screen shot 2016-07-28 at 9 59 20 am" src="https://cloud.githubusercontent.com/assets/5286501/17198702/fadf67c8-54a9-11e6-8592-63376caec6d0.png">

**Comment by oulvhai** [comment]
你怎么打开就怎么关呗。 点那个按钮打开就点那个按钮关， CMD + 7 开就 CMD + 7 关。
