### ISSUE TITLE
webstorm复制粘帖出来的代码只有一行不会自动格式化

### ISSUE THREAD

**Issue by MeCKodo** [oulvhai/MWeb-issues#207]
![image](https://cloud.githubusercontent.com/assets/10184444/15446943/f5998eba-1f61-11e6-9dfa-359ac2aa5061.png)
![image](https://cloud.githubusercontent.com/assets/10184444/15446944/fb632842-1f61-11e6-8571-38ee8377eac8.png)

**Comment by oulvhai** [comment]
暂时可以看看 https://github.com/oulvhai/MWeb-issues/issues/163 这个 issues，可能对你帮助。下一版本将修正。
