### ISSUE TITLE
希望支持发布到 firebase

### ISSUE THREAD

**Issue by wq163** [oulvhai/MWeb-issues#208]
发布服务里希望支持google 的 firebase

**Comment by oulvhai** [comment]
firebase 我看了一下，感觉没必要做什么支持呀。

**Comment by MiYogurt** [comment]
我更希望支持 Wildog 的后台服务。
https://z.wilddog.com/overview/introduction

希望可以把markdown 同步到这个里面的 json数据库 里面。野狗会提供第一个是免费的。

**Comment by oulvhai** [comment]
@MiYogurt 这个就不考虑支持了 :D
