### ISSUE TITLE
Feature Request - Notes List panel customization

### ISSUE THREAD

**Issue by xakraz** [oulvhai/MWeb-issues#21]
I use the External Sources pattern to save my notes via Dropbox or Git.

I would like to be able to customize the display settings of the notes list panel
- Activate / Deactivate the 1 line preview
- Activate / Deactivate the files infos
- Select the ordering of the list

To get a more compact list overview (And you will be my Evernote replacement for life !)

**Comment by oulvhai** [comment]
Activate / Deactivate the 1 line preview
Activate / Deactivate the files infos

added in version 2.0.  Menu: View - List Style ...
