### ISSUE TITLE
能否添加一些设置

### ISSUE THREAD

**Issue by MiYogurt** [oulvhai/MWeb-issues#212]
第二个文件夹栏目，设置是否显示后缀，是否显示简介。

还有就是这个 预览 markdown 的主题 css 上哪去下。

复制有点问题
![原图](https://cloud.githubusercontent.com/assets/10082395/15804254/304bd6a6-2b35-11e6-9a64-4e7fe28f3f01.png)

复制到简书之后，选复制为富文本也不行。
![复制之后](https://cloud.githubusercontent.com/assets/10082395/15804257/66162f20-2b35-11e6-9711-ac611c2ffd6b.png)

**Comment by MiYogurt** [comment]
还有我看 iA Writer 的预览样式不错，能不能移植一份。

**Comment by oulvhai** [comment]
系统的 CSS 在 MWeb app 包中的 Contents/Resources/PreviewAsset/previewCSS 里。
复制到简书如果在简书中用的编辑器是 markdown，可以直接复制所有文本；如果是用 HTML 编辑器，可以先打开预览，然后在预览中全选，然后复制。

iA Writer 样式可以试试这个 https://gist.github.com/jdriscoll/1424000

**Comment by MiYogurt** [comment]
就是复制的文本，MWeb 自动给标题加上了`** # h1 **`这样的加粗样式。用 sublime 打开 复制就没问题。

**Comment by MiYogurt** [comment]
![image](https://cloud.githubusercontent.com/assets/10082395/15813818/9d18493a-2bf4-11e6-89fe-5911298761d6.png)
IA 的样式是这样的。 等有时间了我试着自己写一个吧。 还有一个 bug 就是，在预览窗口滚动的话，代码窗口是不会跟着滚动的。

**Comment by oulvhai** [comment]
样式是可能是简书的编辑器加的，目前只能先粘贴到文本编辑器或者其它纯文本 app，然后再复制，再贴到 简书。 之后可能会考虑加个复制为 纯文本的 菜单。

预览窗口滚动，代码不滚动这个并不是 bug，是故意做成这样的，因为目前预览不是很准确，所以允许预览窗口滚动而代码窗口不动。

**Comment by MiYogurt** [comment]
原来如此，但是我的 简书的设置一直都是 Markdown 的。

# 测试图片

![Girl](http://ww1.sinaimg.cn/large/72f96cbajw1f4j61l63ebj20st0rpthf)
- [x] I don't like you!
- [ ] i want eating!

可能是简书的问题吧，我复制到 github 就没事。复制到简书就出事，用 Sublime 复制就没事。我也不清楚哪有问题，你复制没有问题么？

**Comment by oulvhai** [comment]
我测试过，有问题。这个应该是 MWeb 的复制没有设置为纯文本的原因。复制到 github 没事是因为 github 的留言框只支持纯文本。 这个问题可能会直接修正，也可能会出一个复制为纯文本的功能。

**Comment by MiYogurt** [comment]
![屏幕快照 2016-06-06 下午11.05.42.png](http://ww4.sinaimg.cn/large/72f96cbajw1f4lwkpuyglj21hc0u0gqp)
外部文档模式，开启2栏模式，鼠标选取进入全屏，再按 Cmd+2 就会变成这样，应该是一个 bug 吧。

还有一个就是预览样式，高亮代码的选取的 css 选择器，这个文档在什么地方呢？

**Comment by oulvhai** [comment]
感谢！
高亮代码 CSS 是用 http://highlightjs.org/ 这里的样式，贴到自定样式文件内即可，可参考 sample-css。

**Comment by MiYogurt** [comment]
恩，辛苦开发者修复 bug了。
