### ISSUE TITLE
关于字体等宽问题

### ISSUE THREAD

**Issue by Choate** [oulvhai/MWeb-issues#213]
最近使用MWeb来制作表格，发现一个问题在编辑模式下一个中文字符等于三个空格，是否能够设置为两个空格呢？

**Comment by oulvhai** [comment]
这个貌似是按字体不同，然后宽度会不同的，我所用的是 Courier 字体，两个空格好像宽于一个中文字符。然后我再试了另外的，是像你说的，三个空格等于一个中文字符。 我觉得这问题应该是无解的。
