### ISSUE TITLE
可否有命令行工具

### ISSUE THREAD

**Issue by yumm007** [oulvhai/MWeb-issues#215]
这样就可以通过脚本自动生成PDF后者HTML格式的文档了，谢谢！

**Comment by oulvhai** [comment]
暂无，有的话，第一版也不会这么高级功能 :D

**Comment by oulvhai** [comment]
可以使用 open -a MWeb doc.md 这种命令。

**Comment by ChJJin** [comment]
+1，希望能增加通过命令行到处 pdf 的功能，谢谢！
