### ISSUE TITLE
MathJax公式在自动编号情况下HINT提示时编号错误

### ISSUE THREAD

**Issue by SLTECH** [oulvhai/MWeb-issues#217]
不知为什么图片传不上来……
但这个比较好重现，在里面插入MathJax公式时写：
\begin{equation}
max_{\delta,w,b}\delta
\end{equation}
即指定公式自动编号，这样在编辑状态下，鼠标hover在公式上出现的HINT上数字一直在往上涨，点一次加一次
╮（╯_╰）╭

**Comment by hstdt** [comment]
同样反馈MathJax问题的路过，尝试了一下，这样不对么。

``` mathjax
$$\begin{equation}
max_{\delta,w,b}\delta
\end{equation}$$

$$\begin{equation}
max_{\delta,w,b}\delta
\end{equation}$$

$$\begin{equation}
max_{\delta,w,b}\delta
\end{equation}$$
```

![image](https://cloud.githubusercontent.com/assets/10215098/16002014/eada05ee-3187-11e6-97a4-0db3bb0e7d8b.png)

**Comment by SLTECH** [comment]
呃，楼上同学，我说的可能不准确。用CMD+R预览是正常的，出问题的是在编辑状态下，把光标放在式子上会出个hint，泡泡，这里面是错的。等于编辑状态下，每次把鼠标放在这个式子上，显示出的那个黑底白字的提示是有问题的，每次加1 。
我去改改原来的表述，谢谢！

**Comment by SLTECH** [comment]
![errorequationpreview](https://cloud.githubusercontent.com/assets/2082676/16002307/8ba15472-3189-11e6-9215-4cf8784bb5fc.jpg)
汗，终于能传图了。这张图应该能说清楚了吧！这里的数字，随着我写着，已经变到200多了。

**Comment by oulvhai** [comment]
我已经知道这个 bug 了。 这是因为编辑器内那个预览，只取编写中那块 LaTeX，所以编号会有问题。我再想想怎么修正了，貌似比较麻烦，感谢了。
