### ISSUE TITLE
[bug]MathJax在脚注中的渲染有问题

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#218]
如果把MathJax写在脚注中，而脚注上一行为空行，则无法看到渲染效果，预览正常。

脚注上一行无文字，不渲染:

```
test[^1]

[^1]: $\lim_{n \rightarrow \infty}$
```

脚注上有任意文字渲染:

```
test[^1]

any words
[^1]: $\lim_{n \rightarrow \infty}$
```

PS:cmd+1，cmd+2，cmd+3，个人觉得调整后自动全屏比较科学。全屏的仅编辑器模式下，使用cmd+3，窗口宽度会超过屏幕宽度，还需要手动调整一次。

**Comment by oulvhai** [comment]
无法重现 bug：

![snip20160613_14](https://cloud.githubusercontent.com/assets/2174294/16006795/8af68a84-31a1-11e6-8a1d-b8d99589152f.png)

**Comment by hstdt** [comment]
@oulvhai  

光标都在MathJax内

![image](https://cloud.githubusercontent.com/assets/10215098/16006903/0929d730-31a2-11e6-8182-19125d5dcea2.png)

![image](https://cloud.githubusercontent.com/assets/10215098/16006964/5a322d58-31a2-11e6-903d-d25e4e07c5c3.png)

**Comment by oulvhai** [comment]
原来是说这个，我看能不能修正。
