### ISSUE TITLE
外部模式中文件列表自动刷新问题

### ISSUE THREAD

**Issue by EkkoG** [oulvhai/MWeb-issues#219]
在外部模式中引入文件夹后，在文件夹中添加文件（不是在MWeb中，在Finder 中新建文件，文档列表不会自动刷新。

**Comment by oulvhai** [comment]
我这边两台电脑测试没这个 bug，看看是否还有人遇到。

**Comment by EkkoG** [comment]
http://7xsjsr.com1.z0.glb.clouddn.com/blog-img/1466003581212.gif

Github似乎不支持 Gif？可以打开链接看一下

**Comment by oulvhai** [comment]
确定 bug，暂时可以用 右键 - 刷新

**Comment by oulvhai** [comment]
2.0 版已修正，如果还有问题，请重开。
