### ISSUE TITLE
【1.5.1】为什么更新以后原来sync 的样式都丢失了

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#22]
如题

**Comment by oulvhai** [comment]
这个非常抱歉！！然后我在 Mavericks 和 Yosemite 安装 1.4.1 版然后加入 github_new 再升级到 1.5 版，都没发现 样式丢失问题。你这边有可能提供另外的信息吗？下一版有关删除操作我都会用丢到 Trash 的方式。

**Comment by ferocknew** [comment]
公司mac 没有丢失，可能不是普遍问题
