### ISSUE TITLE
行内代码(``)后接分隔符(----)会被识别为title

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#220]
```
[toc]

`test`

---- 

`not title`
----
```

![image](https://cloud.githubusercontent.com/assets/10215098/16075122/17e7840a-3320-11e6-9e74-2eb4dfd5dc8d.png)

**Comment by oulvhai** [comment]
这本来就是 title 的语法。分隔符的语法要前后空一行的。
