### ISSUE TITLE
无法显示图片

### ISSUE THREAD

**Issue by RayPS** [oulvhai/MWeb-issues#221]
同一个 md 文件在所有 Markdown 编辑器里都显示正常，但是 MWeb 却无法显示。

<img width="798" alt="screen shot 2016-06-16 at 3 28 02 pm" src="https://cloud.githubusercontent.com/assets/1941540/16108642/f9e97d34-33d6-11e6-9f5a-20046f10f638.png">

**Comment by oulvhai** [comment]
可以参考一下：http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html 这文章。
