### ISSUE TITLE
光标位置的不和谐

### ISSUE THREAD

**Issue by binderclip** [oulvhai/MWeb-issues#222]
由我来提两个小问题吧。
1. 在有标题的地方敲回车，光标都会先跳到最前面，然后再跳回正常的位置。反正是要到正常的位置的，不能直接到那边吗？否则会感觉很奇怪。
   ![1to2](https://cloud.githubusercontent.com/assets/8187479/16174913/64b762d8-360d-11e6-917e-76ca82dc31df.png)
2. 一直按 [Down] 到了最后一行之后光标会跑到最前面去，心里有点难受
   ![front](https://cloud.githubusercontent.com/assets/8187479/16174934/de73d214-360d-11e6-85b4-165a229824c9.png)

**Comment by oulvhai** [comment]
暂时不知道如何修，先 mark

**Comment by binderclip** [comment]
@oulvhai 好！

**Comment by binderclip** [comment]
222

**Comment by labmain** [comment]
同样对这个光标位置很不解呀，感觉上像是对所有的非标题进行了缩进似的。。。
