### ISSUE TITLE
图床增加gitlab

### ISSUE THREAD

**Issue by gangyou** [oulvhai/MWeb-issues#224]
我在用mweb 编辑MD格式的公司文档，很多图片希望能够一键发布到公司的gitlab上面，这样在转移到gitlab的时候就不需要再一次把图片一个个上传上去。看了API是有的，用自定义的图床POST FILE NAME也不能自动生成，所以无法通过自定义去集成gitlab。希望考虑一下

**Comment by oulvhai** [comment]
gitlab 不是像 github 类，直接用命令行 push 上去的么？ 图片也是的吧？
然后说到 api ，是不是这个： http://docs.gitlab.com/ee/api/projects.html#upload-a-file ？ 感觉可以用自定义功能的。
