### ISSUE TITLE
更好的支持gitbook/external项目

### ISSUE THREAD

**Issue by uniquejava** [oulvhai/MWeb-issues#225]
要是能参考下gitbook editor的客户端(应该是NW.js做的)
[gitbook editor 1.1.0](https://github.com/GitbookIO/editor-legacy/releases) 

支持这样写书的功能就好了..

一本书是关于某个topic或者某个project的知识库

![image](https://cloud.githubusercontent.com/assets/1049271/16305855/31c449a2-398e-11e6-8867-99562174355d.png)

在mweb中搜寻相似的功能 一直没有找到
1. mweb的external模式好像一次只能导出一个md文件, 目录结构是从这个md中索引出来的,,但是一个md放不下太多的内容, 无法做成一本书
2. mweb的lib模式好像能导出单个目录, 但是目录中的文件是平级的, 不能像gitbook editor中那个拖拽成目录树, 没法做成一本目录结构良好的书.
3. gitbook editor中的章节号是自动插入的, 可以上下拖拽调整顺序, mweb文档的排序似乎是固定的几种, 用户不能上下移动自由排.
4. gitbook这种toc tree并不是以文件夹的结构组织的, 所有的结点都是一个md文件. 我觉得这种方式不错,可以参考一下.

要是您能仿gitbook editor做个类似的新产品或者给mweb加个`book`模式.即使这种模式单独收费, 也非常值得购买

感谢!

.

**Comment by oulvhai** [comment]
hi, 我直接回
1. 是说导出 PDF？做书其实建议直接 gitbook，然后可以直接引入 gitbook 的文件夹在 MWeb 中编辑的，这点你可以下载一些用 gitbook 做的书，然后把文件夹引入 MWeb 即知，包括 gitbook 内的 markdown 中的本地图片，都会正确显示的。比如这本书： https://github.com/softwaredownload/openwrt-fanqiang
2. gitbook editor 中的目录树其实是按 SUMMARY.md，如果不用 gitbook editor 手工编辑也是可以的。
   3.4. MWeb 文档库 因为支持一个文档归类到多个分类的原因，虽然支持手工调整顺序，但是不大好用，这点我还在想怎么解决。

总的来说，目前如果要用 MWeb 写书，可以考虑 MWeb 外部模式 + gitbook 的组合，这样是有拖拽和粘贴插入图片的支持的，唯一的问题是要了解一下 gitbook 的文档组织结构（其实也很简单）。

**Comment by uniquejava** [comment]
Hi
我看了一下最新版gitbook的文档: http://toolchain.gitbook.com/, 下载了5.x版
gitbook的典型目录结构如下:

```
.
├── book.json
├── README.md
├── SUMMARY.md
├── chapter-1/
|   ├── README.md
|   └── something.md
└── chapter-2/
    ├── README.md
    └── something.md
```

可否对gitbook工程(或者说对SUMMARY.md文件) 有更好的支持, 比如:
1. 在mweb中编辑SUMARRY.md的时候能不能给些文件路径提示, 比如输入chapter1/后面就能提示md文件列表
2. Gitbook项目只能通过External模式导入对吧(这个add external source菜单还真不好找, 加到File里边就好了)
3. External模式下是不是一次只能导出一个md文件到pdf(呃...) 能不能自动解析external根目录下的SUMMARY.md, 根据里边的路径, 导出一本完整的pdf书. 
4. 或者如果External中如果没有SUMMARY.md 能不能根据目录结构一键生成SUMMARY.md(需要排除.ignore文件中的目录比如_book)., 太懒不想手工编写

**功能3最迫切**

感谢!

**Comment by uniquejava** [comment]
不喜欢用gitbook editor, 一个原因是速度上没有mweb快,
另外是我太依赖mweb中的`Translate newlines to <br> tags`功能了.用`gitbook pdf`命令生成的pdf不支持mweb中的这个选项,   文字都挤到了一行.

所以 .. 就有了上面的需求.

**Comment by oulvhai** [comment]
External 模式下右键文件夹导出 PDF 这个，其实有计划在 2.0 版发布后慢慢增加，输入提示这个还有待研究，毕竟一个软件不可能做好所有东西。add external source 菜单加到 File 里是非常不错的建议，感谢！

**Comment by uniquejava** [comment]
刚在npm上发布了一个简单的gitbook plugin:  https://www.npmjs.com/package/gitbook-plugin-lb2br
用来在生成pdf 的时候 `Translate newlines to <br> tags`. 暂时解决了用gitbook命令生成pdf的问题.

**Comment by flyBread** [comment]
不支持粘贴图片吗？
