### ISSUE TITLE
如何让编辑窗口不显示图片

### ISSUE THREAD

**Issue by littledu** [oulvhai/MWeb-issues#226]
![image](https://cloud.githubusercontent.com/assets/1784673/16341204/9341d7d2-3a5e-11e6-9df0-f166517b57d4.png)

如上图，编辑器插入图片，只想预览窗口看就可以了，不想编辑器也看到，因为这样滚动就对不准了。如何禁止。

**Comment by littledu** [comment]
感觉影响也不是很大

**Comment by oulvhai** [comment]
偏好设置-通用设置 中可以设定

**Comment by littledu** [comment]
谢谢
