### ISSUE TITLE
为什么同步到 印象笔记 的样式跟我预览的样式不一致

### ISSUE THREAD

**Issue by littledu** [oulvhai/MWeb-issues#227]
如题： 我预览的样式选择的是 `mweb-github`， 但同步到 印象笔记  中的样式却像是 `mweb-octopress`， 求解。

**Comment by oulvhai** [comment]
印象样式定制超麻烦，仅做一款默认的

**Comment by littledu** [comment]
soga, 或许可以看看怎样提供接口，让我们可以自己定制

**Comment by oulvhai** [comment]
只支持 style 这个属性，你感受一下。
