### ISSUE TITLE
【1.5.1】打字机效果，请不要到最后一行才触发，能否在屏幕下1/3 处就触发

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#23]
否则视线调整幅度还是比较大的

**Comment by oulvhai** [comment]
应该是一开启就触发了的，你的情况应该是没开启。或者有 BUG。

这个下个版本想到的优化是：可以设定文档内容高度占编辑器 百分之几 时才会触发。 比如说如果设定为 50%， 那么新建文档并打字，当内容达到一半编辑器时，就会触发。
