### ISSUE TITLE
发布服务增加自定义功能

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#230]
目前发布服务中, 支持自定义图床, 但是内容本身只是支持`wordpress`, `Metaweblog`等几个固定的服务, 并不支持自定义. 这部分有计划开放自定义功能不?

比如, 我可以配置自己网站开放的`api`然后一键发布到自己的网站去(发送的内容保持`markdown`结构)

**Comment by oulvhai** [comment]
请看: https://github.com/oulvhai/MWeb-issues/issues/231  我另开了一个 issues。
