### ISSUE TITLE
关于 MWeb 自定义内容发布（同步） API 以支持私人云或者网站的功能讨论。

### ISSUE THREAD

**Issue by oulvhai** [oulvhai/MWeb-issues#231]
蛮多朋友有这个需求，这个目前我有两个方案：
1. 使用目前 MWeb 已经支持的 MetaWeblog API， 这个 API 优点是使用广泛，是个写作工具可能都会支持。MWeb 也已经自带，自行实现起来也不麻烦（都有现成的代码示例，比如说 typecho，wordpress）。缺点是比较老，不支持 OAuth 2.0 登录。
2. 兼容 https://developer.wordpress.com/docs/ 中的部分 API，就是内容发布相关的 API，登录也是按这个 API。这个 MWeb 目前已经支持了，我要做的工作仅是做到可以自定义 API 地址即可。优点是现代，经 wordpress.com 好几年的发展，基本上已经非常完善了，缺点是无代码参考，要自己做。

其它的方案，比如说 MWeb 官方公布一个 API 这种需求，还是不要了，毕竟 API 不是什么人都可以设计的。如果有什么建议，请在此讨论。

感谢！

**Comment by DawnCool** [comment]
支持第2种方案，但是个人觉得OAuth 2.0太重,可以参考考百度站长验证这个网站是不是自己的

**Comment by KrabsWong** [comment]
应该还会有场景不需要认证，只是希望通过API调用，将文章备份到某个地方。

**Comment by qqlcx5** [comment]
增加GitHub图床的上传功能。写了一个上传经常报错

**Comment by youmengme** [comment]
有结果了么。。。
