### ISSUE TITLE
作者您好，是否可以添加账户管理的功能？

### ISSUE THREAD

**Issue by liberalisman** [oulvhai/MWeb-issues#233]
我有三台设备，分别在不同的地方使用，如果我是用马克飞象，他的账户绑定帮我完美解决了这一问题，但是使用Mweb实在是很让人头疼。

希望可以改进

**Comment by liberalisman** [comment]
我有三台设备，分别在不同的地方使用，如果我是用马克飞象，他的账户绑定帮我完美解决了这一问题，但是使用Mweb实在是很让人头疼。

希望可以改进

**Comment by KrabsWong** [comment]
这应该需要一个云端同步的功能了.

**Comment by oulvhai** [comment]
并不会做帐号管理和云端功能，只会用 iCloud。 
任何软件，只要加了服务器功能，马上要变成按月付费，不然肯定搞不起。

**Comment by liberalisman** [comment]
iCloud功能  下个版本会更新吗？

**Comment by oulvhai** [comment]
@liberalisman 不会，iOS 发布时才会一并更新。
