### ISSUE TITLE
1. 鼠标悬停在编辑图标可否加入功能提示？2. help 里打开markdown 语法帮助，无法阅览

### ISSUE THREAD

**Issue by ccqpein** [oulvhai/MWeb-issues#234]
1. 鼠标悬停在编辑图标可否加入功能提示？
2. help 里打开markdown 语法帮助，无法打开阅览界面。

目前就这两个，有新的会在后面加上

**Comment by oulvhai** [comment]
1. 会有
2. 已重现，非常感谢！
