### ISSUE TITLE
code block只显示在一行

### ISSUE THREAD

**Issue by potatoker** [oulvhai/MWeb-issues#236]
从intellij 粘贴代码到mweb的code block的时候，只会显示在一行。

编辑器里明明有换行:
<img width="581" alt="screen shot 2016-07-07 at 4 22 26 pm" src="https://cloud.githubusercontent.com/assets/5286501/16646886/2436e8a4-445f-11e6-813d-adb1d4df20fd.png">

然而显示是:

<img width="779" alt="screen shot 2016-07-07 at 4 22 37 pm" src="https://cloud.githubusercontent.com/assets/5286501/16646903/33ecd556-445f-11e6-9c1a-bf9c043775f6.png">

譬如下面的效果得来的流程是: 从intellij 粘到Mweb,然后粘到这里（下面是issue编辑网页自带的markdown转换）:

```
public static void Hello(){     System.out.println("Hello world"); }
```

而如果我直接从intellij 粘到这里,（下面是issue编辑网页自带的markdown转换）:

```
    public static void Hello(){
        System.out.println("Hello world");
    }
```

似乎是，往这里(网页)里从intellij粘代码的时候，会正常把换行符也粘过来。。
但是如果从intellij 往Mweb里粘的时候换行符被忽略了.

究竟是我的intellij编辑器设置有问题还是mweb的问题呢？

**Comment by oulvhai** [comment]
如果是 1.9.9 版，暂时可以用 https://github.com/oulvhai/MWeb-issues/issues/163 这个方案解决。

**Comment by potatoker** [comment]
还有就是用tab和```语法的时候，其中的文字不会自动换行(占满一行后),该怎么调整呢？

**Comment by oulvhai** [comment]
@potatoker 是说预览的换行吧，这个要自定义样式，加上：`.hljs{overflow: visible; word-wrap: break-word !important;` 这段样式就会换行了。

**Comment by potatoker** [comment]
@oulvhai 呃 ，是加在previewCSS的sample.css里面是吧?加了没用啊(你上面应该是漏掉了反括号吧，加上了)
我是指使用tab和```语法的时候，其中的文字会在editor下自动换行(我没有输入换行符),然后在preview下没有换行,就像这个网页editor的markdown这样:

```
   ssdfasdfasfasdfasfasdfhsakhfjksahdfkjsahfksfhaskfhksdjfhksjfhkshfksjfhksahjdfksahfkshjfksdhfkashjfksdahfksdajfhkasjhfksadfhksahfdskjfhk
```

然后我希望可以在editor下的自动换行也可以被体现在preview里面

**Comment by KrabsWong** [comment]
`preview`模式下没有换行, 个人理解是因为, `preview`以`html`的方式渲染, 而这一整个字符串没有空格, 会被理解为一个单词, 不换行应该是正确的渲染方式.

你可以试试在上边的css代码里再加一句`word-break: break-all !important`

**Comment by potatoker** [comment]
@yPangXie 是的。。我这算是额外的要求了🙈，好像之前用的Markdown编辑器也没有这一点。。不过，加了那行还是没有做到preview自动换行。。。

**Comment by KrabsWong** [comment]
@potatoker 说起来，弱弱的问一句，`css`代码更新到了`sample.css`里，那么，**"主题样式"**里的**"预览样式(CSS)"**有选择使用`sample.css`不。

**Comment by oulvhai** [comment]
@yPangXie  正解，反正关键就是那行 CSS 。

**Comment by potatoker** [comment]
@yPangXie  嗷嗷，是的，忘记把preview css置为修改过的那个css文件了。。。😓.感谢。。。。

**Comment by potatoker** [comment]
@oulvhai 不过麻烦再问一下，其他主题的preview的css文件在哪里啊。。。我可以自行修改吗。。感谢

**Comment by KrabsWong** [comment]
@potatoker 代回答一下。
默认主题没有开放可视化界面直接修改. 他们保存在程序包里`/Applications/MWeb.app/Contents/Resources/PreviewAsset/previewCSS` 如果需要, 可以自行复制一份到`sample.css`, 再增加定制化的内容.

**Comment by potatoker** [comment]
@yPangXie 恩恩，知道了，感谢感谢
