### ISSUE TITLE
checkbox勾选异常

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#237]
``` markdown
 - [ ] 测试
    - [ ] 子元素
    - [ ] 子元素
    - [ ] 子元素
```

**版本**: 2.0.1 (2.0.1)

**问题的表现**: 点击测试前边的复选框, 并没有被选中, 完全没反应. 第一个子元素也有同样的问题, 但是其他子元素就是好的.

然而.. 我并不知道怎么来复现.... 因为感觉毫无规律...

另外发现一个问题, 点击复选框的时候, 不像以前一样顺滑了, 很容易双击选中. 我本想传一个视频, 但`github`不支持, 用`MWeb`的反馈功能发送过去了.

效果图: 两个未选中的, 始终没办法选中..

<img width="271" alt="2016-07-08 9 43 16" src="https://cloud.githubusercontent.com/assets/12368943/16675085/6d430e9c-44f0-11e6-9809-26591c70c80b.png">

**Comment by KrabsWong** [comment]
补充一下:

把这两个未选中的删掉重新添加, 或者复制粘贴一下. 就可以正常操作了

**Comment by oimotis** [comment]
已收到 bug，非常感谢！

**Comment by oulvhai** [comment]
已收到 bug，非常感谢！
