### ISSUE TITLE
快捷操作按钮行为的建议和一个疑似bug.

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#238]
**版本:** 2.0.4

**建议:**
1. `h1-h6`使用的时候, 需要先选中一行文字, 或者将光标定位到文字上, 才会生效. 是否考虑, 点击的时候, 直接在当前行添加`h1-h6`的标记?
2. 快捷操作栏, 最左侧图标是一个收起按钮, 当收起侧边栏之后, 按钮是否考虑换成向右的, 以标示展开

**疑似bug:**

发生在有序和无需列表的图标上.

当多次点击有序列表图标的时候, 会继续追加有序列表的标记`1`. 但无序列表在多次点击的是偶, 会在追加`*`和移除`*`之间切换. 两者行为不一致, 不知道是不是有意为之?

**Comment by oulvhai** [comment]
这个有待改进
