### ISSUE TITLE
预览模式看不到垂直滚动条

### ISSUE THREAD

**Issue by daleqq** [oulvhai/MWeb-issues#241]
版本: **Version 2.0.6 (222)**
系统版本: **10.11.5**
预览一个长文件时看不到垂直滚动条，截图如下:
<img width="1280" alt="noscrollbar" src="https://cloud.githubusercontent.com/assets/1555563/16905904/42ce2604-4ce0-11e6-9d2d-0d0bef947cd4.png">

**Comment by oulvhai** [comment]
貌似是要开始滚动才会显示菜单，下次会考虑加个一直显示滚动条的选项。
