### ISSUE TITLE
2.06本地图片发布图床失败

### ISSUE THREAD

**Issue by kingjoydom** [oulvhai/MWeb-issues#243]
点击上传本地图片弹不出对话框。。。。

**Comment by oulvhai** [comment]
用法是这样的：

图床的用法是文档内有本地图片，然后调出上传图片界面后，会显示本地的图片在列表中，然后再点上传图片按钮，就上传列表中的图片。

**Comment by kingjoydom** [comment]
原来是这样，我一直以为是直接上传呢！为啥不做可以直接上传了，然后直接去选地址过来写markdown呢？

**Comment by oulvhai** [comment]
用法是本地优先的，暂时没想要修改这个。
