### ISSUE TITLE
建议修改LaTeX公式的字体为Latin Modern Math

### ISSUE THREAD

**Issue by patricorgi** [oulvhai/MWeb-issues#245]
或者谁能教我如何修改LaTeX的字体呀？ #enhancement

**Comment by oulvhai** [comment]
自定义 CSS 中可以修改，增加 .MathJax_Display, .MathJax{ font-family: "你想要设置的字体"; } 即可。

**Comment by patricorgi** [comment]
@oulvhai 是直接添加到sample-css.css文件最后是么？我加入之后，并在样式里选择了sample-css没效果。

**Comment by oulvhai** [comment]
可以导出为 html， 调试好之后才最后增加 预览 css 文件。如果没有生效，放最后试试，如果还不行， .MathJax_Display, .MathJax{ font-family: "你想要设置的字体" !important; } 用这样，试试加个  !important。还不行，自行用 chrome 调试一下看看是什么问题。 

抱歉，一般用户可能不会，但是定制不是给一般用户用的。

**Comment by schwt** [comment]
同在纠结这个问题。Latin Modern Math是latex默认的字体，是印刷、学术、出版里公用的数学字体，不知道为什么mathjax 没有用，导致公式看起来不太自然。

谢谢@oulvhai 提供的方法！我试了第一种方法，直接在.css后面加MathJax_Display，似乎不起作用。
准备学下导出html，然后尝试你说的第二种方法。

这个字体替换掉后，mweb就基本完美了。

**Comment by schwt** [comment]
同在纠结这个问题。Latin Modern Math是latex默认的字体，是印刷、学术、出版里公用的数学字体，不知道为什么mathjax 没有用，导致公式看起来不太自然。

谢谢@oulvhai 提供的方法！我试了第一种方法，直接在.css后面加`MathJax_Displa`，似乎不起作用，设置`font-size`倒能生效。

这个字体替换掉后，mweb就基本完美了。

**Comment by patricorgi** [comment]
@schwt 求 css 文件！

**Comment by schwt** [comment]
@patricorgi 好消息，最新版已经支持公式字体可选了！
建议用 Tex 选项。

**Comment by oulvhai** [comment]
@schwt @patricorgi 都忘记这个 issue 了，抱歉。 这次为了可以选字体，引进了 MathJax 所有字体包，共 126M 的文件。。 整个 MWeb app 大了不少，现在都有点想去掉这个包，然后在设置页面可以下载或者选择用线上的 CDN。

**Comment by patricorgi** [comment]
一年的时间，这个issue终于可以关闭了哈哈，赞👍
