### ISSUE TITLE
建议支持Ghost博客系统

### ISSUE THREAD

**Issue by leeeboo** [oulvhai/MWeb-issues#246]
如题。谢谢。

**Comment by hfreire** [comment]
👍

**Comment by yourtion** [comment]
+1

**Comment by xujialiang** [comment]
+1

**Comment by oulvhai** [comment]
今天开始做 Ghost 功能。详细了解它的 API 后我都震惊了。。

一开始随便看一下是觉得它没有传图的 API，懒得做，因为复制粘贴蛮好用的。

这次开始做了，详细看了它的授权 API，果然是 beta。。 连 client id  和 secret key 的新增都没有做在后端，要用原始方式打开它的 sqlite 数据库， 然后新增，无语！ 它线上的博客服务同样没有，只有 Pro 帐号的用户才能发 email 去求 client id 和 secret key。

这还好，然后 API 介绍是什么鬼，只随便给几行代码说明一下是如何发一个文章。如下：

```
curl -i \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer <access-token>" \
    -X POST -d '{"posts": [{"title": "My API post", "markdown": "Some text"}]}' \
    https://<subdomain>.ghost.io/ghost/api/v0.1/posts/
```

编辑什么的其它 API 都懒得说或者是没有？


结论：Ghost 暂时还是复制粘贴吧，根本就不需要 支持 呀！

**Comment by tkizm1** [comment]
api的确很烂，详细可见
https://api.ghost.org/v1.0.0/docs

**Comment by oulvhai** [comment]
@tkisme 我看的就是这个 文档。

**Comment by linfeng365** [comment]
对各类博客的支持,可以增加用户数; 
但博客系统的变化比较大吧,流行一直在变。
(真正坚持的人又少; 真的坚持也不在乎一个复制粘贴)
真不应该投入太多精力。

**Comment by 99xin** [comment]
可是ghost真的很有用啊 哭cray

**Comment by kimonoki** [comment]
哈哈，我估计也是，ghost开发好像有点慢了，不过自己随便用用感觉还行，之后可能考虑转到其他MWEB支持的平台上吧

**Comment by tkizm1** [comment]
目前1.14.0
https://api.ghost.org/docs/user-authentication
用户认证这一块依旧不好用

**Comment by ideacco** [comment]
@oulvhai 所以目前是放弃开发支持这个系统了么？

**Comment by tkizm1** [comment]
根据之前的comment来看，等ghost做成稳定接口的时候再考虑比较好
