### ISSUE TITLE
希望有Vim模式

### ISSUE THREAD

**Issue by DemonFengYuXiang** [oulvhai/MWeb-issues#247]
首先，非常感谢作者给我们带来这么用心的作品。其次，作为一个vimer，面对市面上绝大多数markdown编辑器都没有vim模式，真心希望作者能够带来vim模式

**Comment by koallen** [comment]
同是Vim用户，希望可以支持这个功能。感谢。

**Comment by zihuyishi** [comment]
同意，没有vim键位简直不知道怎么编辑文档了..

**Comment by jicheng1014** [comment]
我也有此感觉   没vim 不能活

**Comment by lonelyandrew** [comment]
希望添加vim功能，实在是不习惯没有vim的日子。

**Comment by oulvhai** [comment]
VIM 已确认不做 。。。
