### ISSUE TITLE
Metaweblog API相关的变量问题(非常龟毛🌚)

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#248]
我试着在自己的服务器搞了个接口, 可以通过符合`Metaweblog API`规范的方式, 将`MWeb`的文章发布到我自己的服务器.

因为只是处理发布, 所以没有特意用一些模块来处理xml格式的文档, 纯手工提取到我所需要的字段. 于是, 发现`dateCreated`这个字段.. 命名方式不太统一奥...

这个问题很龟毛.. 这个问题很龟毛.. 这个问题很龟毛.. 🌚

<img width="299" alt="2016-07-20 10 43 20" src="https://cloud.githubusercontent.com/assets/12368943/16973566/44c7559c-4e67-11e6-9730-21b290d52f00.png">

**Comment by oulvhai** [comment]
淡定， MetaWeblog API 是非常老的 API 了，现在还在用也只是因为 Wordpress 而已。

**Comment by KrabsWong** [comment]
`MWeb`除了这个接口可以自定义以外, 其他那些, 应该都会跟对应的服务强关联吧. 好像没有别的办法可以直接分享到自己的接口上.

**Comment by oulvhai** [comment]
是的，因为没有这方面的标准呀。除了 MetaWeblog API

**Comment by KrabsWong** [comment]
也是蛋疼~ 不过现在这个用起来也没啥问题. 先这样吧.

**Comment by xunuo** [comment]
@yPangXie  请问有相关代码吗，急需 :)
