### ISSUE TITLE
[1.6.1] 用输入法打中文的 bug

### ISSUE THREAD

**Issue by binderclip** [oulvhai/MWeb-issues#25]
刚刚下载的新版本，不知道是不是个例。试了搜狗、百度、自带的输入法都是图中的情况。

![qq20150731-2 2x](https://cloud.githubusercontent.com/assets/8187479/9000606/a0fd1750-377c-11e5-9a87-4c5bffa80c95.png)

**Comment by oulvhai** [comment]
1.6.3 版已修正并提交到 MAS 和审核加急审核。
