### ISSUE TITLE
能不能顺便把 Marp 的功能也实现了？

### ISSUE THREAD

**Issue by wq163** [oulvhai/MWeb-issues#252]
https://github.com/yhatt/marp

这样就能很方便的导出幻灯片了，既是文档又能导出幻灯片的体验就很爽了。
在同一个软件里做这事情渲染结果也能保持一致（mweb和marp渲染上有不一致的，两个一起用总不如一个体验更好更方便）

**Comment by oulvhai** [comment]
单单 维护 marp 都要不少精力，MWeb 不合适再加此功能。
