### ISSUE TITLE
更改文档库地址的逻辑BUG

### ISSUE THREAD

**Issue by koallen** [oulvhai/MWeb-issues#253]
我刚才试了一下更改文档库位置的功能，好像每次一改就把旧文档库里整个文件夹所有东西移走了。我一开始放错文件夹（我以为MWeb会在里面新建一个），后来改的时候那个文件夹里所有东西都被移过去了。这个地方是不是可以改进一下？

另外我想问一下更改文档库位置和备份有什么很大的区别吗？

**Comment by oulvhai** [comment]
所有东西这个的确要改进一下，感谢。

文档库只有一个位置。 备份就是把文档库备份到别处。

**Comment by koallen** [comment]
谢谢。还有个问题就是移动文档库能不能把旧文档库那个文件夹删掉呢？

另外关于文档库，更改位置带来的实际好处是什么啊？实时的更新吗（相比备份）？感觉这两个功能略重合。

**Comment by oulvhai** [comment]
实际好处是你可以把文档库放网盘，然后在另一电脑用 选择现有文档库 这按钮，选择网盘的文档库，这样就能达到两台电脑使用同一文档库的可能。 还有文档库可以不再隐藏起来，能选择自己想保存的位置。

备份这个的确用处不大了，有可能会拿掉或者改进。

**Comment by koallen** [comment]
明白了，感谢。之前没有意识到备份无法让第二台电脑读取，只能作备份之用。

另外移除旧文件夹的建议还请考虑一下。

**Comment by oulvhai** [comment]
抱歉，我忘记说了，旧文件夹可以删除。

**Comment by koallen** [comment]
不好意思，好像我之前的表述有误。我的意思是在我移动文档库之后，MWeb可不可以把旧文档库那个文件夹删除掉啊？现在只能手动删除。

**Comment by oulvhai** [comment]
这个呀，这么重要的东西我不敢删除呀。不然有人想用回 1.x 版，就有问题了。

**Comment by koallen** [comment]
明白你的意思了。不过我当时是从一个外部文件夹移到另一个，也许可以加个判断源文件夹的功能？不过这个影响不大，手动删除也还好。
