### ISSUE TITLE
希望增加一个手写公式输入的功能

### ISSUE THREAD

**Issue by wizarot** [oulvhai/MWeb-issues#254]
An online demo:http://cat.prhlt.upv.es/mer/

The source: https://github.com/falvaro/seshat
作为web开发者,我自己是没水平做一个了.
希望作者考虑参考下,这东西在特定领域和理工科大学那边,真的是神器啊!

可能会赢得一个很大的市场份额.当然实现难度也不小,给个建议希望作者权衡一下.

**Comment by oulvhai** [comment]
这个真强，不过我也是没水平做一个 :D
