### ISSUE TITLE
对边栏的的小建议

### ISSUE THREAD

**Issue by xun404** [oulvhai/MWeb-issues#256]
1. 左边栏的双击改成展开吧，编辑这个操作用的太少了；
2. 列表只显示选中目录下的文档，不包含子目录的；总觉得很乱
3. 在目录名后面显示当前目录的文档数量

![qq20160723-1 2x](https://cloud.githubusercontent.com/assets/10024821/17076541/9a4e66a4-50e7-11e6-9b37-599306b6b85c.png)

**Comment by oulvhai** [comment]
1. 双击也是比较难操作的一种操作方式吧？
2. 这个暂时不会改，不过不一定，我标记为 discussion 了
3. 这个功能在计划中

**Comment by xun404** [comment]
我的触摸板设置勾选了`轻点来点按`，不会太难操作
Finder的逻辑是 空格是预览 enter是重命名 双击是打开
