### ISSUE TITLE
表格的实际对齐与菜单条的向导不一致的问题

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#257]
表格的对齐，在动作的菜单条的向导，与实际不一致的问题。具体情况主要分两种。

情况1：
1. 默认表格对齐的情况是这样的。第一行的标题居中对齐，其它行左对齐。
2. 但是菜单条的向导（即点击菜单条最右边的表格图标出现的向导），所显示的预览均为左对齐。
3. 这两个存在不一致，需要修改为一致。

情况2：
1. 在向导中使用对齐时，向导中显示的预览的对齐方式是基于列的，即只有当前所在列的对齐会发生变化，其余列不变。
2. 但在实际生成的表格中，却是全局的，即所有的列的对齐方式都改变了，而并非当前列的改变。
3. 这两个存在不一致，需要改为一致。

**Comment by oulvhai** [comment]
其实这个是预览表格的对齐和 Ctrl + Shift + T 这个表格插入和编辑对齐冲突的问题？ 我没理解错吧？

这个是因为表格编辑和预览样式是分开的，然而也不大可能做到统一，因为总不能表格编辑功能也去加载预览的样式。 所以目前如果不设置，默认就是左对齐，设置了，就会增加对齐方式的代码。然后预览样式是有可能重写对齐方式的，即使编辑时设置了对齐方式。

总的来说是：表格插入编辑的对齐是面向生成的 markdown 的。只能保证 markdown 正确。

**Comment by owenzhao** [comment]
你提到了不同的预览的格式不同，我测试了一下，的确是这样的。不同的主题对于默认的标题栏的处理存在差异，有的是默认居中，有的是默认居左。

也就是说，表格的对齐有4种方式。
- 默认--- 仅在的默认的情形下，标题和内容存在对齐不一致的情形，其余对齐方式标题与内容对齐方式是一致的。
- 居左:--
- 居中:-:
- 居右--:

其中默认这个对于不同的预览样式的标题，的确存在差异。不过即便是存在差异，在现有的预览样式中，也是居中的占多数，只有greyshade和octopress这两个是居左，其余的6个都是居右。

在编辑器的表格向导中，我认为还是显示为居中要好一些。因为：
1. 大部分的主题都是居中的
2. 对于默认为居左的主题，实际上，默认和居左这两个样式变成同样的了。这种浪费更像是一种bug而非样式的不同
3. 应该添加除了居中、居左、居右之外的默认快捷键。因为默认与以上3中的格式不相同。现在的向导里一旦选择了其中的一种，就不能回到默认了，只能手工编辑。

---

## 以上是问题1的回复

问题2的回复：

有关问题2，我进一步测试了一下。我发现问题的状况是这样的。

假设存在4列的一个表格。（问题和具体列数无关，只是为了举例方便）
那么你在实现对齐的时候存在一个奇怪的问题。
1. 如果我在第一列的任意一个单元格，按快捷键选择对齐方式，该对齐会应用到所有的列。
2. 如果我在第二列的任意一个单元格，按快捷键选择对齐方式，该对齐会应用到2-4列。
3. 如果我在第三列的任意一个单元格，按快捷键选择对齐方式，该对齐会应用到3-4列。
4. 如果我在第四列的任意一个单元格，按快捷键选择对齐方式，该对齐会应用到4列。

结论：在任意列的任意一个单元格应用对齐，该对齐会被应用到它所在列以及右侧的所有列。但是向导中的显示，却只有该列被应用了对齐。这个就是我想要描述的问题。我倾向于向导是正确的，但是具体的实现出了问题。
