### ISSUE TITLE
重启系统之后会多出来一个窗口

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#258]
当开着MWeb时，重启系统，重启之后，会多出来一个窗口。步骤：
1. 开启MWeb，全屏（我是全屏使用的，没有确认是否和全屏有关）
2. 重启系统，选中重启后打开当前开启的程序
3. 当重启后，右键点击MWeb应用图标，会发现，除了全屏状态的MWeb窗口外，还会出现同样内容的窗口，但是是非全屏的状态。也就是说多开了一个窗口。

**Comment by atever** [comment]
额，类似问题，就是关机时默认   
- [x] 再次登录时重新打开窗口
  ，结果每次开机会蹦出来几十个窗口，每一个文件都新开了一个窗口。
