### ISSUE TITLE
不显示通过相对路径引用的本地图片

### ISSUE THREAD

**Issue by zhuoqiang** [oulvhai/MWeb-issues#26]
如果 markdown 文本使用相对路径来引用本地图片, 预览和导出PDF都不会显示图片, 而是显示一个蓝色的叉

**Comment by oulvhai** [comment]
要看到 外部的 Markdown 文档中相对路径引用的本地图片，只能是用外部模式 (CMD+E)，并把文档所在文件夹引入。 不然不会显示。 这其实是权限问题，为了隐私等各种原因，Apple 在 MAS 上架的 APP 不允许读取 App sandbox  之外的任何资源，除非用户明确受权。 然后你直接用 MWeb 打开 Markdown 文档，MWeb 只会有该文档的读写权限，文档外的图片等等是连读取权限都没有的。 所以要引入这个文件夹，这样 MWeb 就有这个文件夹的读写权限了。

**Comment by zhuoqiang** [comment]
原来如此. 这个功能试了下没用起来, 使用方式上最好能简化一下.

我原来用 Mou 是可以直接生成图片的. 这是因为 Mou 没有使用 sandbox 模型开发的原因?

**Comment by oulvhai** [comment]
是的，没上架 MAS 的 APP 才有这个可能。
