### ISSUE TITLE
导出到印象笔记和HTML遇到的两个问题

### ISSUE THREAD

**Issue by WhiteT** [oulvhai/MWeb-issues#260]
1. 导出到印象笔记的主题和选择的预览主题不一致
2. 导出为HTML后一些样式丢失，比如代码块底色和语法高亮。

**Comment by oulvhai** [comment]
1. 老问题，印象笔记目前仅有做一款默认的样式
2. 导出时有个“选项” 的按钮，点了之后会出来一些选项，勾选 代码高亮即可。
