### ISSUE TITLE
表格过宽导致导出后表格被截断的问题

### ISSUE THREAD

**Issue by huanjuedadehen** [oulvhai/MWeb-issues#261]
表格有多列，将表格撑的有些宽，在预览的时候表格有横向滚动条。

在导出为PDF、图片等的时候，表格被横向截断了，只有前几列，后面的没有了。

**Comment by oulvhai** [comment]
导出 PDF 暂时无解，只能自己加 <br /> 手动调整。 图片有计划改进导出流程。
