### ISSUE TITLE
内容拷贝到简书后莫名其妙多了好多 **

### ISSUE THREAD

**Issue by dvxiaofan** [oulvhai/MWeb-issues#262]
![](http://o7mwf03sy.bkt.clouddn.com/Snip20160727_32.png)

左边是 MWeb 上编辑的内容, 右边是拷贝到简书上时候的截图
每次都要一点一点的删除, 好麻烦呀....
为什么会出现这种情况呢?是我哪里设置的不对?

**Comment by oulvhai** [comment]
昨天 2.0.7 版忘记修这个了， 现在只能粘贴到 其它文本编辑器（比如说 TextEdit），再复制，然后再贴到简书。

**Comment by dvxiaofan** [comment]
好吧, 希望尽快修复了.   总体使用还是非常不错的.
