### ISSUE TITLE
粘贴html文档时链接的处理问题

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#265]
我在Safari中复制一段包含了链接的html代码，然后通过“把HTML粘贴到Markdown”到MWeb，我发现在链接的处理上存在一些问题。

网站上的原文中的链接是相对链接，这在网站上没有问题。但是粘贴到我的文档，问题就来了，还是相对链接。而我的文档的预览是没法点击的。因为相对链接此时是无效的。

而如果我通过Safari右键的复制链接，然后再粘贴，获得的就是绝对链接了。

我觉得这里如果可以自动转换为绝对链接，会更好一些。

**Comment by oulvhai** [comment]
感谢反馈！ 
PS: 目前用 Chrome 好像没问题。
