### ISSUE TITLE
[TOC] 扩展在导出PDF中无链接效果

### ISSUE THREAD

**Issue by zhuoqiang** [oulvhai/MWeb-issues#27]
[TOC] 扩展在 PDF 中显示为超链接, 但点击没有任何跳转效果, 建议:
- 将 PDF 中的 TOC 链接处理为文档内部链接, 实现点击跳转
- PDF 自身有目录功能, 如有可能, [TOC] 也可以一并加入 PDF 原生的目录中

**Comment by oulvhai** [comment]
这个其实暂时不知道如何做。我要研究研究。。

**Comment by slawdan** [comment]
由于Stackedit.io导出的PDF里的TOC可以文档内部跳转，所以我认为现在的问题是个bug……

使用chrome打开导出的PDF时，TOC的链接可以点击，但是会打开浏览器，URL是原md文档的路径……
如：
导出文件 `/Users/HOME/MWeb - 专业的 Markdown 写作、记笔记、静态博客生成软件.pdf`，浏览器打开以后点击链接，跳转到：
`file:///Users/HOME/Library/Containers/com.coderforart.MWeb/Data/Documents/MWeb/LocalData/Docs/#toc_0`
所以我猜测是导出时的URL不对，被自动补全为文件绝对路径了。

以上仅供参考，期望能早点修正这个问题。

> 写开发文档生成了TOC逼格满满却不能点击……

**Comment by oulvhai** [comment]
目前生成 PDF 其实是调用系统的打印功能，可设置功能有限。你的发现非常有用，我猜测应该是用我设定的根路径转成的绝对路径，这次算是有点进展了，但是还要继续测试和研究看看。。

非常感谢！

**Comment by oulvhai** [comment]
我刚刚真测试了一下，发现 Stackedit.io 生成的 PDF 的链接是处理过了的，也就是说不是基本的 HTML 链结的形式了。然后因为他是服务器端生成的 PDF，所用的生成 PDF 的库还真不知道是那个。

你可以用 chrome 打开 Stackedit.io 生成的 PDF，然后鼠标移过去，状态栏上无任何提示。然后正常的连结，即使是下 "#toc_0" 这种，状态栏都会有提示的。

看来这还真不是一下子就能解决的了，我慢慢研究研究。。

**Comment by slawdan** [comment]
我又安装了 [pdf viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm/related?hl=en) 扩展，打开stackedit生成的pdf，得到这么一个链接：
`chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/file:///Users/HOME/Downloads/Hello!.pdf#file%3A///tmp/wktemp-f9971ca6-efce-40e0-9111-e4a63df6cd6f.html%23create-a-document`

`#`号之前都是chrome扩展以及文件的URL，后面看起来像是stackedit服务器端生成PDF的临时文件路径，因为我本地没有这个文件，而且每次打开都是相同的。

对比MWeb导出的PDF的TOC链接：
`chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/web/`

看起来就好像链接完全丢失了一样……

看来文内链接还是挺麻烦的，期待你啥时候搞定这个问题……

> 安装pdf viewer扩展的原因是没找到chrome内置的pdf viewer的源代码放在哪儿了……

**Comment by oulvhai** [comment]
😀 来报告一下，经过今天一整天的折腾，终于是有突破性的进展了！

也说说方案，看看那个真要做这功能的有缘人能看到。
其实非常简单，就是把生成的 PDF，用 cocoa 的 PDF Kit 再处理。大概是找出所有 TOC 连结，并找到所在位置，然后把连结连到所在位置。。 

非常感谢了！

**Comment by slawdan** [comment]
赞哪~期待下次更新时能用，不枉我买了正式版，而且stackedit没续费……

**Comment by oulvhai** [comment]
:D 
这算比较大的功能的，然后这次的版本 LaTex 预览有比较大的 Bug，过两天会提交 1.8.3 版以修正这个 Bug，所以这个功能应该是 1.9 版才会发布。

**Comment by slawdan** [comment]
搞定了？太好了~

**Comment by li8911255** [comment]
我在macOS Sierra（10.12.4）下同样碰到此问题，貌似针对新系统还是有这个bug？

**Comment by li8911255** [comment]
@oulvhai

**Comment by oulvhai** [comment]
@li8911255 在 Sierra 下有严重 bug，暂时不支持。
