### ISSUE TITLE
闲聊 ： Otis上爱范儿啦，连接里有mweb微信群！！

### ISSUE THREAD

**Issue by zminds** [oulvhai/MWeb-issues#270]
[这个独立开发者，开发出一款好用的 Markdown 工具](http://www.ifanr.com/691610?utm_source=rss&utm_medium=rss&utm_campaign=)

微信群连接8月3日前有效
![](http://images.ifanr.cn/wp-content/uploads/2016/07/4.pic_-9.jpg)

**Comment by oulvhai** [comment]
感谢广告！
