### ISSUE TITLE
编辑模式的建议

### ISSUE THREAD

**Issue by qianye0905** [oulvhai/MWeb-issues#274]
MWeb用了一段时间觉得挺好用，但是如果能像Typora一样所见即所得就更好了，编辑的时候根本不用考虑格式。现在使用MWeb的时候都要左右分屏，一边编辑一边观察看格式对不对，挺耗费精力的。

所以更多的时候是MWeb和Typora同时使用，利用Typora来编辑文档，使用MWeb的外部文档库功能来管理文档，如果能把两者的功能结合起来就好了。

**Comment by oulvhai** [comment]
MWeb 比较核心的原则是显示原始文本，所以应该不会做 typora 的所见即所得功能。
