### ISSUE TITLE
从word中复制文案, 粘贴到MWeb是一张图

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#277]
不知道是不是使用姿势不对, 从`Word(v15.22.1)`中复制一段文字, 粘贴到`MWeb`中的时候, 会帖进来一张截图.

**Comment by oulvhai** [comment]
因为 Word 的复制会自动生成一张图在剪切板里，然后 MWeb 也刚刚好支持直接粘贴图，所以如果判定剪切板里有图，会优先贴图。
目前解决的办法是用菜单： 编辑 - 粘贴为纯文本

**Comment by KrabsWong** [comment]
soga, 了解了.
