### ISSUE TITLE
预览和编辑器之间同步滚动的问题

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#278]
现在有做同步，但是我感觉效果不是很好。在我正在编辑的五万字的文档里，滚动编辑器，经常看到右侧的预览与左侧的编辑器的位置整页地不同步。

能不能做到，比如右侧的预览的第一行，在滚动页面时，就尽量始终与左侧的编辑器的第一行一致？

**Comment by oulvhai** [comment]
这个暂时没办法找到比较好的技术能完美解决这个问题，同步预览要很准，目前只建议用 Web 类 Markdown 编辑器。

**Comment by old-dc** [comment]
作者加油呀

**Comment by CloudPai** [comment]
作者加油~~期待攻克技术难关~~

**Comment by CloudPai** [comment]
提个建议：我发现编辑和预览两边的相对位置一般是保持不变的，能否在右侧预览界面中增加一个和左侧编辑区的相对位置调整条（最好是带重置、上移、下移这三个按键）（类似音乐播放器中能手动调整歌词和当前歌曲不同步的功能），这样貌似比实现完全的精确同步要容易一些吧？期待作者的不断优化，加油！！

**Comment by oulvhai** [comment]
这个问题在 3.x 版已列为优先解决了。希望能优化好点。
