### ISSUE TITLE
表格向导插入的文本没有处理为纯文本

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#279]
会包含<div>标签和换行。

https://developer.apple.com/library/watchos/documentation/General/Conceptual/WatchKitProgrammingGuide/AudioandVideo.html#//apple_ref/doc/uid/TP40014969-CH24-SW19

最下面的表格，使用向导插入视频参数的效果是这样的：

|  
<div>Video codec: H.264 High Profile</div>

<div>Bit rate: 160 kpbs at up to 30 fps</div>

<div>Full screen resolution: 208 x 260 in portrait orientation</div>

<div>16:9 resolution: 320 x 180 in landscape orientation</div>

<div>Audio bit rate: 32 kpbs stereo</div>

 |  |  |
| --- | --- | --- |
|  |  |  |

由于存在换行，整个格式都错乱了。

**Comment by oulvhai** [comment]
有些东西只能手动处理了。然后 markdown 的表格很弱，换行都不支持，只能手动加 `<br />`

**Comment by owenzhao** [comment]
对，我现在都是手动插入的。
