### ISSUE TITLE
从终端打开MWeb的外部模式

### ISSUE THREAD

**Issue by koallen** [oulvhai/MWeb-issues#280]
可否考虑像文本编辑器Atom一样，可以在terminal里面调用`atom test.py`来打开`test.py`。有时候在terminal里面写点东西想预览一下Markdown的效果。

**Comment by oulvhai** [comment]
暂时不能直接打开 priview，可以用 open -a MWeb md.md 然后再 cmd + r

**Comment by koallen** [comment]
谢谢，但是有个问题就是打开的同时会打开文档库（因为我默认是文档库模式）。这个有办法解决吗？

**Comment by oulvhai** [comment]
好像没有，因为 MWeb 毕竟不是纯的 markdown 编辑器，可以装个 macdown 或者 Typora，命令也是一样的，open -a Typora xx.md，macdown 好像直接支持 macdown xx.md 这个方式。

**Comment by koallen** [comment]
谢谢！
