### ISSUE TITLE
能否增加发布到简书的选项

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#285]
有时候会想把一些笔记发布到简书上面，但是简书的编辑器比MWeb难用太多了，每次拷贝的话也有点麻烦，特别是图片没上传的话，所以能否像支持印象笔记、Wordpress之类一样来支持直接导出到简书呢？

感谢！

**Comment by oulvhai** [comment]
简书没有 API，没办法支持。

**Comment by yajiez** [comment]
原来是这样，那就不在简书发了，谢谢！
