### ISSUE TITLE
多窗口的界面主题可否不同？

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#303]
两个问题：
## 1. 既然MWeb支持多窗口，那么可否不同的窗口支持不同的界面主题？

比如我现在开了两个窗口，一个是整理之前的博客，这个我希望开明亮的主题；一个是我今天的工作计划，我希望采用“黑色模式”。
## 2. 现在新建窗口是在文件菜单，我认为移动到窗口菜单更为合适。

我当初到窗口菜单找，发现没有，还以为没有这个功能。

**Comment by oulvhai** [comment]
1. 不会做这个的，这样会显得很复杂
2. 很多 app 都是把新窗口放这个菜单的，Safari 都是。
