### ISSUE TITLE
tab可以自动更换为空格

### ISSUE THREAD

**Issue by pangwu86** [oulvhai/MWeb-issues#31]
![image](https://cloud.githubusercontent.com/assets/326471/9025620/87a1b234-393e-11e5-95c4-336e8af3ef5d.png)

上面图中使用tab时, 预览出来的代码排版有问题
下面改成空格就显示正常了

很多编辑器里都提供输入tab时自动换成几个空格, 推荐加个开关, 可以设置

**Comment by ferocknew** [comment]
的确是一个很需要改进的需求

**Comment by oulvhai** [comment]
这个功能已经做好了，就等什么时候上架。

**Comment by oulvhai** [comment]
1.7.1 版已支持。
