### ISSUE TITLE
经常性在回车时莫名其妙复制当前行

### ISSUE THREAD

**Issue by Renkai** [oulvhai/MWeb-issues#32]
```
在 scala repl 中的结果
scala> add(secondLazy,firstLazy)
second lazy
first lazy
res0: Int = 3

res0: Int = 3
```

像这样… 我粘贴了一份内容,按回车加上```,res0:Int = 3 就被复制了

**Comment by oulvhai** [comment]
我反复测试如下：
粘贴
scala> add(secondLazy,firstLazy)
second lazy
first lazy
res0: Int = 3

然后按回车加下 ```， 好像不会复制，也就是无法重现 Bug。
程序中也不可能加上这种程序，我猜会不会是其他铺助输入软件的原因？
或者能提供一个能重现 Bug 的方法？

如果谁也遇到这个问题，欢迎提出。

**Comment by Renkai** [comment]
我感觉是软件切出再切回很容易发生这个问题,还有写完一段文字后,等待一会儿,再按回车也很容易这样

**Comment by oulvhai** [comment]
按上边的步骤操作了一些时间，我目前还是没办法重现 Bug。 
看看有没有朋友也遇到过。

**Comment by oulvhai** [comment]
按上边的步骤操作了一些时间，我目前还是没办法重现 Bug。 
看看有没有朋友也遇到过。
