### ISSUE TITLE
发布到印象笔记数学公式不能显示

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#320]
刚发现发布到印象笔记的时候，笔记中的数学公式显示的是源代码，类似`\[a+b=c]\`这样的，是目前不支持显示数学公式吗？

**Comment by oulvhai** [comment]
2.0.9 版才支持，请等下周，下周就发布 2.0.9 的 Mac App Store 版，如果是官网版的，现在就可以更新了。

**Comment by yajiez** [comment]
谢谢！
