### ISSUE TITLE
macOS 10.12 上无法使用

### ISSUE THREAD

**Issue by YDD365** [oulvhai/MWeb-issues#323]
刚刚购买的，在 macOS 10.12 上没法用啊，显示不了内容也无法编辑！希望尽快解决！

**Comment by Tomyail** [comment]
![image](https://cloud.githubusercontent.com/assets/350722/18004512/f6108b1c-6bc6-11e6-8fd3-349cfbfaf4d4.png)
有图有真相～

**Comment by oulvhai** [comment]
升级到 2.0.9 试试。
