### ISSUE TITLE
建议，搜索结果能否高亮搜索关键字？

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#33]
可以参考 Ulysses 的情况，未必需要那么炫。
但是，毕竟是很有用的

**Comment by ferocknew** [comment]
好吧，我发现，整站搜索和文件内搜索竟然是分开的。。。哈

**Comment by oulvhai** [comment]
:D 文档库是搜寻整个。。

外部模式引入的文件夹是搜寻当前选中的。
要搜寻全部引入的文件夹的话，万一那位引入 Documents 这种文档和层级超多的，就会很慢。

**Comment by binderclip** [comment]
整站搜索能不能支持高亮啊？
有的时候会搜索一个关键字，然后出来一堆文件，需要靠那个高亮来快速定位自己想要的内容。

**Comment by oulvhai** [comment]
嗯。已有计划改进一下。。
