### ISSUE TITLE
外部模式下，文件属性显示的是文件的创建时间，可否改成显示修改时间，或两个都显示

### ISSUE THREAD

**Issue by basefas** [oulvhai/MWeb-issues#333]
RT，作者我总问问题你不要烦我，墙裂要求完善外部功能的细节，还有就是外部模式下，我使用00，01这样的数字来命名md文件的时候，文件排序是倒序的，希望加强文件的排序功能，感谢。

**Comment by oulvhai** [comment]
排序设置可以参考这张图：
![](http://zh.mweb.im/asset/img/cn/h-1-3.jpg)
