### ISSUE TITLE
图像不能正常显示

### ISSUE THREAD

**Issue by Renkai** [oulvhai/MWeb-issues#34]
<img width="1101" alt="2015-08-14 11 17 10" src="https://cloud.githubusercontent.com/assets/3381789/9266610/106a636e-4276-11e5-8989-d2879833ae69.png">
不知道是因为png不支持还是因为我实在library之外打开的文档.

顺道一提,我觉得自动拖拽图片到文档的同时,画质被压缩得太低了.希望能够不压缩,保持原画质.
另外,svg,pdf格式的矢量图希望也能支持.

**Comment by oulvhai** [comment]
拖拽是没压画质的，是直接复制原图。然后图片不显示的问题请参考这个 issues: https://github.com/oulvhai/MWeb-issues/issues/26

svg,pdf 拖进来会变为连结，然后因为 Markdown 支持 HTML，所以你可以随意用。
