### ISSUE TITLE
遇到了一个 印象笔记 同步失败的问题

### ISSUE THREAD

**Issue by ichibown** [oulvhai/MWeb-issues#344]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo=0x608000e74440 {NSLocalizedDescription=Content of submitted note was malformed, parameter=Attribute "id" must be declared for element type "h3".}

**Comment by ichibown** [comment]
补充：版本 2.0.9 (239)
然后看了下上版本的 changelog 是有一个 印象笔记的发布样式强化的，我的这篇文档中用到的 md 元素只有:下划线、分割线、h3，把所有的 h3 改成 h4 后错误信息也随之改成了 "h4"

**Comment by oulvhai** [comment]
@BownX 这个错误的话，你的系统是不是 10.10 ？ 目前 10.10 下发布到 evernote 有严重 bug，无法发布出去。这个将在下个版本修正。

**Comment by ichibown** [comment]
的确是，今天升了下 10.11，问题解决，感谢！

**Comment by ichibown** [comment]
10.11.6 (15G31) 上也出现了类似的问题，请一并看一下吧，感谢~！
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=An invalid XML character (Unicode: 0x10) was found in the element content of the document.}

**Comment by oulvhai** [comment]
@BownX 这个错误是说你的文档中有一个 0x10 的字符，这个不是 XML 支持的字符，不能发布到印象笔记。 这个要用 sublime 等等高级的文本编辑器才可能看得出来。

**Comment by RuiShe** [comment]
类似情况， Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "input" must be declared.} ？？

**Comment by oulvhai** [comment]
@RuiShe 印像笔记不支持 <input ，你看看你的文档是否有这个。

**Comment by jamesdongdong** [comment]
类似情况    Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "mark" must be declared.}  
后来我把mweb里面的高亮语法====全部去掉之后，就可以发布在evernote上面了，希望更改一下这个bug

**Comment by Gatsby23** [comment]
现在Mac上又出现了这个问题，麻烦问下该如何更正呢？

**Comment by oulvhai** [comment]
@Gatsby23 换为 mweb-* 的预览样式。

**Comment by jamesdongdong** [comment]
还是印象笔记同步问题，mweb上面高亮了但是推送到印象笔记上没有出现高亮，但这次没报错。望更改bug。
![image](https://user-images.githubusercontent.com/28383935/34142012-cef23558-e4bf-11e7-8d5a-28355ec7b186.png)

**Comment by oulvhai** [comment]
@jamesdongdong  印象笔记不支持高亮这个 html 标签。

**Comment by sunhanwu** [comment]
Error Domain=com.evernote.sdk Code=3 "Not permitted to perform action" UserInfo={NSLocalizedDescription=Not permitted to perform action, parameter=authenticationToken}

完全不能同步了，不知道什么原因，10.13.5的系统

**Comment by oulvhai** [comment]
@sunhanwu 这个错误 需要删除印象笔记服务再增加

**Comment by Hao-World** [comment]
在2.2.9的时候一直这样，更新了3.1.1 还是这个情况 
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "t" must be declared.} 
好多笔记都不能发布到印象笔记 系统是10.12.6

**Comment by oulvhai** [comment]
@Hao-World 你文档中的 `<t` 改成 `&lt;t` 也就是所有 < 都要用 `&lt;` 来换。或者用代码 \`<t\` 包起来。印象笔记的格式就是这样一个情况，我用程序直接把所有 < 替换也不合适，毕竟有时候用户会各种写法。

**Comment by Hao-World** [comment]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Error processing document: Invalid a href attribute:media/15298511595160/Spring01.ppt}

为什么不能传文档到印象笔记中了了    求解。
我是这样引入的文件

Spring01   (media/15298511595160/Spring01.ppt)  



在Mweb中是可以打开的，不过现在这个版本不直接打开这个文档，而是跳转到文档库的文件夹中

**Comment by Donald-Su** [comment]
> @Hao-World 你文档中的 `<t` 改成 `&lt;t` 也就是所有 < 都要用 `&lt;` 来换。或者用代码 `<t` 包起来。印象笔记的格式就是这样一个情况，我用程序直接把所有 < 替换也不合适，毕竟有时候用户会各种写法。

文档中使用到了'doc <topic>'字段，前面加上转义字符'\'问题解决，即：修改为'doc \<topic>'不在出现上述问题，有类似问题的可以参考下
