### ISSUE TITLE
 每次启动都报错

### ISSUE THREAD

**Issue by paulQuei** [oulvhai/MWeb-issues#347]
每次启动时都报错：“Can't Found Library Database! Please check the Library Location Setting.”

我尝试过卸载，并删除配置文件，仍然无效！！

**Comment by oulvhai** [comment]
什么操作会变成这样？
解决办法是在 偏好设置 - 通用设置中 选择现有的文档库，如果你要重置文档库，请参考：https://github.com/oulvhai/MWeb-issues/issues/336
