### ISSUE TITLE
如果我想使用一些备份/同步服务,该怎么做呢?

### ISSUE THREAD

**Issue by Renkai** [oulvhai/MWeb-issues#35]
比如想用github作为保存笔记的地方…
如果想用mweb提供的自动建站服务,我似乎就不能自定义原始markdown内容的保存目录了

**Comment by oulvhai** [comment]
**2015/9/16 Update**：文档库已于 1.7.1 版提供备份功能！  

你可以使用外部模式 （CMD + E）

一般情况下都建议用外部模式。需求本地笔记和 MWeb 的静态博客生成功能才用文档库模式。
文档库模式备份请用菜单： Help - 中文帮助   拉到最后。 文档库不支持同步！
