### ISSUE TITLE
发布到印象笔记的问题

### ISSUE THREAD

**Issue by GavinXue** [oulvhai/MWeb-issues#351]
## 报错信息

Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "functionname" must be declared.}

貌似没找到完全相同的报错问题~

**Comment by GavinXue** [comment]
原来是我的文档中还有这样的字符  `_<FunctionName>_ <Situation>`.导致了错误，虽然不明白错误是怎样造成的

**Comment by oulvhai** [comment]
@GavinXue 印象笔记只支持有限的 xml 标记，你的写法会转化成 `<em><FunctionName></em>`，所以会提示不支持 元素 <FunctionName>。可以用 `&lt; &gt;` 代替 `< >`。
