### ISSUE TITLE
无法发布到印象笔记

### ISSUE THREAD

**Issue by lanotte** [oulvhai/MWeb-issues#352]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo=0x60800067f140 {NSLocalizedDescription=Content of submitted note was malformed, parameter=Attribute "id" must be declared for element type "h5".}

**Comment by oulvhai** [comment]
目前 10.10 （Yosemite） 以下的系统会有问题。issues 重复，关之。
