### ISSUE TITLE
进入编辑模式后 页面空白

### ISSUE THREAD

**Issue by Asherlate** [oulvhai/MWeb-issues#354]
在mac os 版本 macOS Sierra 10.12 Beta (16A285a) 中
进入编辑模式后 内容是空的 ，只有背景

MWeb 版本 2.0.8 (228)

。。。应该是系统版本跟软件不兼容问题导致的
能否尽快修复下。。已经习惯于用MWeb来编写文档.现在之前写的好多文档无法修改
急~！

**Comment by oulvhai** [comment]
升级到 2.0.9 试试
