### ISSUE TITLE
重新打开文件后，图片无法加载，要再添加一次才能加载

### ISSUE THREAD

**Issue by jwsky** [oulvhai/MWeb-issues#358]
mac os seirra最新版 13'mbp 
mweb收费版

例如!分割[]分割(/Users/xxx/Desktop/work/xxx.png)

忽略分割两个字

**Comment by oulvhai** [comment]
增加图片的用法请看看：http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html 这里。
