### ISSUE TITLE
mac os seirra导出pdf死机

### ISSUE THREAD

**Issue by jwsky** [oulvhai/MWeb-issues#359]
mac os seirra导出pdf死机
死机比例80%，是否勾选了导出大纲视图都一样

**Comment by oulvhai** [comment]
暂时回复一下这个严重的问题的状态：

目前无法解决，查不到 macOS 下 PDF 生成的类库 apple 改了什么鬼东西，同样的代码，仅在 macOS 下有问题，而且造成问题的代码只有一行，就是生成大纲重新保存的代码。 不做大纲就不会有问题（现在不勾选还有问题，那是因为不勾选也进行这个过程）。

暂时决定下个版本中 macOS 将去掉 大纲视图的功能，11.9 ～ 11.11 不受影响。

**Comment by oulvhai** [comment]
2.1.0 版已修正。
