### ISSUE TITLE
希望可以提供接口或插件机制允许粘贴图片时自定义上传资源到云服务

### ISSUE THREAD

**Issue by knightli** [oulvhai/MWeb-issues#36]
比如：配置中提供一个选项，允许用户通过 js 或者 dsl 的方式自定义一段脚本

这段脚本的输入是 MWeb 给的图片 buffer 和文件信息（比如是 png 格式的图片）

这段脚本的逻辑就是拿这个图片的 buffer 去上传资源，并最终得到一个线上的资源 url

这段脚本的输出是上传结果， 成功 or 失败， 成功时还需要返回 url

由于上传资源可能涉及到用户私密配置，同时考虑上面的脚本又可能希望被同类需求用户简单的复用
所以这里初期可以直接让用户处理这种复用和自定义（也就是自己去找来这段脚本，并且自己从代码里找到私密配置的部分修改掉），后期可以通过脚本插件化和配置化来优化（插件开发者可以把脚本中的个性化配置部分抽取出来，放在脚本配置的入口给用户自行配置）

通过这种方式，可以极大的规避图片资源的引用管理问题（比如重新组织文档目录时，涉及引用资源的重新修改），同时，这种模式下的外部源模式，资源相对比较简单，进而也可以提供外部源的 build site 功能了。

**Comment by oulvhai** [comment]
这个功能其实有计划，但是还未找到非常好的方式。定义脚本的方式因为使用上有点难度，我还要研究一下。 

然后外部模式的图片资源引用问题的话，可以通过下图的设置解决：
![snip20150825_4](https://cloud.githubusercontent.com/assets/2174294/9458125/6b5c337e-4b1d-11e5-8611-8d6954f340fe.png)
这样设置后，如图中的话，所有拖入的图片都会放在 TextDocuments/media 下，重新组织文档和目录也是没问题的。

外部源 build site 功能确认不会做，因为这个的话，目前有很多非常成熟的方案。

**Comment by oulvhai** [comment]
1.9 增加图床功能。
