### ISSUE TITLE
有序列表嵌套无序列表 有序顺序问题

### ISSUE THREAD

**Issue by Chen-Hu** [oulvhai/MWeb-issues#360]
我在有序列表2 中 添加无序列表导致，第2项 从1开始排序。
如图
<img width="1048" alt="2016-09-21 13 48 30" src="https://cloud.githubusercontent.com/assets/6964498/18778234/f3d23d74-81a5-11e6-809f-510eb9b9afd3.png">

**Comment by oulvhai** [comment]
可以这样写：

```
1. 列表

    First Header | Second Header
    ------------ | -------------
    Content from cell 1 | Content from cell 2
    Content in the first column | Content in the second column

2. 列表
```

也就是列表项间空一行，然后内容前都加一个 Tab

**Comment by Chen-Hu** [comment]
嵌套中 加tab 确实解决了。
刚开始用mark down 很多问题搞不清是自己语法问题还是软件问题。
谢谢耐心回复。

**Comment by oulvhai** [comment]
@Chen-Hu 是 MWeb 所用的解析器要求这样写。其实 Markdown 的话，列表不建议做复杂的结构。可以用标题 ## 1. 标题  这样写。
