### ISSUE TITLE
把文章中图床图片保存到本地

### ISSUE THREAD

**Issue by Latias94** [oulvhai/MWeb-issues#369]
你好，我想问问能不能把文章中的网络图片保存到本地（外部模式中保存到图片文件夹）并且替换为本地图片地址（/media/xxx.jpg），和上传图床相反，因为有时候需要更换图床，这样可以重新上传到别的图床。

**Comment by oulvhai** [comment]
暂时可以切换到预览，并复制一下，然后用菜单： 编辑 - 把 HTML 粘贴为 Markdown

**Comment by atjason** [comment]
@Latias94 可以试试图床搬家神器 [iPic Mover](https://itunes.apple.com/cn/app/id1183822957?ls=1&mt=12)，可以一键将 Markdown 中的图片从一个图床搬到另一个图床。

![](http://ww2.sinaimg.cn/large/006y8lVagw1fajaszqardg30ia0bc4cp.gif)

**Comment by Latias94** [comment]
@atjason 你好，你是作者吧？我使用过后提点个人需求：
* 把已经存进其他图床中的图片下载到本地，并替换文档对应图片的地址(相对地址或绝对地址)
* 把已经存进其他图床中的图片下载到本地，并上传到另外一个图床，替换文档对应图片地址为新外链地址

只支持本地图片的转移是否有点局限了呢？

**Comment by atjason** [comment]
@Latias94 
1. 目前并不支持这个功能，只是把本地图片、或者已经在图床的图片，上传至新图床。
2. 并不是『只支持本地图片』呀，默认就是同时上传本地图片、和其他图床的图床。只是有个『仅上传本地图片』的选项，对应只上传本地图片、不上传已经在图床中的图片这种需求。妈呀，好绕…

@oulvhai 抱歉在你的场子里说别的产品了…

**Comment by Latias94** [comment]
@atjason 谢谢，已经解决，如果能支持像 iPic 支持上传至其他图床就好了。

**Comment by atjason** [comment]
@Latias94 iPic 就是我开发的，iPic Mover 是 iPic 的衍生品，专门用于图床搬家，而且本质上是调用 iPic 来上传至七牛、又拍、阿里云 OSS、Flickr、Imgur 等图床。

**Comment by Latias94** [comment]
@atjason 我知道，之前我以为只支持新浪图床，也就是说上传图床的选择跟 iPic 所选的图床一样。

**Comment by atjason** [comment]
@Latias94 恩，你说的没错，iPic Mover 就是把图片上传至 iPic 当前选中的图床。

**Comment by oulvhai** [comment]
@atjason 没关系，哈哈！
