### ISSUE TITLE
外部源模式有无可能提供文档库那种 build site 的功能？

### ISSUE THREAD

**Issue by knightli** [oulvhai/MWeb-issues#37]
如题。

外部源模式的源 md 用 git 服务来管理版本是很方便的
但有时候也很想要 build site 出来
目前发现不行

没有这样设计，我相信是有原因的
原因是什么呢？可以说说 讨论下么？

> 猜测是外部源模式下，信息结构松散一些，缺少一些文档库 build site 时所需的必要信息，导致 build 无法进行。。。但具体是卡在什么地方，没太想明白

**Comment by oulvhai** [comment]
如之前的所说：外部源 build site 目前有非常成熟的方案。
