### ISSUE TITLE
导出 PDF 没有大纲

### ISSUE THREAD

**Issue by devonliu02** [oulvhai/MWeb-issues#370]
版本 2.1.0 (248)

内容导出 PDF 没有大纲，且 toc 的内容也无法正常跳转。

**Comment by oulvhai** [comment]
这个的原因是 macOS 不知道修改了什么 API，这功能使用起来会 CPU 100% 而且假死一段时间才能导出。 
所以 macOS 下暂时去掉这功能，有可能是永久性去掉，除非找到另外的办法。

当然 EL Capitan 和 Yosemite 还是有这个功能的。

**Comment by li8911255** [comment]
请问现在有解决这个问题么？大神

**Comment by li8911255** [comment]
@oulvhai

**Comment by oulvhai** [comment]
还没解决

**Comment by hh-in-zhuzhou** [comment]
@oulvhai 如果是Sierra的原因，你有给苹果提交bug报告么？你这个app我非常喜欢，我也是苹果开发者，今天推荐给同事，可是发现没有windows版，有点遗憾。这个用来给软件专业学生上课的话非常的方便，可以一边讲课一边画时序图和写文档，你考虑考虑，是另一个商机。

**Comment by oulvhai** [comment]
@hh-in-zhuzhou 没确认是不是 bug，可能是我写法错误，然后一直不知道正确的写法。。
再说了，给苹果提交 bug 是万年无结果的类型，我会再尝试看看，不然就只能等 High Sierra 版本了。Windows 版还没决定是否要做，感谢建议！

**Comment by GerrieWell** [comment]
希望快点解决... 大纲和TOC

**Comment by saup007** [comment]
@oulvhai typora 导出 pdf 是 ok 的，目录树，TOC 都可以点击跳转到指定位置。

**Comment by oulvhai** [comment]
@saup007 是的， typora 好强还免费。。感觉好受打击 😂

**Comment by saup007** [comment]
@oulvhai typora 导出 pdf，最后一页是空白的 Bug，哈哈。MWeb 也很好用的。

**Comment by oulvhai** [comment]
to all，今天再尝试解决这个问题，发现是 sandbox 的问题。如果关掉 sandbox，无任何问题。开启 sandbox 的话，不管怎么写都不行。决定在 Sierra（10.12） 放弃这个功能了。 

好消息是，在 High Sierra  下 （10.13），无任何问题，代码没有作任何修改都 OK，想用这个功能只有等 High Sierra 发布了。。然后下个版本会在 High Sierra 下开放这个功能。

也就是说，这个功能仅 Sierra 不可用，应该还是可以接受的吧。。毕竟我是真没办法了。

**Comment by oulvhai** [comment]
2.2.4 版已开启在 High Sierra 下支持 PDF 生成 TOC

**Comment by uclort** [comment]
@oulvhai 作者您好，high sireea 下请问生成 pdf 之后，点击大纲目录，并不能跳转到具体位置。

**Comment by uclort** [comment]
@oulvhai MWeb App Store 版本，2.2.8，mac os 10.13.1。

**Comment by oulvhai** [comment]
@mTerminal 是不是 [TOC] 那部分没办法跳，实测 大纲还是可以正常跳的。

**Comment by uclort** [comment]
@oulvhai 确实是这样，是我没搞清楚区别，不好意思。
另外正确情况应该是点击 [TOC] 也可以跳转吧，我试用了一下上面朋友说的 typora，用 typora 导出 pdf 后，大纲和 [TOC] 都可以正常跳转。

**Comment by oulvhai** [comment]
@mTerminal 是这样，MWeb 可能跟 typora 用的生成方式不一样， MWeb 用的是苹果的 PDFKit 生成的，这货自从 10.12 被改了之后就有小问题，在 10.12 非 Sandbox 下干脆直接不支持。我看看能不能修正吧。。

**Comment by uclort** [comment]
好的，了解了，是有点坑人。😂

2017-12-01 17:03 GMT+08:00 Otis <notifications@github.com>:

**Comment by zzfmyway** [comment]
你好，我用的是官网下载版本 Version 2.2.9，OSX 10.13.3。

还是遇到上述提及问题，[TOC] 那部分和footnote没办法跳，大纲可以正常跳。

请问这还是已知问题待修复吗？谢谢！

**Comment by oulvhai** [comment]
10.13 的 TOC footnote 不能跳问题，只能后续优化了。 10.12 无大纲问题在 MWeb 3 已解决，方法很简单，App 改成 非 sandbox 即可。 MWeb 2.x 应该是不会有解了。

**Comment by breeze-ev** [comment]
新版没有导出没有大纲选项了吗
