### ISSUE TITLE
在全屏模式下按ESC会退出全屏

### ISSUE THREAD

**Issue by mingelz** [oulvhai/MWeb-issues#371]
当时只是输入法打错了键，想按 ESC 取消，结果多按了一下就退出全屏了。
版本：2.1.0（248）

**Comment by oulvhai** [comment]
Apple 习惯性是 ESC 退出全屏的，除非 焦点 是到 输入框。 你可以试试其他程序。

**Comment by mingelz** [comment]
我自己试了一下：
- 焦点在输入框也会退出全屏：系统的备忘录、QQ
- 无论如何都不退出全屏：Atom、Chrome
- 焦点在输入框才不退出全屏：Finder

看起来这个逻辑应该是各应用自己的设定了。

那就说一下我自己的使用感受吧：

在以输入为主的应用中，如 MWeb、Atom、备忘录，QQ，输入中输错了可能会习惯性的按 ESC，甚至按多次ESC（就像 Copy 的时候重复多次的 Command + V）那样，此时其实并没有退出全屏的意愿。不过也如上举的几个例子，竟然大部分的默认是哪怕焦点在输入框也退出全屏，这与我的心理预期确实不太一致。

或者加个配置项 ;-)

**Comment by dragonkid** [comment]
编辑器习惯用 vim，按 `esc` 是习惯动作，希望可以提供一个配置，防止按 `esc` 退出全屏。

BTW，也希望可以提供 vim 模式。

**Comment by oulvhai** [comment]
目前暂时还是按 macOS 的默认行为。
