### ISSUE TITLE
不支持对选中多行增加、减少缩进

### ISSUE THREAD

**Issue by knightli** [oulvhai/MWeb-issues#38]
现在是 tab 了之后，这篇选中文本被直接替换成了 tab

这个特性还是很常见的，一旦发现不行，很纠结，只能再打开别的编辑器去编辑，略蛋疼
希望能够支持~

一般是: 快捷键 tab、shift tab，菜单里 indent, outdent

**Comment by oulvhai** [comment]
有这个功能： CMD + [  或 CMD + ]  在 Actions 菜单可以找到。 Xcode 也是用这个快捷键。

**Comment by knightli** [comment]
那么可否把tab shift tab支持了？很多编辑器里都是这个键？：）

**Comment by oulvhai** [comment]
的确是这样，我研究一下这样做是否有问题。

**Comment by oulvhai** [comment]
1.9 已支持
