### ISSUE TITLE
使用七牛图床后报错

### ISSUE THREAD

**Issue by moskize** [oulvhai/MWeb-issues#383]
在配置好七牛图床后，试上传一张图片之后，报错。弹出对话框，对话框内容如下：

*\* Error! **
Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: bad request (400)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x608000e32760> { URL: http://upload.qiniu.com/ } { status code: 400, headers {
    "Access-Control-Allow-Headers" = "X-File-Name, X-File-Type, X-File-Size";
    "Access-Control-Allow-Methods" = "OPTIONS, HEAD, POST";
    "Access-Control-Allow-Origin" = "*";
    "Access-Control-Expose-Headers" = "X-Log, X-Reqid";
    "Access-Control-Max-Age" = 2592000;
    "Cache-Control" = "no-store, no-cache, must-revalidate";
    Connection = "keep-alive";
    "Content-Length" = 54;
    "Content-Type" = "application/json";
    Date = "Tue, 25 Oct 2016 04:11:53 GMT";
    Pragma = "no-cache";
    Server = "nginx/1.8.0";
    "X-Content-Type-Options" = nosniff;
    "X-Log" = "body;UP/400;UP:9/400";
    "X-Reqid" = "8iAAAGf9iG8Eq4AU, 8iAAAGf9iG8Eq4AU";
} }, NSErrorFailingURLKey=http://upload.qiniu.com/, com.alamofire.serialization.response.error.data=<7b226572 726f7222 3a22696e 636f7272 65637420 7a6f6e65 2c20706c 65617365 20757365 2075702d 7a322e71 696e6975 2e636f6d 227d>, NSLocalizedDescription=Request failed: bad request (400)}

**Comment by oulvhai** [comment]
这个是 400 错误，换个 API 试试。七牛的 API 好像会区域性不大稳定。
