### ISSUE TITLE
预览出错

### ISSUE THREAD

**Issue by raidyue** [oulvhai/MWeb-issues#385]
这个地方预览出错了，第2张图是另外的工具中的预览图没有问题
<img width="1060" alt="2016-10-27 22 49 58" src="https://cloud.githubusercontent.com/assets/2962896/19772232/266029d8-9c98-11e6-8f13-11e3a84283bd.png">
<img width="831" alt="2016-10-27 22 50 30" src="https://cloud.githubusercontent.com/assets/2962896/19772243/30cc26d8-9c98-11e6-8314-6f70c574b9e3.png">

**Comment by oulvhai** [comment]
在 MWeb 中， `2.` 上面加空行（也就是列表上面加空行）就表示是新的列表了。删除那个空行即可。
