### ISSUE TITLE
无法发布到 Typecho

### ISSUE THREAD

**Issue by vayn** [oulvhai/MWeb-issues#386]
MWeb 版本：2.1.0
Typecho 版本：[GitHub 上托管的最新版本](https://github.com/typecho/typecho)

问题描述：设置 Metaweblog API 成功，验证成功。发布文章时可正常获取分类，但是点击发布后，加载动画一直持续（超过20分钟，没耐心试了）。没有任何回应，但发布实际失败，Typecho 未收到新文章。

**Comment by oulvhai** [comment]
我测试了一下，好像 master 的是 beta，的确不行，我不知道是修改了什么。然后我测试稳定的版本，比如说 v1.0-14.10.10-release  这个就可以。

**Comment by vayn** [comment]
感谢回复！
找到原因了，就是因为这个提交: [Update Response.php](https://github.com/typecho/typecho/commit/65637a33d18b6db9378d11a77145521aa9e3a1fe#comments)。和 MWeb 无关，不过也折腾了一晚上

**Comment by woodylan** [comment]
我也遇到这个问题了，搞了一天了，期间换了成z-blog，这个对markdown显示不太好，替换了CSS也很乱。

**Comment by woodylan** [comment]
v1.0-14.10.10-release 这个版本可以，但是图片传不了。

**Comment by oulvhai** [comment]
@igenglong 感觉是 typecho 的 Metaweblog API 的问题，看谁入坑修一下。

**Comment by ideacco** [comment]
@oulvhai 求修坑!!!

**Comment by oulvhai** [comment]
@ideacco 我就不修了，毕竟对 typecho 不了解，我自己又没在用 :D。

**Comment by lvtao-net** [comment]
试试这个。我是成功的https://www.lvtao.net/tool/mweb-markdown-post-typecho-uppic.html
