### ISSUE TITLE
使用七牛图床空间为华东报错，如果为华北则正常。

### ISSUE THREAD

**Issue by moskize** [oulvhai/MWeb-issues#389]
报错内容请参考 https://github.com/oulvhai/MWeb-issues/issues/383

这个报错只有在非华东空间会报。

**Comment by oulvhai** [comment]
感觉像是七牛的问题，因为他的 API 什么的都没改。

**Comment by mildnes** [comment]
这个问题我之前在Twitter上跟作者说了。。我试验了所有地域的空间，目前只有华东地区正确，其他的都是400。。我用ipic上传到七牛就都没有问题。

**Comment by oulvhai** [comment]
@mildnes 感谢如此有用的反馈！
