### ISSUE TITLE
feature request: toggle live preview

### ISSUE THREAD

**Issue by ghost** [oulvhai/MWeb-issues#391]
We may don't want preview to be simultaneously same as editor's area sometimes.

**Comment by oulvhai** [comment]
Try CMD + R

**Comment by ghost** [comment]
@oulvhai Yes, I noticed this function before, but it seems unavailable.
Whatever I clicked it from menu or used shortcut, it switch my current layout from editor+preview to editor or preview only.

**Comment by oulvhai** [comment]
@haodong toggle live preview is:  Open a new window for live preview? It's removed in version 2.x.

**Comment by ghost** [comment]
@oulvhai No, they're two panes in the same window.

**Comment by oulvhai** [comment]
@haodong  May be I didn't know what your question is.
Sorry for my english.

**Comment by ghost** [comment]
![nov-10-2016 10-58-40](https://cloud.githubusercontent.com/assets/8103074/20163089/ad15f77c-a734-11e6-8b87-988e5a50138d.gif)

As you can see, I just hope it may have a button to toggle the live-preview function. But the `Cmd+R` shortcut was not what I expected. It should be, once it toggled, the left side can be able to scroll up or down while the right side maintains frezon.

**Comment by oulvhai** [comment]
A specific  request.
Thanks.
