### ISSUE TITLE
[TOC] 展示多了一个点

### ISSUE THREAD

**Issue by JarnTang** [oulvhai/MWeb-issues#399]
展示的效果如下图：
![image](https://cloud.githubusercontent.com/assets/791043/20383082/5d9b7702-ace9-11e6-8464-475567fc7f20.png)

     
源代码：
![image](https://cloud.githubusercontent.com/assets/791043/20383146/94543856-ace9-11e6-9326-967c05cef55e.png)

**Comment by JarnTang** [comment]
我发现H2下必须是H3，这样toc不会有问题，如果H2下放的不是H3，而是H4，5，6等则会有问题

**Comment by oulvhai** [comment]
@JarnTang 这样是会多套一个空的层级，感觉没什么问题吧，如果不加那个空的层级，下边再有 h3 时，会看上去，上边的省的一层的 h4 像 h3
