### ISSUE TITLE
不同category引用同一文档时，引入的图片在mweb中都正常，一旦导出html，第二个文档生成的html照片链接失效

### ISSUE THREAD

**Issue by zminds** [oulvhai/MWeb-issues#405]
![image](https://cloud.githubusercontent.com/assets/1445705/20798347/7d710a84-b819-11e6-8272-c82eaf6c08f1.png)
文档本身所在位置生成的静态html
![image](https://cloud.githubusercontent.com/assets/1445705/20819519/b6f4ed6a-b86f-11e6-97cf-3bcb235a287a.png)

文档第二个引用生成html
![image](https://cloud.githubusercontent.com/assets/1445705/20819520/ba29454e-b86f-11e6-8a36-ab7cb6c0bb92.png)

经过查看，发现在第二个引用生成的html目录下，没有这个文档中引用的图片。

**最好支持导入别的目录下的图片**，否则引用很容易导致图片丢失，除非全部用云存储

而且好像如果文档没有引用 没有任何办法在目录下附加图片，比如：我想在额外放一张图片指定在文章列表上，这里输入的图片路径我只能在生成目录定义一个目录，还担心以后不小心删除了
**最好把图片和文档都放在文档库的目录中**
![image](https://cloud.githubusercontent.com/assets/1445705/20819521/bd60e5fa-b86f-11e6-8af6-944f1a630e65.png)

**Comment by oulvhai** [comment]
图片和文档的确是放在文档库目录中的。
我经常这么干呀，也就是一个文档中设置为两个不同的静态博客，然后貌似没问题？

如图：
![14811987052257](https://cloud.githubusercontent.com/assets/2174294/21009459/a6c46ddc-bd81-11e6-9bc3-e875375f03d9.jpg)

**Comment by zminds** [comment]
额 不好意思 复现不了了 ，谢谢回复
