### ISSUE TITLE
崩溃bug

### ISSUE THREAD

**Issue by duncup** [oulvhai/MWeb-issues#407]
点击帮助下的Markdown文档按钮后崩溃，本机可重现。
版本 1.9.9 (203)
OSX系统。

**Comment by oulvhai** [comment]
这个 Bug 升级到新版本就可以了，因为不再修正 1.9.9 版了。

**Comment by duncup** [comment]
好的。谢谢回复。

**Comment by duncup** [comment]
另外请问有序列表是否有快捷键呢？找了好久似乎没有? @oulvhai
