### ISSUE TITLE
search框不小心输入了空格导致笔记“丢失”

### ISSUE THREAD

**Issue by uniquejava** [oulvhai/MWeb-issues#41]
Hi, 有时在底部的search框不注意按下了两个或以上空格。然后就会发现所有的笔记都不见了。。。

建议：在仅输入空格的时候可否不触发 搜索 事件。见下图.. 
![search box issue](https://cloud.githubusercontent.com/assets/1049271/9705725/ecf8f7a4-5500-11e5-8d5f-fff82c80e7ef.png)

**Comment by oulvhai** [comment]
看到丢失吓我一跳！
感谢建议！

**Comment by oulvhai** [comment]
搜索框移到上边了，应该不会触发这情况而不知了。空格还是不去掉，因为有时候可能会搜索词前后有一空格的情况。
