### ISSUE TITLE
2.1.1版本更新安装不成功

### ISSUE THREAD

**Issue by shiweihappy** [oulvhai/MWeb-issues#413]
mac系统10.12.1， 无法从2.1.0版更新到2.1.1版本

**Comment by oulvhai** [comment]
~~暂时可以手动下载： https://dl.devmate.com/com.coderforart.MWeb/2.1.1/1481645190/MWeb-ProMarkdownwriting%2CnotetakingandstaticbloggeneratorApp-2.1.1.dmg 来解决。感谢反馈！~~

已修正这个 Bug，重新更新一次应该可以了。
