### ISSUE TITLE
请问文档大纲怎么切换不同标题?

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#415]
按⌘+7 出现文档大纲,然后怎么选择不同标题?
除了鼠标外,可以用键盘选择吗?

**Comment by oulvhai** [comment]
随便点一标题，Focus 后，就可以上下箭头选择了。

**Comment by linfeng365** [comment]
@oulvhai 看能不能这样:

⌘+7 出现文档大纲, 并自动 Focus 到大纲上;
上下选择后, 通过`回车` 回到编辑窗口;

总之, ⌘+ 7 就激活大纲。

**Comment by oulvhai** [comment]
对，这的确合理一点。感谢建议！

**Comment by linfeng365** [comment]
如果更进一步优化快捷键,可以在上下标题跳转就更好了。
⌘+ ↑ 跳到上个标题;
⌘+ ↓ 跳到下个标题。

**Comment by linfeng365** [comment]
基本功能实现
