### ISSUE TITLE
不能"另存"为md文件?或导出为 md 文件。 

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#419]
为了在另外的 Markdown 打开(可以复制粘贴法) ,或思维导图打开。(如iThoughts)

**Comment by oulvhai** [comment]
文档库的话，在列表中右键可以，我再加个导出当前文档的入口好了，感谢建议。

**Comment by linfeng365** [comment]
@oulvhai 

Mweb 可以发布"复制HTML"这个功能非常赞!

如果增加一个"复制 Markdown",又方便了一点。(我现在一般用,全选,复制)

**Comment by linfeng365** [comment]
功能实现 关闭
