### ISSUE TITLE
在preview界面复制的文字可否带样式

### ISSUE THREAD

**Issue by uniquejava** [oulvhai/MWeb-issues#42]
Hi，Good day! 我是一个重度的markdown使用者。。我之前用的gitbook editor在preview界面复制出来的文本 然后粘贴出来是带样式的，我发现MWeb复制出来的是纯文本格式，我得先导出成html，然后打开html文件，然后再复制（好麻烦。。。）

我希望我发的邮件格式非常漂亮， 所以。我希望在preview界面复制出来的东西和preview上看到的样式是一模一样的，而不是纯文本的。。。

Thank you so much .

**Comment by uniquejava** [comment]
看到有人 提了类似的需求，，提需求的人竟然是鹏哥 @freewind 。。程序圈的世界好小。：）

**Comment by oulvhai** [comment]
:D 
为啥我在 Preview 窗口 CMD + A 然后 CMD + C， 然后转到 mail app CMD + V 后是带图片和格式的？难道是系统不一样？我是 Yosemite。

 @freewind  是不是要这种功能就好。
