### ISSUE TITLE
如何设置软件语言为中文

### ISSUE THREAD

**Issue by AFutureD** [oulvhai/MWeb-issues#428]
macOS系统语言为英语，从App Store下载MWeb后打开，默认语言为英语，如何设置为中文？希望不改变系统语言为中文。

**Comment by oulvhai** [comment]
目前无法这样做。

**Comment by bao3** [comment]
估计可以用一个比较脏的方式来解决：打开软件包，用中文内容覆盖 英文语言包。我没试过，但应该可行。
