### ISSUE TITLE
由于重度使用，所以很希望能将md 文件内的链接体验做的更好

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#43]
现有版本已经能实现从A 文件跳转到B 文件了
但是，跳转到的时候是打开新窗口，而且，左侧的list 也是不对的。

细节作者你可以自己体验一下。
你可以参考一下gitbook 或者sublime，文件之间跳转的时候，希望：
1. 不要在新窗口打开而是当前窗口
2. 左侧list 也对应正确选择到当前文件项目

**Comment by oulvhai** [comment]
目前我测试外部模式左侧的 list 是对的，文档多时好像是没有滚动到合适的位置，这点会再优化一下。
文档库目前是不会选中。

然后：
1. 目前还是决定在新窗口打开（将来某个版本做好 Tabs 功能时会考虑在新 Tab 中打开）。
2. 这个会再优化。

感谢建议。

**Comment by knightli** [comment]
弱问下，现在的版本，怎么在内部 link 另一个文档并且能在编辑模式打开？

比如这样的结构：

```
- folder
  - a.md
  - b.md
```

 `a.md`里这样 link

```
[b](./b.md)
```

我试了两种方式：
- 在配置里勾选了`编辑模式 link 可点击`，然后在编辑模式下点这个 link，结果弹了 OSX 自己的打开文档的框，我选择 MWeb 之后没任何效果
- cmd+4切到预览模式，在预览里点这个 link，提示`找不到 b.md`

我的版本是 Version 1.7.1 (126)

**Comment by oulvhai** [comment]
我试了一下没问题， 你可以看一下默认的打开 .md 文档的软件是什么，目前点击后其实是调用默认的软件打开的。

**Comment by knightli** [comment]
点了以后：
![](http://7xkrm0.com1.z0.glb.clouddn.com/12fe7458d140b1c52929a0636938ab5a.png)

然后选择应用程序,默认那些能打开 md 文件的编辑器，都是灰的：
![](http://7xkrm0.com1.z0.glb.clouddn.com/5833eabca826fc8ec9ca2122728b3b0e.png)

无奈只能切换到所有应用程序，肯定是优先再选 MWeb 自己。。。

![](http://7xkrm0.com1.z0.glb.clouddn.com/072c0e28736eeb62b9505594e0c12b1a.png)

结果没反应

又操作了一遍，选 Haroopad，也没反应

再操作一遍，选 Atom，结果发现 Atom 被唤起了，但没打开 b.md 这个文档

注1：这里的 link 链接，我试过`./b.md` 和 `b.md`，效果相同
注2：我的默认打开 md 文件的应用程序：
![](http://7xkrm0.com1.z0.glb.clouddn.com/012477a16d200b042a466bb82b5d0667.png)

**Comment by oimotis** [comment]
可以试试这样： 在 Finder 中右键.md文档，选择 Get Info，然后在 Open width 里选择要首选软件，然后 点 change all。。

如果还不行，试试重启一下系统（有可能重启就好了）

再不行我也没办法了。

**Comment by oulvhai** [comment]
可以试试这样： 在 Finder 中右键.md文档，选择 Get Info，然后在 Open width 里选择要首选软件，然后 点 change all。。

如果还不行，试试重启一下系统（有可能重启就好了）

再不行我也没办法了。
