### ISSUE TITLE
请增加一个"复制 Markdown",类似现有的"复制HTML" 

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#431]
"复制HTML"这个功能非常赞!

现在 Markdown 语法流行,很多场合需要。
比如: 微信公众号, GitHub 等等

**请增加"复制 Markdown"。**

**Comment by linfeng365** [comment]
今天 50%off 给一批 Markdown 新手推荐了 。 MWeb 应该会越来越多人使用的。

**Comment by oulvhai** [comment]
@linfeng365 非常感谢！
