### ISSUE TITLE
怎么批量更新文档的category

### ISSUE THREAD

**Issue by uniquejava** [oulvhai/MWeb-issues#433]
我平常都是随意建文档. 没注意分类, 现在我加了个新的Notes分类
我从uncategories分类中找到了这些文档 ,  并将它们全部选中, 然后打开右键的设置界面, 选择Categories为Notes,
但是好像只有第一个文档设置了分类, 其它选中的都没有设置.

一个个设置好麻烦.

求改进

**Comment by uniquejava** [comment]
突然开窍了, 将所有的文档 拖到Notes下就可以拉.  :smile:

**Comment by oulvhai** [comment]
正解
