### ISSUE TITLE
推荐参考一下为知笔记，的确很希望用Mweb 做自己离线的知识管理

### ISSUE THREAD

**Issue by ferocknew** [oulvhai/MWeb-issues#44]
如题

**Comment by ferocknew** [comment]
用下来，为知比较好的地方，特别是MWeb 没有的：

**标签** ！！！

好吧，有了标签，实在太方便了！！！

**Comment by oimotis** [comment]
标签是说文档库？ 外部模式是支持文档加标签的。

然后文档库，我认为用好分类功能已经可以了，有空我了解一下为知笔记看看再讨论一下这个。
你如果有兴趣也可以列一下关键点或者直接说改进建议。

**Comment by oulvhai** [comment]
标签是说文档库？ 外部模式是支持文档加标签的。

然后文档库，我认为用好分类功能已经可以了，有空我了解一下为知笔记看看再讨论一下这个。
你如果有兴趣也可以列一下关键点或者直接说改进建议。

**Comment by ferocknew** [comment]
不不不，你误解了
分类和标签是两种完全不同的东西。
分类是有父子关系的，比如：A 文章要么在B 分类，或者C 分类，不能同时在2 个分类中。

而标签则是另一个维度，平行的。
A 文章可以有B 标签，也可以有C 标签。
D 文章页可以有B 标签，也可以有E 标签。

互不干扰。
最优的场景为：
A 文章在B 分类，有C 标签
D 文章在A 分类，也有C 标签。

blog 其实也需要tag 功能，比如，很多博客系统提供的tag cloud ，即标签云，就这个道理。
而标签，是用来提升搜索效率的工具，比如，google、apple、php ... 之类

**Comment by oimotis** [comment]
在我看来，标签只剩下提升搜索效率的工具这个用途了。
标签和分类都是知识归类。有时候专注一类用法并非坏事，任何方法，用熟悉了，就能有效率，如果还有标签，有时候会在想，打不打标签？标签打得够不够等等。  然后直接用分类归类还可以精炼知识和文档库，随意增加，或更改名称。 树型结构也非常好记忆。。 如果要平行结构，也可以专门建一大分类做平行结构归类。

关键一点是：知识是要不断重看，精炼才有价值。 不然还不如直接用 google

**Comment by oimotis** [comment]
注： oimotis 也是 oulvhai  同一人。。

**Comment by ferocknew** [comment]
并不想改变任何人的想法。

> 标签只剩下提升搜索效率的工具这个用途了。

这点作用足以。
例如：redis、php、数据操作、搜索引擎、
一篇文章到底归在哪一类，特别是Tree 太深（三层以上）的时候，会很纠结。
能帮助到搜索，那至少，以后查阅起来不用递归太深。

**Comment by oimotis** [comment]
为何一定要归为一类。。 我直接设为多类。。 所以支持设置为多个分类后， 标签真有没有都没差了。 分类同样也可以提升搜索效率（虽然现在还没有做这个功能）。

**Comment by ferocknew** [comment]
期待您的更新

**Comment by oimotis** [comment]
从一开始就支持设置为多分类了。。 搜寻这个还没很好支持。
