### ISSUE TITLE
同步到印象笔记后代码块缩成一行，无换行和缩进（样式乱了）

### ISSUE THREAD

**Issue by limboinf** [oulvhai/MWeb-issues#440]
版本 2.1.1 (255)

**在MWeb中显示如下：**

![](http://beginman.qiniudn.com/2017-01-18-14847075529506.jpg)

**同步后显示如下：**

![](http://beginman.qiniudn.com/2017-01-18-14847076341839.jpg)

**PS. 正确的markdown语法：**

![](http://beginman.qiniudn.com/2017-01-18-14847077008295.jpg)

**Comment by oulvhai** [comment]
可以尝试更新到 最新版 2.1.4 版试试。如果还没修正，我再看看是什么情况。。 感谢！

**Comment by limboinf** [comment]
@oulvhai 您好，升级最新版本了，**实验了一下还是同样问题**，同步印象笔记其他都没问题，很棒，就是代码这块有问题。

**Comment by oulvhai** [comment]
@BeginMan 试了一下，没办法重现，奇怪了。如图：
![snip20170118_20](https://cloud.githubusercontent.com/assets/2174294/22054928/5b77efb6-dd93-11e6-8916-ada7bfec09e9.png)

如果能提供能重现的 markdown 文档就好了，我分析一下是什么问题。
