### ISSUE TITLE
边编辑边预览，卡顿感明显

### ISSUE THREAD

**Issue by sasuke6** [oulvhai/MWeb-issues#445]
一边编辑一边预览的时候，⌘ + 4模式，输入法输入的速度变得很慢，卡顿感明显，字母输入已经完成但还没出现，取消⌘ + 4后缓和

**Comment by amooly** [comment]
同感，这个问题，最近时常出现。在mweblite上就没有出现。

**Comment by brickmaker** [comment]
目前最新的还是有这个问题，3.1.6 MacOS 10.13.6
