### ISSUE TITLE
建议：打开编辑模式下 link clickable 时，可否配置 cmd按下时才可 click

### ISSUE THREAD

**Issue by knightli** [oulvhai/MWeb-issues#45]
这个 clickable 有时候挺实用  
但有时候又会造成困扰：
- 有时候会误点击到
- 有时候希望编辑 link 相关的文字或链接地址，但光标就无法方便的点到要修改的位置，只能点在旁边，再方向键移动光标

联想了下其他类似软件里的体验，觉得默认不可点，按下 cmd 键之后可点是个不错的主意
供 @oulvhai 参考 :)

**Comment by oulvhai** [comment]
不错的建议！

**Comment by oulvhai** [comment]
最新版本已实现。
