### ISSUE TITLE
发布到Evernote报错

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#452]
试了好几篇文章，都报了同样的错误，错误如下图所示：

![image](https://cloud.githubusercontent.com/assets/733113/22489031/24672ddc-e80d-11e6-96c2-6225df27accf.png)

**Comment by oulvhai** [comment]
更新到最新版本试试。

**Comment by yajiez** [comment]
目前版本是2.1.4，在APP Store没发现有更新

**Comment by oulvhai** [comment]
这个错误是说你的文档中有 <h3 这个元素，然后其中有为 id 的属性，这个 id 属性不被印象笔记支持。 总的来说是像 `<h3 id="">` 这样的 html。 如果你的文档中没有，可以试试删除 MWeb App，然后重新下载试试。

**Comment by yajiez** [comment]
文档中的三级标题都是直接使用###表示的，没有显式的给出id属性。

如果重新安装MWeb，之前的各种相应配置还有文档库什么的需要手动备份处理吗？

**Comment by oulvhai** [comment]
@xiruizhifu 看来是安装包有问题，直接删除 App 不用备份。
