### ISSUE TITLE
导出PDF时，PDF会多出一个空白页

### ISSUE THREAD

**Issue by dalutou** [oulvhai/MWeb-issues#455]
右键点击第二栏中的文档列表，选择「导出为 PDF...」，生成的PDF会多出一个空白页。

点击右上角的导出图标，选择「保存为 PDF」，则一切正常，不会产生空白页。

macOS 10.12.3 / MWeb 2.1.4

**Comment by oulvhai** [comment]
3.1.8 已解决。
