### ISSUE TITLE
将预览中内容粘贴到mail.app中后文章内跳转超链接失效

### ISSUE THREAD

**Issue by nsolcampbell** [oulvhai/MWeb-issues#46]
在mail中粘贴后超链接样式仍然存在但是点击没有反应了，有办法修复么？

**Comment by oulvhai** [comment]
mail app 里用： 右键连接： Open Link 即可。

**Comment by nsolcampbell** [comment]
跳转到外部链接是可以的，但是跳转到文章内部的链接好像不行，比如TOC生成的目录的连接就失效了

**Comment by oulvhai** [comment]
喔，这个目前还没找到能解决的方法 --> 估计也没办法解决这个的。。
