### ISSUE TITLE
上传图片后直接复制带有Markdown语法的图片链接

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#462]
在将本地图片上传至图床后，在那个上传窗口点击眼睛图标就能打开浏览器看图片了，所以单纯的复制图片链接的意义就不是很大了，所以如果能够复制得到带有Markdown语法的图片链接会更方便一些。

比如这样：

`![](http://i.imgur.com/KgUPme1.png)`

**Comment by oulvhai** [comment]
这个也没意义，你直接点以边的复制 markdown 按钮，所有本地图片都会替换好并复制到剪切板。

**Comment by yajiez** [comment]
但是，点击复制 markdown 按钮会复制本文档的所有内容，但是有时候只需要复制图片链接

**Comment by oulvhai** [comment]
其实你可以先点工具栏上的插入图片的markdown语法按钮，好像快捷键都有。然后再粘贴图片网址。

**Comment by yajiez** [comment]
唉，要是其他地方编辑起来都像MWeb这么方便就好了，主要是这个使用场景太频繁，所以减少一个步骤就会让整个流程快很多，这个是非常细的个人化需求，如果觉得没必要还是算了。

**Comment by yajiez** [comment]
刚才因为这个被关了重新开了一个，也一并关了吧，只是希望可以考虑一下能否在图片上添加一个右键菜单，感谢🙏
