### ISSUE TITLE
行内的==解析为高亮

### ISSUE THREAD

**Issue by Jackliu91** [oulvhai/MWeb-issues#47]
我的一行内容中需要==，这个==会被解析为当前行高亮，有没有转义的办法？
还有因为只是一个符号，我不想用`==`这种插入代码的方式。

**Comment by oulvhai** [comment]
目前的解决办法只有加 \， 像这样： \==不高亮内容==  或者全部 = 前面都加 \ 也是可以的。

**Comment by Jackliu91** [comment]
3q！暂时只能这么解决了。不过这样的话在其他markdown编辑器中会造成歧义。

**Comment by oulvhai** [comment]
这个是官方语法，应该不会有影响。

**Comment by Jackliu91** [comment]
但比方说我在github中 打\==就是\==啊 不会转义

**Comment by oulvhai** [comment]
呃，也是喔。。 下次加个选项好了。

**Comment by Jackliu91** [comment]
谢谢，刚从mou转过来，希望越做越好。

刘建坤，云南大学软件学院
