### ISSUE TITLE
导出HTML 流程图不显示

### ISSUE THREAD

**Issue by LiSunny** [oulvhai/MWeb-issues#470]
将画好的流程图导出HTML  在Google Safari 都不显示 直接显示源码 这是什么情况
<img width="346" alt="2017-02-16 1 50 36" src="https://cloud.githubusercontent.com/assets/10544522/23009131/23bdaf16-f44f-11e6-906e-3a87dc9a0c6f.png">

**Comment by oulvhai** [comment]
导出时的面板在会有一个选项的按钮，点开后会有一个顺序图和流程图的复选框，勾选即可。

**Comment by LiSunny** [comment]
OK 谢谢 很有责任感的独立开发者 赞一个
> 在 2017年2月17日，上午11:27，Otis <notifications@github.com> 写道：
> 
> 的面板在会有一个选项的按钮，点开后会有一

**Comment by hh-in-zhuzhou** [comment]
这个选项不仔细看还真发现不了

**Comment by oulvhai** [comment]
计划改进一下这个，也就是按 markdown 文档智能选择吧 :D

**Comment by oulvhai** [comment]
3.1.8 版本已实现按 markdown 文档内容智能选择。
