### ISSUE TITLE
Mac版的设置里主题样式的字体大小设置有问题

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#472]
实时预览会慢半拍。比如原本是14，然后你改成1，这时没反应，你改成20，这时显示的就是1大小的了。也就是说，实时更新的预览结果总是上一条的，而不是当前的。

用自带的+1，-1的控件也能试出来。比如你点3次字体变大，然后点一下字体变小，虽然你点的是字体变小，但是实际上它反映的上一条，所以实际编辑界面的字体反而是变大的。

这个最大的麻烦，由于你预览的不是当前的设置，而是上一条。当你满意之后，关了程序，下次再开MWeb时，由于程序加载时是设置里的实际值，因此打开的效果和之前的预览的是不一样的。

**Comment by oulvhai** [comment]
3.1.8 版本修改了设置方式。
