### ISSUE TITLE
内部模式文件管理方式

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#475]
点击父目录会连同子孙目录的文件一起显示出来，这十分不合理，这其实是递归显示，请增加非递归显示，只显示当前目录文档

**Comment by oulvhai** [comment]
加个选项的话，的确可以考虑。

**Comment by fmewtwo** [comment]
请尽快支持非递归显示，作为目录应该首先支持非递归显示，然后在功能的扩展上可以拥有递归显示，你见过哪个系统的目录默认是递归显示文件的？文件目录层级一多，上层目录根本找不到自己文件了，你不难受么。

**Comment by oulvhai** [comment]
@1412kid 之后我又考虑了一下，由于 MWeb 的设计问题（一个文档可以多分类） ，所以不递归显示会有点奇怪。。 所以，要这个功能的，直接用外部模式好了，外部模式还能更好同步呢。

**Comment by fmewtwo** [comment]
>（一个文档可以多分类） ，所以不递归显示会有点奇怪。
@oulvhai  我就不明白，你到底是怎么想的。
1. 一个文档因为可以多分类才更能体现一个目录只显示隶属于该目录文件的重要性，B目录是A目录的子目录，我勾选一个文件只隶属于B而不隶属于A，为什么要在A中显示此文件？这个显示结果和同时勾选AB是一样的，如果我确实想这么干，我直接AB都勾选好了，你给了用户勾选方式，你的目录视图根本做的不够彻底，勾选与视图的呈现存在矛盾。
2.  用内部模式存储的文档都快500多份了，很多文件都是从未知笔记移来的，而且你的内部模式才支持博客，你现在让我用外部模式， 你是在搪塞我吗？ 你的外部模式目录支持的就很优秀么，你的外部模式好像还显示子一级目录的文档，尽管你用目录名隔开了，子目录一多父目录的感觉仍然是一坨，
3.  既然支持多级目录管理文档，然后点击一个目录递归显示出所有文件，这就是反人类！ 就系统而言这和mac、windows文件管理方式没什么不同。
4.  四我也不想再说什么了，这个问题仅仅就是修复勾选目录级后的view，你看着办吧，我是个文档很多的人，你的这个目录视图就是个差评！

**Comment by oulvhai** [comment]
@1412kid  感谢如此详细说明，其实点父分类递归显示的原因是： wordpress 或者几乎全部网站都是这样做的。 我建议你用外部模式并非随便说的，单单静态博客这种功能，外部模式用 hexo 这种明显更强大和跨平台。 然后外部模式是否显示子一级目录，可以设置一下的（默认是显示）

如果加了这个选项，首先分类的文档统计数要变动，然后很多情况下可能点了父分类，列表中没看到什么文档，用户会疑惑，因为所有的使用习惯都是父分类包括所有子分类的文档。

**Comment by 1412kid** [comment]
我终于知道问题的根源了，你的观点是文档库是作为博客内容的仓库，在这个立场上，父目录递归显示子文件是理所当然的，这的确是理所当然。作为个人知识库应该使用外部模式，因为作为个人知识库这个立场，非递归显示文件是必须的。没错，外部模式+hexo的确可以完成一个markdown到博客的发布，不过这似乎对小白来说有点门槛，其他先不说，hexo的各种使用要各种命令，不是每一个mac用户都知道那个终端是干啥用的——！，我当初使用mweb认为外部模式可以用来管理一系列现有的文档，也可以引用同步盘实现多人编辑，不过这个内部模式更适合用来构建个人知识库。
1. 我们并不需要知道文档究竟在磁盘的哪个具体目录，只要逻辑上的分类正确就可以，未知笔记如此，mweb也是如此，我们只需要知道整个文档库在哪，并把文档库做好备份就可以万事大吉。
2. 当需要导出一个文件给他人时，直接用mweb导出即可，也不需要到finder中cp一份。
3. 最重要的一点，整个知识库中想发表哪篇文档，就勾选哪篇，点击重新生成博客，git到服务器完成了。
以上3点，使我用内部模式构建了一个知识库，在内部模式中，有一个一级目录作为博客，博客中有各种子目录，其他的一级目录都是文档库，当文档库中谋篇文档要发表时，直接在对应的博客目录中勾选，自去年7月份以来，就是这么干的而且并没有什么不愉快的地方，直到文档库的子目录变多，文档变多，才使我感到视觉上恶心。
文档库作为知识库并没有什么不可以，各种条件都具备，除了这递归问题。
总而言之就是使用姿势不同，不知道有没有跟我一样的人。

问题解决参考
文档库就是文档的仓库，不是博客内容的仓库。在这个立场观点中，将一个目录设置为文档库，应该有非递归的视图支持。将一个目录设置为静态网站后，目录就应该递归显示文件
作者看着办吧，最后一次讨论该问题。

**Comment by fmewtwo** [comment]
@oulvhai 我终于知道问题的根源了，你的观点是文档库是作为博客内容的仓库，在这个立场上，父目录递归显示子文件是理所当然的，这的确是理所当然。作为个人知识库应该使用外部模式，因为作为个人知识库这个立场，非递归显示文件是必须的。没错，外部模式+hexo的确可以完成一个markdown到博客的发布，不过这似乎对小白来说有点门槛，其他先不说，hexo的各种使用要各种命令，不是每一个mac用户都知道那个终端是干啥用的——！，我当初使用mweb认为外部模式可以用来管理一系列现有的文档，也可以引用同步盘实现多人编辑，不过这个内部模式更适合用来构建个人知识库。
1. 我们并不需要知道文档究竟在磁盘的哪个具体目录，只要逻辑上的分类正确就可以，未知笔记如此，mweb也是如此，我们只需要知道整个文档库在哪，并把文档库做好备份就可以万事大吉。
2. 当需要导出一个文件给他人时，直接用mweb导出即可，也不需要到finder中cp一份。
3. 最重要的一点，整个知识库中想发表哪篇文档，就勾选哪篇，点击重新生成博客，git到服务器完成了。
以上3点，使我用内部模式构建了一个知识库，在内部模式中，有一个一级目录作为博客，博客中有各种子目录，其他的一级目录都是文档库，当文档库中谋篇文档要发表时，直接在对应的博客目录中勾选，自去年7月份以来，就是这么干的而且并没有什么不愉快的地方，直到文档库的子目录变多，文档变多，才使我感到视觉上恶心。
文档库作为知识库并没有什么不可以，各种条件都具备，除了这递归问题。
总而言之就是使用姿势不同，不知道有没有跟我一样的人。

问题解决参考
文档库就是文档的仓库，不是博客内容的仓库。在这个立场观点中，将一个目录设置为文档库，应该有非递归的视图支持。将一个目录设置为静态网站后，目录就应该递归显示文件
作者看着办吧，最后一次讨论该问题。

**Comment by 1412kid** [comment]
再补充一点，用户用你的外部模式构建了一个知识库，然后想发表某篇文章同时想使用你的博客功能，还得将这片文章复制到内部模式中是么？呵呵！

**Comment by oulvhai** [comment]
@1412kid 的确是各人的用法不同，当时我做的是文档库分类和静态网站分类可以相互无损转化，所以即使递归显示做的时候比非递归困难很多，性能也差很多，但是也必须这样做了。也从未觉得这是不合理的，然后你也是第一个反馈这部分。
我的意见是，如果是要加个选项区分开来，如果不是 MWeb 蛮多用户需求这样的话， 是会增加复杂度的。软件增加复杂度当然是会更强大，但是也要花更多精力保持稳定和后续的维护，毕竟只能加功能，不能减功能的。

我加个 讨论的标签，另外，针对你这个需求，我也会再考虑考虑是否有另外的方式。 

再有就是：全部用外部模式也是可以的吧，hexo 命令行没有很难用的。

**Comment by 275445361** [comment]
@oulvhai  一开始也是直接用的内部模式，感觉内部模式比外部模式功能多，最近新增的目录统计数也都是内部模式有而外部模式没有，内部模式有标签外部模式也没有，不公平啊-。-，内部模式的确不适合寻找属于父目录的文件，现在已经使用外部模式了，我不喜欢发博客，对于博客功能到时无所谓-0-

**Comment by fmewtwo** [comment]
@oulvhai  深夜收到另一个用户讨论的email，使我又忍不住又想多说几句0.0！作者见谅吧
这一次从产品的角度来说，mweb分为内部模式和外部模式，内部模式与外部模式该怎么理解？作为一个普通用户+有软件使用经验的用户来说， 内部模式应该理解为：mweb自身管理文件的方式，这种方式与为知笔记或有道笔记或印象笔记是一样的，用户可以基于这种方式创建文件，用户不需要知道文件的保存形式，一切由软件来帮你管理，这就叫“笔记系统“。 外部模式应该理解为：可以通过该软件来管理现有目录文件或创建新的文件位于指定磁盘目录，这种方式与sublime与typora 一样的，这种方式其实充当的是”编辑器“的角色。
（说到这顺便赞美一下mweb这两种方式，这两种方式使其成为markdown的大杀器一点也没错，我曾试用用过的关于markdown”编辑器产“产品有，Byword，typora，Haroopad，sublime，类似”笔记系统“的有道笔记、为知笔记、TextNut，ulysses，有的太贵用不起，有的效果太垃圾，曾经使为知笔记，要不是它15年11月-16年7月一直不更新，很多效果体验差，我也就不知道有mweb了-.-!  扯远了)
@275445361  谈到这里，那么内部模式比外部模式功能多，我觉得是个必然

----

以上就是我理解所谓的"内部模式"，如果我理解的是对的或者大众用户是这么理解的话，那么文档库可以生成静态博客仅仅是这个模式的一个功能！那么抛开这个功能的话，拥有非递归的视图再正常不过了。

作者的出发点或观点是：内部模式仅仅是一个博客后台，递归视图才是正常的。

**Comment by oulvhai** [comment]
@1412kid @275445361 我又想了一下，感觉可以在文档列表那里加一个是否按分类分组的功能。开启这个功能后，文档列表中的显示会像 Ulysses 那样，然后属于父分类但是不属于任何子分类（即未分类）的文档就会在最前面，从而达成你们的需求。 这样的好处是不影响现在的概念。 不知道我说清楚这个功能了没有。

**Comment by fmewtwo** [comment]
@oulvhai  >然后属于父分类但是不属于任何子分类（即未分类）的文档就会在最前面   没明白，不过我特意又下载了Ulysses， Ulysses也是递归显示的文件，只不过它会把当前目录的的文件放在最前面，如果是和Ulysses的方式一样也是可以接受的， 最起码能看清当前目录有哪些文档，而现在mweb内部模式文档列表就是一锅粥啊！

Ulysses其实应该是作者模仿的对象，Ulysses也是内部模式+外部模式，仔细测试了Ulysses还是很强大的，而且是UI更胜一筹啊，我觉得Ulysses可以更换目录图标等功能都是很不错的，这些都可以抄过来啊，不过mweb更适合国人

因为mweb文档库列表不好，突然有不想用mweb的冲动，不知道将来有没有文档库批量转换外部模式的方式，这可能略复杂，如文档引用链接等都得考虑， 当然了，还没见过哪个笔记系统能有这个功能，使用类似内部模式可能意味着被这款软件绑架，移植性最好的还是外部模式， 但是还是觉得内部模式用起来省心舒服。

我不清楚作者心中定位的文档库到底是个怎么的概念， 但有一点我还是想强调一下：正如和Ulysses的文档库一样，文档库就是本软件自身管理文档的方式，所以在视图、查找、定位这些功能要尽量做的舒服。文档库不能定位成一个类似wordpress博客管理后台，如果是这样，那么mweb的内部模式就仅是一个生成博客的工具了。

**Comment by oulvhai** [comment]
@1412kid 的确是你说的那个方式。MWeb 文档库的定位是这样的：当时做 MWeb 的时候首先是要满足生成博客的功能，然后因为 wordpress 的这种结构，本身就可以用来管理笔记，所以就都做成跟 Wordpress 一样。 MWeb 也正是因为这点而用上数据库，然后后来做 iOS 和做同步就变得不方便起来了。 这个模式目前已经是不可逆的了，正如之前所说，软件只能加功能，不可能减功能。一般的做法是出一个 3.0 版，重新设计，去掉一些功能，增强一些功能，但是目前还没有这个计划。

如果要转换，可以试试右键分类 - 导出为 markdown，只是这个功能并不会保持目录结构。MWeb 的文档库是开放的，文档库结构由一个 mainlib.db 和 一个 docs 文件夹组成，docs 文件夹内是所有的笔记。对这个导出不满意的话，就只能自行写程序导出了。

再说说，Ulysses 其实不是 MWeb 的模仿对象，独立开发者的任何软件都是先满足自己的需求的，也就是基本上是独一无二的 :D 。

**Comment by fmewtwo** [comment]
mweb 版本2.2.1 终于见到了按分类分组，解决了多层目录下文件所属的视图问题，能一眼看出这个文件隶属于哪个目录里了。
美中不足就是感觉好丑啊。这个UI设计有待优化啊  >.<

**Comment by oulvhai** [comment]
@1412kid  目前的确问题不少，不过还是基本可用的。。然而还是有种想全部重写，而且仅支持 macOS 10.13 及以上的冲动。

**Comment by aRe00t** [comment]
请问 *按分类分组* 在哪里, 右键菜单里看不到啊.  版本 2.2.7 (303)

**Comment by fmewtwo** [comment]
@aRe00t   三栏视图， 中间视图右键点击一个文件就能看到， 我说的是内部模式

**Comment by yeatszhang** [comment]
非常感谢解决该问题！
