### ISSUE TITLE
导出HTML时代码段没有语法高亮

### ISSUE THREAD

**Issue by libotony** [oulvhai/MWeb-issues#48]
我平时预览用mweb-github，文件内容会包含一定的代码段，预览和导出PDF时，代码段是有语法高亮的，但是导出HTML后缺没有语法高亮
<img width="486" alt="2015-09-21 12 48 58" src="https://cloud.githubusercontent.com/assets/8411962/9985490/5c1e0836-605f-11e5-99f8-356091724c35.png">
上图为编辑器以及LivePreview
<img width="311" alt="2015-09-21 12 49 22" src="https://cloud.githubusercontent.com/assets/8411962/9985492/5f42cb32-605f-11e5-8e07-6bc07b9e0f1d.png">
上图为导出的html文件在chrome中打开的效果
<img width="329" alt="2015-09-21 12 49 34" src="https://cloud.githubusercontent.com/assets/8411962/9985493/6210675c-605f-11e5-98f3-001060a4d980.png">
上图为导出的PDF打开的效果

**Comment by oulvhai** [comment]
原来 EL Capitan 会隐藏掉选项。。 我估计你也是在用 EL Capitan 不然不会没有注意到选项。。 如下图，点 Options 就会看到了，

![snip20150921_1](https://cloud.githubusercontent.com/assets/2174294/9985729/2d55e96a-6064-11e5-831c-0539aeceb07c.png)

**Comment by libotony** [comment]
我用的yosemite，不过没注意到，多谢啦
