### ISSUE TITLE
文档引用链接出现bug

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#480]
内部库模式中,一个文档引用链接第一次打开很好，然后关闭打开的标签页，第二次打开将会是一片空白，bug请尽快修复。以前没记得有过，当前软件版本为2.1.6

**Comment by oulvhai** [comment]
10.11 下未能重现，你的系统版本是？

**Comment by 1412kid** [comment]
我的系统版本是10.11.6 @oulvhai

**Comment by fmewtwo** [comment]
@oulvhai   新更新的2.1.7  文档引用链接依然有bug，只有我自己有这bug吗？  我系统版本10.11.6，问题重现请参看https://ooo.0o0.ooo/2017/03/14/58c7c82ae8bb5.gif  如果是这有我这问题，请给予指导。

**Comment by oulvhai** [comment]
@1412kid 确认 bug，非常感谢！

**Comment by fmewtwo** [comment]
原来这个bug存在好久了， 在 #330 就已经被标注bug了，这么久了都没修复， 浏览了很多issues， 感觉不错的功能还不少而且都被标注enhancement，有的都快1年了，也没见实现！

**Comment by oulvhai** [comment]
@1412kid 软件并非一定要实现所有 enhancement 的 issue，都会有各种考量。然后，总会有各种 issue 的，enhancement 然后并不修这种，有可能是很麻烦的，有些是我研究后不知道怎么修的，还有不影响核心功能的，或者有就更好，没有也能有其他方式用的。 enhancement 的意义还在于：作为下一个重构的大版本的参考。

**Comment by oulvhai** [comment]
@1412kid 这些情况也只有真做过软件才能真了解 :D

**Comment by fmewtwo** [comment]
mweb 2.2.1 版本修复了该bug
