### ISSUE TITLE
含有本地图片的md文件关闭再打开后，图片不再显示了

### ISSUE THREAD

**Issue by indicolite** [oulvhai/MWeb-issues#487]
含有本地图片的md文件关闭再打开后，图片不再显示了，变成只显示一个框框，里面一个问号。谢谢

**Comment by oulvhai** [comment]
可以看看是不是： http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html 这个问题。

**Comment by indicolite** [comment]
已设置，图片显示正常。感谢LZ！！
