### ISSUE TITLE
app store上购买的出现这个问题，无法编辑存储地址

### ISSUE THREAD

**Issue by jinphen** [oulvhai/MWeb-issues#49]
![image](https://cloud.githubusercontent.com/assets/4998074/10009861/5df91388-6115-11e5-8f15-effe5bcb65b7.png)

**Comment by jinphen** [comment]
和Themes切换一下就闪退了
![image](https://cloud.githubusercontent.com/assets/4998074/10009881/a3ec63a4-6115-11e5-9ccd-d46d32b2acb0.png)

**Comment by oulvhai** [comment]
问题 1 请打开文档库，然后右键自带的 MWeb 分类，选择 Build Site， 这样就没问题了。 如果 MWeb 分类已删除，请 Build Site 任何一个分类一次即可。（修正版过两天就提交）

问题 2 是切换预览 CSS 吧？我没遇到过。我再测试测试看看。

**Comment by jinphen** [comment]
嗯，Build Site之后General有内容了。但如果在没有Build Site的情况下General是空的，就如问题1，在空的情况下切换到Themes，再切回来或重复切几下，程序就挂了。

**Comment by oulvhai** [comment]
嗯，这问题已修正了，修正版也已提交。 过 10 天左右应该可以通过审核并上架。

**Comment by jinphen** [comment]
好的，谢谢~~~
