### ISSUE TITLE
如何从Time Machine备份中恢复文档

### ISSUE THREAD

**Issue by yunhao** [oulvhai/MWeb-issues#499]
由于MacOS出了问题，使用Time Machine全盘备份后重装了系统。然后发现自己大意了，之前MWeb导出的备份并不是最新的，还缺失几篇。不知道可以从Time Machine备份中恢复文档吗（只恢复MWeb不恢复系统）。谢谢

**Comment by taohonker** [comment]
我之前遇到过这种情况，在你自己认定的 Library Location 处恢复，里面有 docs, mainlib.db, metadata 等内容。

**Comment by oulvhai** [comment]
我先介绍一下 MWeb 的文档库的结构，为：

docs 文件夹，里面放的是每一篇笔记，每个文件名是像 `14155103200742.md` 这样的，为独立的 markdown 文档，可以直接打开和修改， docs 里的 media 文件夹则是放笔记的附件。
mainlib.db 文件是保存文档库的分类、标签和分类所属的笔记
metadata 文件夹是保存发布服务和图床上传的信息

了解了这个，就应该知道怎么恢复了。

**Comment by yunhao** [comment]
问题已解决，谢谢
