### ISSUE TITLE
希望点击dock上的图标后，能显示窗口及原有内容，能继续编辑

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#5]
现在mweb的行为是这样的：
1. 点击关闭后，窗口消失
2. 点击dock上的图标后，没有任何反应
3. 按快捷键cmd+L后，可以打开窗口，但光标不在编辑器，之前的光标位置也丢失

期望行为：
1. 点击关闭后，窗口消失 （不变）
2. 点击dock上的图标后，显示原来的窗口
3. 并且聚焦于编辑器，以及上次的编辑位置，可以直接继续编辑

我刚测试了一下我常用的其它软件:unibox, chrome, EuDic, omnifocus, sky, qq, sublime, sourcetree, slack，它们的行为都是一致的：点击dock上的图标后，将会显示原有窗口或新窗口。希望mweb也能提供这样的功能（或者至少提供一个选项）

现在的行为给我带来的不便：
1. 点击dock图标没有反应，让我觉得很奇怪，开始还为以程序崩溃了
2. 我必须知道cmd + L这个快捷键，才能打开原有窗口
3. 原来的光标位置没了，也没有focus在编辑器，我可能需要先点击一下编辑器，然后再想一想才能找到这次正在编辑的位置，比较累
4. 我使用了apptivate来自定义快捷键快速启动程序，对于其它的程序，我在任何情况下都可以按一下快捷键就打开，但对于mweb，我需要先按一下那个快捷键，再按cmd+L，不太方便

**Comment by oulvhai** [comment]
耶，这样说来是要重点考虑了。

**Comment by freewind** [comment]
:+1:
