### ISSUE TITLE
可以添加管理本地md文件的功能吗

### ISSUE THREAD

**Issue by mio4kon** [oulvhai/MWeb-issues#50]
把Mweb当纯md工具,但发现无法导入写好的源文件进行归类(事实上是可以导入,但并非源文件,修改后源文件并不修改).现在只能到保存md的文件夹中打开md文件才能修改源文件.

**Comment by oulvhai** [comment]
请使用外部模式。
CMD + E 打开外部模式，点左下角的 + 增加文件夹 或者 直接把文件夹拖入（仅限付费版）
