### ISSUE TITLE
mac系统10.11.6， 无法更新版本。

### ISSUE THREAD

**Issue by beiyeren** [oulvhai/MWeb-issues#501]
从2.1.5升级到2.1.6以及2.1.6升级2.1.7，都是卡在解压更新这个界面。
重试过很多次。

**Comment by oulvhai** [comment]
抱歉，漏回了！！
目前可以直接去 mweb.im 官网下载试用版即可。 会自动激活的。

**Comment by beiyeren** [comment]
好的
