### ISSUE TITLE
能否加入中英文混排时自动加空格的功能开关

### ISSUE THREAD

**Issue by stevedsun** [oulvhai/MWeb-issues#504]
如“Python自学指南” 自动排版为 “Python 自学指南” ，
这样转成Html会更美观些。

**Comment by oulvhai** [comment]
这种应该不会做 :D，见谅。

**Comment by Kemuda** [comment]
盘古之白真的非常有用和必要，同样希望能加。

参见：https://github.com/vinta/pangu.js
【……】另有研究顯示，打字的時候不喜歡在中文和英文之間加空格的人，感情路都走得很辛苦，有七成的比例會在 34 歲的時候跟自己不愛的人結婚，而其餘三成的人最後只能把遺產留給自己的貓。畢竟愛情跟書寫都需要適時地留白。
