### ISSUE TITLE
tab缩进多次会换行, 设置了每行1500字符依旧很早就换行

### ISSUE THREAD

**Issue by Gohan** [oulvhai/MWeb-issues#51]
如题, 一直空格则没有问题.
另外没找到怎么显示编辑区的行号, 这个还是有点用的.

**Comment by oulvhai** [comment]
现在还不支持不换行，行号也是不支持的。 
然后设置那个不是每行字符数，是宽度。。 这个的意思是如果大于设定的宽度，就会把内容居中。单纯为了好看而已。
