### ISSUE TITLE
请支持文档库文件查询时连同目录名一起显示出来

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#516]
在 #475  的讨论后， 如果作者采用UIysses的文档库视图，那就再好不过了， UIysses的文件查询时也会连同目录一起显示出来，对于在大量文档中清晰定位一个文档的有很大的帮助。

其实查询时在内部模式和外部模式都采用这种视图都是很不错的，不过mweb的外部模式只支持当前目录查询则体现效果不如内部模式大。

不知道其他的issues有没有提到让外部模式支持全目录查询，我觉得外部模式需要有全目录查询的功能，在此多少提一下吧。

**Comment by oulvhai** [comment]
外部模式全目录查询不是没考虑过，只是目前我还无法解决如果文件夹文件数很多的情况下的性能问题。另外 #475 这个已计划改进了，这个是核心体验，然后还不是很麻烦，我准备下个版本改进。
