### ISSUE TITLE
驗證wordpress.org出現error message

### ISSUE THREAD

**Issue by yulai** [oulvhai/MWeb-issues#518]
您好，之前試用時發現可以順利將自架設的wordpress加入發布服務
後來購買更新後，就無法驗證，並出現以下的錯誤訊息
<img width="416" alt="2017-03-28 1 47 43" src="https://cloud.githubusercontent.com/assets/6111332/24370444/04dc22e2-135a-11e7-8464-e6c44c4fe36a.png">

請問這是什麼原因呢？xmlrpc.php也可以正常獲取
懇請賜教，感謝:D
http://yukishi.tw/xmlrpc.php

**Comment by oulvhai** [comment]
我记得我回过这个问题的邮件。

就是你的 xmlrpc 的地址会重定向为 http://yukishi.tw/xmlrpc.php?i=1 ， 所以建议你博客类型那里选择 metaweblog API ，然后发布 API 填入 http://yukishi.tw/xmlrpc.php?i=1 试试。

**Comment by yulai** [comment]
謝謝您，我後來嘗試還是發現會出現
<img width="518" alt="2017-05-19 10 46 29" src="https://cloud.githubusercontent.com/assets/6111332/26231226/a666142a-3c80-11e7-9a22-e65012a23bcb.png">
不支援的URL
還有其他可以嘗試解決錯誤的方法嗎？
謝謝:)

**Comment by oulvhai** [comment]
@yulai 你的 blog 的 xmlrpc 好奇怪，第一次开 http://yukishi.tw/xmlrpc.php 会定向到  http://yukishi.tw/xmlrpc.php?i=1 然后再次开  http://yukishi.tw/xmlrpc.php 就不会重定向了。有没有可能是安装了什么 wordpress 的 xmlrpc 的安全插件导致？

**Comment by yulai** [comment]
感謝您提供方向，後來我發現應該是主機商問題，我換了主機商這個問題就解決了，謝謝您:)
