### ISSUE TITLE
更改文章日期后，文章列表的焦点不对

### ISSUE THREAD

**Issue by iwinux** [oulvhai/MWeb-issues#52]
复现步骤：（在一个设定了 `Order by Newest on Top` 的分类里）选中一篇文章，设定一个比当前日期早的日期。

现象：这篇文章会被移动到列表的底部，列表里的焦点自动切换到了原位置的下一篇文章，但是编辑器里的焦点还保持在当前文章。

截图：

![2015-09-30 at 11 56](https://cloud.githubusercontent.com/assets/98864/10184126/bc8a2198-676a-11e5-8917-db532797abea.png)

**Comment by oulvhai** [comment]
2.0 版由于加了 Tabs 功能，文章列表变成纯导航了，焦点无意义了。
