### ISSUE TITLE
设置图片大小后 文字排版问题

### ISSUE THREAD

**Issue by 5lx** [oulvhai/MWeb-issues#523]
```
Mweb 版本: 2.1.7 (268)
```
```
![lxxx](xxx.png)
```
圆点盖住了图片
![image](https://cloud.githubusercontent.com/assets/6583339/24481813/f9e1e964-14ba-11e7-9310-802dd7515edf.png)

**Comment by oulvhai** [comment]
目前只能换个预览样式试试了。
