### ISSUE TITLE
发布到evernote国际版的时候，出现了如下提示，请问该怎么解决？谢谢

### ISSUE THREAD

**Issue by a1576799** [oulvhai/MWeb-issues#524]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=An invalid XML character (Unicode: 0x14) was found in the element content of the document.}

**Comment by oulvhai** [comment]
这个错误是说你的文档中有 0x14 这个印象笔记的 xml 格式不支持的字符，删除这个即可。 这个字符在 mweb 中是看不到的，在高级的编辑器，比如说 sublime 中有可能看到。

**Comment by a1576799** [comment]
非常感谢，但是我在sublime中没看到显示特殊字符，而且已经成功用sublime发布到Evernote了，已经放弃mweb了
