### ISSUE TITLE
单个文件破3万个字就特别卡顿

### ISSUE THREAD

**Issue by i5ting** [oulvhai/MWeb-issues#525]
非常明显

**Comment by oulvhai** [comment]
是不是边编辑边预览模式然后代码比较多？这样的话，可以试试菜单： 视图 - 在实时预览中关闭代码高亮。
或者不用边编辑边预览。

**Comment by fmewtwo** [comment]
+1, 文字很多时， cmd+1，2，3，4 切换视图会有很明显的卡顿
即便是在纯编辑模式下，连续用delete删除时文字时，也会出现卡顿

**Comment by oulvhai** [comment]
@1412kid 是这样，这部分之后再优化优化。

**Comment by windpls** [comment]
+1，写到1.1W字左右（没开Preview）能感受到些许卡顿了（MBP/I7/16GB RAM），建议尽快优化 @oulvhai

**Comment by oulvhai** [comment]
@windpls 我测试不出来，实际上我使用的话， 破 3w 都没感觉卡。请问你用的系统版本和输入法是？如果能提供原文档给我试试就更好了。

**Comment by windpls** [comment]
@oulvhai 系统版本是macOS Sierra 10.12.4，输入法是搜狗输入法（4.0.0.3496）具体卡顿的点主要是当文本较多时，使用delete键删除字符后会有小停顿，如果连续删除多个字符那就会造成明显停顿。

看了下，其实问题跟上面的1412kid提到的一样。

**Comment by windpls** [comment]
@oulvhai 此外，能不能添加一个选项来关闭编辑模式下的CSS渲染功能，使其变成一个纯文本编辑器？经常编辑大笔记，一不小心就10W+字了

**Comment by oulvhai** [comment]
@windpls 连续删除的确是，我测试得出来，感谢！另外纯文本的功能，暂时不太考虑，有空会尝试优化一下吧。。

**Comment by kchen0x** [comment]
@windpls 想要关闭编辑器的 CSS 其实很简单。

主题&样式 -> 编辑器主题 -> 编辑

自己创建一个空文本，例如我命名为 `zero.style` 然后，刷新，选择这个样式。

duang，MWeb 就变成一个纯文本编辑器了。

**Comment by ATiGr** [comment]
@quentin-chen 你这个hack有点厉害，哈哈，我咋就没想到呢。（我是完全自定义了一遍style文件，搞的更复杂了，哈哈）

**Comment by DeveloperErenLiu** [comment]
我也存在这个问题，字数超过两万以上就非常卡。
发现一个规律，如果打开三栏视图就不卡，四万多字都不卡，如果两栏视图或者只显示编辑页面，就超级卡，卡到不能动。。。

**Comment by oulvhai** [comment]
这个会一直优化，但是有些难以突破，先关。
