### ISSUE TITLE
新建一个 Category，build site 就会 crash

### ISSUE THREAD

**Issue by EggmanQi** [oulvhai/MWeb-issues#53]
10.10 & 10.11 均会发生。

Process:               MWeb [3913]
Path:                  /Applications/MWeb.app/Contents/MacOS/MWeb
Identifier:            com.coderforart.MWeb
Version:               1.7.1 (126)
App Item ID:           954188948
App External ID:       813281158
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MWeb [3913]
User ID:               501

Date/Time:             2015-10-02 09:16:41.548 +0800
OS Version:            Mac OS X 10.11 (15A284)
Report Version:        11
Anonymous UUID:        3139FFE9-8062-753E-E4C6-27B49DC887D1

Sleep/Wake UUID:       227C86A1-5C68-4460-B680-2AB60E59E96C

Time Awake Since Boot: 3000 seconds
Time Since Wake:       1900 seconds

System Integrity Protection: enabled

Crashed Thread:        4  Dispatch queue: com.coderforart.mweb.buildSite

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[13]'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff93f2fbd2 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff8d905dd4 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff93e2a06e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
3   CoreFoundation                      0x00007fff93e29efb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
4   MWeb                                0x0000000101332f51 MWeb + 884561
5   MWeb                                0x0000000101333044 MWeb + 884804
6   MWeb                                0x000000010133824e MWeb + 905806
7   MWeb                                0x00000001013ac66a MWeb + 1381994
8   libdispatch.dylib                   0x00007fff93df98ff _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x00007fff93dee453 _dispatch_client_callout + 8
10  libdispatch.dylib                   0x00007fff93df3083 _dispatch_queue_drain + 754
11  libdispatch.dylib                   0x00007fff93df96c9 _dispatch_queue_invoke + 549
12  libdispatch.dylib                   0x00007fff93dee453 _dispatch_client_callout + 8
13  libdispatch.dylib                   0x00007fff93df22e3 _dispatch_root_queue_drain + 1890
14  libdispatch.dylib                   0x00007fff93df1b48 _dispatch_worker_thread3 + 91
15  libsystem_pthread.dylib             0x00007fff945b04f2 _pthread_wqthread + 1129
16  libsystem_pthread.dylib             0x00007fff945ae375 start_wqthread + 13

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff9dcd1c96 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff9dcd10d7 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff93ea5024 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff93ea44ec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff93ea3d38 CFRunLoopRunSpecific + 296
5   com.apple.AppKit                0x00007fff9615b4b9 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 124
6   libsystem_trace.dylib           0x00007fff99608082 _os_activity_initiate + 75
7   com.apple.AppKit                0x00007fff961edd18 -[NSMenu performActionForItemAtIndex:] + 131
8   com.apple.AppKit                0x00007fff961edc8b -[NSMenu _internalPerformActionForItemAtIndex:] + 35
9   com.apple.AppKit                0x00007fff961edae3 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
10  com.apple.AppKit                0x00007fff9609223d NSSLMMenuEventHandler + 708
11  com.apple.HIToolbox             0x00007fff9805c98e DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) + 1231
12  com.apple.HIToolbox             0x00007fff9805be18 SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) + 404
13  com.apple.HIToolbox             0x00007fff98071df6 SendEventToEventTarget + 40
14  com.apple.HIToolbox             0x00007fff980bbd2e SendHICommandEvent(unsigned int, HICommand const_, unsigned int, unsigned int, unsigned char, void const_, OpaqueEventTargetRef_, OpaqueEventTargetRef_, OpaqueEventRef**) + 411
15  com.apple.HIToolbox             0x00007fff980e70f7 SendMenuCommandWithContextAndModifiers + 59
16  com.apple.HIToolbox             0x00007fff980e70a8 SendMenuItemSelectedEvent + 188
17  com.apple.HIToolbox             0x00007fff980e6f84 FinishMenuSelection(SelectionData_, MenuResult_, MenuResult_) + 96
18  com.apple.HIToolbox             0x00007fff980c5f11 PopUpMenuSelectCore(MenuData_, Point, double, Point, unsigned short, unsigned int, Rect const_, unsigned short, unsigned int, Rect const_, Rect const_, __CFDictionary const_, __CFString const*, OpaqueMenuRef**, unsigned short_) + 1794
19  com.apple.HIToolbox             0x00007fff980c4fec _HandlePopUpMenuSelection8(OpaqueMenuRef_, OpaqueEventRef_, unsigned int, Point, unsigned short, unsigned int, Rect const_, unsigned short, Rect const_, Rect const_, __CFDictionary const_, __CFString const_, OpaqueMenuRef*_, unsigned short_) + 610
20  com.apple.HIToolbox             0x00007fff980c4be3 _HandlePopUpMenuSelectionWithDictionary + 287
21  com.apple.AppKit                0x00007fff961e4b30 _NSSLMPopUpCarbonMenu3 + 6168
22  com.apple.AppKit                0x00007fff96306609 -[NSCarbonMenuImpl _popUpContextMenu:withEvent:forView:withFont:] + 200
23  com.apple.AppKit                0x00007fff9630646e -[NSMenu _popUpContextMenu:withEvent:forView:withFont:] + 194
24  com.apple.AppKit                0x00007fff966a71e4 -[NSView _showMenuForEvent:] + 85
25  com.apple.AppKit                0x00007fff963008e6 -[NSView rightMouseDown:] + 100
26  com.apple.AppKit                0x00007fff963e8a90 -[NSControl _rightMouseUpOrDown:] + 515
27  com.apple.AppKit                0x00007fff966b9cc1 -[NSWindow _reallySendEvent:isDelayedEvent:] + 2108
28  com.apple.AppKit                0x00007fff960fed31 -[NSWindow sendEvent:] + 517
29  com.apple.AppKit                0x00007fff9607ed5a -[NSApplication sendEvent:] + 2683
30  com.apple.AppKit                0x00007fff95ee5f3e -[NSApplication run] + 796
31  com.apple.AppKit                0x00007fff95eaf162 NSApplicationMain + 1176
32  libdyld.dylib                   0x00007fff9253a5ad start + 1

**Comment by oulvhai** [comment]
感谢报 Bug。 应该是没有文档属于这个 Category 的原因。 目前可以设置至少一个文档属于该 Category 再 Build site。 Build site 是只针对所选的 Category 的。

下次我加个提示。

**Comment by EggmanQi** [comment]
@oulvhai Category 里面是有内容的。

点击 Edit 设置 Build site，preview build site 的时候也会有问题，感觉是写路径的问题？

**Comment by oulvhai** [comment]
可否把 Edit 后出来的设置截图给我看一下？如果不方便公开的话，可以发 mail 给我。如果是路径问题，或者可以试试更新到 1.7.3， 然后再去 Preferences - Genaral 改一下 build site 的位置。 1.7.1 的是有些 bug 的。

**Comment by oulvhai** [comment]
1.9 已修正
