### ISSUE TITLE
MWeb可以显示代码块行号吗？

### ISSUE THREAD

**Issue by MayfeelYang** [oulvhai/MWeb-issues#530]

**Comment by MayfeelYang** [comment]
代码块的行号

**Comment by MayfeelYang** [comment]
show the line number of code block

**Comment by oulvhai** [comment]
MWeb 所用的代码高亮为 <https://highlightjs.org/>，其官方并没有支持行号，然后也没有好的插件支持这个。

**Comment by AlickH** [comment]
用这个 js 可以实现吗
https://github.com/mikkeloscar/SHJS-Linenumbers

**Comment by xfarmer** [comment]
show the line number of code block +1

**Comment by oulvhai** [comment]
@SIDmao 不可以，MWeb 用的是  https://highlightjs.org/ 这个高亮

**Comment by liqt** [comment]
这个有办法支持一下吗？ 还有支持设置代码块的主题样式吗？

**Comment by oulvhai** [comment]
主题样式在 CSS 中设置的，放倒最后即可。@liqt

**Comment by zombiecong** [comment]
https://github.com/wcoder/highlightjs-line-numbers.js ，这个可以吗？

**Comment by oulvhai** [comment]
@zombiecong 看上去不错，我整合一下看看效果。

**Comment by oulvhai** [comment]
to all

我试加了一下，发现样式冲突太多，然后所有预览样式都要修改和调整，包括静态网站部分，发到印象笔记的样式也问题比较大。 这个功能暂时不加了。

**Comment by luispuerto** [comment]
Line numbers in codeblocks whould be a wonderful feature. I've tried to implement changing the css, but I was able to add numbers just to the first line of the block. I don't know why...

**Comment by oulvhai** [comment]
MWeb 3 已把预览的高亮库换成 https://prismjs.com/ ，已支持行号。
