### ISSUE TITLE
建议：增加vim模式的编辑方式

### ISSUE THREAD

**Issue by jakerxu** [oulvhai/MWeb-issues#54]
- 平时一直使用vim编辑，希望作者增加这个模式，能有效提高编辑效率。
- 使用者很多程序员啊，vim/emacs党众多。 
- markdown plus新版本已实现，marked2也有vim模式，望参考。

**Comment by oulvhai** [comment]
是这样，之前也有朋友提过。其实最大的问题是我不会用 VIM。
我只能说有空研究研究看看。

WebView 类的 Markdown 编辑器基本上都统一用 https://ace.c9.io/build/kitchen-sink.html 这个库（本身支持 VIM 模式），加个 VIM 模式没有很麻烦，所以基本都支持 VIM 模式。

**Comment by nsolcampbell** [comment]
同希望有vim模式，在长文档下vim有很强大的优势，比较适合markdown。

**Comment by tinytub** [comment]
同希望有这个功能.用了几天 Lite, 用起来感觉很不错.忍不住买了付费版,如果再来个 VIM 模式那就完美了.

**Comment by defp** [comment]
我之前也是vim用户，不过感觉没啥必要
如果习惯hjkl的话，可以做下键绑定

**Comment by finviman** [comment]
加上当然好啦。

**Comment by toobigdata** [comment]
加上当然好啦。

**Comment by CodeTheWorld** [comment]
同求加

**Comment by xrivendell7** [comment]
同求加入Vim模式，这样更适合程序员使用

**Comment by oulvhai** [comment]
目前变成暂无计划了。 手动 [/点个蜡烛]
