### ISSUE TITLE
iCloud 内容同步太慢，能否增加一个手动刷新的机制？

### ISSUE THREAD

**Issue by 0xjiayu** [oulvhai/MWeb-issues#543]
如题，另外，Mac 端，偏好设置-->选择现有文档库-->iCloud Drive/MWeb/mweb_documents_library/
提示「错误：请选择一个有效的位置」

**Comment by 0xjiayu** [comment]
这个双端同步体验实在太影响使用了，害得我现在只能用「备忘录」作为双端同步的辅助中转工具：手动把iOS客户端的内容拷贝到备忘录的 iCloud 目录，再去 macOS 上从备忘录里把最新内容拷贝到 MWeb for Mac 客户端…

**Comment by oulvhai** [comment]
1. iCloud Drive 没有手动刷新这个功能，你让他刷新，实际上刷不刷，开发者也不知道。
2. 应该是用 “另存为” 这个按钮，不要用选择现有文档库
3. 系统备忘录用的是叫 Cloud Kit 的技术，听说是蛮快的，特点是不是文件系统，是数据库结构的，不适合 MWeb 用。

**Comment by 0xjiayu** [comment]
原来如此，多谢回复。

**Comment by vickiegpt** [comment]
Problem still exist.

**Comment by Holden-Lin** [comment]
我的ipad一直显示同步中
