### ISSUE TITLE
MWeb can't open PDFs in editor mode

### ISSUE THREAD

**Issue by teaqu** [oulvhai/MWeb-issues#548]
If I try to open a PDF file in editor mode, MWeb can't open the file. It looks like it might be because MWeb adds a full stop onto the extension so macOS doesn't know how to open it. 

<img width="629" alt="screen shot 2017-04-27 at 1 49 05 pm" src="https://cloud.githubusercontent.com/assets/583418/25496834/731bb476-2b50-11e7-918a-0a9b7305525a.png">

Thanks!

**Comment by oulvhai** [comment]
3.1.8 版本改为在 Finder 中显示。
