### ISSUE TITLE
发布到印象笔记失败

### ISSUE THREAD

**Issue by FrancisKong** [oulvhai/MWeb-issues#549]
将笔记发布到印象笔记时出现下面的错误：

<img width="470" alt="2017-05-02 22 44 29" src="https://cloud.githubusercontent.com/assets/7656698/25623145/0983e9d8-2f89-11e7-91b3-1d02046ba8bb.png">

**Comment by FrancisKong** [comment]
用 sublime 打开文档后看到了导致错误的特殊字符，删掉后就可以正常发布了

**Comment by YujieShui** [comment]
我也碰到这个错误，问问是打开什么文档，删了什么？没看懂 @FrancisKong

**Comment by FrancisKong** [comment]
就是用 sublime 打开你写的 markdown 文档，应该会看到一个特殊的字符（具体是什么我也不记得了），把那个字符删掉就好了 @YujieShui

**Comment by oulvhai** [comment]
目前最新版好像能自动过虑这种字符了，我测试了一些字符没问题，只是不知道全不全。

**Comment by YujieShui** [comment]
更新了也不行.. 而且没找到特殊字符😓 还好就一个文档不能同步，也没事
