### ISSUE TITLE
部分快捷键失效以及疑问

### ISSUE THREAD

**Issue by yuyandong** [oulvhai/MWeb-issues#55]
基于 Version 1.8.1 (148)
## 部分快捷键失效 ！！
- 在外部文件夹模式中，无法使用 'new  in liabrary ' 的快捷键 ( Shift + Command +N  ) 生成新的文档（ 文档模式可以生成）
- 更严重的是两个模式里都无法使用Command+F 进行 **查找**
## 为什么有些常用快捷键没有支持 ？
- 没有全屏模式的快捷键；
## 是否计划增加部分快捷键 ？
- 系统热键 显现／隐藏 MWeb ?  ( iTerm 2 这点上做的不错 )
- Toggle Floating  模式的快捷键 ？

**Comment by oulvhai** [comment]
外部模式新增文档目前好像没有做到快捷键（之后会加上，感谢提醒）。 
CMD + F 我在 EL Capitan 、 Yosemite 、Mavericks 中测试都没问题。你的情况是？

全屏模式和 Toggle Floating 的确没有快捷键，有考虑增加，但是快捷键的安排目前还没想好，所以才不做。全屏模式快捷键估计会先加上，因为这个应该没冲突的（感谢提醒）。

系统热键 暂时不考虑（这种热键应该给非常重要的 App，比如说截图类就可以用），感谢建议！

**Comment by yuyandong** [comment]
- CMD ＋ F 排查后发现是我个人的Alfred 的workflows 占用了，经此提醒，我已经找回。谢谢。

**Comment by yuyandong** [comment]
### V1.83 快捷键未增加

> 在外部文件夹模式中，无法使用'new in liabrary' 的快捷键 (Shift + Command +N) 生成新的文档（ 文档模式可以生成）

@oulvhai  ,没有这个快捷键真的很不方便，新建文件还需要去找文件夹。。。费时还打断思绪
在CMD+E模式中， 还是无法使用`Shift + Command +N`创建的当下使用的文件夹的新文档；
 `CMD＋N`  建议参考 Ulysses ，不要在让用户使用Find程序寻找本地存储位置

**Comment by oulvhai** [comment]
这个的确是未增加，主要是一直在考虑一并处理快捷键的问题。 

目前比较正常的使用方法是点 第二列下面搜寻框的 “+” 按钮。 当然使用 Finder 也是可以的，不过我觉得还是点 “+” 比较方便一点。 这个应该还是不会太影响使用的吧？因为 MWeb 目前是没有全面快捷键化的。
