### ISSUE TITLE
是否自定义默认新文件命名规则

### ISSUE THREAD

**Issue by ATiGr** [oulvhai/MWeb-issues#552]
是否可以允许用户自定义新文件命名规则。

现在我在外部模式下，新建笔记，默认的名称为 `YYYY-MM-DD.md`，但是我个人长期的笔记积累都是 `YYYY.MM.DD - Topic`。

所以，如果我可以改变默认命名的规则，就可以节约每次新建文件时修改 `-` 的繁琐操作。

此外，我相信很多其他用户也会有自己的习惯，比如用流水号，用固定的前缀，等等。

给予用户适当的个性化空间，会使用户更加顺手。

**Comment by oulvhai** [comment]
想动手做这个，然后发现设置项目目前已经蛮多的了，这个选项虽然可以个性化空间，但是也会增加设置项目，主要是手动修改一下也不是很不方便，所以就先不做了。
