### ISSUE TITLE
新增预览样式和若干问题反馈

### ISSUE THREAD

**Issue by kchen0x** [oulvhai/MWeb-issues#553]
我为 MWeb 新增了一个 [预览样式](https://github.com/quentin-chen/mweb-marxico) 以填补目前样式的不足。

另外：

1. iOS 版的样式希望可以通过电脑导入，或者直接使用 iCloud 和 Mac 版的保持同步。现在在 iOS 上编辑 CSS 文件的体验为零。
2. 建议为 Mac 版加上全局快捷键快速新建文档并录入，以提高使用效率。（我目前采用的折中办法是使用 Keyboard Maestro：激活 MWeb -> cmd+L -> cmd+N），尽管如此，并不优雅。
3. Mac 版键入文字时，首先是灰色字体，延迟半秒钟之后才会变成深色正常字体。我不清楚这个特性的目的何在，也不知道怎么关闭。但是，这使得我在输入的时候总有一种轻微的卡顿的感觉，并不清爽。
4. 七牛云图床在开启**原图保护**（官方建议开启）时，只能通过`资源地址+样式分隔符+样式后缀`的形式访问图片。建议在上传工具中添加这一支持。
5. 偷偷打听一下：iOS Pro 版提高收费的时候，Mac 版会不会限时降价？推荐朋友入手的好时机（偷笑

**Comment by CYsuncheng** [comment]
是不是不能适配3.0了？

**Comment by kchen0x** [comment]
是的：
3.x 自定义预览样式不再像 2.x 那样支持整个文件夹自定义方式，仅支持单个 CSS 文件。

而我暂时还没有购入3.0版本的。
@oulvhai 欧大大送我个3.0我接着维护啊 :)

**Comment by oulvhai** [comment]
你这个样式好像就是单个 CSS 文件吧？
3.0 你要 MAS 版还是非 MAS 版？ 发个邮件给我。
