### ISSUE TITLE
是否可以增加自动生成/删除目录功能？

### ISSUE THREAD

**Issue by ocarol** [oulvhai/MWeb-issues#556]
如题，希望在文档中，写完文档后，能有一个"生成/更新/删除"文章目录的功能（不只是右侧显示，我说的是在文档的最上面内容插入文档目录，这样文章粘贴到博客中，也能保留目录）,就像word一样；我觉得这个功能还是很有必要的，至少给我带来了困扰，希望作者可以采纳

**Comment by oulvhai** [comment]
这个好像不用吧？如果需要的是文本形式的目录，用 [TOC] 这个语法，然后直接复制预览那边的即可。如果要的是带连接那种，直接复制 HTML 即可。
