### ISSUE TITLE
iOS Mac 同步问题

### ISSUE THREAD

**Issue by LavareX** [oulvhai/MWeb-issues#557]
- Mac: Version 2.1.7 (268)
- iOS: Version 2.2.7 build 318

Mac 版使用文档库模式，并将库设置在 iCloud 上。
iOS 上在对应的文件夹上新建 MD 文件，用默认文件名「2017-05-12」同步后，在 Mac 版显示不了，若用「14941665073999」文件名则可以。

**Comment by oulvhai** [comment]
iOS 同步 Mac 的文档库的方法，请先在 iOS 的设置中开始 MWeb for Mac 文档库，然后会有提示，按照提示做，然后等待同步完成即可。
