### ISSUE TITLE
用 mathjax 绘制 matrix 时，换行有问题

### ISSUE THREAD

**Issue by meritozh** [oulvhai/MWeb-issues#558]
```
$$
\begin{pmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\\
a_{21} & a_{22} & \dots & a_{2n} \\\
\vdots & \vdots & \ddots & \vdots \\\
a_{m1} & a_{m2} & \dots & a_{mn} \\\
\end{pmatrix}
$$
```

在 MWeb 中以上代码才可以正常渲染出一个矩阵，但 mathjax 的实际语法里，矩阵换行为 `\\`，而不是 `\\\`

**Comment by oulvhai** [comment]
尝试了一下，好像 mathjax 和 mweb 的效果一样？

<img width="512" alt="screen shot 2017-05-15 at 10 52 38" src="https://cloud.githubusercontent.com/assets/2174294/26041063/d5a6f640-395c-11e7-92c7-52f7ee1e734f.png">
<img width="1106" alt="screen shot 2017-05-15 at 10 52 54" src="https://cloud.githubusercontent.com/assets/2174294/26041064/d5e39e7e-395c-11e7-9970-b9e72127a0df.png">

**Comment by meritozh** [comment]
@oulvhai 发现问题了，设置里disable `smartypants` 就没问题了
