### ISSUE TITLE
vim模式什么时候支持？

### ISSUE THREAD

**Issue by cryinstall** [oulvhai/MWeb-issues#565]
我自己是付费用户， 也推荐2个同事付费了，(for mac)，
最近用了一段时间，没有vim支持真心不想用了

搜索相关issue，2015年就有码农提出希望增加这个功能，到现在也还没有

**Comment by cryinstall** [comment]
额，发现作者不会用vim，所以不做。。。。

那退而求其次，在mac下本身是有macvim，我尝试使用这个编辑，然后想在mweb里面预览，
发现mweb对于外部编辑导致文件变化的支持实在是做的太烂了...  这块能不能优化一下

**Comment by cryinstall** [comment]
额，试用了一下vscode...  我后面可能直接用它了..  

建议楼主把项目开源了吧...

**Comment by oulvhai** [comment]
vscode 的确好用。
然后开源应该是不会的， vim 至目前还是没考虑支持，感谢建议了！
