### ISSUE TITLE
LaTex 长数学表达式不是太优美。

### ISSUE THREAD

**Issue by yanyuechuixue** [oulvhai/MWeb-issues#57]
正常的LaTex 应该是这样：
![3d1c912e-ed18-4bed-9d72-a14a50fd2b65](https://cloud.githubusercontent.com/assets/6822194/10747852/0e1f8d88-7c95-11e5-8d24-95ebb328af02.png)
而MWeb 的是这样：
![e7e17910-8539-4037-8596-213c27aa0b4c](https://cloud.githubusercontent.com/assets/6822194/10747868/2ceb2ef2-7c95-11e5-88eb-673b352a354b.png)
有个蛮明显的重心下移。
不是啥大事，闲着没事干的时候可以优化一下，不管也没关系。

**Comment by oulvhai** [comment]
:D 
感谢建议。
数学公式可以贴出来吗？因为我基本不写 LaTex 。 估计可以 CSS 调一下还是怎么样。。

**Comment by yanyuechuixue** [comment]
$$r_s(z)=\frac{c}{H_0}\int_0^{1/1+z}\frac{da}{{a^2E(a)\sqrt{3(1+\frac{3\Omega_bh^2}{4\Omega_\gamma h^2}a)}}}$$
以上是公式~
换主题好像没有什么太大效果。。。

**Comment by oulvhai** [comment]
试了一下这个公式，好像在 MathJax 最新版都是这样解析的。你可以试试 https://www.mathjax.org/ 里的Try Live Demo

我猜你图中那个公式估计是 MathJax 的旧版， MWeb 一开始是用 旧版，然后换到新版的确是不一样了的。

然而现在肯定不会换成旧版的了，所以这个问题应该暂时无解。
