### ISSUE TITLE
请问 MWeb 还在做吗，将近 3 个月没有更新了

### ISSUE THREAD

**Issue by situfang** [oulvhai/MWeb-issues#570]
是在憋大招还是什么的，好奇了解一下，新版本有预计时间没～

**Comment by fmewtwo** [comment]
我也想知道，之前提的bug和建议什么的都怎么样了， 是不是在憋大招，我的大刀早已饥渴难耐了

**Comment by grock304** [comment]
是啊，最近发布到印象笔记显示完全不正常，相当的困扰啊。

**Comment by kingjoydom** [comment]
同问，有没有试用beta版本的功能呀？还有IOS版本有TF嘛？

**Comment by yajiez** [comment]
同问，之前提的关于外部模式下同时显示 Rmd 和 md 文件类型的建议被标注为 Very High 了，满怀期待的一直等更新，现在使用中经常需要右键在文件夹显示后再打开需要的 Rmd 文件，相当繁琐，希望作者能早日更新，万分感谢~

**Comment by oulvhai** [comment]
@situfang @1412kid @grock304 @kingjoydom @yajiez  不是憋大招，是这些日子有别的事，也就这个月才缓下来，然后在做 iOS 的 Dropbox 和 WebDAV 同步。过些天会发 TF，然后才会有时间更新 Mac 和顺便 修 TF bug。
感谢各位关注！

**Comment by ATiGr** [comment]
强烈建议先更新Mac啊...  毕竟写大量的东西还是Mac下面顺手，然后和一个不能打开的网站的同步功能总觉的可以稍微等等。（逃

开玩笑啦，只要能更新就好，谢谢作者。

**Comment by kingjoydom** [comment]
@oulvhai ios的TF想申请需要怎么弄？会在哪里告知？

**Comment by oulvhai** [comment]
@ATiGr 这个月大部分时间会用在 Mac 版上 :D
@kingjoydom 按 姓,名,email  这种格式发到 coderforart[at]gmail，今天已经可以 TF 了。

**Comment by hh-in-zhuzhou** [comment]
请问TF是啥意思？

**Comment by oulvhai** [comment]
@hh-in-zhuzhou TF 是指参加 iOS 版的测试。
