### ISSUE TITLE
发现shell和terminal的没有有代码高亮的样式，希望能加上

### ISSUE THREAD

**Issue by ghost** [oulvhai/MWeb-issues#571]
平时需要记录很多命令行，但是terminal和shell的高亮似乎并没有，可否加一个？

**Comment by oulvhai** [comment]
MWeb 用的是 https://highlightjs.org/ 可以参考 https://highlightjs.org/ 支持的所有高亮： http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html

**Comment by hrzhao76** [comment]
开发者你好。
我也发现了确实没有Shell的高亮。可否更新一下？

**Comment by hrzhao76** [comment]
而且预览的部分也没有高亮。如果能添加功能如从代码块直接复制，就更好了
