### ISSUE TITLE
提些建议, 关于 * 和 >

### ISSUE THREAD

**Issue by uxyheaven** [oulvhai/MWeb-issues#572]
1 
```
* aaaaa
```

这样敲回车后是

```
* aaaaa
* 光标
```

此时在按tab键是

```
* aaaaa
*      光标
```

能否改成按了tab后是这样

```
* aaaaa
     * 光标
```

再按del的时候就变成

```
* aaaaa
* 光标
```

2

```
> 光标
```

这个在按两次回车的时候是

```
>
>
> 光标
```
能够改成

```
>

光标
```

**Comment by hh-in-zhuzhou** [comment]
私以为，这样的建议并不妥当，默认的处理是合乎逻辑的，按你的意思修改好，一时爽了，会引发其他的问题，反而导致不方便。

**Comment by oulvhai** [comment]
我竟然漏掉这个！ 抱歉了！
列表这个是可以改进，因为 * 后再加 Tab 的需求几乎没有。
引用这个是因为引用可以空行，里面可以加各种东西，有两次回车还是引用的需求。是否要改还要权衡。

**Comment by uxyheaven** [comment]
建议1可以修改下么

**Comment by oulvhai** [comment]
1. 在 3.1.8 是按你说那样处理了。仅是 del 部分不处理。
2. 引用这个暂不做更改。
