### ISSUE TITLE
将文章发布到印象笔记后，印象笔记里的文章中的代码没有格式

### ISSUE THREAD

**Issue by uhayate** [oulvhai/MWeb-issues#576]
MWeb：
![image](https://cloud.githubusercontent.com/assets/11769715/26579311/d82b75fc-4565-11e7-9e58-f9b740bd73f7.png)
印象笔记：
![image](https://cloud.githubusercontent.com/assets/11769715/26579344/ee9e55a2-4565-11e7-92b3-526735f7448a.png)

**Comment by oulvhai** [comment]
新版印象笔记好像解决了这个 bug。
