### ISSUE TITLE
有序列表，如果有编号，编号会混乱

### ISSUE THREAD

**Issue by DavidYangfei** [oulvhai/MWeb-issues#577]
系统：OS X Yosemite 10.10.5
版本：2.1.7

<img width="734" alt="qq20170602-191653 2x" src="https://cloud.githubusercontent.com/assets/1400178/26723529/7b04c888-47c7-11e7-95c4-161c5290b32d.png">

**Comment by oulvhai** [comment]
Markdown 语法是这样的，列表的数字是随意的，你全部写 1，也会在预览时自动好。

**Comment by xfarmer** [comment]
3的子项目应该要再缩进一下，也就是项目三的子项目应该用tab缩进，然后才是1. xxxx

**Comment by oulvhai** [comment]
原来如此，是帮助写错了，抱歉，我没看清楚！
