### ISSUE TITLE
MathJax支持问题

### ISSUE THREAD

**Issue by ghost** [oulvhai/MWeb-issues#578]
写入LaTeX公式时经常会出现很奇葩的格式问题，比如下面这个`\hat`：

![](https://ws2.sinaimg.cn/large/006tNc79gy1fgbyexd0y3j307a02sq2y.jpg)

这已经严重影响阅读了，希望可以修复。

还有数学公式的字体一直都很奇怪，看起来很别扭，希望可以改进。

**Comment by oulvhai** [comment]
公式可以发出来我试试吗？ 不大懂 LaTeX，所以不知道具体是什么情况。

**Comment by ghost** [comment]
这个公式是`$$\hat{\text{x}}=\text{Norm}(\text{x}, \mathcal{X})$$`，这个公式应该是这个样子的：

![](https://ws4.sinaimg.cn/large/006tNc79gy1fgds0elk8qj306u011wec.jpg)

但是现在明显尖角号发生了偏移。

而且现在的公式字体太奇怪了，建议换成LaTeX默认的字体Latin Modern Math。

**Comment by oulvhai** [comment]
你这边是怎么偏的？我试一下，好像没问题，如图：
<img width="699" alt="2017-06-08 4 10 32" src="https://user-images.githubusercontent.com/2174294/26918609-4f6a719e-4c65-11e7-97f0-6c4cec0864a8.png">

你可以看一下 MWeb 偏好设置 - 主题样式 那里，是否启用了 Smartypants，如果启用了，禁用看看 （这个好像也没关系）。

**Comment by ghost** [comment]
我没有启用Smartypants，主题样式设置如下：

![](https://ws2.sinaimg.cn/large/006tNc79gy1fgdv78lepxj30ym0w0q7s.jpg)

**Comment by ghost** [comment]
我尝试了用AppCleaner做完整的卸载和重装，还是有问题。

**Comment by ghost** [comment]
尝试用客人用户，问题依旧。

具体偏的样子如下，尖角号偏到了旁边：

![](https://ws4.sinaimg.cn/large/006tNc79gy1fgdwc8o5w1j31jg086jsa.jpg)

**Comment by oulvhai** [comment]
@clavichord93 我這邊好像是無法重現了，10.11，10.12 系統都正常。加個討論標籤看看有沒有人遇到。

**Comment by ghost** [comment]
10.12.5上会出现问题吗？

**Comment by oulvhai** [comment]
@clavichord93 我升级到 10.12.5 后，确认会出现这样的问题。。。 真是太奇怪，版本号小小不一样，竟然有这种差别。非常感谢！

**Comment by ghost** [comment]
希望尽快修复！

**Comment by ghost** [comment]
我这里更新之后还是不能正常显示…是要做什么设置吗？

**Comment by oulvhai** [comment]
奇怪呀，我再测试测试。。

**Comment by oulvhai** [comment]
@clavichord93 我测试好像是正常了的。MacOS 版本 10.12.5 

![2017-07-02 7 56 52](https://user-images.githubusercontent.com/2174294/27769635-e9ab094a-5f60-11e7-93b0-c55c5f958d25.png)

**Comment by ghost** [comment]
我试了一下，使用Common HTML和SVG渲染已经正常了，但是HTML-CSS还是有bug。但是已经可以使用了。

**Comment by oulvhai** [comment]
@clavichord93 MWeb 导出的 html 是用 HTMLorMML ， 因为这个可能是 safari 的 bug，chrome 就没问题。我再想一想要不要统一为 SVG。
