### ISSUE TITLE
请问怎样把出现在桌面上的asset文件夹移动到其它位置？

### ISSUE THREAD

**Issue by nsolcampbell** [oulvhai/MWeb-issues#58]
在使用mweb粘贴图片适合貌似会在桌面自动生成一个asset文件夹，请问有没有办法让这个文件夹不出现在桌面上？

**Comment by oulvhai** [comment]
MWeb 生成的应该是 media 文件夹吧？ 如果你手动改成 asset ， 那应该是 asset。 MWeb 生成的文件夹其实是在引入的文件夹下的。估计是你引入了桌面，所以文件夹才会在桌面创建。
