### ISSUE TITLE
添加微信公众号平台的发布样式

### ISSUE THREAD

**Issue by bigknife** [oulvhai/MWeb-issues#589]
微信公众号作为主要的内容平台之一，存在这样的需求：在MWeb中使用Markdown编写好内容，然后复制粘贴到公众号编辑框。

目前的问题是，粘贴过去后，发布的内容样式就丢了。

**Comment by xfarmer** [comment]
一年了，现在能支持么？

**Comment by oulvhai** [comment]
现在可以配合 markdown here 使用，可以搜索一下 mweb markdown here。更好的支持还在想怎么做。

**Comment by oulvhai** [comment]
https://github.com/oulvhai/MWeb-issues/issues/862
