### ISSUE TITLE
代码块有些关键字加粗

### ISSUE THREAD

**Issue by saup007** [oulvhai/MWeb-issues#590]
例如：

```
A1、B1、C1 为 A、B、C 满足条件
A1、B1、C1 为 A、B、C 满足条件
```

B1、C1   B、C 都加粗了。

还有，代码块里是否可以加个功能，可以保留格式 。

```
> | command | 时间复杂底 |
> | --- | --- |
> | hset key field value | O(1) |
```

| command | 时间复杂底 |
| --- | --- |
| hset key field value | O(1) |

**Comment by oulvhai** [comment]
下个语言定义就可以了。比如说 

    ```txt
    保留格式的代码
    ```

这样。

**Comment by saup007** [comment]
嗯，是这样。
默认# 是灰色的，用 txt # 就跟下面文字一样黑色的，python 就可以了， 但 shell 也不行。不纠结了，python 标注也可以。
