### ISSUE TITLE
letex代码块最后会出现奇怪的竖线，影响阅读。

### ISSUE THREAD

**Issue by xwzy** [oulvhai/MWeb-issues#594]
Mac os版本10.12.5 

<img width="137" alt="2017-07-02 11 58 41" src="https://user-images.githubusercontent.com/13077117/27767113-f4301560-5f1d-11e7-972e-e43ecfaa7076.png">
<img width="62" alt="2017-07-02 11 58 45" src="https://user-images.githubusercontent.com/13077117/27767114-f516751e-5f1d-11e7-952e-2d6e8cdc98d2.png">

**Comment by oulvhai** [comment]
MWeb Lite 会这样，目前还是没有决定更新。
