### ISSUE TITLE
两栏（编辑+预览）模式

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#6]
希望可以提供这样一种模式：左边编辑，右边预览

虽然现在可以打开独立的实时预览窗口，但需要调整两者的位置，不太方便。

这个模式有两个好处：
1. 对于markdown的初学者很有用，快速反馈
2. 有时候对于预览的格式要求很高，比如写文档给人看，使用该模式可以快速修正

你提到不打算提供该模式，不知道原因是什么？

**Comment by oulvhai** [comment]
原因是现在已经三栏了，再加一栏就四栏了，有点难用。 然后还会多一个预览选项。。因为现在的预览我很喜欢，不可能会去掉的。

**Comment by freewind** [comment]
可能我表达的不清楚：
1. 现在的东西都不用变, 预览也不需要去掉
2. 提供一个新的模式，比如 `2 panels (edit + preview)`
3. 不是在三栏的基础上再加一栏，而是一共只给两栏（编辑区和预览区），不显示左边的category/article list。就像mou那样

![image](https://cloud.githubusercontent.com/assets/333781/7787271/e1c5931a-0235-11e5-9982-868bf5cff56d.png)

**Comment by oulvhai** [comment]
如果是说提供一个 菜单和快捷键， 使用了之后就变成你图中的调节好样子倒是可以考虑。

我暂时坚持不做成 Mou 那样的想法。 :D

**Comment by freewind** [comment]
嗯，有这样的菜单最好，我发现这种模式对我来说比较方便，特别是对样式要求比较高的时候

**Comment by oulvhai** [comment]
:D 现在也还行吧。调节一下也不费什么事。做软件最怕的是把 20% 的需求做好了， 80% 经常用的反而没做好。

**Comment by freewind** [comment]
哈哈，如果你开源，或者提供插件机制，也许我能自己来定制了

**Comment by oulvhai** [comment]
:D 因为我现在是独立开发者，然后代码也写得比较乱，所以暂时不考虑开源。 之后会考虑的。
