### ISSUE TITLE
搜索功能实现的效果不理想

### ISSUE THREAD

**Issue by yuyandong** [oulvhai/MWeb-issues#60]
刚才在 CMD + E 模式中使用搜索功能，发觉搜索的效果不理想。
- 不是完全匹配关键词，显现结果。
- 貌似是模糊匹配，会显现很多无关的结果。

还碰到一种情况，输入搜索的内容，回车后，导致软件卡死，无法点击界面的内容

**Comment by oulvhai** [comment]
搜寻功能的确还要优化。 

外部模式的搜索目前其实是实时索引，所以如果你当前选中的文件夹下有大量文件，是会卡。卡死我倒是没遇到过，我再测试。

**Comment by zfl420** [comment]
怎么样才能让MWEB从google改成百度搜索？

**Comment by oulvhai** [comment]
@zfl420  直接改网站模板。
