### ISSUE TITLE
Mweb定时备份，是否可以按文档模式分目录保存，文件名为标题名

### ISSUE THREAD

**Issue by saup007** [oulvhai/MWeb-issues#602]
Mac上 MWeb 定时备份到 Dropbox，但保存后，所有文件在一个目录，且名字都是数字的。
如果能够分类且文件名是标题名，同步后 Windows 也可以使用工具来查看。

**Comment by oulvhai** [comment]
不能，这样备份的话，MWeb 无法从备份中恢复。

**Comment by saup007** [comment]
哈哈，其实想 Windows 跨平台相向同步，现在只能同步到 Dropbox，之后 windows 查看。

反向，现在是编译 markdown，知道哪个编译过，手工导入。哭。。
