### ISSUE TITLE
最新的 2.2.2 版本外部模式下右侧的文档大纲无法滚动

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#604]
如题，升级到最新的 2.2.2 版本后发现，打开外部模式后，文档大纲那里不能像以前一样可以使用双指上下滑动了，非常不方便。

另外，文档大纲上新加的“浮动方式”那个按钮勾选了也没什么反应 (13.3 MacBook Pro)，并且放在那里也显得比较突兀，建议可以放在视图工具栏里面。

**Comment by oulvhai** [comment]
1. 的确是 bug，过几天发个版本修正一下，非常感谢！
2. 非浮动方式，大纲是跟编辑器并排的，浮动方式后，会浮动在编辑器上。 还是有反应的吧？比较突兀这个，我再想想怎么解决。。

**Comment by yajiez** [comment]
好像选浮动后确实有点变化，但是浮动的大纲好像并不能拖动，并且还会遮挡正文部分。所以建议还是对这个处理一下吧。

**Comment by oulvhai** [comment]
@yajiez 浮动就是用于临时看一下大纲而不会影响编辑器（更改大小），看完点一下编辑器即可重新编辑这个流程。 拖动的话，目前的设计不大适合，因为每一文档都会有一个大纲。

**Comment by yajiez** [comment]
哦，这样说我明白了，不过这需要配合 CMD + 7 使用，这样会比较顺手。对于我一般是长期开着大纲，所以之前体会不到浮动的意义，拖动大纲确实是没必要。

双指拖动的问题能尽快解决就好了，浮动这个怎么样都可以，使用影响不大，只是把勾选框放在工具栏下面的话大纲栏看起来会清爽一些。

**Comment by oulvhai** [comment]
@yajiez 滚动问题 2.2.3 应该是解决了吧？

**Comment by yajiez** [comment]
嗯，更新后已经解决了，谢谢！
