### ISSUE TITLE
Send Feedback 只会转到浏览器，不会打开页面

### ISSUE THREAD

**Issue by Simon7281** [oulvhai/MWeb-issues#61]
MWeb 版本 1.8.1(148)
系统版本 Mac OSX 10.11.2 Beta (15C27e)
默认浏览器 Chrome 46.0.2490.80 (64-bit)

**Comment by oulvhai** [comment]
Send Feedback 其实是打开默认的发邮件客户端。

想不到还会转到浏览器，感谢报 Bug。
