### ISSUE TITLE
文档库是什么意思？

### ISSUE THREAD

**Issue by yaocz512** [oulvhai/MWeb-issues#610]
为什么我按cmd + L 没有任何反应

**Comment by youchenlee** [comment]
是否你本來就在 Library（文檔庫） 模式？
看左上角的 Library
<img width="188" alt="screen shot 2017-07-23 at 1 56 49 am" src="https://user-images.githubusercontent.com/181350/28493451-43a9e968-6f4a-11e7-89af-edd4a27b4d64.png">
