### ISSUE TITLE
TOML 文件头支持

### ISSUE THREAD

**Issue by yajiez** [oulvhai/MWeb-issues#618]
Hugo (Go 语言编写的速度极快的静态博客编译引擎) 中的配置文件还有页面文件等会大量用到 TOML 文件头格式，这种格式就是三个加号开始三个加号结尾，和 YAML 格式非常类似， TOML 格式的示例如下：

```
+++
# 这是一行注释
author = "name"
date = "2017-01-01"
+++
```

目前 MWeb 会对 TOML 格式的文件头进行渲染，希望能够在下一版中对 TOML 文件头添加一些基本支持，也就是在编辑模式和预览模式下都将其原样显示不进行渲染，目前的主要问题是无论是编辑模式还是预览模式都会将注释行渲染成一级标题，比如编辑模式下会显示成这样：

![](http://i.imgur.com/fuI4Its.png)

上图中 `#` 号开头的行应该是注释行，但是会显示的非常突出，希望能够对此改进一下，非常感谢！

**Comment by lxmfly123** [comment]
同样希望增加对 yaml 头的支持

**Comment by oulvhai** [comment]
我在用的版本 3.1.9 处理了 +++ 的问题。
`#` 这个是标准的 markdown 语法了，目前不做处理。在意的话可以在 `#` 前加一空格。
