### ISSUE TITLE
使用[TOC]生成目录后转为pdf，点击目录无法跳转

### ISSUE THREAD

**Issue by SunsetWan** [oulvhai/MWeb-issues#620]
使用[TOC]生成目录之后把文档转为pdf文档，然后打开pdf文档，点击目录，无法跳转，能否尽快解决这个bug，谢谢!

**Comment by SunsetWan** [comment]
@oulvhai

**Comment by saup007** [comment]
可能要 10.13 之后或非 10.12 。#370

**Comment by nameryan** [comment]
目前版本 2.2.9 (312)，生成的目录还是无法跳转哦。

找了一圈还是MWEB制作markdown风格的pdf最专业，就差这个功能了！

**Comment by oulvhai** [comment]
这个需要继续优化，目前仅 ElCapitan 的可以跳。
