### ISSUE TITLE
[wish Mac] Ability to drag-drop an External folder onto the app's icon

### ISSUE THREAD

**Issue by twardoch** [oulvhai/MWeb-issues#622]
I don't use the library feature in MWeb Mac, I prefer my own folders (since I do technical writing). 

Generally, the support of MWeb's external folder structure is good. However, currently, the process of **opening** an external folder is unorthodox: I need to click on the `+` icon in the sidebar and pick an external folder there. When I try to drag-drop a folder on the app's icon, the app reports `The document **nameofthefolder** cannot be opened`. 

If possible, please add the ability to "open" a folder via drag-drop. Then of course, that folder should be added to the sidebar just as it currently does when I use the `+` icon.

**Comment by oulvhai** [comment]
Solve in MWeb 3.1.8.
