### ISSUE TITLE
导出到印象笔记标题字体超级大

### ISSUE THREAD

**Issue by selfboot** [oulvhai/MWeb-issues#625]
二级标题之前导出到印象笔记看着还挺舒服，不过最近导出的话，标题一下子变的超级大。（可能是印象笔记的 锅）

![image](https://user-images.githubusercontent.com/2769831/28751356-e03e07da-7537-11e7-99b6-bed3d636af89.png)

**Comment by oulvhai** [comment]
这个应该是看你选的是什么预览样式。

**Comment by selfboot** [comment]
选的是 mweb-github 预览样式，之前还是挺正常的字体大小的。

话说，如果我想更改自带的预览样式的化，在哪里可以改呢，貌似没有找到 mweb-github 的CSS文件。

此外，预览和印象笔记里的效果有很明显的出入，比如我用 sample-css 来预览，效果挺好的，

![image](https://user-images.githubusercontent.com/2769831/29508160-038296b6-8686-11e7-9c9c-d8573aac723b.png)

然后发布到印象笔记，无序列表没有悬挂缩进了，并且字体也变化了：

![image](https://user-images.githubusercontent.com/2769831/29508169-0b9dd68a-8686-11e7-9486-b64e7ad0b16d.png)

**Comment by zephyrich** [comment]
同样有这个问题，请问有计划修复这个问题吗

**Comment by zephyrich** [comment]
@oulvhai 我查看了下马克飞象更新的导出格式，应该是印象笔记那边html的效果变了，标题等字体比原先大了不少。希望能对应更新插入的css样式使字体大小回归正常
