### ISSUE TITLE
时序图过宽, 导出时, 不能显示完全.

### ISSUE THREAD

**Issue by gavin-k** [oulvhai/MWeb-issues#627]
在 Mweb 的 `2.2.3 版本` 中, 画`时序图`的时候, 要是过宽,比如定义四个角色.然后导出 最右边一节不能看到了. 

系统属性:
MacBook Pro (Retina, 15-inch, Mid 2015)
版本 `10.12.6 `
Darwin Kernel Version `16.7.0`

**Comment by pukguy** [comment]
都3.0版本了，这个问题还没有解决？

**Comment by oulvhai** [comment]
这个是原本用的 js 库的限制，建议用新版本的 mermaid 画这类图。MWeb 中的语法： https://zh.mweb.im/markdown.html#toc_19  mermaid 官网 https://mermaidjs.github.io/
