### ISSUE TITLE
可否新增发布到简书平台？

### ISSUE THREAD

**Issue by jcx70100** [oulvhai/MWeb-issues#628]
平时用简书比较多，由于用mweb写文章体验很不错，可是每次发布都要打开网页复制粘贴到简书页面，有点麻烦，作者是否可以将简书也添加到发布平台。

**Comment by saup007** [comment]
我记得作者回复过，简书没有开放 API。

**Comment by jcx70100** [comment]
好的，谢谢
@saup007
