### ISSUE TITLE
MWeb支持iCloud同步

### ISSUE THREAD

**Issue by kirajun** [oulvhai/MWeb-issues#63]
当前版本只有支持备份到本地的功能，可否支持备份到iCloud？或者有替代的方案。

**Comment by oulvhai** [comment]
所有同步需求请用外部模式(CMD + E)。

文档库同步是大坑，目前坚决不入坑！！备份到 iCloud 什么的，备份的文件夹选择 iCloud Dirve 里的就可以了。

**Comment by a1ickgu0** [comment]
能支持把 `Library` 采用`指定目录`的方式指定到 iCloud Driver上不？

**Comment by oulvhai** [comment]
Library 不支持指定目录！
Library 使用了数据库，如果数据库同步坏了，或者多个设备使用时，没能同步到最新版（就是某设备修改后没完全上传），打不开或者少了数据，等等就非常麻烦了！

**Comment by kirajun** [comment]
因为经常换设备工作，如果能**无缝切换**则更为方便，毕竟备份的文件还是要保存，关闭，然后在另一台电脑上开启的，而**无缝切换**的效果就是，换了设备，你可以继续之前的工作，很方便。

**Comment by oulvhai** [comment]
这的确是最终目标，但是 Library 目前还做不到这样。其实有考察过一些方案，但是不能保证 100% 靠谱。如果一个方案有丢失数据的风险，我宁可先不做。

像 Apple 的 Notes App，应该是达到无缝切换了，也是有人反映丢了数据。

总的来说，目前可靠的无缝切换方案是直接把整个文件夹丢 Dropbox 或 iCloud Drive 里，然后用官方的同步 App。只是用 MWeb 的外部模式引入。 这是最成熟稳定的方案。因为网盘都有历史记录，MWeb 本身也有支持文档版本 File - Revert To - xxxx。 这样才能最大程度保证数据没问题。

**Comment by kirajun** [comment]
OK，再次感谢提供这么好的软件。

**Comment by morphinewan** [comment]
是否考虑使用如同1Password的那种方案，iCloud接口同步CoreData。然后自身再加一个定期备份功能。如果碰到多设备同步造成数据错乱，至少用户还可以在某台设备上使用某个定期备份来恢复到最近的完好版本。

外部模式我试用了一下，不是很方便。个人还是比较喜欢库的使用方式的。

@oulvhai 谢谢作者开发这么一款优秀的软件，但是本身如果没有跨设备同步功能，有点欠缺。跨平台无法实现，用苹果一家的跨一下设备做到同步，应该还是可以的。

**Comment by oulvhai** [comment]
@morphinewan 跨设备同步目前最好的方案是 2014 年新出的 CloudKit，听说苹果自家的 Notes 就是用这个， 1Password 也是用这个。 这个方案跟目前文档库的理念有所冲突，目前会把 markdown 保存到一个 .md 文档中，额外的数据保存在一个 CoreData 数据库中，这个是比较稳定的方案，即使数据库坏了，文档因为是 文本格式文档 并一个个保存的，不会有问题。而用 CloudKit 则是会保存在 CloudKit 的数据库中，我其实有计划单独做一个 App 测试这个情况。

感谢建议！

**Comment by morphinewan** [comment]
@oulvhai 谢谢说明

Markdown文件归根结底也是一个大的字符串而已，而且序列化后也能保存在CoreData中。不用外部文件，全靠数据库也没什么不好。iCloud没那么不堪，如果追求保险，倒是可以定期把mkdown以文件形式备份到别处。

如果现在跨设备编辑文档还需要借助dropbox这种第三方同步工具，导出导入的，有点繁琐。

**Comment by oulvhai** [comment]
全靠数据库是没什么问题，但是一旦要同步，加上设备在线离线的不确定性和网络的复杂性，问题就大起来了。 iCloud 目前大概是分为三个，一是 文件形式的 iCloud Drive （这个一般来说是最稳定的），一个是 CoreData 同步（这个是最不稳定，非常易出问题）。一个是2014 年新出的 CloudKit，这个出来我觉得很大的原因是因为 CoreData 同步上问题太大了，因为 CloudKit 也是跟 CoreData 一样是数据库形式的，只不过限定比较多，是 KV 形式，API 也相差很多，他是修改了就即时同步（比较像 evernote 形式），而不是像 CoreData 先离线保存。所以说 CloudKit 是相对可以做的。 

我开始做 MWeb 的时候是不大懂这个，听说 CoreData 可以同步，就用 CoreData 搞起了。

**Comment by morphinewan** [comment]
我也没怎么开发过CloudKit，前几天还看过一些相关的教程。貌似现在同步，不只是支持KV形式了吧。打开App的同步选项，剩余用法和一般的本机CoreData并无二致。
