### ISSUE TITLE
是否考虑 Typora 写作风格，一边写一边预览

### ISSUE THREAD

**Issue by saup007** [oulvhai/MWeb-issues#634]
是否考虑 Typora 写作风格，边写边预览，的确比传统一边预览一边写要好很多，特别是在修改的时候。

**Comment by menduo** [comment]
+1

**Comment by oulvhai** [comment]
Typora 好像也在慢慢进化了，MWeb 没必要再做一个，最主要是这功能比较难做。所以不会考虑。
