### ISSUE TITLE
印象笔记同步的问题

### ISSUE THREAD

**Issue by littledu** [oulvhai/MWeb-issues#64]
同步只能单向同步吗？比如我在两台机器都使用了 mweb, 在其中一台上向印象笔记同步了文章后，另一台无法从印象笔记同步过来，有没有办法解决

**Comment by oulvhai** [comment]
MWeb 只支持发布到印象笔记，是 **发布** 而不是同步。

所以没有办法从印象笔记同步过来。

**Comment by littledu** [comment]
@oulvhai 
那有办法做同步吗

**Comment by oulvhai** [comment]
@littledu 印象笔记的格式是它专用的，Markdown 可以转为它的格式，但是它格式就不能很好地无损转回 Markdown，所以目前不会做。

**Comment by littledu** [comment]
@oulvhai 
有个叫 马克飞象 的印象笔记插件，他支持同步，但如果在印象笔记修改了后，同步回来格式就会不对的，但理论上用 markdown 编辑的，是不会在 印象笔记 中编辑的，所以，我觉得这个功能可以做，不需要去考虑转回来后的格式问题。辛苦辛苦

**Comment by oulvhai** [comment]
@littledu  马克我用过，好像他现在不支持在印象中修改了。修改要跳回他那了。 不是一定没问题的功能 MWeb 是暂时不考虑去做的，不然一个转换不好，就会丢数据。

**Comment by littledu** [comment]
@oulvhai 
这样啊，那你是怎么去解决多台设备的问题呢，就是在一台机器编辑了，在另一台机器还想编辑同样的内容

**Comment by oulvhai** [comment]
@littledu 用 MWeb 的外部模式（CMD + E） 引入 Dropbox 等网盘的文件夹就可以了。

**Comment by littledu** [comment]
嗯，也是一个解决方案，谢谢了 @oulvhai

**Comment by Calmjoy** [comment]
但是网盘不如evernote的收集功能强大，可以从各种渠道收集信息保存到evernote。
