### ISSUE TITLE
Bash 里面的#被认为是题目的标识符了。

### ISSUE THREAD

**Issue by lxp121** [oulvhai/MWeb-issues#645]
例如输入
![image](https://user-images.githubusercontent.com/350564/29254801-39b7364c-80cd-11e7-9d18-871056e6905a.png)

在Github里面，会正常识别为：

> ```Shell
> # Modify Makefile.config according to your Caffe installation.
> cp Makefile.config.example Makefile.config
> make -j8
> # Make sure to include $CAFFE_ROOT/python to your PYTHONPATH.
> make py
> make test -j8
> ®# (Optional)
> make runtest -j8
> ```

但是在Mweb里面，会被认为有两个1号题目，输出结果变为：

![image](https://user-images.githubusercontent.com/350564/29254797-2fa38d18-80cd-11e7-855c-ee4abf964202.png)

**Comment by lxp121** [comment]
发现了问题了，应为前面接的是一个bullet行，因此必须要多空一行才能正确识别脚本。

这个在github上可以正确解读，Mweb里面需要一点小trick

**Comment by oulvhai** [comment]
最新版本已解决。
