### ISSUE TITLE
site build path  使用问题

### ISSUE THREAD

**Issue by defp** [oulvhai/MWeb-issues#647]
![image](https://user-images.githubusercontent.com/612381/29349768-23253326-828e-11e7-826f-c682c2e61793.png)

 之前设置过导出位置
点change的时候，只能设置父目录，怎么修改截图中的  `blog`

![image](https://user-images.githubusercontent.com/612381/29349777-2b3cd1c2-828e-11e7-85cf-f4e40ecaa446.png)

**Comment by defp** [comment]
会自己加上blog 后缀

**Comment by defp** [comment]
这个好像是最开始使用的文件夹的名字

**Comment by oulvhai** [comment]
的确是按最开始的名称。

**Comment by defp** [comment]
有方法改吗？

**Comment by oulvhai** [comment]
最新版本还是没办法改，放到 3.2.x 一并改进静态博客相关。
