### ISSUE TITLE
iOS app dropbox同步，可否增加auth重新认证

### ISSUE THREAD

**Issue by BoWuGit** [oulvhai/MWeb-issues#649]
刚开始dropbox auth授权后，一直同步不下来，所以就试着在dropbox 授权app里删除mweb，然后再次同步的时候就会报错，应该是授权问题。
再尝试卸载MWeb，并重新安装，好像都记录了账户信息，不会再重新连接dropbox授权了。
谢谢。

**Comment by oulvhai** [comment]
可以看看 设置页面底部有没有 清除并重新授权 dropbox   的按钮，有就点击即可。

**Comment by BoWuGit** [comment]
嗯找到了，可是dropbox根目录的文件同步不下来，文件夹可以，不知道为什么？ 试了很多次。
谢谢。

**Comment by oulvhai** [comment]
不支持根目录
