### ISSUE TITLE
印象笔记同步问题

### ISSUE THREAD

**Issue by zhoujiajun88** [oulvhai/MWeb-issues#65]
一份很比较长的文档，里面有一些 JavaScript 代码，导出至印象笔记，程序未响应

![image](https://cloud.githubusercontent.com/assets/5774888/11088680/15dc663e-889f-11e5-9ba4-8b1ed856faab.png)

过些时候后，报

![image](https://cloud.githubusercontent.com/assets/5774888/11088685/1f10100c-889f-11e5-9fe6-359ba7a153fe.png)

**Comment by zhoujiajun88** [comment]
该 md 导出 html 是正常可以使用的

**Comment by oulvhai** [comment]
印象的格式比较严格的点，这个错误是说： 你的文档中的某 HTML 元素 P 有一个 name 的属性，这个好像是不支持的（我英文不大好，不知道是不是这样），删除这个才能发布。当然不排除会有其他错误。

一般来说，只写 Markdown 然后发布到 印象才会比较正常。

**Comment by oulvhai** [comment]
未响应这个我再查查。非常感谢。

**Comment by zhoujiajun88** [comment]
1、 p 的 name 节点是有的，文章中有做的锚点链接。我删了再试试
2、 未响应，然后我强制结束了，有一份 Apple 的日志这里太长发不上来，昨天报告给 Apple 了
