### ISSUE TITLE
可否增加对为知笔记(WizNote)的支持？

### ISSUE THREAD

**Issue by crayygy** [oulvhai/MWeb-issues#66]
感觉发布服务已经添加了很多了，不知道还有没有其它的准备增加？

感谢制作这样一款精美实用的软件，已经离不开它了。

**Comment by oulvhai** [comment]
为知没有 API，没办法增加。
如果某服务比较多人用，然后又有比较好的 API，就会考虑增加。

**Comment by crayygy** [comment]
好的～谢谢
