### ISSUE TITLE
[Feature Request] 希望 iOS 里打开外部链接时使用 app 内的浏览器打开

### ISSUE THREAD

**Issue by menduo** [oulvhai/MWeb-issues#660]
就像现在的Twitter、Tweetbot之类的那样。

另外，mac 上外部资源模式下，可以打开相对路径的 md 文件，希望 iOS 也能支持！

谢谢！

**Comment by menduo** [comment]
谢谢您标记为 high，请问进展如何…………

**Comment by menduo** [comment]
另外有一点不知能否做到。

常见的在app内调用safari打开链接时，一般会铺满整个页面。假如有a、b两个tab，在a tab内打开时，就没法看b tab的内容了。

如果能做到在a打开时还能同时切换至b查看内容，那就太好了，记录一些信息时同时能参考旁边的网页内容，完美！！！

**Comment by oulvhai** [comment]
iOS 的外部模式就是首页底部 像 云朵的 icon 的按钮。 
这个无意外应该是下个版本吧，然后 a,b tab 这个，是说 iOS 的 iPad 版的分屏功能？ MWeb 是一个编辑器，应该不会做这种。

**Comment by menduo** [comment]
sorry 是我没描述清楚。

我说的外部模式情况是说，我外部文件a里有链接，链接地址也是外部文件b，相对路径，在mac上，我点这个链接时可以正确地打开b文件。

我希望ios也能支持。

ab是说，以Twitter官方app为例。两个tab分别是首页、搜索。当我在首页里点击某个链接时，会在app内调用Safari打开网页，此时还在app内，可是，此时这个网页铺满了整个app，我无法同时切换到搜索tab，如果我想用搜索功能，只能关闭在首页打开的这个网页。

我想是否可以同时支持两个tab。

**Comment by oulvhai** [comment]
iOS 文件打开这个应该会修正。

a,b tab 这个的话，MWeb 没用到 Tab bar，所以无法达成你的需求。

感谢建议！

**Comment by menduo** [comment]
@oulvhai ok。谢谢。
