### ISSUE TITLE
在代码段中按删除键，预览不刷新

### ISSUE THREAD

**Issue by Jadyli** [oulvhai/MWeb-issues#662]

**Comment by oulvhai** [comment]
好像无法重现。。

**Comment by Jadyli** [comment]
```
    add
```
这种，光标移到add前面删空格或者tab，预览都不会动。

**Comment by oulvhai** [comment]
我测试好像会动，只是有些预览样式不明显。

**Comment by Jadyli** [comment]
![image](https://user-images.githubusercontent.com/15962904/30359028-a254961c-987a-11e7-9d8c-1ccf73c4870d.png)
你看这张图，我左边删到头了，但是右边还是没有动

**Comment by oulvhai** [comment]
@Jadyli  确认 bug，感谢！

**Comment by oulvhai** [comment]
最新版本已解决此问题。
