### ISSUE TITLE
IOS版无法打开UTF-16 的text 文档

### ISSUE THREAD

**Issue by yuyandong** [oulvhai/MWeb-issues#664]
因为使用了 Unclutter Note， 它创建的文档命名过长，比如Unclutter Note 2017-03-15 18.11.29.txt。

通过dropbox 同步到手机上，但是MWeb ios 版本无法查看这类长文件名，可能是时间xx.xx.xx.txt 导致MWeb 无法辨识文件格式。

请修正。谢谢

**Comment by oulvhai** [comment]
应该不会呀， iOS 不认格式，全部文档都会列出的，难道是同步不过来？

**Comment by yuyandong** [comment]
已经同步到本地，链接，如图 ![20170909150494405486627.png](http://7xohl0.com1.z0.glb.clouddn.com/20170909150494405486627.png)

**Comment by yuyandong** [comment]
@oulvhai

**Comment by oulvhai** [comment]
我测试了一下，好像没问题，如下图：
iOS 10.3.2

![img_1177](https://user-images.githubusercontent.com/2174294/30307435-bd37fdcc-97b0-11e7-872c-c9f758a05a35.PNG)
![img_1178](https://user-images.githubusercontent.com/2174294/30307436-bd6623d2-97b0-11e7-9e8e-64d60ac0a5f0.PNG)

**Comment by yuyandong** [comment]
也很奇怪，同一个文件夹里的[中文名文件.txt]就可以打开，其他的自动命名的文件都打开不了。

**Comment by yuyandong** [comment]
测试后，发现是u软件自建的是utf-16 编码，所以在MW上打不开。转换格式为UTF-8 后正常打开。MWeb 有办法默认也识别和正确打开utf-16 的文档？ @oulvhai

**Comment by oulvhai** [comment]
@yuyandong 非常感谢测试和反馈。我看看能不能修正这个问题。

**Comment by oulvhai** [comment]
最新版本已经解决这个问题。
