### ISSUE TITLE
经常换电脑，又不能revoke之前电脑的授权，有点崩溃

### ISSUE THREAD

**Issue by i5ting** [oulvhai/MWeb-issues#666]
半年内换了4台mac.....

**Comment by oulvhai** [comment]
目前暂时可以发邮件给我重置， 取消授权功能我再考虑考虑。。

**Comment by i5ting** [comment]
棒棒哒

**Comment by defp** [comment]
你这情况太特殊了

**Comment by oulvhai** [comment]
2.2.7 版已加入取消授权的功能，可以使用 MWeb 菜单 - 取消在此设备的许可证。

**Comment by huowenxuan** [comment]
刚买了3.1.1，没找到这个功能，请问新版本还支持这个功能吗

**Comment by oulvhai** [comment]
@huowenxuan 支持的。如果你看不到，可以重启 MWeb
![image](https://user-images.githubusercontent.com/2174294/42406592-785252b2-81dd-11e8-8751-fd827c41a1a0.png)
