### ISSUE TITLE
建议添加 Cross-References 功能

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#667]
非常需要 Cross-References 这个feature

参考：[How to link to a named anchor in Multimarkdown?](https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown)

**Comment by chenzz** [comment]
看起来要实现这个功能需要 https://github.com/hoedown/hoedown 支持
有没有考虑换一个 markdown 渲染库？如 http://fletcherpenney.net/multimarkdown/

**Comment by oulvhai** [comment]
多库渲染的计划在 MWeb 3.x 的外部模式有规划。
