### ISSUE TITLE
建议添加『全局搜索』功能：

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#668]
建议添加一个非常实用的『全局搜索』功能：
如任意情况下（当前hover的程序不是MWeb）点击 cmd+shift+j，则会打开MWeb，并搜索关键字。

类似的功能 印象笔记，有道词典都有提供，建议 MWeb添加该功能。
![image](https://user-images.githubusercontent.com/5676311/30034298-05322104-91d3-11e7-8d59-72c7cdadd001.png)

更好的解决方案是添加一个Alfred Workflow来进行全局搜索：
![image](https://user-images.githubusercontent.com/5676311/30034328-3781c524-91d3-11e7-9fd9-14f53ce0dd59.png)

**Comment by oulvhai** [comment]
ref: https://github.com/oulvhai/MWeb-issues/issues/420#issuecomment-324609861
