### ISSUE TITLE
web-medium-like-theme 主题搜索功能有bug 

### ISSUE THREAD

**Issue by yuyandong** [oulvhai/MWeb-issues#67]
http://coderforart.com/mweb-medium-like-theme.html （用oulvhai 同学的是图方便，同一主题举例）
进入该网页搜索框，打开谷歌的结果，并未包含`site`的结果。

中途会`http://google.com/search?q=site%3Acoderforart.com&q=%E7%BC%A9%E7%95%A5%E5%9B%BE`
但是结果却不包含 site

**Comment by oulvhai** [comment]
是说 http://google.com/search?q=site%3Acoderforart.com&q=%E7%BC%A9%E7%95%A5%E5%9B%BE 这个网址不对？ 我打开发现是正确的？

**Comment by yuyandong** [comment]
网址是对的，不过在我这里结果是普通搜索的全网络的结果。并非coderart网址内的结果
你在 http://coderforart.com/mweb-medium-like-theme.html 这里能 实现搜索功能？

**Comment by oulvhai** [comment]
我打开上面的网址是仅仅 coderforart.com 的结果。

搜索功能是自动加的，比如说你填入的 Site URL 是  http://zh.mweb.im/  ，那么所带的 site 参数就会是 zh.mweb.im。

**Comment by yuyandong** [comment]
Lantern的网络条件下我又重新测了下：

### A. V2EX测试：

在v2ex 搜索 图片 ，跳转到谷歌后，谷歌的搜索框里会显现：`site:v2ex.com/t 图片`
(谷歌搜索结果地址) https://www.google.co.jp/search?q=site:v2ex.com/t+%E5%9B%BE%E7%89%87&gws_rd=cr,ssl&ei=1OZNVqrPDoqv0gSC3rTAAw

### B. coderforart.com测试

在(CORDERART)[http://coderforart.com/mweb-medium-like-theme.html] 搜索图片，跳转到谷歌后，谷歌的搜索框里会显现：`图片` （这里搜索的就不是coderart 站点了，而是与我目的相反的全网搜索。。。）

(谷歌搜索结果地址) https://www.google.co.jp/search?q=%E5%9B%BE%E7%89%87&gws_rd=cr,ssl&ei=rOhNVpGJJeHLmwX_2IPwDQ

## B测试返回无效结果 原因

`是说 http://google.com/search?q=site%3Acoderforart.com&q=%E7%BC%A9%E7%95%A5%E5%9B%BE 这个网址不对？ 我打开发现是正确的?`

lantern科学上网的缘故，我这里
`http://google.com/search?q=site%3Acoderforart.com&q=%E7%BC%A9%E7%95%A5%E5%9B%BE`
会跳到`https://www.google.co.jp/search?q=%E7%BC%A9%E7%95%A5%E5%9B%BE&gws_rd=cr,ssl&ei=vetNVozPLKTVmgX6s7eYDA`

换VPN科学上网后，结果就回正了：
https://www.google.com/search?q=site%3Acoderforart.com&q=%E7%BC%A9%E7%95%A5%E5%9B%BE&gws_rd=ssl

然而在Lantern 方式F墙的网络里，对比下面的两个地址，明显不同 在q=site(?)这个地方
`http://www.google.com/search?q=site:v2ex.com/t%20%E5%9B%BE%E7%89%87` 
`http://google.com/search?q=site%3Acoderforart.com&q=%E5%9B%BE%E7%89%87`

可见使用「mweb-medium-like-theme」模板生成的网站，在它页面使用搜索功能，关键词（至少在我这里是）不奏效了。。。是 该主题的搜索引擎网址适配度不够。。。不如V2EX...

**Comment by oulvhai** [comment]
竟然有这种事，Lantern 会去掉重复的 Query String 参数！
这个应该不是主题的 Bug，应该是 v2ex 版兼容性更好！我有时间改进一下。

**Comment by oulvhai** [comment]
1.9 自带的主题已修正。

**Comment by oulvhai** [comment]
已有主题在这里更新： https://github.com/oulvhai/mweb-medium-like
