### ISSUE TITLE
生成的静态文件可以自动根据分类创建文件夹存放吗？

### ISSUE THREAD

**Issue by Beace** [oulvhai/MWeb-issues#671]
原本生成的静态文件如下图：

![image](https://user-images.githubusercontent.com/13284978/30202317-932ffb0e-94b0-11e7-8155-1813a2573268.png)

客户端文件结构是这样：

![image](https://user-images.githubusercontent.com/13284978/30202301-85410c04-94b0-11e7-9f06-07cd9cf17602.png)

随着文章不断加入，整个文件夹显得特别庞大，而且单个文件不容易找到，如何在生成`html`的时候像客户端一样自动创建文件夹并且分类。例如以下结构。

```
/javascript
  --articles.html
/css
  --articles.html
/...
  -- ...
```

**Comment by oulvhai** [comment]
@BeAce 不能，这样的话，预览起来会像 hexo 这种静态网站，要 http 服务器，然后图片路径和页面连接也是要绝对位置的。
