### ISSUE TITLE
MWeb生成的网站，手机浏览器访问时，站点自动套用主题的问题。

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#672]
链接是[这个](http://parussoft.com/chs/poster.html)，请使用iPhone或者安卓手机访问。

当使用手机访问时，会自动套用移动界面主题。如图的主题。iPad访问不会自动套用这个主题，而是显示和电脑一致的主题。

![mIZE4.jpg](https://s1.imgchr.com/2017/09/08/mIZE4.jpg)

主题的侧面导航里有两个链接，一个是about，一个是Achieve。这两个链接都是我不需要的。是由自动提供的主题主动生成的。访问我的网站的人一旦点击这两个页面，就会显示404，然后用户会以为是我的网站出了什么问题。

这样太不好了。请尽快解决这个问题。

**Comment by oulvhai** [comment]
@owenzhao 前几天看到，计划有空改一下，然后发现已经修改了，在 https://github.com/oulvhai/mweb-medium-like/ 这里。全部替换或者仅替换 header.html 这个文档即可。

**Comment by owenzhao** [comment]
没看懂回复。

是说最新版的MWeb，选择清空并重建网站，然后重新传一下就可以了？

**Comment by oulvhai** [comment]
@owenzhao 不是的，是把你目前的网站模板换成  https://github.com/oulvhai/mweb-medium-like/ 这里的，然后清除并重新生成网站，再重传即可。

**Comment by owenzhao** [comment]
不打算更新到MWeb里吗？每台电脑都要这么设，有点儿麻烦。再说我用的也不是这个主题啊。我用的是mweb-octporess的变种。

**Comment by oulvhai** [comment]
@owenzhao 一开始的设计是方便用户修改网站模板的，加上网站都是 100 年不会改动的，所以设计为程序更新，但是主题不更新。目前只能是自行更新了。然后你截图看，所用的主题就是 mweb-medium-like 。

**Comment by owenzhao** [comment]
这个问题好像不单单是换个主题的问题。我替换了之后，还是我原来一样。

另外，我自己自定义的菜单也没有出现。如果没有自动套用这个主题，菜单是能自动出现的。

新地址是这个：[http://parussoft.com/chs/Poster/index.html](http://parussoft.com/chs/Poster/index.html)

再次说明：我默认的主题不是这个主题。这个主题是当iPhone用户访问时，被自动套用的。是不是这里出了问题。

另外，提出更新主题，重新清空再传的方法无效。

**Comment by owenzhao** [comment]
我找到问题所在了。我的主题是旧版mweb-medium-like，不是我以为的octopress。没问题了。
