### ISSUE TITLE
多个换行怎么处理？

### ISSUE THREAD

**Issue by jaywhj** [oulvhai/MWeb-issues#673]
已经选中了 把换行转为<br>标签，输入一个回车能换一行，继续回车后就不再换行，没效果了，暂时使用<br>代替的

**Comment by jaywhj** [comment]
七牛上传增加图片处理后缀（图片处理代码）
这个怎么用？

**Comment by oulvhai** [comment]
多个换行可以四个空格加回车，或者直接用 `<br />`
可以编辑七牛上传服务，填入处理代码。

**Comment by jaywhj** [comment]
四个空格加回车 没有效果，只能一个换行，<br/>没问题


开 2017年9月12日 在 上午11:39:06, Otis (notifications@github.com) 写到:

多个换行可以四个空格加回车，或者直接用 <br />
可以编辑七牛上传服务，填入处理代码。

**Comment by est7** [comment]
为什么只能用< br /> 才能换行, 四个空格加回车预览并没有生效
