### ISSUE TITLE
在上传服务中添加 又拍云 的支持

### ISSUE THREAD

**Issue by bestony** [oulvhai/MWeb-issues#674]
我个人用又拍云比较多，不知能不能提供又拍云的支持。

**Comment by willin** [comment]
同。

@oulvhai 另外还有一个问题， 就是是否可以静态网站直接生成发布到这些静态存储服务上，或者添加个SFTP发布服务。

**Comment by oulvhai** [comment]
@willin 自行传上去即可。可以用一些 sftp 同步软件等等。

**Comment by oulvhai** [comment]
最新版本已支持。
