### ISSUE TITLE
MWEB的一个痛点

### ISSUE THREAD

**Issue by Jadyli** [oulvhai/MWeb-issues#676]
多终端没法同步。
我公司一台电脑，家里一台电脑，都装了mweb，使用git同步，但是由于这个db文件，没办法同步，两边的新增文件在db中无法合并。是否能够支持不要db文件呢，直接使用文件夹，文件名也直接使用文档的一级标题。不然这样使用很蛋疼

**Comment by lainding** [comment]
为啥git不能同步db文件呢？

**Comment by oulvhai** [comment]
@Jadyli 使用文件夹为何不用外部模式？ MWeb 目前必须 db，无法去掉。

**Comment by Jadyli** [comment]
好的
