### ISSUE TITLE
能否提供一个能在Windows环境中 向文档库里增加文档的方法

### ISSUE THREAD

**Issue by lainding** [oulvhai/MWeb-issues#680]
如题！

可以通过第三方同步实现文档库的同步，由于工作电脑是Windows，这样以后可以在Windows下创建文档，用其他编辑器也可以进行编辑。回到Mac上或iOS上还可以继续做。

**Comment by lainding** [comment]
或者能不能提供一个DB库使用的引擎，以及库结构，自己想办法写一个创建的脚本什么的。

**Comment by oulvhai** [comment]
可以看一下 文档库中的 docs 文件夹内的文档的文件名规则，按这个规则的文件都会自动变成文档库内的文档。这个文件名规则是 unix时间戳 + 4位乱数 + .md  。 你可以简单复制 docs 内最新的文档并改动一下后四位来创建文档。

db 的结构可以看 文档库下的 mainlib.db 文件。这个是 sqlite 文档，存放的是文档库的分类和分类所属文档等信息。

**Comment by lainding** [comment]
想请问文档库的地址。
另外，想请问cat表中catType, sort的编码规则。

**Comment by oulvhai** [comment]
@lainding 
catType：
顶层网站分类 11
顶层一般分类 12
子分类  13
所有文档  15
垃圾箱  14
最近文档 18
未分类文档 19

sort 其实也是 unix时间戳 + 4位乱数，一般来说跟文件名一样。

**Comment by mgdreamingstar** [comment]
也有一样的需求，但又不太懂相关的技术……
