### ISSUE TITLE
[Feature Request]文档库模式下 自动链接

### ISSUE THREAD

**Issue by menduo** [oulvhai/MWeb-issues#681]
能否支持文档库模式下自动链接，比如，markdown 里边的 `[[你好]]` 自动链接到 文档库中标题为 『你好』的文档。

谢谢。

**Comment by oulvhai** [comment]
文档库目前可以 右键 文档列表，然后选择 复制文档连接，然后粘贴。

**Comment by menduo** [comment]
@oulvhai 这个我知道，我的意思是 auto link，自动链接。

**Comment by linfeng365** [comment]
自动链接不可取; 现在的链接方法是链接到文档的文件,每个文件有独立唯一的 id ;
保证了可以**迁移**;脱离 MWeb  也可以使用。
如果按标题,文档的链接脱离 MWeb 编辑器就不可用了。

**Comment by menduo** [comment]
@linfeng365 没错，确实存在这样问题。Mweb 在导出时自动替换成相应链接就可以了。就像wiki一样。

**Comment by linfeng365** [comment]
我的意思是 文档名不是唯一的,可以命名相同的文档名;
只有文件名是唯一的;
比如:  ```[DTD 简介](mweblib://15068642622469)```

**Comment by menduo** [comment]
嗯嗯。确实会有你说的问题。就我自己的使用习惯而言，基本没有重复的。尤其是当有这个功能时，我会更加注意。
