### ISSUE TITLE
ipad bug 反馈

### ISSUE THREAD

**Issue by willin** [oulvhai/MWeb-issues#684]
第一个是计数：

![wx20170913-145523](https://user-images.githubusercontent.com/1890238/30363665-b3b6d608-9826-11e7-9102-a36ac46f5cbb.png)

显示是不对的， 而且目录的标题也是不对的。

第二个是iPad上新建文档，不能在当前分类（目录）默认都到了未分类。

第三个是iPad上无法删除文档。

另外还有一个 mac 的：

```mermaid
graph TD

action[Star一个项目] -->interface(调用star接口)
interface --> |抛出参数一致| coding(封装 Coding API)
interface --> |抛出参数一致| github(封装 Github API)
```

流程图 静态页面生成，不显示；markdown预览也不显示。

预览：  https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKCmFjdGlvbltTdGFy5LiA5Liq6aG555uuXSAtLT5pbnRlcmZhY2Uo6LCD55Soc3RhcuaOpeWPoykKaW50ZXJmYWNlIC0tPiB85oqb5Ye65Y+C5pWw5LiA6Ie0fCBjb2Rpbmco5bCB6KOFIENvZGluZyBBUEkpCmludGVyZmFjZSAtLT4gfOaKm+WHuuWPguaVsOS4gOiHtHwgZ2l0aHViKOWwgeijhSBHaXRodWIgQVBJKQ==

后来未发现- -竟然不支持 mermaid， 但现有但流程图也是有问题的：

![wx20170913-154426](https://user-images.githubusercontent.com/1890238/30365513-98e7883e-982d-11e7-8f9a-47737061f504.png)

生成页面后一半被盖掉了

**Comment by willin** [comment]
另外还有一个 mac 的：

```mermaid
graph TD

action[Star一个项目] -->interface(调用star接口)
interface --> |抛出参数一致| coding(封装 Coding API)
interface --> |抛出参数一致| github(封装 Github API)
```

流程图 静态页面生成，不显示；markdown预览也不显示。

**Comment by oulvhai** [comment]
mermaid 支持方法可参考： http://zh.mweb.im/14689205256580.html
另外你的文档库好像触发 bug 了，我正在排查。
感谢反馈！
