### ISSUE TITLE
章节缩进

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#69]
能否增加一个选项，预览/导出的时候新章节自动缩进？不然所有的章节都顶头，找下一个段落有点难，也不好看（对于我的审美观）。
目前使用“&nbsp”强制缩进的话，md文件这边就不好看了。。

**Comment by hstdt** [comment]
p{
 text-indent: 2em; /_em是相对单位，2em即现在一个字大小的两倍_/
}
加入sample-css，然后切到sample-css做预览，预览算是可以自动缩进了。需要2个回车的新段落。
导出的html不知道在哪加。
PS:这样又和Ordered冲突。

**Comment by oulvhai** [comment]
这个需求目前只能自定样式。然后的确是像这样下，如果跟 Ordered 冲突，在 MWeb 的样式中可以这样下：`div>p{text-indent: 2em; }` 。
自定样式 sample-css 后，导出 HTML 时选 sample-css 样式即可。

**Comment by hstdt** [comment]
```
1. TEXTA
2. TEXTB
```

正常

但是(为了保证1和2不断，DetailText前加TAB或空格)
1. testA
   
   DETAILTEXT
2. testB
3. testC

就会变成
![image](https://cloud.githubusercontent.com/assets/10215098/11291089/99961eb4-8f77-11e5-8be4-685fdcfe0e8d.png)

Footnote也自动缩进了。变成了这样
![image](https://cloud.githubusercontent.com/assets/10215098/11290969/6106bca8-8f76-11e5-93a4-a9f6ab263126.png)

缩进好难。。TAT

**Comment by oulvhai** [comment]
你上面的效果都是因为你加了 `p{text-indent: 2em;}` ，才会这样，你可以 Copy HTML 看看实际的 HTML 是怎么样的，如下是实际的 HTML

```
<ol>
<li><p>testA</p>

<p>DETAILTEXT</p></li>
<li><p>testB</p></li>
<li><p>testC</p></li>
</ol>
```

所以你可以我上面说的 `div>p{text-indent: 2em; }` 试试

**Comment by hstdt** [comment]
恩，这个问题解决了，应该是早上没有reload。
谢谢，现在用着非常开心~
