### ISSUE TITLE
外部文件夹列表排序混乱

### ISSUE THREAD

**Issue by ATiGr** [oulvhai/MWeb-issues#692]
错误如图 [Bad](https://i.imgur.com/kkxu5yN.png)

过去，文件夹列表是按照拼音顺序排序的。这样，所有的 “极客技巧” 类都会紧挨在一起。

正确如图 [Good](https://i.imgur.com/jddAGv0.png)

现在为什么是乱的？

**Comment by oulvhai** [comment]
之前的排序设置不影响文件夹的，后来的排序设置改成文件夹也受影响了，所以。。。  这个我考虑一下要不要改回来。。 感谢！

**Comment by ATiGr** [comment]
@oulvhai 感谢回复！还是非常希望改回来，因为原先的方式，我的笔记非常有序，现在就很纠结，文件夹多的时候要来回的找。（现在不得已暂时改用sublime text了，就是因为这个小变化）

或者希望能为文件夹的排序方式加一个toggle，这样不同习惯的用户各得其所。十分感谢！

**Comment by ATiGr** [comment]
已经更新到 2.2.7，天啊改回来了！好开心！  感谢 @oulvhai ！
