### ISSUE TITLE
[iOS] 发布服务支持设置默认目录/默认笔记本

### ISSUE THREAD

**Issue by bestony** [oulvhai/MWeb-issues#695]
## 需求描述
印象笔记的导出时每次都需要选择笔记本，能否添加支持默认的笔记本？

因为个人习惯，所有非印象笔记写就的内容都会进入 InBox

对于其他人的工作流来说，也可能有例如 MWeb 的笔记本来作为数据导入

## 当前实现
发布时选择，无法设置默认笔记本

## 目标实现
允许在创建发布服务后，设置默认笔记本、默认标签等

Btw，可以创建一个 issue template 来规范issue的提交

**Comment by oulvhai** [comment]
@bestony issue template 的话，目前 issue 提交基本上问题不大，所以就随意了。

**Comment by oulvhai** [comment]
我手上的 3.0.4 版本已改为记下最后一次选择的分类。
