### ISSUE TITLE
升级新系统，文件夹命名，拖动有问题

### ISSUE THREAD

**Issue by defp** [oulvhai/MWeb-issues#698]
![image](https://user-images.githubusercontent.com/612381/30843535-6c7c8610-a24f-11e7-9c6c-8b3d4d0b1905.png)
保存后名字不变，双击编辑文件夹名还是ELK

拖动文件夹也有问题

系统

![image](https://user-images.githubusercontent.com/612381/30843551-797c391e-a24f-11e7-945f-14e99404d952.png)

**Comment by cnzgray** [comment]
出现同样的问题，而且在删除分类之后，左侧的导航同步发生错乱。

**Comment by defp** [comment]
重启文件夹名就恢复正常

**Comment by bluest-hu** [comment]
同样遇到该问题，望解决。

**Comment by defp** [comment]
https://github.com/oulvhai/MWeb-issues/issues/690 好像一样的问题

**Comment by WingCH** [comment]
同樣問題
拍了問題demo片段
https://drive.google.com/file/d/0B4UgN78lsXiVa0VRd2JURVVXbms/view?usp=sharing

**Comment by oulvhai** [comment]
修正版本 2.2.6 已发布，更新一下即可，感谢反馈！！
