### ISSUE TITLE
调整 New 和 New in Library的快捷键

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#7]
New的快捷键是`cmd+n`，New in Library的快捷键是`cmd + shift + n`。

现在使用起来的感觉有点奇怪，因为当普通模式下（三栏，有category），想在选中的category中创建一个新文档，觉得按`cmd+n`是正常的行为，但是发现弹出来一个独立窗口，得把它关掉再看一下真正的快捷键`cmd+shift+n`才能在当前选中的category中创建。。。

或者能否提供自定义快捷键，让我自己选择合适的快捷键？

**Comment by oulvhai** [comment]
正常来说： `CMD + N` 应该是用得比较多。然后会考虑增加自定快捷键！

**Comment by iwinux** [comment]
`CMD + N` +1

**Comment by defp** [comment]
同样的感觉，快捷键新建文档不方便

另外新建按钮是不是放到上边会方便点
![image](https://cloud.githubusercontent.com/assets/612381/13899252/94713340-ee24-11e5-9853-6e3c1d9b49ee.png)
