### ISSUE TITLE
编辑器对MD标题语法渲染效果不一致

### ISSUE THREAD

**Issue by a1ickgu0** [oulvhai/MWeb-issues#70]
![snip20151119_4](https://cloud.githubusercontent.com/assets/9400523/11264046/81460510-8ecb-11e5-8ff1-62f027e98c82.png)

如图，三个标题都是通过 cmd+3 添加的标计，显示效果不同，虽然对使用没有影响，但是看起来总觉得怪怪的。 

Feature or Bug ?

**Comment by oulvhai** [comment]
确认是 Bug，感谢！

**Comment by oulvhai** [comment]
1.9 已修正
