### ISSUE TITLE
[新功能]多选并导出为 JOSN 格式

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#701]
导出内容为:
1. 文件名
2. 创建时间
3. 文本主题
4. 文本内容

导入有空也可以考虑做。

>我希望 MWeb 成为一个超强的文档管理系统;替代 evernote , dayone 等等

**Comment by oulvhai** [comment]
功能太多会让用户困惑，然后也不好针对优化。
不过看了这么多 issue，慢慢对新版本也有一些基本概念了。

**Comment by linfeng365** [comment]
导入是为了从其它软件导入笔记。
导出是为了对笔记做进一步的处理。
在导出过程中,多选功能很重要。

**Comment by linfeng365** [comment]
比如:
从 Dayone 导入数据。

**Comment by oulvhai** [comment]
目前仅计划优化支持导入时保持文件夹结构（变成目录结构），导出时可以按设置好的文件名导出。
其它格式转换就靠自己动手了。
