### ISSUE TITLE
希望优化代码块粘贴功能

### ISSUE THREAD

**Issue by Jadyli** [oulvhai/MWeb-issues#702]
如果我想在代码块中只贴一个方法，那么在AndroidStudio中复制出来的方法，因为这些方法是在类里面显示的，每行前面肯定带了一堆缩进，但是方法单独贴到MarkDown里就显得不好看了，我得一行一行删除缩进，所以建议增加自动检查代码块最前的字符，然后所有行按这个字符的缩进往前自动删除。
现在效果：

```
    public void onRequestRefresh() {
    }
```
期望效果：

```
public void onRequestRefresh() {
}
```

**Comment by oulvhai** [comment]
选择后 Shift + Tab 进行处理。
