### ISSUE TITLE
iPad Pro 代碼塊 高亮效果失效

### ISSUE THREAD

**Issue by WingCH** [oulvhai/MWeb-issues#707]
詳細看圖

![image1](https://user-images.githubusercontent.com/19588517/31068654-86b38c7c-a78b-11e7-9c31-b2f10b9982e4.jpeg)
![image2](https://user-images.githubusercontent.com/19588517/31068664-8ecf6ffc-a78b-11e7-8b6d-9afa21229f07.jpeg)

**Comment by A6669** [comment]
在ipad内点击左上的齿轮，有一个选项可以打开代码高亮，作者默认关闭的原因是打开后预览会变慢。
