### ISSUE TITLE
Footnote2个问题

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#71]
1. 如果Footnote中有空格，那么就会没有Footnote格式的提示，强迫症看得难受，还会怀疑是不是写错了。

```
word[^test1].

[^test1]: NOSpace 

word[^test2]

[^test2]: A space。

```

![image](https://cloud.githubusercontent.com/assets/10215098/11291364/3cc1ad7c-8f7a-11e5-8092-2c750426534a.png)

2.如果不把Footnote写在md文件的最后面，那么就会导致Preview错位，Footnote多了之后，就完全对不上了，这个算是可以避免的bug吧。

**Comment by oulvhai** [comment]
1.9 已修正
