### ISSUE TITLE
XML-RPC fault `parse error. not well formed'

### ISSUE THREAD

**Issue by sawyeron** [oulvhai/MWeb-issues#710]
在发布功能中的“Metaweblog API”，配置了自己博客。但是在选择分类、标签等信息后发布，提示错误。
<img text-align="center" width="526" alt="2017-10-03 10 35 41" src="https://user-images.githubusercontent.com/16789220/31107756-44703b7a-a827-11e7-8e29-01e4f4a4e696.png">

- 系统 MacOS 10.13
- MWeb 2.2.4

**Comment by sawyeron** [comment]
- 系统 MacOS 10.13
- MWeb 2.2.4

**Comment by oulvhai** [comment]
感觉是 xmlrpc 的问题，能否去线上的 xmlrpc 验证一下 xmlrpc 的情况？ google 搜索 xmlrpc validation 这种。

**Comment by sawyeron** [comment]
没有用其他工具验证。

更新了2.2.6后，昨天更新成功，特此反馈。

这篇文章[《WebFont 与著作权》](https://imouyang.com/webfont-yu-zhe-zuo-quan.html)就是用MWeb发布的，很棒！
