### ISSUE TITLE
“偏好设置”-“发布服务”界面卡顿？显示问题？

### ISSUE THREAD

**Issue by sawyeron** [oulvhai/MWeb-issues#711]
<img width="591" alt="2017-10-03 10 35 14" src="https://user-images.githubusercontent.com/16789220/31107820-c34c4c68-a827-11e7-80d9-3fe2eeddac64.png">

- 系统 MacOS 10.13
- MWeb 版本 2.2.4

**Comment by oulvhai** [comment]
修正版本 2.2.6 已发布，更新一下即可。

**Comment by sawyeron** [comment]
是的，新版已修复该情况。
