### ISSUE TITLE
修改左侧导航栏修改信息后无法即时刷新

### ISSUE THREAD

**Issue by pulgawang** [oulvhai/MWeb-issues#712]
无论是修改文章的category还是修改名称、移动文章等等，都需要关闭mweb后才显示正常

os:macos 10.13
version:Version 2.2.4

**Comment by pulgawang** [comment]
[issues 698](https://github.com/oulvhai/MWeb-issues/issues/698) 就是这个问题

**Comment by oulvhai** [comment]
修正版本 2.2.6 已发布，更新一下即可。
