### ISSUE TITLE
搜索功能太弱

### ISSUE THREAD

**Issue by A6669** [oulvhai/MWeb-issues#716]
有时搜索东西时，想再某个标签下或某个类别下搜，但mweb没有这种功能，举例
AAA tag:bbb, title:ccc, -category:ddd
上面表示在具有标签bbb和标题含有ccc但不属于ddd类别的文件中搜索AAA。

**Comment by linfeng365** [comment]
+1 
印象笔记有的功能。

**Comment by oulvhai** [comment]
这种语法不错，感谢建议！

**Comment by tianhao** [comment]
我做了个alfred 的workflow，目前支持搜索多个关键字，支持 tag 筛选
https://github.com/tianhao/alfred-mweb-workflow

**Comment by A6669** [comment]
@tianhao 谢谢，对我很有帮助，能否添加上对标题title，和分类的支持，标题可以理解为文件的第一行。

**Comment by A6669** [comment]
@tianhao 应该使用Alfred Powerpack还是alfred for mac？

**Comment by tianhao** [comment]
@HongTao628  需要 Alfred Powerpack 哦，非 Alfred Powerpack 没法使用 workflow

**Comment by A6669** [comment]
@oulvhai 這個用起來還是不太方便，希望能早日加上對分類，標籤和標題（第一行）的支持，謝謝。

**Comment by tianhao** [comment]
我最近修改workflow后已经支持标题搜索了，-h 关键字1，关键字2，... 
不过分类稍微有点复杂，暂时没打算做分类搜索
当然原生支持最好了

**Comment by oulvhai** [comment]
从 MWeb 3.1.8 版本开始支持以下的搜索语法：

```
[keyword1] [keyword2]... [-c category1,category2...] [-t tag1,tag2...] [-h keyword1,keyword2,...] 
```

**相关例子：**

1. 如果填入 “MWeb 博客”，将查找文档内容包含有 “MWeb” 和“博客”这两个关键字的文档。
2. 如果填入 “MWeb 博客 -c 分类1,分类2”，将查找分类同时包含“分类1”和“分类2”，并且文档内容包含 “MWeb” 和“博客”这两个关键字的文档。
3. 如果填入 “MWeb 博客 -h 发布,样式”， 将查找标题同时包含“发布”和“样式”，并且文档内容包含 “MWeb” 和“博客”这两个关键字的文档。
4. 在外部模式中，如果填入 “MWeb 博客 -h 发布,样式”， 将查找文件名同时包含“发布”和“样式”，并且文档内容包含 “MWeb” 和“博客”这两个关键字的文档。
