### ISSUE TITLE
左侧的目录出错

### ISSUE THREAD

**Issue by xgz123** [oulvhai/MWeb-issues#718]
系统:macos high sierra
版本: 2.2.4 (293)
问题:
1. 删除一个目录, 其他目录的名称就乱了,  出现重复, 再次打开恢复正常
2. 某个目录显示`(17)`这样, 意思是有文件, 点击却没有
3. 某些目录下明明有文件夹, 点击却是空的, 再次打开, 点击该位置, 恢复正常(子文件夹及文件出现)

**Comment by oulvhai** [comment]
更新至 2.2.6 版应该OK了。
