### ISSUE TITLE
链接名不支持空格

### ISSUE THREAD

**Issue by firemiles** [oulvhai/MWeb-issues#72]
比如 [link 1](./link.md) 这样的链接无法正常正常跳转。

**Comment by oulvhai** [comment]
这个连结的目前是点了之后打开 link.md 吗？

如果是，请用外部模式引入 link.md 的所在文件夹就可以了。不然 MWeb 是没有权限读取 link.md 的。更详细可参考：https://github.com/oulvhai/MWeb-issues/issues/26

**Comment by firemiles** [comment]
link.md已经被我添加进去了，这个无法跳转的原因是link 1之间有空格，如果我改成[link-1](./link.md)就可以正常跳转，不知道这个问题是不是普遍存在的还是我的个例。

**Comment by oulvhai** [comment]
我暂时无法重现这个问题。

**Comment by firemiles** [comment]
![image](https://cloud.githubusercontent.com/assets/3798688/11451609/1c8b2036-9607-11e5-8661-84d8f977d6eb.png)
如图中的情况，如果有空格就是链接失败，没有就可以

不好意思浪费了你的时间，我发现真正的原因是在链接里的空格，并不是名称里空格😅

**Comment by oulvhai** [comment]
你报了一个语法高亮的 Bug，非常感谢！

**Comment by oulvhai** [comment]
1.9 已修正。
