### ISSUE TITLE
导出 Markdown ... 时,能自动在换行前加两个空格吗?

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#723]
**原因:**
Markdown 格式,换行需要加两个空格。
这个习惯真反人性。
很多编辑器都可以直接换行,不用加两个空格。(比如:GitHub 文本框就不需要加两个空格。)

但输出为标准的 Markdown 后,换行就不起效果了。
MWeb 也有把换行转为 `<br>`标签选项。很好用。

**期望:**
导出 Markdown 格式,自动处理把在换行前加上两个空格。
最好是有设置选项。决定是不要使用该功能。

**评价:**
有这小功能,就完美了。

**Comment by oulvhai** [comment]
目前不太考虑自动改动原文档的功能。

**Comment by linfeng365** [comment]
@oulvhai  导出是格式,并不是改变原文档。并且在 `把换行转为 <br>标签` 之下提供一个选项`导出 Markdown 文档自动在换行前加2个空格` 就好了呀

我想到只有自动格式化是最统一,方便的了。
如果确实没有,我只能自己写一个程序用来把导出的 md文件 换行前加2个空格的处理了。
