### ISSUE TITLE
更新后mweb打不开了

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#725]
什么个情况，刚更新后就打不开了， 重启计算机也没用

**Comment by fmewtwo** [comment]
能不能测试好再发布，我去，手贱一更新，这么不耽误事么

**Comment by oulvhai** [comment]
@1412kid 你系统版本是？目前仅测试过 10.12 和 10.13， 10.11，10.10，10.9 都没测试，因为测试环境暂时被我搞坏了。
如果你是 10.12，10.13，可以试试去官网下载试用版覆盖看看，可能是更新出问题了。

**Comment by fmewtwo** [comment]
系统 10.11.6  我已经又换回到2.2.4

**Comment by oulvhai** [comment]
@1412kid 我刚刚用 VirtualBox 装了 10.11 和 10.10 来测试，好像都没问题。可否帮忙试试直接去官网下载试用版本，然后不覆盖原版本，放在桌面上或者文档文件夹里直接打开，看看是否会打不开。或者如果打开直接闪退，可否发反馈给我？ 

目前我好像暂时没有真机测试的环境。

非常感谢！！

**Comment by oulvhai** [comment]
@1412kid 我用真机测试，找到 bug 了，然后此 bug 的修正版本，2.2.6 版也已发布，你可以去官网下载试用版直接试，没问题后再覆盖。
非常感谢！
