### ISSUE TITLE
mac 端和 iOS 端的目录点击都无法跳转相应条目。

### ISSUE THREAD

**Issue by uclort** [oulvhai/MWeb-issues#727]
app 均为最新版，mac OS 10.13，iOS 11.1 beta2 ，iOS 端此问题存在好久了，之前发过邮件，最近一次更新也没有解决。

**Comment by linfeng365** [comment]
没碰到过;  (macOS 10.11, iOS 最新版;)

**Comment by ltmsyvag** [comment]
同楼主，表示同样无法跳转.

特意说明一下这里说的 “目录” 是在编辑器中输入 [TOC] 后，最终在 preview 中生成的目录链接，不是 MWeb 自带的目录功能（macOS 上 `cmd` + `7` 调出的目录）

我的 MWeb app 均为最新版，系统为 macOS High Sierra， iOS 11，均为最新版. 可以确定这个问题是系统升级后才出现的，在 Sierra 和 iOS 10 时无此问题

**Comment by linfeng365** [comment]
我的 [TOC] mac版可用, iOS 版不可用。(macOS 10.11, iOS 最新版;)

**Comment by oulvhai** [comment]
目前确认的确是预览下生成的 TOC 点击无用，iOS 11 和 High Sierra 下都不行。我试分析了一下代码，感觉是系统 bug 可能性比较大，因为 Apple 并没在文档中说改动到这部分。

**Comment by saup007** [comment]
关注下。也遇到 TOC 预览不能跳转的问题。

**Comment by eyes4** [comment]
同样的问题，顶

**Comment by oulvhai** [comment]
经测试，此问题应该是解决了。
