### ISSUE TITLE
链接问题

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#728]
`[本地链接文件](本地链接地址)  `使用本地链接地址不可以么？ 
请增加本地链接的支持

**Comment by linfeng365** [comment]
@1412kid  我测试了一下, 是支持本地链接地址。
但有 bug 。

```
[用户目录](/Users/linfeng365/)

[txt](/Users/linfeng365/output.txt)

[pdf](/Users/linfeng365/物性论 (Lacretius C.T.).pdf)
```

在编辑模式,都能打开。
在预览模式下, 目录, pdf 能打开,
但 txt 不能打开。

其它类似没用测试。

**Comment by oulvhai** [comment]
@1412kid @linfeng365 这个打开如果是 txt 或者 markdown 文档，会调用 MWeb 打开，然后 MWeb 要打开这链接中的文档，首先要有读写这个文档的权限。而这个权限一般情况下是没有的，只有用外部模式引入 MWeb 中的文件夹内的文档才有。

所以一般情况下是不能打开 txt 文档的，但是如果连接是引入 MWeb 的文件夹内的文档，就能打开。

**Comment by linfeng365** [comment]
@oulvhai 
在编辑模式,都能打开。而且是调用了系统的默认打开程序;
我的是 Sublime Text 打开了 txt。

**Comment by linfeng365** [comment]
@oulvhai 
只是在 在预览模式下, 目录, pdf 能打开,
但 txt 不能打开。

**Comment by linfeng365** [comment]
请标记为 bug。

修复 在预览模式下,  txt 不能打开的问题。

别的一些软件是支持的,而且很好使用。

**Comment by oulvhai** [comment]
@linfeng365 已标记。

**Comment by fmewtwo** [comment]
@oulvhai   我是希望目标文件能用它默认的软件去打开，不是在mweb里打开，  我链接了一个pdf，显示"应用程序Mweb没有权限打开XXXXX.pdf"，  这几天刚升级系统到了 10.13，   我记得以前是能打开pdf什么的，现在不能用了也包括txt之类的。

**Comment by oulvhai** [comment]
@1412kid 这方面的东西并未做改动。Apple 什么鬼都偷偷改了，然后一点说明都没有的。我看看能不能修。

**Comment by A6669** [comment]
@1412kid @oulvhai  @linfeng365 在mac10.10.5下有相同问题，mweb2.2.8，本地链接`[pdf](/Users/name/Lacretius.pdf)`
在预览模式下点击，显示mweb无权限打开此文件，这是bug吗，可能和10.13无关，望修复。
