### ISSUE TITLE
右键菜单export和菜单栏export不一致，以及流程图无法导出到docx

### ISSUE THREAD

**Issue by antony9** [oulvhai/MWeb-issues#73]
- 右键菜单中，有Export as HTML/PDF/Markdown。而在菜单栏中，File下有Export as HTML/RTF/Docx。为啥设置的功能不一样？是故意的么？
- 流程图（sequence diagram）导出到pdf时非常美观，导出到docx时则完全丢掉了格式。

**Comment by oulvhai** [comment]
1. 不是故意的，是 File 下忘记加 PDF 了。
2. 目前导出 docx 功能是非常原始的，连图片都不支持，只能在一般的情况下够用。

**Comment by antony9** [comment]
其实我想说的是，我觉得导出到docx功能好好用。。。
尤其是对于纯文字，感觉导出非常完美。。。

**Comment by oulvhai** [comment]
这功能其实是想做好的，但是要花很大精力，所以估计一段时间内都会这样了。 一般使用应该没问题，大概流程是导出后不满意，就在 pages 等软件中调整。

**Comment by LavareX** [comment]
Version 2.1.4 (257)
1. 在菜单栏中，File 下还没有 Export as Markdown。
