### ISSUE TITLE
macOS 2.2.6(300) 版发布到印象笔记报错

### ISSUE THREAD

**Issue by grock304** [oulvhai/MWeb-issues#730]
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Attribute name "light" associated with an element type "div" must be followed by the ' = ' character.}

**Comment by oulvhai** [comment]
如果你文档中没有 <div 元素和名和 light 的属性，可以试试用 mweb-*  这些预览样式。否则的话，去掉 div 中为 light 的属性即可。

**Comment by grock304** [comment]
可是我的文档里只有 #、```、* 这三种标记而已，样式用的是 mweb-github，而且之前都能发布，这次时隔半个月，只改了几个错别字而已……
