### ISSUE TITLE
使用列表标记的时候，换行后的第一个Tab，希望能自动做缩进。

### ISSUE THREAD

**Issue by awayings** [oulvhai/MWeb-issues#734]
使用列表标记(`*`)的时候，换行默认会生成自动增加一个`*`标记，很多时候会需要做子标签。这时候操作流程是光标移动到自动生成的`*`前-> 按`tab` -> 光标移动到最后。十分不方便。能否在自动生成`*`的时候，第一个tab默认做缩进从而生成。

`*` 后按 `shift-tab` 会减少缩进。然而直接按 `tab` 确不会增加缩进。不对称的设计不够友好。mac 版本。

> 简洁-效率 是这个工具的核心特点。希望在文本编辑的这个功能上的优先级更高一些。即使这个功能点很小。

**Comment by oulvhai** [comment]
最新版本已按这个设计。
