### ISSUE TITLE
mac端：列表预览情况下的序号存在问题

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#739]
[TOC]

### 1、bug描述：
列表预览情况下的序号不符合预期

#### 2.1、markdown：
```markdown
1. 元素1

关于元素1的说明

2. 元素2
```

#### 2.2、预览结果：
![image](https://user-images.githubusercontent.com/5676311/32041884-65156608-b9fb-11e7-816a-508603f497dd.png)

#### 2.3、预期结果：
`2.` 预览时应该也是`2.`，而不应该是 `1.`

**Comment by oulvhai** [comment]
这种写法在 MWeb 的用法是：  「关于元素1的说明」 前后要空一行才行。

**Comment by chenzz** [comment]
已经空过了，还是有问题

**Comment by oulvhai** [comment]
@chenzz 前面应该还要加 Tab，如图：
![image](https://user-images.githubusercontent.com/2174294/32260565-b7c08974-be96-11e7-908a-87d485780d21.png)

**Comment by chenzz** [comment]
感觉这个设定有点奇怪……

**Comment by oulvhai** [comment]
@chenzz 这个是 MWeb 所用 markdown 解析库的语法，也就是说必须这样写，才会正确解析。

**Comment by chenzz** [comment]
建议在mweb的demo里添加这个语法说明

**Comment by oulvhai** [comment]
@chenzz 我先记下，感谢建议！
