### ISSUE TITLE
mac端：生成pdf时应该列出目录

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#740]
### 1、问题描述：
生成的pdf没有列出目录

#### 2.1、markdown：
```markdown
### 1、标题1

关于标题1的说明

### 2、标题2

关于标题2的说明
```

#### 2.2、导出pdf结果：
![image](https://user-images.githubusercontent.com/5676311/32042230-75515a30-b9fc-11e7-81d1-416d3670729c.png)

#### 2.3、预期结果：
左侧列出所有标题

**Comment by oulvhai** [comment]
目前这个功能，仅 Sierra (10.12) 系统不支持。

**Comment by chenzz** [comment]
那这个是bug了，请修复吧~

**Comment by oulvhai** [comment]
@chenzz 参考 https://github.com/oulvhai/MWeb-issues/issues/370 这里，详细说明了情况。
