### ISSUE TITLE
ios 端 icloud 不会自动更新 mac 上建立的文件, 系统 ios11

### ISSUE THREAD

**Issue by lhrkkk** [oulvhai/MWeb-issues#745]
mac 上在 icloud 内的 Mweb 文件夹内新建的文件,  在 ios 端查看并无更新. 

但是如果是对已有文件做修改或删除, ios 端是可以看到更新的. 

新建的文件需要用 files 打开 Mweb 文件夹, 然后下载下来, 才能在 mweb 里面看到. 

系统是 ios11

**Comment by oulvhai** [comment]
目前还没发现 Apple 有**马上**自动更新的 API，非即时的就有，我肯定是有调用了，但是更新不更新，还是不能控制了。

**Comment by lhrkkk** [comment]
@oulvhai 我这边是无法更新, ios 必须进入 files 里面打开 Mweb 文件夹才能更新. 我的 mac 是10.11系统, 不知道和这个有没有关系? 但是 ios files 里面已经看到所有文件了, 文件应该已经上传到 icloud 上面的

我在 byword 里面建立新文件, byword 是可以自动更新的

**Comment by lhrkkk** [comment]
所以我目前使用的是 dropbox 同步, 还算正常, 但是还有个问题 #750 , 可以参看下

**Comment by oulvhai** [comment]
@lhrkkk 可能是双端支持 iCloud Drive 会触发一些机制吧，我仔细研究一下，感谢你的反馈！
