### ISSUE TITLE
 ios 端希望增加全文搜索功能, 像 mac 端一样

### ISSUE THREAD

**Issue by lhrkkk** [oulvhai/MWeb-issues#746]
非常喜欢 ios 端 mweb 的搜索过滤器, 这个过滤器很方便, 但是发现目前只能搜标题. 希望能够和 mac 端一样能搜全文. 

如果可以, ios 端和 mac 端都希望可以加个选项, 选择搜标题还是搜全文, 这样可以更好的过滤和搜索.

**Comment by oulvhai** [comment]
这个我测试下来觉得比较费能耗，最近也是没有发现好办法。我再研究看看好了。

**Comment by hytor-yang** [comment]
#850

**Comment by oulvhai** [comment]
iOS 最近计划个蛮大的升级，计划增加此功能。
