### ISSUE TITLE
关于文档库模式的想法：1. md文件可自定义名字; 2. 标签类似Hexo注释在文档上方

### ISSUE THREAD

**Issue by lihsai0** [oulvhai/MWeb-issues#749]
# 关于MWeb的使用反馈

### 就当前版本这样做可能导致的问题：

用户通过MWeb以外方式重命名md后，MWeb无法依据db文件找到对应文章。

### 考虑到的解决方案：

  1. 这个功能可以作为一个“自定义标题模式”，开启这个模式后，警告用户⚠️如果通过MWeb以外方式重命名md，将会使MWeb找不到文章
  2. MWeb发现对应文章丢失的话，列出丢失的文章，让用户去选择文章对应md文件或者放弃这篇文章。

前者好做但是不太友好，后者友好点但是工作量不小。这两个解决方案都有一个共同问题就是会产生失效文件。因为MWeb可能还需要做一个清理功能来清理docs下失效的md文件。

### 可行性讨论：

当前版本应该是把这些信息作为字段存储到了db文件中。这个功能感觉只是提供了更好的源文件可读性，不需要像Hexo一样去解析这些信息。因此相对来说好做，也并不会对现有系统产生影响

### 考虑到的具体做法：

在设置中可打开这个功能，然后在MWeb保存文件时读取标签等信息，像以下方式一样插入md文件开头

``` html
<!--
    title: Title
    author: xxx
    tags:
      - MWeb
      - Feedback
    categories:
      - CustomerFeedback
    date: 2017-10-31 12:00:00
-->
```

因为当前开头的标签等信息已经很漂亮了，如果想做的更好点，可以加些字符让MWeb编辑这个文件时忽略这个开头（不显示这个开头）。当然这样做可能会有一定的工作量。

比如像这样的字符来告诉MWeb忽略这个开头：

``` html
<!-- MWeb Ignore
    title: Title
    author: xxx
    tags:
      - MWeb
      - Feedback
    categories:
      - CustomerFeedback
    date: 2017-10-31 12:00:00
-->
```

**Comment by oulvhai** [comment]
文档库不支持自定义文件名等等是为了性能考虑，也就是说十来万规模的笔记也能很快。 MWeb 有一个文档可归类于多个分类的需求，这样管理起来更灵活，因为这个，很多特性无法做，同步也比较麻烦，但是我认为是值得的。

所以要自定义文件名或者 hexo 的用法，建议还是用外部模式。

**Comment by lihsai0** [comment]
技术浅，开始对您使用的技术好奇了。都是根据文件名读写文件，方便透露一下为什么会产生这种性能问题吗？

**Comment by oulvhai** [comment]
@lihsai0 是这样的，支持自定义文件名的话，可以另开一个数据表，保存固定名和自定义的名，这样倒是问题不大，但是没有必要，文件名在文档库也不会用到。 
而像 hexo 这种文件头部加 YAML 信息的做法，如果文件多的话，统计文件的头部信息就是会比较费性能。

**Comment by Jadyli** [comment]
+1,希望外部模式增加可自定义新建文件的头部模板信息功能

**Comment by oulvhai** [comment]
@Jadyli 这个其实是特殊用法，还在考虑是否要这样优化。 其实这个需求更适合的是使用快速输入类软件，比如 aText 这种。
