### ISSUE TITLE
ios端 dropbox 同步功能，建议每次进入mweb的时候，都要自动主动同步一次

### ISSUE THREAD

**Issue by lhrkkk** [oulvhai/MWeb-issues#750]
发现现在 ios 端要想获取 dropbox 的更新, 必须手动同步才可以. 建议用户每次切入 mweb 的时候, 都自动主动同步一次. 

因为如果不同步, 用户所对旧版本文件做的修改存盘后, 会覆盖 dropbox 的云端内容. 

可以参考 ulysses，是启动必同步并自动定时同步的。

**Comment by oulvhai** [comment]
目前最新版本还是改成按需同步。已再次修正了同步的一些问题。
