### ISSUE TITLE
ios 端, 希望可以像editorial一样，按空白区域滑动，不需要按左边缘才可以滑动。

### ISSUE THREAD

**Issue by lhrkkk** [oulvhai/MWeb-issues#752]
ios 端, 右手操作的时候, 从编辑文件回退到目录的时候, 必须从左边缘滑动, 比较不方便. 如果可以像 Editorial 一样, 按住屏幕任何区域都可以滑动, 会大大优化日常体验.

**Comment by linfeng365** [comment]
回到目录不是最频繁的操作吧?
我到希望可以不回目录,跳转上一文档,或下一文档。

后续如果增加 前进后退操作; 那么回到目录,可能就没有手势了。只能按钮。
那么跳转上下文档,又没有手势的可能。只有增加按钮了。
看来遥遥无期啊。

**Comment by oulvhai** [comment]
回到目录现在这样可以了的，MWeb 又不是阅读类的 app。
