### ISSUE TITLE
问题反馈：命令行打开过个文件在新windows中打开，而不是新tab

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#757]
问题反馈：命令行打开多个文件在新windows中打开，而不是新tab

如使用以下命令打开多个文件

```shell
open -a /Applications/MWeb.app /path/to/aFile.md
open -a /Applications/MWeb.app /path/to/bFile.md
open -a /Applications/MWeb.app /path/to/cFile.md
```

每个文件在不同的window里，显得很不方便。

希望能在同一个window，不同的tab中。

这个功能主要是解决
https://github.com/tianhao/alfred-mweb-workflow
这一项目的这个问题
https://github.com/tianhao/alfred-mweb-workflow/issues/3

**Comment by oulvhai** [comment]
最新版本已解决此问题。
