### ISSUE TITLE
已发布到 wordpress的文档更新之后在 Wordpress 中状态成为定时发布

### ISSUE THREAD

**Issue by imfht** [oulvhai/MWeb-issues#758]
Wordpress 版本: 4.8.3
MWeb 版本：2.2.7

**Comment by oulvhai** [comment]
可以试试把你 Wordpress 的时区调成跟你电脑的一样。

**Comment by liyang85** [comment]
和时区没有关系，我的WordPress时区是上海，电脑也一样，但问题同样会出现。

**Comment by imfht** [comment]
经测试问题已经无法复现（疑似已经修复），原因不明。 @oulvhai 你还存在这个问题吗？

**Comment by oulvhai** [comment]
@fiht 我测试是没问题的，所以我想仔细再试试。。感谢反馈。 如果你知道怎么复现，也可以回复。

**Comment by imfht** [comment]
找到复现了方式了。
测试时间：北京时间晚九点
****
## 新建文档，时间正常：
![image](https://user-images.githubusercontent.com/15059493/34107835-b236b1f0-e438-11e7-8652-ee075499aeb1.png)
## 编辑文档之后，点击发布到 Wordpress，时间错误
![image](https://user-images.githubusercontent.com/15059493/34107888-dd607d02-e438-11e7-8d45-ccfa99126850.png)
****
一个暂时的解决方法是在更新的时候手动点击`今天`按钮

**Comment by liyang85** [comment]
请问这个bug计划何时修复？因为我会持续更新发布过的文章，目前这种每次更新都把原始发布日期增加8小时的情况让人不胜其烦。

**Comment by imfht** [comment]
新版本已经修复，关掉了~
