### ISSUE TITLE
希望可以增加发布到Github的功能

### ISSUE THREAD

**Issue by chensifeng** [oulvhai/MWeb-issues#76]
MWeb和Github有很多天生的共同之处。如果能在MWeb上编译，然后一键同步到Github上，就完美了！

**Comment by lxmfly123** [comment]
非常需要这个功能

**Comment by ZhaiHaiSheng** [comment]
同需要..文章现在能实现直接发到HEXO么?

**Comment by lfyzjck** [comment]
+1

另外目前有个BUG，静态网站编译的时候，一旦编译过一次，输出路径就无法修改了

**Comment by oulvhai** [comment]
最新版本已实现发布脚本功能。
