### ISSUE TITLE
cmd + 1，2，3，4 切换视图有重大bug

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#760]
cmd + 1，2，3，4 切换视图非常卡， 按的快一点整个mweb就卡死无响应了
(mweb2.2.7， 系统10.13)

另外在这吐槽下10.13系统，升级后是屁事真多，感觉又上了苹果的当。

**Comment by oulvhai** [comment]
macOS 10.13.1, mweb 2.2.7， 胡乱按了一会，暂时未能重现。

**Comment by xingchengyusi** [comment]
mweb 2.2.7, Mac OS 10.13.1 一样的问题。

我只有在三栏视图模式或者三栏视图加预览视图才能顺利写作，如果仅显示编辑器或者二栏视图的话，则会卡顿到完全不能工作。但是如果在全屏模式中，就没有这个问题。

而且这个问题不仅存在于MAC中，在iOS中，如果我仅使用编辑器模式后，过一段时间，会频繁在编辑器模式和显示文档库的模式之间来回转换，频率较快，影响使用。iOS版本11.1

**Comment by oulvhai** [comment]
@xingchengyusi 有这个问题可以删除 MWeb app 再重新下载试试。有朋友遇到过这情况。

**Comment by xingchengyusi** [comment]
谢谢，我会试试～
________________________________
