### ISSUE TITLE
MWeb 正式版发布到印象笔记出现问题

### ISSUE THREAD

**Issue by abnerwang** [oulvhai/MWeb-issues#761]
买了MWeb正式版，对 lite 版的发布效果很满意，但是正式版反而在发布的时候出现问题了。将预览样式设置成 mweb-octopress，开始发布到印象笔记，出现如下错误：

![snip20171109_1](https://user-images.githubusercontent.com/3347482/32595110-80e27ece-c569-11e7-855c-ed65dd4d76fb.png)

将预览样式设置成 mweb-github 可正常发布，可是在手机端查看内容那个格式简直让人无力吐槽，看上去非常奇怪。

对 lite 版用着满意才购买的正式版，可是哪知道正式版 bug 这么多，希望尽快解决吧！心累呀

**Comment by abnerwang** [comment]
@oulvhai

**Comment by abnerwang** [comment]
我的系统 Mac OS high sierra

**Comment by oulvhai** [comment]
感觉是印象笔记样式的新规则，需要修改一下 mweb-octopress 这个预览样式，下个版本修正。感谢反馈！

**Comment by oulvhai** [comment]
@abnerwang 我测试几篇文档，用的是 mweb-octopress 样式，都成功了。然后我仔细查了一下，好像不是 mweb-octopress 的问题。 应该是你文档中有 <div 这个文本或者元素，然后又有 sans 这个属性。简单的办法是把 < 换成`&lt;` 试试。

**Comment by oulvhai** [comment]
@abnerwang 在 High Sierra 下重现此 bug，非常感谢！

**Comment by Funnyang** [comment]
@oulvhai 这个 bug 修复了么

**Comment by Magusliuj** [comment]
@oulvhai "把 < 换成&lt;" 我只在引用网页的时候用到了"<" 仍然有这个问题
