### ISSUE TITLE
为什么更新完后代码块的预览都不高亮了

### ISSUE THREAD

**Issue by fmewtwo** [oulvhai/MWeb-issues#767]
系统(10.13.1)  mweb(2.2.8)  代码的预览样式全都没了， 我又恢复到2.2.7后还是没有，出什么问题了。

另外#760 切换视图有bug 2.2.8依然有， cmd+1 视图根本就不能工作，直接卡死无响应， 就我一个人有问题么

**Comment by oulvhai** [comment]
@1412kid 可以删除 MWeb app 再重新下载试试。有朋友遇到过这情况。 
代码高亮没有，还可以看看菜单：视图 - 在实时预览中禁用代码高亮 是否勾选。
