### ISSUE TITLE
图片复制粘贴上传到七牛的bug

### ISSUE THREAD

**Issue by Jadyli** [oulvhai/MWeb-issues#775]
外部模式下，设置自动上传到七牛，复制粘贴到编辑器中，比如我的文件名是img1.jpg,文件会上传到七牛，文件在七牛的名字也是这个，但是编辑器显示的图片地址是15113480793902.jpg这种。。。直接将图片拖到编辑器是正常的。

**Comment by oulvhai** [comment]
看样子是七牛的配置中的 图片 URL 前缀没填，可以参考 ：http://zh.mweb.im/how_to_use_qiniu_url.html

**Comment by Jadyli** [comment]
填过了啊，mac版的。
![image](https://user-images.githubusercontent.com/15962904/33412511-b9cbfba8-d5c6-11e7-99ca-3a9000e43c51.png)

**Comment by oulvhai** [comment]
@Jadyli 我明白了，你是说从 Finder 中复制图片文件，然后粘贴到 MWeb？ 目前还不支持这种方式。文件只支持拖拽方式。粘贴是指截图然后粘贴。

**Comment by Jadyli** [comment]
好的，明白
