### ISSUE TITLE
publish 到印象笔记失败

### ISSUE THREAD

**Issue by cnbleu** [oulvhai/MWeb-issues#78]
以下是返回的错误代码。

Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "meta" must be declared.}

**Comment by oulvhai** [comment]
你的文档可能有 <meta 这种字符。 印象笔记认为这种是一个 html 元素，所以不允许发布。 你可以用 `&lt;` 代替 < 试试。

**Comment by cnbleu** [comment]
@oulvhai 确实有 <meta  这种字符，使用 mweb 做技术笔记用的，每个文档都手动处理的话挺费时的，你们可以程序处理下吗？

**Comment by oulvhai** [comment]
下一版可以尝试修正一下看看。

**Comment by cnbleu** [comment]
@oulvhai 多谢！

**Comment by selfboot** [comment]
我也遇到这个问题了，不过每次用 ` ` 来包裹<meta> 这种字符就行了。比如 `<head>`
