### ISSUE TITLE
求 X callback url Scheme 啊

### ISSUE THREAD

**Issue by menduo** [oulvhai/MWeb-issues#784]
真的很需要哪！

**Comment by menduo** [comment]
期待下个版本支持啊！哪怕只能从外部app跳转到指定文档啊！

**Comment by menduo** [comment]
@oulvhai hi 大神，这个功能估计什么时候会发布呢？能安排到下个版本吗？因为会影响到我接下来的一些app购买安排。😍😍😍

**Comment by oulvhai** [comment]
@menduo 标记了 very high 的都会是一两个版本内。

**Comment by menduo** [comment]
@oulvhai 感谢！
