### ISSUE TITLE
必须切换到三栏视图模式下工作，否则就会卡，Cpu占用高

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#785]
切换到仅显示编辑器模式(cmd+1)/双栏视图模式(cmd+2)就会非常非常卡，cpu用满(不工作情况下一般1%都不到)。

 系统： macOS 10.13.1，MWeb 2.2.8 (308)

![image](https://user-images.githubusercontent.com/10215098/33298895-f39f75e8-d423-11e7-9ea3-6e65eb0026f2.png)

下面是正常情况下和非正常情况下的主线程取样数据的不同。

正常：
![image](https://user-images.githubusercontent.com/10215098/33299914-bb3729d0-d428-11e7-8f53-08c8d09220d0.png)

非正常：
![image](https://user-images.githubusercontent.com/10215098/33299919-c73d9976-d428-11e7-9f60-822be41a270d.png)

最后附上完整的取样文件(非正常)：

[“MWeb”的取样.txt](https://github.com/oulvhai/MWeb-issues/files/1508345/MWeb.txt)

**Comment by oulvhai** [comment]
这个问题收到过几次反馈，然后我测试时没发现，都是删除 MWeb app 然后重新安装解决的。 你可以试试。我也看看能否重现。

**Comment by chenzz** [comment]
我也遇到了同样的bug

系统：10.13.2
MWeb：2.2.8 (308)

**Comment by Lnybb** [comment]
遇到同样的问题

系统：10.13.2
MWeb：2.2.8

**Comment by oulvhai** [comment]
看看谁能提供重现办法。
MWeb 2.x 也修，如果可能修的话。

**Comment by hstdt** [comment]
@oulvhai 已经把2卸载掉了。现在3上面这个问题解决掉了。

**Comment by oulvhai** [comment]
先关好了。
