### ISSUE TITLE
[建议]    支持图床功能

### ISSUE THREAD

**Issue by a1ickgu0** [oulvhai/MWeb-issues#79]
有些文章是要发布到  Web 上，但不是当前 MWeb 所支持的服务，此时文章中所有图片只能单独上传图床后更新图片链接，之后才能发布。

因此建议支持图片上传图床（比如`七牛`,`贴图库`啥的）功能，基于文章设置。

**Comment by oulvhai** [comment]
1.9 版有图床功能，支持google photos, imgur, 自定义三种。

暂时不支持七牛 ---> 其实内置的自定义方式是支持的（有测试过），但是七牛的 token 会在 12 小时内过期，然后又要重新生成，然后生成的算法好像只有 php 版本，objc 版本直接建议说从服务器生成 token。。怎么会有这么难用的 API。。 然后我刚刚看了贴图库，好像跟七牛一个样。。。

**Comment by a1ickgu0** [comment]
哦，1.9 版本快 Release 了不，期待。

**Comment by oulvhai** [comment]
上周日提交审核了。 运气好的话就下周一，不好就要 明年了。
