### ISSUE TITLE
希望可以增加对 Emoji 的支持。

### ISSUE THREAD

**Issue by liberalisman** [oulvhai/MWeb-issues#794]
作者您好，在写东西时，发现打不出 Emoji 表情，希望可以增加对其的支持

**Comment by oulvhai** [comment]
可以吧，ctrl + cmd + space 后，可以选择 Emoji，然后再点回编辑器即可插入。

**Comment by liberalisman** [comment]
哈哈哈 ，爱你爱你爱你
