### ISSUE TITLE
如何通过Shell命令导入外部markdown文件？

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#797]
## 需求

目前有一个需求，把几百个markdown想导入MWeb，一个个手动复制肯定不行，所以想写个脚本来做。

## 问题

* 现在每个MWeb的文件标题都是MWeb生成的一个数字，所以肯定不能自己随便指定一个。
* Categroy、tag也无法指定。

## 需求

需要一个这样的命令：

mweb-import /path/to/markdown/file category tag-name

来把一个markdown导入到指定 Category、指定Tag

## 其他

请务必支持这个功能~！

**Comment by tianhao** [comment]
你可以写一个脚本:
1.把文件复制过去; 2.重命名成规范的名称; 3.添加记录到db；4.重启MWeb.app

**Comment by chenzz** [comment]
@tianhao 
如何确保文件名不会重复呢？
文件名的生成规则是？
如果文件名有某些命名规则，自己随意命名一个是否会造成后面产生冲突呢？

**Comment by tianhao** [comment]
@chenzz  
时间戳(date +%s精确到秒)+4位数字.md
或
时间戳(其它语言精确到毫秒)+1位数字.md, 
要么直接用这个:
`perl -MTime::HiRes -e 'printf("%.0f.md\n",Time::HiRes::time()*10000)'`

测试：
```
i=0
while [ $i -lt 100 ]
do
  i=$((i+1))
  perl -MTime::HiRes -e 'printf("%.0f.md\n",Time::HiRes::time()*10000)'
done
```

**Comment by chenzz** [comment]
@tianhao 
佩服~！多谢~！

我准备用

```shell
filename="`date +%s`0000"
```
来生成文件名啦。

@oulvhai 
确认下，这样可以么

**Comment by tianhao** [comment]
@chenzz 不要偷懒用0000，1秒钟可以完成很多文重命名，用0000会使在同1秒内重命名的文件都重命名为一个文件名，最后只保留1个文件。
```
mv xxx 1230000.md 
mv yyy 1230000.md #覆盖1230000.md
mv zzz 1230000.md #覆盖1230000.md
```
要不就用高级语言吧，逻辑严谨。

**Comment by chenzz** [comment]
@tianhao 
准备这样搞

```shell
filename=`gdate +%s%N | cut -c1-12`
sleep 1
```

**Comment by linfeng365** [comment]
批量导入功能 +1

**Comment by oulvhai** [comment]
@chenzz @tianhao @linfeng365 

时间戳(date +%s精确到秒)+4位数字.md
或
时间戳(其它语言精确到毫秒)+1位数字.md

把这样的文件名的文件，直接放到 docs 下，然后回到 MWeb，点所有文件，会自动导入数据库，当然 ，是在未分类。

设置分类 和 tag 有点麻烦，如果已有分类和 tag，可以在 cat_article 或 tag_article 表新增一条记录，两表的结构都一样，三个字段： id, rid,aid，其中 id 是自增的，rid 就是 分类或 tag 的 id，aid 就是文档的 id（时间戳(date +%s精确到秒)+4位数字）。如果不是已有 tag，就要新增 tag，并取 id 然后再这样。

另外，关于 分类 的 id 和 tag 的 id，有点不一样，分类的 id 是用 cat 表的 uuid 字段，tag 的 id 是 tag 表的 id 字段。

**Comment by chenzz** [comment]
赞~！

**Comment by chenzz** [comment]
@oulvhai 

问下，cat_article和tag_article 表中的rid啥意思？

**Comment by chenzz** [comment]
@oulvhai 

脚本写完了，为啥分类文章数目不对呢？
![image](https://user-images.githubusercontent.com/5676311/33989689-58da1954-e103-11e7-8413-4c72d7145747.png)


文章数目不是通过统计 cat_article 表里的数目来显示的么……？

**Comment by chenzz** [comment]
感谢各位帮助，脚本已经写完，欢迎使用~
https://github.com/chenzz/mweb-hexo-importer
