### ISSUE TITLE
怎么在finder中打开某个位于Library中的文档？

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#8]
写了一篇文档，想把它上传到github上，但是不知道它的位置在哪里

**Comment by oulvhai** [comment]
可以用导出或外部模式。然后位置你可以右点 标题栏。

![address](https://cloud.githubusercontent.com/assets/2174294/7787267/b9e695f6-0235-11e5-9614-0bd78029e8bd.png)
