### ISSUE TITLE
关于LaTex的一个bug

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#800]
inline latex 
单行显示时有预览
多行显示时**没有预览**

例子：
```latex
$ h_{\theta}(x) = \theta^T x = \theta_0 + \theta_1x $

$ 
h_{\theta}(x) 
= \theta^T x 
= \theta_0 + \theta_1x 
$

```

![image](https://user-images.githubusercontent.com/5676311/33867734-a5d64fb4-df39-11e7-8078-4e64f52b9473.png)

![image](https://user-images.githubusercontent.com/5676311/33867740-ae59fcf8-df39-11e7-94ff-841dfb9d5c7b.png)

第二张图没有预览

**Comment by oulvhai** [comment]
@chenzz 单个 $ 只能在一行的，多行的只能用 $$ 。

**Comment by chenzz** [comment]
其实我想要的是 Diaplayed LaTex 能像 Inline LaTex 一样左对齐~

问题转移到这里了：
https://github.com/oulvhai/MWeb-issues/issues/813
