### ISSUE TITLE
是否考虑扩展Markdown语法

### ISSUE THREAD

**Issue by KrabsWong** [oulvhai/MWeb-issues#802]
`markdown`本身的语法对日常的一些操作已经足够了, 如果扩展下语法, 可能会在一些场景下提供非常大的便利.

比如, `table`里添加`list`的时候, 要混合一些`html`代码进去, 写起来/看起来都有点儿蛋疼.
 [http://pandoc.org/](http://pandoc.org/) 看了下`pandoc`是可以支持到这种 case 的.

不过这些到不是个什么刚需

**Comment by oulvhai** [comment]
@yPangXie 目前 MWeb 的 markdown 解析器是 c 写的，我无力扩展支持，当然可以支持另外的解析器，但是整体搞起来相当麻烦，也不统一。
