### ISSUE TITLE
建议增加同步到自定义的Git仓库

### ISSUE THREAD

**Issue by lvtao-net** [oulvhai/MWeb-issues#803]
做为重度的MWeb用户，平时基本上全是用它了。
希望能有自定义同步到指定仓库的功能，比如我们公司现在有内网的git服务器，平时的文档全是md.
现在我们都是写完了，用shell脚本监控同步。很尴尬。

若能自动提交到git仓库（能带着附件一起更好）, 即甚好.

**Comment by oulvhai** [comment]
Sandbox（上架 Mac App Store 的） 的 app 是无法做这种的，像 MWeb 做处自动发布网站到 git 的功能都是用复制命令行并打开 Terminal ，然后让用户粘贴的办法。
