### ISSUE TITLE
如何设置Site的Preview浏览器？

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#807]
目前Site的Preview浏览器缺省是Safari，如何设置成Chrome？

习惯使用Chrome了。

**Comment by oulvhai** [comment]
试过 chrome，然后不知道怎么了，相同的参数无法打开预览的页。所以就仅 Safari 了。

**Comment by oulvhai** [comment]
我手上的版本 3.1.9 已经修改为使用默认的浏览器打开了。
