### ISSUE TITLE
如何设置一篇文章从属多个分类？

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#808]
网站介绍上说[『一个文档可以设置为属于多个分类』](http://zh.mweb.im/)如何设置呢？

我尝试了拖动一篇文章到另一个分类，结果发现从一个分类变成了另一个分类。

**Comment by oulvhai** [comment]
点击顶部那个条

![image](https://user-images.githubusercontent.com/2174294/34092756-02d2db90-e400-11e7-9bb8-a005adf29b0b.png)
