### ISSUE TITLE
发布到 Wordpress.org 验证失败

### ISSUE THREAD

**Issue by eloxt** [oulvhai/MWeb-issues#810]
这个是自建的 WordPress 站点，点击验证之后出现这个错误弹窗，不知道该怎么解决。

xmlrpc.php访问正常。

![34069262-38343fdc-e288-11e7-9bf2-0d202056a0f9](https://user-images.githubusercontent.com/7691760/41899798-eb1f1d4c-795f-11e8-803e-d263fc3a0df9.png)

**Comment by oulvhai** [comment]
感觉比较可能是网络问题。
或者可以新增一个测试帐号，然后发到 coderforart[at]gmail 给我测试看看？

**Comment by eloxt** [comment]
@oulvhai 已经发送，感谢。

**Comment by oulvhai** [comment]
@vwh 好像还没收到，垃圾箱也没有。

**Comment by oulvhai** [comment]
@vwh 收到了，非常有意思，一样的代码， iOS 可以， mac 就不行。。 感谢反馈这 bug，请先不要删除测试帐号。

**Comment by oulvhai** [comment]
@vwh 这个问题好像暂时无解，我关注中，测试帐号要删除也是可以。感谢了！

**Comment by eloxt** [comment]
今天我又尝试了一次，自己修复了……已经添加成功了。还是感谢作者帮忙调试。

**Comment by daihy8759** [comment]
貌似验证还是有问题，提示协议错误，https才会出现

**Comment by kbrx93** [comment]
验证添加成功，最开始几次也可以正常 post，但是之后就一直「协议错误」了，但实际上是成功了，这样导致没有出现更新选项？博客类型：typecho 1.1 正式版。猜想是不是 1.1 修改了 xmlrpc 返回值，导致 mweb 判断是操作失败了？

**Comment by songhao8080** [comment]
![image](https://user-images.githubusercontent.com/10607039/55369854-da3e1580-552a-11e9-99de-8a168758f695.png)

**Comment by songhao8080** [comment]
禁用了xml-rpc 怎么办啊
