### ISSUE TITLE
在macOS 下的文件命名 能不能以自行命名文件为文件名 crazy???

### ISSUE THREAD

**Issue by CGerAJ** [oulvhai/MWeb-issues#817]
<img width="214" alt="wx20171219-101202 2x" src="https://user-images.githubusercontent.com/20548301/34137289-15b6a5d4-e4a5-11e7-8d3a-4dd40c46c363.png">

 #### 做文件分类文件命名的时候   真的cry & crazy

####可否 文件命名以系统文件命名为准

####可否 支持系统文件夹直接拖拽

####可否把文件命名的权限给用户自身 而不是软件生成一串不认识的文件名 谢谢！

**Comment by oulvhai** [comment]
请用外部模式 （CMD + E） http://zh.mweb.im/mweb-1.4-add-floder-octpress-support.html

**Comment by CGerAJ** [comment]
TKS
