### ISSUE TITLE
能否导出为Hexo格式的文档

### ISSUE THREAD

**Issue by mozhu1024** [oulvhai/MWeb-issues#823]
一直用Hexo作为Blog、也不想换、
然后就是希望能够在MWeb写文档，一键导出文章到Hexo的_post文件夹(如果图片上传到图床的话，导出的时候，自动改变图片的链接)

**Comment by chenzz** [comment]
hexo反人类，不要用hexo了，把hexo导入到MWeb吧 🤣

用我写的脚本：https://github.com/oulvhai/MWeb-issues/issues/809

**Comment by mozhu1024** [comment]
MWeb 的路由。。。。。比较尴尬

**Comment by chenzz** [comment]
MWeb路由……啥意思？

**Comment by mozhu1024** [comment]
@chenzz 生成的页面不能自定义别名,文件名是固定的。。。
数字.html 并没有 just_for_test.html 友好

**Comment by chenzz** [comment]
我记得MWeb是可以指定页面名称的，欢迎fork 我的脚本进行更改~

**Comment by mozhu1024** [comment]
emmmmm, 发现新大陆
