### ISSUE TITLE
超链接渲染bug

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#83]
如果超链接带有2个下划线,那么渲染就会有点问题.

比如这个网址: http://blog.csdn.net/ydc__/article/details/46788939

![image](https://cloud.githubusercontent.com/assets/10215098/11886821/4cb646ac-a569-11e5-9fa4-c21aad30962e.png)

**Comment by KrabsWong** [comment]
两个下划线是加粗强调. 可能没处理..

**Comment by oulvhai** [comment]
非常感谢，这个问题在 1.9 版修正了。1.9 版应该会在这些天上架，因为今天 InReview 了。不过久久没过。。

另外还有一个写法可以暂时避免：`<http://blog.csdn.net/ydc__/article/details/46788939>` 这样写。

**Comment by KrabsWong** [comment]
或者转义下:
- `[http://blog.csdn.net/ydc__/article/details/46788939](http://blog.csdn.net/ydc\_\_/article/details/46788939)`
- `[http://blog.csdn.net/ydc\_\_/article/details/46788939](http://blog.csdn.net/ydc__/article/details/46788939)`

**Comment by oulvhai** [comment]
@yPangXie 感谢帮回！对对，转义也是可以，虽然麻烦了点。

**Comment by hstdt** [comment]
@yPangXie   @oulvhai  谢谢2位的回复,解决了就好~

今天InReview真幸福,我9号提交的iOS审核,到现在还是待审核状态 TAT

**Comment by oulvhai** [comment]
@hstdt  MWeb 今天过了 :D 。
