### ISSUE TITLE
七牛云图床上传时图片前缀功能无效

### ISSUE THREAD

**Issue by HyperGroups** [oulvhai/MWeb-issues#839]
七牛云图床上传时图片前缀功能无效
图片总是传到根目录

**Comment by HyperGroups** [comment]
我就是因为这个图床功能才付费的，不想因为一个小功能被坑爹了。。。

**Comment by ghost** [comment]
+1 在验证的时候七牛图床的图片前缀不太好使~

**Comment by oulvhai** [comment]
主要是七牛的文档坑爹，没说到这部分，现在才发现他是直接把 /path/ 这个 / 当文件名了 😂
