### ISSUE TITLE
代码高亮和有序列表的问题

### ISSUE THREAD

**Issue by chroming** [oulvhai/MWeb-issues#84]
代码在整体有缩进的情况下编辑界面无法高亮语法；
有序列表在某项中如果有非缩进行，下面即使按接着上面的顺序手动输入序号在预览中也会显示为从序号1开始

**Comment by oulvhai** [comment]
😂 抱歉，真看不大懂问题是啥？ 可否直接来张截图？ 感谢！

**Comment by chroming** [comment]
代码高亮的问题是指:
![qq20151220-0](https://cloud.githubusercontent.com/assets/9926275/11917121/c826b89a-a734-11e5-90f3-032db06303f2.png)

下面的代码只是上面代码整体加上了缩进,但这样就没有语法高亮了.不过我刚刚发现缩进情况下代码似乎不需要加```js这种结构?是不是我的用法不对.

有序列表的问题是指编辑界面如下,其中序号`2.`是我手动输入的,因为`1.`下面需要加上一些东西不能使用自动生成的序号`2.`:
![qq20151220-1](https://cloud.githubusercontent.com/assets/9926275/11917124/dc95b5c4-a734-11e5-9188-b9f1510c2146.png)
但在预览界面显示成这样:
![qq20151220-0](https://cloud.githubusercontent.com/assets/9926275/11917127/3f827348-a735-11e5-9987-e500bc209026.png)
也就是把我手动输入的`2.`转换成`1.`了

**Comment by oulvhai** [comment]
1. Markdown 的语法规定如果用缩进方式就不用加 ``` 了，会把缩进后的都变为代码
2. 你这样写是会变成两个 ol 的，试试下面的方法：

```
1. 测试测试

    测试测试测试

2. 测试测试
3. 测试测试

```

**Comment by chroming** [comment]
谢谢: )
