### ISSUE TITLE
Mweb下划线不生效

### ISSUE THREAD

**Issue by Chandler-Lu** [oulvhai/MWeb-issues#840]
Mweb：App Store，Version 2.2.8 (308)
以下截图分别为：
1. 写作界面
2. 预览界面
3. 导出成docx
![screen shot 2018-01-09 at 09 49 09](https://user-images.githubusercontent.com/18322610/34701332-9f9fbe60-f522-11e7-8395-798722e722c5.jpg)
![screen shot 2018-01-09 at 09 49 16](https://user-images.githubusercontent.com/18322610/34701333-9fd0e0b2-f522-11e7-8388-6f7e3321960d.jpg)
![screen shot 2018-01-09 at 09 49 42](https://user-images.githubusercontent.com/18322610/34701334-a002c212-f522-11e7-90c3-f1148959af12.jpg)

**Comment by oulvhai** [comment]
MWeb 3.x 修正了这个解析错误。
2.x 不打算更换为 3.x 的解析库。主要是保留 2.x 的用户的使用习惯，因为改动还蛮多的。
