### ISSUE TITLE
[Feature Request] details 和 summary 标签支持

### ISSUE THREAD

**Issue by menduo** [oulvhai/MWeb-issues#843]
Hi：

我知道 gfm markdown 是支持这两种标签的。这两个标签对于写文档来说特别好，文档比较长时，可以用来折叠，而且折叠里边的内容还可以用 markdown 语法，很棒。希望：

1、工具栏以及快捷键增加这两个标签的支持；
2、支持批量展开、收起各个 details（如果在预览和编辑页面都能这样操作就太好了）。

谢谢。

PS：贴一个演示，我觉得挺好呢。

# 摘要与详情 details&summary
- a
- b 

    <details><summary>摘要与详情，这里是摘要</summary>

    这里是详情啊详情。

    ## nihao
    ```python
    def miao():
        return 555
    ```
    </details>

- c

**Comment by oulvhai** [comment]
这个有意思了。
