### ISSUE TITLE
弱弱地问一下作者最近动态。建议开发新版，提高价格加钱。

### ISSUE THREAD

**Issue by menduo** [oulvhai/MWeb-issues#845]
计划什么时候发下一版？very high 和 high 标签的怎样了？

很关注。

另外，可以考虑发个全新版，提高一下价格。（主要是想让作者投入更多的精力……）

谢谢。

**Comment by linfeng365** [comment]
支持再发新版,收点钱。持续开发。

**Comment by ltmsyvag** [comment]
开发新版收钱 +1

**Comment by yuanyuanyuan** [comment]
作者最近好像没有动静了。。。会不会跳坑了。。。。

**Comment by oulvhai** [comment]
to all:

最近在专心做 v3，希望能快点出来。另外 windows 版今年也有计划。

**Comment by yuanyuanyuan** [comment]
作者终于回复了。。。。还以为真弃坑了~很好很好，我对作者这个作品也是很满意的

**Comment by yuanyuanyuan** [comment]
不过 windows 感觉付费的用户没有 mac 的高吧，毕竟 win 的用惯了破解~

**Comment by oulvhai** [comment]
@yuanyuanyuan Windows 版想了很久还是决定做。作者三年多无所事事，感觉只留下了 MWeb，其它一无所成，想来想去只能在做软件的路上入深坑了。。

**Comment by yuanyuanyuan** [comment]
@oulvhai 只是觉得，版本太多，维护不过来，并且如果热卖的版本满足不了那些顾客的话，到头来可能竹篮打水一场空呢，其实我们都明白，肯定越多越好，但是不能忘了大跃进啊，我觉得张小龙的微信十年磨一剑，确实真的好，不过如果是经济收入问题，可以改为订阅版，其实无他，只是一枚想这个软件越来越好的热衷粉的心声而已。。。。

**Comment by yuanyuanyuan** [comment]
@oulvhai 如果人手充足，资金雄厚，人才济济的话。。。。当我放了个屁吧~哈哈哈

**Comment by yuanyuanyuan** [comment]
作为一枚用过有道云，evernote，onenote，slysess，markediter，quiver ，bear的用户来说。。。最后就只剩下 mweb 了，当然还存在改进空间，也有一些小问题，但真心希望这个软件可以一直用到最后~~

**Comment by oulvhai** [comment]
@yuanyuanyuan 主要考虑有：
1. 既然入深坑，总要考虑发展。
2. 目前的版本维护和更新时间上有富余，发展好了，有资金自然什么都好说，发展不好也自信 hold 得住。
3. 计划做 Windows 版本，其实是经过一段时间研究的，包括技术选择和可行性，目前已经确定用 WPF, C#, C 来写。另外我入行一开始就是学 C# 入门的，虽然久不写，还算有点基础。

用户反馈和建议也是我非常主要的动力来源，今年会努力让 MWeb 更好来回馈使用 MWeb 的朋友！！
感谢了！

**Comment by yuanyuanyuan** [comment]
1. 热烈祝贺大佬开坑成功~~个人写 php js 来回切换经常懵逼。。。。。
2. 建议参考改为订阅版，前提是不订阅可以继续使用，订阅可以更新版本，并且订阅之后，软件的 bug 和功能迭代可以做到较为频繁的更新
3. 以上，敬礼。

**Comment by menduo** [comment]
@oulvhai 谢谢您的回复。另外个人建议多关注一下 issue 动态，回复也好，做标签也好。会让用户感受到你在持续关注跟进。

**Comment by ltmsyvag** [comment]
@yuanyuanyuan 你可以试试 boostnote

**Comment by yuanyuanyuan** [comment]
@ltmsyvag 试了一下，屌炸飞哦，居然还可以用 iframe，字体渲染好漂亮，snap 的多文件也是赞赞的，不过预览没跟随滚动，导出有点弱， @oulvhai 觉得大佬可以改改样式~

**Comment by fmewtwo** [comment]
这几天我更新了sublime着实让我眼前一亮，非常赞的UI， mweb是时候来个3.0版本了，一定也要让我们眼前一亮啊

**Comment by Chandler-Lu** [comment]
@oulvhai 那我也给dalao提个建议，希望新版本的界面能够统一一下。现在更改编辑界面的主题后，左侧边栏的主题不发生变化，看起来就像界限分明的3块，感觉有些难受。如果融合度更高一点就好啦，一如即往的支持～

**Comment by A6669** [comment]
@oulvhai  v2用户升级到v3要收费吗？

**Comment by chenzz** [comment]
不行的话建议多招点人吧，mac客户端好久不更新了。。。

**Comment by hedame** [comment]
+1

**Comment by randomatom** [comment]
@oulvhai  我倒不建议 近期支持windows平台。
* 启动win大版本，平台差异太多，能复用的代码估计不多，这样导致需用的资源很多。对个人开发者，同时维护3个不同平台版本，不一定能承受。
* 从目标用户来看，用mac平台的，很可能也用IPhone。但用windows可能就不多了。
* 短期来看，widows平台无法收费，也很难得到收入支持后续开发；
*  同时支持mac 以及 IOS 端类似软件，基本上是免费订阅的同类软件中做的最好的。但是竞争者软件也蛮多的，也很快会更上。现有平台的功能目前做的不错，但是也说不上最好，不继续优化，可能导致用户流失。


建议近期还是集中精力，将现有完善、优化现有平台的功能，做一个**小而美**的软件^_^
比如新版本，可以考虑美化一下UI。这个可能容易被个人开发者所忽略。
软件功能基本有了，这时候优化UI的性价比可能会更高。很多人，其实是看脸的。
祝MWeb越走越远~

**Comment by chenzz** [comment]
@randomatom @oulvhai 

+1 在开发windows之前，先把macOS 版的bug 先修下把 🤣
现在macOS 类似软件这么多，别windows版开发出来，mac版用户都走了

祝MWeb越来越好~

**Comment by oulvhai** [comment]
to all:

最近 MWeb 推进得比较慢，各种原因了，虽然这样，但是按计划来说，六月份应该是能发布的。这次更新其实是重开项目重写了，去掉 Maverick 的兼容，对 macOS 的最低版本提高到 EL Capitan，以解决 High Sierra 下的一些我都无法重现的问题。

issues 也很久没回复了，其实我都不敢看。。先上两张截图，证明 MWeb 还活着。

## 文档库模式截图
<img width="1051" alt="2018-05-15 6 40 04" src="https://user-images.githubusercontent.com/2174294/40052535-b35a16ec-5870-11e8-8190-ee000a25e7b6.png">

##  外部模式截图

<img width="976" alt="2018-05-15 6 40 53" src="https://user-images.githubusercontent.com/2174294/40052546-bf120436-5870-11e8-890c-f551aa578c19.png">

可以看到外部模式变成文件树的方式了。

@yuanyuanyuan
MWeb 订阅模式这个版本的更新确定不会做了，我更希望 MWeb 变成稳定不用怎么更新的模式。

@menduo 很多不回复主要是我本身是个偏犹豫不决的人，对于建议会考虑很多，这样会严重影响进度。不知道你们有没有由于自己某功能或者代码写得不好，以至于迟迟不动手的情况。

@Chandler-Lu 新版本有这个功能。

@HongTao628 要收费了，不然 MWeb 应该难以发展了。

@randomatom @chenzz 
的确是这样，所以 Win 版只是计划，实际还要看看。

感谢关注及回复的朋友！！

**Comment by menduo** [comment]
@oulvhai 感谢冒泡。

理解你的犹豫。不过你的代码只有自己能看到，所以别纠结这点。

功能上，我觉得应该列个大清单，把重要的排出来，再把重要项的依赖项排出来，然后再整理整理，可以做一个里程碑。

小步迭代，给自己信心，也给用户信心。

如果能把其中一些工作用合适的方式交给用户来贡献，也是不错的。不过似乎没发现有哪些可以这样。
