### ISSUE TITLE
[操作增强] `⌘+L` 跳转行。类似 "TextMate" 或 "TextEdit" 。

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#846]
类似 "TextMate" 或 "TextEdit" 。 
通过快捷键 `⌘+L`,
输入行数,
跳转到某行。

sublime text,
快捷键是 'ctr + g' 

可以默认不显示行号,
在按下快捷键后, 显示行号。
并出现输入框。

![screen shot 2018-07-05 at 13 26 17](https://user-images.githubusercontent.com/8175652/42304107-31bc6fae-8057-11e8-80d1-eedc0fb166d9.jpg)

**Comment by oulvhai** [comment]
规划在 MWeb 3.x
