### ISSUE TITLE
upyun 的图片处理代码无效

### ISSUE THREAD

**Issue by conversun** [oulvhai/MWeb-issues#847]
填写参数后没有产生效果, 抓包发现 policy 中没有加入图片处理参数 , 应该是没有把参数加进去

建议使用这个字段 x-gmkerl-thumb 同步处理参数
 [http://docs.upyun.com/cloud/image/#_5](http://docs.upyun.com/cloud/image/#_5)

**Comment by oulvhai** [comment]
截图看看你填写的情况，或者是有什么没加上的？
MWeb 的图床是直接拼成一个 网址的。
前缀（域名） + 文件名 + 处理代码 。
