### ISSUE TITLE
[Feature Request] Formatting options for the note list

### ISSUE THREAD

**Issue by afeblot** [oulvhai/MWeb-issues#849]
I'd be very happy to be able to display the note list as it is shown by default in the mobile app, one line with the note title and date (to get a more compact view allowing to display more notes).

Some settings in the Desktop app would be welcome to allow some customization:

* How many lines of note body [0-5]
* date: displayed or not
* date: displayed on title line or on its own line
* ....  you get the idea :-)

**Comment by oulvhai** [comment]
try menu:

![image](https://user-images.githubusercontent.com/2174294/42411965-67f02c82-8237-11e8-8cb4-526719425365.png)

**Comment by afeblot** [comment]
Sure.
But It would be so much better if you could display the title AND the date on a single line :-)

**Comment by oulvhai** [comment]
try two line

**Comment by afeblot** [comment]
I did. But that takes 2 lines :-D

**Comment by oulvhai** [comment]
:D we plan change iOS UI, may not for one line and date.
