### ISSUE TITLE
转化成pdf后的问题

### ISSUE THREAD

**Issue by fantianwen** [oulvhai/MWeb-issues#85]
1、[toc]生成的目录希望能够跳转；
2、绘制的表格如果太长，会在markdown预览中生成滚动条，但是转成pdf后不能滚动

**Comment by oulvhai** [comment]
1. 付费版应该是会跳转了吧，免费版不支持的。
2. 这个暂时无解。

**Comment by KrabsWong** [comment]
个人感觉, 表格太长的时候, 不如直接保持原样 →_→
OS X上滚动条默认不显示, 查看表格的时候, 可能会漏掉一些列

**Comment by fantianwen** [comment]
@oulvhai 
好吧，感觉应该上付费版的了。。。谢谢解答。O(∩_∩)O
