### ISSUE TITLE
建议MWeb支持“粘贴”添加附件

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#851]
现在MWeb无法通过粘贴添加附件，cmd+c 然后 cmd+v得到以下结果

![image](https://user-images.githubusercontent.com/5676311/35468348-e0071df8-0356-11e8-98b3-41a307c6335c.png)

建议能达到和拖动添加附件一样的效果

![image](https://user-images.githubusercontent.com/5676311/35468350-e72191c2-0356-11e8-8e9d-f06cc680a473.png)

P.S. MWeb做的好棒啊，有没有个什么众筹什么的，看作者更新有点慢啊

**Comment by CloudPai** [comment]
+10086，我也想建议这个功能呢哈，希望作者增加这一功能！ios+mac都买了

**Comment by CloudPai** [comment]
对了，图片貌似支持网页版的复制粘贴到mweb，但是本地图片不能进行复制粘贴到mweb。求完善

**Comment by chenzz** [comment]
好棒，看到问题已经修复了。
![image](https://user-images.githubusercontent.com/5676311/37107400-341bac4c-226f-11e8-8187-5d5fc76b009c.png)
