### ISSUE TITLE
MWEB 开启卡死并使CPU飙升（有遇到的可否进来反馈一下）

### ISSUE THREAD

**Issue by lonely7yk** [oulvhai/MWeb-issues#852]
最近使用的时候开启MWEB时，MWEB卡死，几乎不能操作，CPU占到100%左右，重装软解仍然不行，亟待解决。

**Comment by minbaby** [comment]
同样的问题。不过似乎用外部库好像不是。不知道啥情况

**Comment by lonely7yk** [comment]
我的外部库也是这样，现在靠 MWEB Lite 度日

**Comment by oulvhai** [comment]
这种情况好像无法重现，有几个用户反馈这样，但是我都无法重现。目前也找不到什么有效果的线索。

**Comment by randomatom** [comment]
这可以考虑类似「看门狗」的方式调试定位。

1. 多起一个检测线程；
2. 在其他可能导致卡死模块里，进入前  向检测线程 checkin 一下，退出后 checkout。
3. 如果发现长时间没有 checkout，说明 该模块 卡死。

**Comment by oulvhai** [comment]
@randomatom  
你这个好高级，我研究一下。 其实我的原则上是不会为少数用户而整个引入检测代码的，我是觉得更多功能更多更多 bug 的理解。所以很多情况都要手工排查。要加也只会是测试版本。
目前连统计代码都不加，就是为了保持程序干净。

**Comment by dbgoa** [comment]
遇到同样的问题，打开就卡死，求助。。。

**Comment by oulvhai** [comment]
@dbgoa 有什么怀疑的可能信息可以分享吗？

**Comment by oulvhai** [comment]
先关好了。
