### ISSUE TITLE
无法生成静态网页

### ISSUE THREAD

**Issue by vcve** [oulvhai/MWeb-issues#857]
![2018-02-01 8 11 21](https://user-images.githubusercontent.com/19594552/35677845-2a6843de-078c-11e8-9238-9f61f9fd4b16.png)
如图，看不到目录也找不到主题，按了生成网页也没有反应。咋回事哦？

**Comment by Chandler-Lu** [comment]
连模板都不选拿什么生成网页？？？

**Comment by vcve** [comment]
模板那里没东西哦！

**Comment by vcve** [comment]
谢谢上面那个小朋友哦，我在模板文件夹下载了个模板就行了！
