### ISSUE TITLE
MWeb内笔记丢失

### ISSUE THREAD

**Issue by alex-liuziming** [oulvhai/MWeb-issues#859]
您好，在2月3号的时候发现2月1号之前的笔记丢失，还有一份2月2号晚上的笔记也丢失了，笔记缩略图为空白，打不开，导出为pdf也是空白的，之前没有遇到这种情况。
<img width="1440" alt="mweb" src="https://user-images.githubusercontent.com/20107871/35803672-9fd8dae0-0aaf-11e8-8c56-295ea97d6c15.png">

**Comment by nsdont** [comment]
我也遇到了

**Comment by nsdont** [comment]
@AlexanderLiuzm 是不是将文件存放在 iCloud 中，他会把一些文件保留在云端，本地只有一个快捷方式，在 mweb 里面就是只有文件名，没有内容了，我这边是这种情况

**Comment by oulvhai** [comment]
未清楚这种情况是怎么发生的。。 帮助里更新了一笔记文档库安全的说明： https://zh.mweb.im/15303755379614.html ，感兴趣可以看看。

**Comment by congdepeng** [comment]
我丢失了3次了，就是只有标题，没有内容了，点击标题显示Untitled！！！
绝对是一个大Bug，反馈给Mweb开发者但是他找不出原因！！！！！！！！

在2.0版本的时候就遇到了，后来换用其他编辑器。
然后3.0版本出来忍不住又购买了，以为没问题了。
刚刚！！！就是刚刚！！！笔记内容全丢失了！！！！

**Comment by congdepeng** [comment]
我丢失了3次了，就是只有标题，没有内容了，点击标题显示Untitled，绝对是一个大Bug，反馈给Mweb开发者但是他找不出原因！！！！！！！！！！！！！！！！！！！！！

**Comment by congdepeng** [comment]
我丢失了3次了，就是只有标题，没有内容了，点击标题显示Untitled，绝对是一个大Bug，反馈给Mweb开发者但是他找不出原因！！！！！！！！！！！！！！！！！！！！！

**Comment by woshiyexinjie** [comment]
我也是，很奇怪
