### ISSUE TITLE
1.未使用素材的清理 2.图片粘贴隐患

### ISSUE THREAD

**Issue by hstdt** [oulvhai/MWeb-issues#86]
文件A粘贴进去一张图片,但是最终没有使用这个图片,但是文件A的media文件夹里好像还存在这张图片,那么就会造成资源浪费.可以手动清理么

还有一种情况,从文件A粘贴图片路径到文件B,然后当文件A被删除了之后,文件B中的图片还能显示么?如果不能,建议粘贴图片的时候,用复制而不是引用.

另:标记中有无序列表功能,为什么没有有序列表功能呢.

**Comment by oulvhai** [comment]
1. 外部模式要手动清理用 Finder 即可， 文档库可以点右上角的 扳手按钮（CMD + 7)  再点 Media tab， 就会看到所有插入过的图片了，可以在这里清理。  
2. 文件 A 删除了，文件B 如果有引入到文件A的图片，就不能显示了。这个应该一看就明白，因为引用的都是文件路径。如果要在文件B重新加一份重复的图片，可以在文件B再把图片拖进去一次的。 
3. 这个的确漏了，感谢指正！

**Comment by hstdt** [comment]
@oulvhai 

前2点我都没说清楚.语死早..
1.我的意思是能不能有一个一键清除所有未使用素材的功能,避免占用空间的浪费(目前用的iCloud备份,得精打细算..)有时候放了个比较大的附件,结果最终未使用,积少成多会造成臃肿吧.
(或者将未使用的文件在"图片&文件"这里标示出来,这个应该好判断点,搜索文本中有没有出现这个文件名)

2.能否进行一次判定.如果复制了一张图片,但是路径是另一个media文件夹,那么就将这张图片复制到本md文件对应的media文件夹中,更换成新的图片路径,从而避免删除了前一个MD文件可能造成的图片无法显示的问题.(同时也可以给用户一个提示或选择?)

这2个问题应该都算是一个素材的问题吧,当然,都属于用户自己可控的问题,就是想着有点提心吊胆,就怕以后看自己写的文件,结果发现图片/附件找不到了或者堆积如山.

**Comment by oulvhai** [comment]
1. 使用 “图片&文件” 这里标出来倒是可以考虑。
2. 这个其实是这样的： 假如只是想引用，那么就复制文本就可以了，假如想重新复制一份到当前文档，可以用右键原图，然后 Copy Image，或者 再原图再拖入一次到 当前文档。 如果全部统一复制一份新的，这样就不能很好使用引用的功能了。

真实使用不会堆积如山的。毕竟自己写的文档，什么图用到了，什么用不到，基本都会明白的。

**Comment by hstdt** [comment]
@oulvhai 
能否在文档中的的图片右键中加入"彻底删除此图片"的功能,目前的删除只是删除了引用,一旦图片多了,彻底删除就很难做到了(要从那么多张图片缩略图中找到那一张.)

**Comment by oulvhai** [comment]
@hstdt 很有用的建议，应该会加上。
