### ISSUE TITLE
【功能建议】在新标签页打开新笔记的快捷键或者配置项

### ISSUE THREAD

**Issue by plus2047** [oulvhai/MWeb-issues#863]
目前在标签页打开新笔记需要右键选择。为知笔记提供有一个配置项，能够选择默认在新标签页打开笔记，能否也提供这样一个配置项呢？或者快捷键也可以，如 Command + 鼠标点击笔记则在新标签页打开。

**Comment by oulvhai** [comment]
目前是双击可以新标签打开。
