### ISSUE TITLE
Preview CSS issues

### ISSUE THREAD

**Issue by davestewart** [oulvhai/MWeb-issues#866]
Hi there,

Firstly, THANK YOU for an awesome editor!

I have happily paid my money; you're doing a damn fine job, Sir.

So, on to the issues:

### 1. The Edit button next to the preview theme seems to go to the wrong folder

The folder that opens is: 
```
/Users/Dave/Library/Containers/com.coderforart.MWeb/Data/Documents/themes/PreviewCSS/
```

The folder that seems to have the themes in, and update when I save are:

```
/Applications/MWeb.app/Contents/Resources/PreviewAsset/previewCSS
```

### 2. The CSS file seems to be protected

I have to edit the above CSS files using `sudo`

I guess if they were in the correct place, I wouldn't need to?

### 3. I can't seem to make the CSS reload when I edit it then click reload from the prefs panel

I guess this is also because the files are in the wrong place?

But what would be super cool would be if the files were watched, then the UI would update as I typed - just like the markdown I'm editing.

Hopefully you can fix this / tell me if my install is not working properly.

Thanks,
Dave

PS. More people need to know about this awesome editor

**Comment by oulvhai** [comment]
Added debug mode in MWeb 3.x
![image](https://user-images.githubusercontent.com/2174294/42411745-f950f264-8233-11e8-93f5-efea55524b1d.png)
