### ISSUE TITLE
Mathjax `\cancel` 命令在 iOS 上颜色错误

### ISSUE THREAD

**Issue by ltmsyvag** [oulvhai/MWeb-issues#872]
此错误只出现于深色背景的 preview theme，比如 mweb-Tomorrow

在 macOS 版中，叉除符号可以正确显示：
![screen shot 2018-03-03 at 17 44 09](https://user-images.githubusercontent.com/29622362/36932897-5d7131a0-1f0b-11e8-8169-59945b67d85c.png)

但在 iOS 版中，变为（不正确的）黑色：
![img_0385](https://user-images.githubusercontent.com/29622362/36932922-cc652b8e-1f0b-11e8-932f-8ed5c35c41c7.jpg)

**Comment by oulvhai** [comment]
mathjax bug ?
