### ISSUE TITLE
bug反馈：复制的网页图片在附件列表中不显示

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#873]
#### bug重现步骤：

1. 打开https://www.cnblogs.com/yufeng218/p/6623329.html
2. 复制页面内容
3. 打开MWeb，然后 Edit->Paste Markdown From HTML
4. 查看附件列表，发现没有图片，然而图片确实是已经复制到本地了。如图所示，

![image](https://user-images.githubusercontent.com/5676311/36971404-ae69a532-20a6-11e8-9cd5-a55e74479e8a.png)

#### bug导致的问题：

某个图片已经没有了，对应的 mardown 已经删除了，但是还是存在硬盘上，占据空间。

**Comment by oulvhai** [comment]
我在用的 3.1.9 版本已修正。
