### ISSUE TITLE
[Feature Request] Make external project files, opening as a separate window, optional  

### ISSUE THREAD

**Issue by davestewart** [oulvhai/MWeb-issues#874]
As primarily a documentor, I almost never use the built in Library.

As such, each time I open MWeb, I have to find and close the Library window. It's not the end of the world, but is kind of irritating, and out of step with all other software I own.

I'd like to suggest making the dual-window approach optional, via a General preference:

```
[x] Open external projects in a separate window
```

This could be the default if that is what people are used to :)

If unchecked, only one window would open at startup, and both project trees would display on the left:

```
LIBRARY
    All
    Recent
    Uncategorized
    Trash
    MWeb
EXTERNAL
    Recent
  + Project 1
  + Project 2
  - Project 3
      Folder 1
    + Folder 2
```

Thanks for your consideration.

**Comment by oulvhai** [comment]
Hi, you can enable this option:

![image](https://user-images.githubusercontent.com/2174294/42411469-de4f9380-822e-11e8-8ce7-64c6feb11255.png)

**Comment by davestewart** [comment]
Hi,

Not sure you if you got the point of my issue, but I don't want to open two windows.

Plus, splitting library and external as windows seems really weird from a UX perspective
