### ISSUE TITLE
标签过多导致最下一行标签被挡住一般

### ISSUE THREAD

**Issue by EINDEX** [oulvhai/MWeb-issues#875]
![image](https://user-images.githubusercontent.com/13883964/37084356-3bd5abb4-222d-11e8-8ff4-a5e2c42650ed.png)

**Comment by carsonwah** [comment]
同樣情況
v2.2.9

![2018-03-23 02 30 35](https://user-images.githubusercontent.com/25053707/37790706-41fbfe82-2e42-11e8-9ec5-dbc08fce6815.png)

可以滾動，但是是整個container滾動，所以看不到的依然看不到

**Comment by oulvhai** [comment]
在 3.1.9 版本将修正。
