### ISSUE TITLE
保存笔记的时候报错

### ISSUE THREAD

**Issue by carryxyh** [oulvhai/MWeb-issues#877]
报错内容如下
Error Domain=com.evernote.sdk Code=11 "Content of submitted note was malformed" UserInfo={NSLocalizedDescription=Content of submitted note was malformed, parameter=Element type "boolean" must be declared.}

**Comment by oulvhai** [comment]
文档中的 `<boolean` 改成 `&lt;boolean` 或  \`<boolean\` 用代码包起来。
