### ISSUE TITLE
Command+R进入预览视图无法使用PageUp&Down键滚动

### ISSUE THREAD

**Issue by LudwigWS** [oulvhai/MWeb-issues#878]
在有滚动条的窗体下，全键盘的PageUp & PageDown键可以方便地翻页。在MWeb中的编辑模式下可以正常使用，但是一旦Command+R键进入预览模式阅读，上述键就无法翻页，必须得单击编辑界面才可以正常使用，这样的体验很不流畅。似乎Command+R进入预览视图的时候滚动条不是激活的状态，所以无法使用这两个键。如果可以，请修复这个小问题，谢谢！MWeb非常好用！

**Comment by oulvhai** [comment]
点一下预览页就会切换焦点到预览页了，这时可以用 pageup Y pagedown
