### ISSUE TITLE
發佈到Medium Request failed: bad request (400)

### ISSUE THREAD

**Issue by jason820** [oulvhai/MWeb-issues#88]
嘗試了幾篇不同的內容都是出現如下畫面
![Imgur](http://i.imgur.com/xyNEDmR.png)

**Comment by oulvhai** [comment]
这个 Bug 已确认，目前还不知道是否是 Medium 不让我发布了。发邮件给他们，还没回。

**Comment by oulvhai** [comment]
MWeb 无法发布到 Medium 是中文版不小心引入的 Bug，英文版无影响。中文版状态选：Unlisted 也可以发布。 下版将修正。

**Comment by KrabsWong** [comment]
以Unlisted状态发布之后, 是不是Medium会对发布的内容做什么处理??

MWeb里的编辑截图和最终发布到Medium的效果图如下.

![markdown](https://cloud.githubusercontent.com/assets/12368943/11990043/e08f78e8-aa42-11e5-803b-ee6c39300d44.png)
<img width="607" alt="medium" src="https://cloud.githubusercontent.com/assets/12368943/11990048/eea9ccc6-aa42-11e5-88ce-7005619bfb02.png">

**Comment by oulvhai** [comment]
Unlisted 这个我倒不是很清楚，这个是他 API 里有这个选项。
然后发布后 Medium 的确会自己再处理过一次。具体怎么处理主比较复杂了。反正跟发布前的 HTML 不一样。

**Comment by ghost** [comment]
[官方对于 Unlisted posts 的说明](https://help.medium.com/hc/en-us/articles/215552778-Unlisted-posts)

## Unlisted posts

To set a post as unlisted while in edit mode:

Click the Publish button in the top-right corner of the page.
Click Scheduling/Audience/License
Click Your audience: All of Medium > Unlisted.
Click Save.
Unlisted stories will not appear in the home feed, profile page, tag page, or search on Medium, nor will they appear in notifications or email digests. 

To share an unlisted story, simply share the URL of the post. Unlisted stories are not password protected.

**Comment by Queequeg92** [comment]
最新的mweb3依然存在类似的问题，网络没问题，但是发布到medium的时候返回bad request 400，希望能修复一下

**Comment by oulvhai** [comment]
@Queequeg92 如何重现？

**Comment by Queequeg92** [comment]
@oulvhai 不知您所指的重现是什么？我首先按照官方教程设置好了medium的token，然后编辑了一个简单的hello world测试文档，试着直接publish到medium上，但是返回error: bad request 400。具体的设置请看下面截图。另外，我的网络环境访问medium没有问题，在mweb 3中设置token也没有问题。
不知道软件是否有日志，如果有的话我可以提供。
![screen shot 2018-07-08 at 17 51 00](https://user-images.githubusercontent.com/8766653/42418679-ee9e9c32-82d7-11e8-96eb-0f3ef2650ade.png)
![screen shot 2018-07-08 at 17 46 36](https://user-images.githubusercontent.com/8766653/42418686-fdd959e4-82d7-11e8-9953-cfd99497316e.png)

**Comment by oulvhai** [comment]
token 可以提供吗？ 你可以新增一个，然后我测试后你再删除。我会发到  Draft。 如果可以，请邮件联系我： coderforart@gmail.com

**Comment by Queequeg92** [comment]
可以，已发送到邮箱，谢谢 @oulvhai

**Comment by ileadall42** [comment]
@yPangXie 你的这个发布到medium 支持markdown语法的吗？

**Comment by tine8899** [comment]
我也遇到了，是因为中文问题吗？英文貌似没问题
