### ISSUE TITLE
点击上传本地图片无响应

### ISSUE THREAD

**Issue by lcjingdi** [oulvhai/MWeb-issues#880]
已经授权google photo了 但是点击上传本地图片的时候没有任何反应

**Comment by bigpotato920** [comment]
+1

**Comment by softinio** [comment]
Everything was working fine but recently started having this issue ... think after updates. 

Any ideas when this will be fixed or whats causing issue?

**Comment by oulvhai** [comment]
@lcjingdi @bigpotato920 用法： https://zh.mweb.im/15303740497765.html

@softinio https://www.mweb.im/15306175365886.html
