### ISSUE TITLE
重新安装，点击新增分类、新建文件都无效了

### ISSUE THREAD

**Issue by huigeek** [oulvhai/MWeb-issues#884]
删文件时，不知道怎么的，MWeb 里之前的目录什么的都没了，点击新增分类，新建文件都没有效果。
于是删除软件，重新安装了一次，新装的依然是新增分类、新建文件没有效果

**Comment by huigeek** [comment]
![image](https://user-images.githubusercontent.com/13644163/37695609-8b3c0368-2d0b-11e8-95f7-386aec98ddc5.png)

**Comment by oulvhai** [comment]
解决了？
