### ISSUE TITLE
生成的網站沒有sitemap.xml

### ISSUE THREAD

**Issue by carsonwah** [oulvhai/MWeb-issues#886]
- 我看有關主題的[文檔](http://zh.mweb.im/custom-site-theme-detail-zh.html)是有提及有sitemap.xml。
- 然後看作者自己的blog([coderforart.com](http://coderforart.com/sitemap.xml))也是有sitemap。
- 然後[每個主題](https://github.com/oulvhai/MWeb-Themes)的根目錄也是有sitemap。

但我試過v2.2.9內置的4種主題全部都沒有生成sitemap.xml，請問是bug還是未完成的feature？

**Comment by oulvhai** [comment]
感觉是你的网站分类的文档没有 普通文章，只有 page ，肯定是必生成  sitemap 的。或者使用清除然后重新生成一下。
