### ISSUE TITLE
在“评论”代码中，请问如何获取当前文章的编号？

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#888]
在“评论”代码中，请问如何获取当前文章的编号？

因为需要把文章和对应的评论系统做一个关联，想知道如何获取当前文章的编号？

即在以下红框中如何获取文章编号？
试过了`{{ post.date }}`，不行。

![image](https://user-images.githubusercontent.com/5676311/37893533-e5785c36-310d-11e8-84e7-067c9e98f9bc.png)

**Comment by oulvhai** [comment]
可以使用文章的网址做 ID
