### ISSUE TITLE
建议增加批量导出功能

### ISSUE THREAD

**Issue by leonardluo** [oulvhai/MWeb-issues#89]
我们在使用MWeb编写文档，一个目录下会有比较多的文档，我们希望能增加批量导出的功能把一个文件夹下的所有MD的文档导出到HTML，谢谢！

**Comment by oulvhai** [comment]
目前文档库可以支持把分类下的文档导出为 一个 HTML（右键分类即可）。 外部模式暂时不支持。

**Comment by bestony** [comment]
能否支持 PDF 的批量导出？

@oulvhai

**Comment by oulvhai** [comment]
@bestony 右键文档库分类导出 PDF。不过会整合为一个 PDF。

**Comment by MrLeekon** [comment]
额，可以批量发布到Bloger或Evernote么，就是多个MD一起发，压了很多本地文件没发布(〒︿〒)

**Comment by pinocc** [comment]
+1, mweb 中的文档想批量发布到语雀
