### ISSUE TITLE
关于增加复习功能的建议

### ISSUE THREAD

**Issue by linvis** [oulvhai/MWeb-issues#896]
复习应该是笔记的一个重要功能
但目前各家笔记基本都靠人来安排复习，所以是能考虑添加类似艾斯浩宾曲线，帮助提醒用户复习？

**Comment by Dan-Sylvain** [comment]
个人以为 MWeb更注重于文本输入的流畅性, 是一个文字编辑工具. 辅以Markdown以及Mweb特有的对图片的一些格式上的调整, 重在"导出"和"发布". 并不是作为一个永久收集信息的信息库存在的(Wiki), 所以也可能不会支持复习笔记这样的功能.

**Comment by linvis** [comment]
有道理，这涉及到了开发者对产品定位的问题了。我是看到MWeb侧边栏提供了了分类和搜索的功能，所以把它当做WiKi来用，像日常文本输入，我个人倾向于使用更纯粹，不包含这部分功能的markdown编辑器。

**Comment by oulvhai** [comment]
复习这个的确偏了点 :D
