### ISSUE TITLE
Mac OS 10.13.4 (17E199) MWeb 显示问题

### ISSUE THREAD

**Issue by swlfigo** [oulvhai/MWeb-issues#898]
刚升级到  Mac OS 10.13.4 , 使用MWeb 写MarkDown时候，如果有图床图片，在实时可以观看模式下，一边编辑Markdown，预览界面出现白色闪问题，还有就是左右(编辑区与实时显示界面)位置对不上..

**Comment by oulvhai** [comment]
已知问题
