### ISSUE TITLE
是否要区分Library的概念？

### ISSUE THREAD

**Issue by freewind** [oulvhai/MWeb-issues#9]
mweb里提到了Library的概念，以及external，我觉得挺难理解的，每次都要想想。

我想能否直接让Library对应于磁盘上的目录？这样左侧栏里，每个一级分类，可以对应于磁盘上的某个目录，它们的子分类对应于那个分类下的一个子目录。

这样我就可以方便的对目录进行操作，比如上传到github上。

**Comment by oulvhai** [comment]
你的需求正是外部模式的所有功能。所以：请用外部模式。
![image](https://cloud.githubusercontent.com/assets/2174294/7787284/201906ba-0236-11e5-90ed-9492a18cf6ff.png)
如上图，你可以勾选这个选项，这样的话，除非你明确打开 Library 模式，否则就不会看到了。

Library 模式是提供一个不用想文档存在那里，和文档名称是什么。 也提供一个文档可以选择多个分类来管理。另外还提供把整个分类生成静态网站的功能。

**Comment by freewind** [comment]
原来如此！之前在使用Library模式时感觉不太安心的地方是因为那些文档保存在一个我看不到的地方，没有备份到远程服务器，一旦程序出现问题，可能导致我写的东西找不到了（之前使用别的出现过这个问题），所以想“如果它直接对应一个目录就好了，我可以对它们进行备份”。

目前Library里的文档能否同步到远程服务器？

**Comment by oulvhai** [comment]
http://zh.mweb.im/qa.html 看这里的 QA 说了如何把 Library 备份到 dropbox 或者其他也可以的，只建议备份。

保存地方不可见的好处是你不会破坏到 Library 的结构。
然后按我的使用经验来说，如果云服务不足够贵，并不比自己备份和保存保险，目前就dropbox 看上去是靠谱的。

**Comment by oulvhai** [comment]
然后 你可以看到 MWeb 的文档库的结构，都是用 纯文本的 markdown 文档，这个设计可以做到程序出问题了文档也不会有问题。 然后 文档库的文件夹一般不可见，为 MWeb 私有，也一定程度上避免了误删等问题。

**Comment by freewind** [comment]
我的文本东西一般都是手动commit到github上的，感觉它比较靠谱。看来是可以把`~/Library/Containers/com.coderforart.MWeb/Data/Documents/MWeb/docs`里的东西提交上去
