### ISSUE TITLE
外部模式下导出图片,pdf的问题

### ISSUE THREAD

**Issue by pangwu86** [oulvhai/MWeb-issues#90]
版本: 1.9.1
环境: 在外部文件夹模式下
问题: 
1 .保存为图片, 复制为图片 均无反应
2. 导出pdf, 文档中包含图片的话, pdf中没有, 会变成?小图标

**Comment by oulvhai** [comment]
1. 这个我测试好像没问题，是所有文档都如此还是特殊文档？如果是特殊，可否 mail 给我分析一下？ Help - Send Feedback
2. MWeb 有扩展了一下 markdown 的图片语法，`![w33](pic.jpg)`  这种写法中， w33 表示将图片宽度设置为 33px ， 还有 l33  居左， c33 和 m33 居中， r33 居右，你看看是不是由于这个写法的原因图标会变小？
