### ISSUE TITLE
图表格式混乱

### ISSUE THREAD

**Issue by duckbill** [oulvhai/MWeb-issues#900]
markdown代码如下：
```
| 集群主机 | 名称 | 启动状态（Y/N） | 旧IP地址 | 新IP地址 | 是否变更（Y/N） | 变更状态 | 备注 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 93 | dbhome | N | 空 | 空 | N |  | 模板 |
| 93 | debian | N | 空 | 空 | N |  | 模板 |
| 93 | src | N | 空 | 空 | N |  | 模板 |
| 93 | 192.168.2.100 | Y | 100 | 40 | Y |  |  |
| 96 | rq-192.168.1.111 | Y | 111 | 55 | N |  | 不知道密码暂不可
```
但是mweb导出pdf时候达不到如下效果：

| 集群主机 | 名称 | 启动状态（Y/N） | 旧IP地址 | 新IP地址 | 是否变更（Y/N） | 变更状态 | 备注 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 93 | dbhome | N | 空 | 空 | N |  | 模板 |
| 93 | debian | N | 空 | 空 | N |  | 模板 |
| 93 |src | N | 空 | 空 | N |  | 模板 |
| 93 | 192.168.2.100 | Y | 100 | 40 | Y |  |  |
| 96 | rq-192.168.1.111 | Y | 111 | 55 | N |  | 不知道密码暂不可

**Comment by randomatom** [comment]
你的表格，我这试了一下，没问题啊
