### ISSUE TITLE
无法预览本地图片

### ISSUE THREAD

**Issue by bigpotato920** [oulvhai/MWeb-issues#903]
Mac环境下2.1.7版本，通过语法 ![](filepath/to/pic)无法展示图片，其它markdown编辑器可以显示

**Comment by wosta** [comment]
Mac 版本 2.2.9 (312) 我也遇到了，相对路径下本地图片无法加载，然后使用一次绝对路径后显示出来了

**Comment by oulvhai** [comment]
参考一下是不是这个原因： https://zh.mweb.im/15304187309476.html
