### ISSUE TITLE
所以笔记太长还是要 crash 的啊...

### ISSUE THREAD

**Issue by ltmsyvag** [oulvhai/MWeb-issues#904]
在有很多较复杂的数学公式的情况下（MathJax ），在输入长笔记时 mac app 崩溃了... 其实这也是可以预料到的，因为开着预览输入时，每改一个字符 preview 都要重排，在笔记已经很长的情况下，不断地输入意味着 preview 要不断地重排很多的内容，这样就果然还是容易死掉吧...

建议加入根据键盘输入情况决定是否生成预览的功能，比如只在停止输入一段时间后重新刷新预览，mac 下的 LaTeX 编辑器 Texpad 用的就是这个机制.

**Comment by oulvhai** [comment]
这个目前只能关掉预览。毕竟内容少的用户想即时的。然后大部分情况还是少内容的。
