### ISSUE TITLE
使用搜索功能闪退

### ISSUE THREAD

**Issue by javahuang** [oulvhai/MWeb-issues#905]
mac 系统版本 10.12.6
mweb 版本 2.2.9（312）
在侧边栏搜索，然后点开其中一个文档，**大概率情况出现闪退**

另外，滚动预览页面的时候，编辑页面能不能随着滚动？因为我经常要开预览模式查看笔记，但是当焦点移出 mweb 之后，预览页面又回到编辑的位置，这个很不爽啊。我现在使用的 vscode 的 md 预览都是双向滚动的。

**Comment by kyochou** [comment]
同样的问题, 如果内容多于一屏, 在打开预览界面编辑时预览界面就会闪屏. 这个问题很严重啊. 我以为几天就会修复. 已经影响到基本使用了. 希望作者重视一下. @oulvhai

**Comment by oulvhai** [comment]
3.x 的确有计划优化。2.x 不打算优化这个了。
总的来说，两版现在都无改进。
