### ISSUE TITLE
切换view 特别卡 

### ISSUE THREAD

**Issue by ifsc01** [oulvhai/MWeb-issues#906]
系统
![image](https://user-images.githubusercontent.com/33216463/38655070-0ac0c52a-3e45-11e8-955c-ab271b17f5ff.png)

切换只有editor的时候，明显感觉要很长时间才能反应过来，而且单个editor也很卡
![image](https://user-images.githubusercontent.com/33216463/38655079-17fba9d0-3e45-11e8-8f19-fdadd142f585.png)

**Comment by ifsc01** [comment]
录制了视频

https://www.dropbox.com/s/u2ulznxlhd5qg6c/VID_20180412_113303.mp4?dl=0

**Comment by oulvhai** [comment]
的确好卡。。
