### ISSUE TITLE
配置七牛云存储的时候一直返回 631

### ISSUE THREAD

**Issue by ManaStuDent** [oulvhai/MWeb-issues#913]
我已确认 api 地址，空间名称，AK，SK 均已正确。
华东地区存储空间，选择 http://up.qiniu.com
我的七牛云就一个存储空间，名称很简单，所以我不认为名称会配置错误
AK，SK 均从新生成后粘贴过来的
由于我使用另外一款图床软件可以正常上传图片，所以问一下大家有没有相同的情况。
OS：10.13.4 High Sierra
软件版本：2.2.9

**Comment by oulvhai** [comment]
631  是指定空间不存在，可以在 空间名那里 CMD + A 然后删除，手打填一下。
