### ISSUE TITLE
词数字数统计错误bug

### ISSUE THREAD

**Issue by lonelyandrew** [oulvhai/MWeb-issues#917]
右侧词数字数统计的数字显示不正确.

![2018-04-27 19 48 42](https://user-images.githubusercontent.com/4616534/39360842-648cf718-4a52-11e8-8ef7-12f855f27ac1.png)
![2018-04-27 19 48 47](https://user-images.githubusercontent.com/4616534/39360845-69a16036-4a52-11e8-92bd-e1999cdf8b77.png)

**Comment by oulvhai** [comment]
字数统计算是一个难题了。暂时没有好办法，先关。
