### ISSUE TITLE
必现卡死问题

### ISSUE THREAD

**Issue by wonderffee** [oulvhai/MWeb-issues#919]
新用户，正在用最新的MWeb Mac试用版，发现流程图功能比较好用，但是一不小心发现了一个必现的问题
我是仿照 https://blog.csdn.net/Subson/article/details/78054689 里面的流程图代码在MWeb里敲着测试
在敲下面的代码时:
```mermaid
graph TB
st(开始)-->op[操作]
```
因为中英文输入法切换混乱的问题，在输入其中的>符号时用的是中文环境，导致输出了》，输出了之后整个MWeb就卡死无响应，强行退出重新打开，刚刚输入的内容就全部没了。

我怀疑是js处理出错你这边没有处理异常而导致的
另外就是自动保存的问题，想问一下MWeb自动保存的间隔是多少

**Comment by ltmsyvag** [comment]
不要用试用版了，试用版作者已经很久没维护了

**Comment by oulvhai** [comment]
Lite 版？ 已下架。不过也有上架的计划，未确定。
