### ISSUE TITLE
关于有序列表显示不正确的问题

### ISSUE THREAD

**Issue by ChangLiuXYZ** [oulvhai/MWeb-issues#92]
如果我编辑了一个有序列表：

![image](https://cloud.githubusercontent.com/assets/12593872/11991790/55f7854c-aa59-11e5-814e-d5380df13d06.png)

我在第二行后敲个回车，结果并不是我希望的变成1.2.3.4，反而是下面这样：

![image](https://cloud.githubusercontent.com/assets/12593872/11991822/bbd443fa-aa59-11e5-8a09-2ec38acc94d3.png)

变成了1.2.3.3

**Comment by oulvhai** [comment]
感谢建议！

**Comment by ChangLiuXYZ** [comment]
1.9.3 貌似还存在这个问题？

**Comment by oulvhai** [comment]
嗯。没有 Close 的 都是没修正的。这个其实影响不是很大，所以优先级不高，因为即使都用 1. 解析出来的列表也是正确的。

**Comment by oulvhai** [comment]
最新版本已实现。
