### ISSUE TITLE
编辑器黑色主题的问题

### ISSUE THREAD

**Issue by ChangLiuXYZ** [oulvhai/MWeb-issues#93]
我想调成类似官网这种黑色主题，看上去棒棒哒：

![image](https://cloud.githubusercontent.com/assets/12593872/12006091/ce4a8798-ac01-11e5-8038-4f16bebd2727.png)

然而我在我的设置中找了找，发现了这个：

![image](https://cloud.githubusercontent.com/assets/12593872/12006094/f2948c84-ac01-11e5-9c18-53811d664f89.png)

结果两项都只能设置编辑区的颜色，左边的文件夹区域改不了啊。。。

![image](https://cloud.githubusercontent.com/assets/12593872/12006097/192adb8c-ac02-11e5-98b2-c3c1b7e2d9c1.png)

**Comment by KrabsWong** [comment]
是勾选"视图"里的黑暗模式.
<img width="310" alt="2015-12-26 9 00 10" src="https://cloud.githubusercontent.com/assets/12368943/12006470/ca1fbf1e-ac13-11e5-8ecd-a92888736132.png">

**Comment by oulvhai** [comment]
对， 上面的是设置，View 菜单才是切换。

**Comment by dpc11** [comment]
提一个不知道算不算 Bug 啊，也是和亮、暗模式有关的。就是无论处在什么模式时，在偏好设置下无论更改亮、暗主题设置都会立即发生变化、

**Comment by oulvhai** [comment]
这个是故意如此做的，这样可以即时看到真正效果。
