### ISSUE TITLE
[优化建议] Tab的“确认打开”含义模糊，且无提示

### ISSUE THREAD

**Issue by randomatom** [oulvhai/MWeb-issues#930]

**Comment by randomatom** [comment]
Tab页里的「确认打开」感觉是「锁定」的意思。
<img width="226" alt="image" src="https://user-images.githubusercontent.com/6417202/39749453-44d074c2-52e5-11e8-8baa-25bebcff4af6.png">
就是该Tab页的文章，不会再被新点击 文章取代。新的文章，会另起一个tab页显示。
建议用「锁定」表示，而且在上面加个「🔐」之类的标识，而且将其移到「左边」。
图标如果不好加，也可以用 **emjoi 文字**。

例如，safari的显示，「固定便签页」。
<img width="174" alt="image" src="https://user-images.githubusercontent.com/6417202/39751319-619b002c-52ea-11e8-904f-ea32e0d06d69.png">

**Comment by oulvhai** [comment]
3.1.9 版本改为 「固定此标签页」
