### ISSUE TITLE
<div>标签导致Markdown表格无法渲染

### ISSUE THREAD

**Issue by liyang85** [oulvhai/MWeb-issues#932]
[MWeb官方英文文档](http://www.mweb.im/markdown-syntax-guide-full-version.html#html)说可以插入块级元素标签：

> The only restrictions are that block-level HTML elements -- e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. -- must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces.

我有一个如下结构的Markdown表格，MWeb可以正常渲染：

| 虚拟机角色 | 网卡 | 网卡模式 | IP地址 | 地址获取方式 | 默认网关 |
| --- | --- | --- | --- | --- | --- |
| client | `eth2` | host only | `172.16.125.61/24` | static |  |
| client | `eth3` | bridge | `192.168.2.226/23` | dhcp |  |
| client | `eth3:1` |  | `ifconfig eth3:1 10.0.0.61/24` | manual | `ip r a 192.168.11.0/24 via 10.0.0.74` |
| router | `ens33` | bridge | `192.168.3.58/23` | dhcp |  |
| router | `ens33:1` |  | `ifconfig eth3:1 10.0.0.74/24` | manual |  |
| router | `ens34` | host only | `172.16.125.74/24` | static |  |
| router | `ens34:1` |  | `ifconfig ens34:1 192.168.11.74/24` | manual |  |
| VS | `ens34` | host only | `172.16.125.71/24` | static | `ip r a default via 172.16.125.74` |
| VS | `ens34:1` |  | `ifconfig ens34:1 192.168.11.71/24` | manual |  |
| RS #1 | `lo:1` | loopback | `192.168.11.71/24` | script |  |
| RS #1 | `ens34` | host only | `172.16.125.72/24` | static | `ip r a default via 172.16.125.74` |
| RS #2 | `lo:1` | loopback | `192.168.11.71/24` | script |  |
| RS #2 | `ens34` | host only | `172.16.125.73/24` | static | `ip r a default via 172.16.125.74` |

但我按照官方文档的说明插入`<div>`包围Markdown表格后，

![image](https://user-images.githubusercontent.com/20695423/39814649-c04a1954-53c7-11e8-86a4-b3a943dd9434.png)

导致表格无法渲染：

![image](https://user-images.githubusercontent.com/20695423/39814657-c7889632-53c7-11e8-9231-7cce5b10f6d4.png)

请问是什么原因？如何解决？

---

备注：我插入`<div class="table-container">`标签的目的是：稍后可以在博客上增加相应的CSS，例如`.table-container { overflow-x: auto; }`，来控制表格在小屏幕上可以左右滑动，所以我非常需要这个功能。谢谢。

**Comment by randomatom** [comment]
这个问题 我给 mweb的 hoedown 库打了补丁，并提交 给 作者整合，他也接受了。
顺利的话，下个版本估计能解决这个问题。
@liyang85

**Comment by randomatom** [comment]
其实现在还有一个办法可以解决这个问题：

```html
<script>
document.write("<div>")
</script>

| titile1 | title2 |
|-------|-----|
| aaaa |  bbbb |


<script>
document.write("</div>")
</script>

```

**Comment by liyang85** [comment]
非常感谢 @randomatom 的帮助，希望MWeb尽快推出新版。如果短时间内用不了新版，用JS添加标签不失为一种临时解决方案。

**Comment by liyang85** [comment]
我看到 [randomatom/hoedown-mweb](https://github.com/randomatom/hoedown-mweb) 主页上建议「更好的办法是换库：github的cmark库」，作者 @oulvhai 在我去年11月提交的issue #769 提到了这个库，不知是否有计划换库？

**Comment by randomatom** [comment]
@liyang85 ： 据说更改需要蛮多，这个库打打补丁也能用，作者好像说 暂时不换。

**Comment by liyang85** [comment]
明白了，多谢。

坦白讲，目前我使用MWeb比较顺手，但还是希望能够越来越好，看着Open的Issue快600条了，不了解MWeb的人看到可能会产生不信任的感觉，如果换库能解决问题，希望作者能早下决心实施。

另外，作者最近似乎很少出现在这里，也没有新版本发布，不知道是否在准备新功能，希望作者能适当公布一下最新进展。

**Comment by oulvhai** [comment]
@liyang85 @randomatom  cmark 库我猜也不支持你这种写法，按 markdown 的语法规则，只要是出现 html，里面的东西必须不解析。

**Comment by randomatom** [comment]
@oulvhai github支持这种写法。3.x的库已经改好了。

**Comment by oulvhai** [comment]
@randomatom 我好奇测试了一下，github 的回复好像不认可这种语法
```
<div>
| titile1 | title2 |
|-------|-----|
| aaaa |  bbbb |
</div>
```
会变成

<div>
| titile1 | title2 |
|-------|-----|
| aaaa |  bbbb |
</div>

**Comment by randomatom** [comment]
@oulvhai 前面需要多加空行。

```
<div>

| titile1 | titile2 |
|------|------|
|aaa | aaa |

</div>
```



<div>

| titile1 | titile2 |
|------|------|
|aaa | aaa |

</div>

**Comment by oulvhai** [comment]
@randomatom 加空行这本质上是分成三段了，因为 markdown 中的 html 语法正是前后空一行。MWeb 2.x 应该是针对 html 中的空行也直接输出，所以才无法解析这种写法。

**Comment by randomatom** [comment]
上文说了，对 \<div\> 等标签，后面需要 blank lines，内部的元素才能作为 markdow 语法解析。
否则就当html了。

The only restrictions are that block-level HTML elements e.g. \<div\>, \<table\>, \<pre\>, \<p\>,   __must be separated from surrounding content by blank lines__ , and the start and end tags of the block should not be indented with tabs or spaces.

**Comment by oulvhai** [comment]
竟然还有这种特殊情况对待！其实我也没细看 Markdown 语法说明。真是有意思了。
