### ISSUE TITLE
<优化建议>文档排序功能不自动刷新

### ISSUE THREAD

**Issue by remainsu** [oulvhai/MWeb-issues#934]
mac 客户端的 文档排序功能不会自动刷新。
比如：选择了最后修改靠前。  但最后修改的文档，并不会自动排在最前面，而是每次都需要 重新选择一次排序规则，才会生效。
建议更改一下。谢谢。

**Comment by oulvhai** [comment]
已修正

**Comment by remainsu** [comment]
您好。 看起来 并没有被修复呀...    我的版本是：版本 2.3.0 (2.3.0)   mac
