### ISSUE TITLE
[优化建议 - IOS] 首页的搜索框 的 搜索范围 

### ISSUE THREAD

**Issue by randomatom** [oulvhai/MWeb-issues#935]
目前进入 首页，首页的搜索框 的 搜索范围 ，是根目录的几个目录的文件名。
但是，就那三四个目录，几乎没有人会在根目录，搜索文件名吧。

建议：在「根目录」的搜索框，范围改为「**全部文件**」，既符合人的直觉，也少了一个步骤。

**Comment by oulvhai** [comment]
iOS 将改版，到时综合考虑这个。
