### ISSUE TITLE
[优化建议] svg 图片在 「编辑模式」无法显示；

### ISSUE THREAD

**Issue by randomatom** [oulvhai/MWeb-issues#936]

**Comment by oulvhai** [comment]
今天仔细研究了一下， macOS 显示 SVG 图片需要另外的库，iOS 找到一个算靠谱的，macOS 的不能直接用 iOS 那个库，要用别人的 fork 的。看了一下实现，蛮复杂的。 

这个先关掉，暂时不想引入这个库。
