### ISSUE TITLE
批量生产有序列表的数字大于9的下一个数字会跳回1

### ISSUE THREAD

**Issue by Mirage-Zero-Nine** [oulvhai/MWeb-issues#938]
即，无法生成 11. 12. etc...
<img width="887" alt="screenshot 2018-05-29 at 11 07 42" src="https://user-images.githubusercontent.com/14092462/40667960-5e9d88ca-6331-11e8-9023-84557a14e6db.png">
如图所示。

**Comment by oulvhai** [comment]
收到，已在 MWeb 3 中计划改进。
