### ISSUE TITLE
Code-blocks' line numbers, code-bloks' themes & editor's styles.

### ISSUE THREAD

**Issue by luispuerto** [oulvhai/MWeb-issues#941]
Hi! 

First of all thanks a lot for your app because it's really great app and it's almost perfect for my purposes. 

However, I have some suggestions to make. 

1. I would love to have an option fo have codeblock with numbers. Whether if is just changing the preview css or with just an option. I've been trying to make if possible changing the css but I didn't succeeded totally. 
I tried to apply [this solution](https://stackoverflow.com/questions/40842277/create-line-numbers-on-pre-with-css-only) and I failed. I was only able to produce code-blocks with a number in the first line, or  in random lines with the code-block partially destroyed. I'm good with the css and I didn't have to much time to investigate this. 
Do you think you can produce a set of styles with line numbers in the code-blocks? Perhaps it's a quick and dirty solution. 
![screen shot 2018-06-01 at 11 51 09](https://user-images.githubusercontent.com/22882880/40831834-b395eaf8-6592-11e8-9766-2c60196e5659.png)
![screen shot 2018-06-01 at 11 54 24](https://user-images.githubusercontent.com/22882880/40831835-b3b6b4ea-6592-11e8-8bbd-9eb10530127b.png)

2. It would be also great if the code-block style could be changed independently of the preview CSS. For example, I love the the github preview, but I would like to have dark code-blocks. 

3. I'd love to have more styles to choose for the editor —and for the code-blocks. My prefer —twilight— isn't there and I would like to be able to use for the editor and perhaps for the code-blocks. Is there anyway I can easily add it or perhaps create it? 

Thanks a lot for your work.

**Comment by luispuerto** [comment]
PS/ it's pity that the vast majority of the issues here are in Chinese because they could be a great source of knowledge for everybody interesting the app and not only the Chinese speakers ...

**Comment by oulvhai** [comment]
MWeb 3.x now support line number for preview.
@luisspuerto Sorry, because MWeb author didn't good at English.
