### ISSUE TITLE
MWeb 卡死，无法使用

### ISSUE THREAD

**Issue by fka2004** [oulvhai/MWeb-issues#943]
MWeb是我在appstore上全价购买的，使用过程中经常遇到打开后直接卡死，cpu 90%左右，而且关闭再次打开也没用，非常耽误工作，请问有什么办法解决，谢谢
电脑配置mbp 13 系统10.13.3

**Comment by oulvhai** [comment]
如果能稳定重现，请邮件联系我： coderforart@gmail.com。
或者可以试试最新发布的 3.x
