### ISSUE TITLE
导出 HTML，title 会有 # 号

### ISSUE THREAD

**Issue by coldice8** [oulvhai/MWeb-issues#945]
文件导出 html title 上会有 # 号，应该是去掉的。

**Comment by randomatom** [comment]
会不会写法不对？比如说
* 在 多个 #号 之间有 **空格**？
* 或者 行首 有 **空格**？

**Comment by coldice8** [comment]
@randomatom 不是。你可以试试。导出 html，在 head 里的 title。

**Comment by randomatom** [comment]
我试过，没问题。
你可以有问题的例子，发上来看看。要不作者也很难排查问题。

**Comment by coldice8** [comment]
@randomatom 
```
# 我是大标题
我是正文。
```
导出为 HTML。查看 HTML 源码。
```
<head>
<meta charset="utf-8">
<title># 我是大标题</title> // 注意这行。
</head>
```

**Comment by oulvhai** [comment]
好像是修正 了。
