### ISSUE TITLE
标签管理太乱，让人摸不清头脑

### ISSUE THREAD

**Issue by mysql-inception** [oulvhai/MWeb-issues#947]
在左侧文件管理栏中，单击一个文件时，默认都会去替换右边已经打开的一个文件，这个替换策略真是让人摸不着头脑，难道是替换最近使用的文件吗？这样会很不友好，比如刚才在看一个文件，突然要看另一个文件，单击之后，之前正在看的文件消失了。。。。

建议在配置中加一个选荐，单击时默认选择新建标签还是替换标签，替换策略也可以加一个选项，是替换谁的问题。

感谢

**Comment by oulvhai** [comment]
可以双击或者右键在新标签中打开以固定。
