### ISSUE TITLE
删除默认的文章后，再打开不显示界面

### ISSUE THREAD

**Issue by nanbingxyz** [oulvhai/MWeb-issues#955]
版本是3.0.1
删除Library 中默认的文章后（ Library 中一篇文章也没有了），再打开不显示界面，只能通过新建文件进入外部模式。 也无法通过菜单打开Library。但通过快速笔记新增一篇文章后，问题解决。

**Comment by oulvhai** [comment]
应该没问题了，如果还有，再开。
