### ISSUE TITLE
文件夹目录可替换成标签目录

### ISSUE THREAD

**Issue by nammmm** [oulvhai/MWeb-issues#956]
当前版本2.2.9，最左侧显示文件夹目录，如果想要按标签查找文档则需要两步：首先点击右下角的标签，然后再选择目标标签。希望能够实现点击右下角的标签图标时可以把当前的文件夹目录视图替换成标签目录，这样对习惯按标签查找文档的人会是一个很棒的功能。

**Comment by oulvhai** [comment]
3.x 版已有计划改进
