### ISSUE TITLE
前后切换多个文档的快捷键

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#958]
同时编辑多个文档。
前后切换多个文档。
如果能像在文件目录中"前进","后退"那样操作,会很自然。
也像是浏览器的"前进","后退"那样。

一般是用
command + ] 前进
command + [ 后退

**Comment by oulvhai** [comment]
功能太过高级

**Comment by linfeng365** [comment]
@oulvhai 

我发现, MWeb 本身有记录前后文档切换顺序的
在 (⌘+w) 关闭文档的时候,会 "后退"切换打开的文档。
这就是"后退" 功能呀。

如果能提取出来,只做 "后退" 功能,也是极好。

这个快捷键功能,
相当于系统的 "⌘+ tab", Safari 的 "⌘ + [ "。
**通用,且高频。**

建议开发。
