### ISSUE TITLE
到出到html，不能渲染显示流程图

### ISSUE THREAD

**Issue by joket1999** [oulvhai/MWeb-issues#96]
1. 如题，导出html，有流程图的话，不能显示，只显示流程图编码。（发现是因为导出html是没有调用flowchartjs）
2. 导出pdf，流程图长的话分页了，中间截断了，很不好。能不能整体缩小后再导出，这样一页能够显示流程图。还有就是能否
3. 能否加入导出png

**Comment by oulvhai** [comment]
1. 导出 html 时有几个选项，选择后即可显示流程图
2. 这个我想想怎么修正（因为目前所用的生成 PDF 的技术无法知道是否会截断）
3. 右上角的分享按钮有 保存为图片的功能，不过是为 JPG，但是想来差不多。
