### ISSUE TITLE
finding images

### ISSUE THREAD

**Issue by chipbrock** [oulvhai/MWeb-issues#961]
Hello

I’m trying to set up an already working site - not a blog, but actually chapters of a textbook. 

I cannot get MWeb to recognize the directory where my images are stored. For a variety of reasons my directory structure is as follows:

Markdown files live in:

./git-ed/ed2019_GR/_lectures/file.md

The images live in:

./git-ed/assets/motion/figs/image.png

My markdown files refer to images as:

![mac](../../assets/motion/figs/mackinac.png){:width="400px"}*Sights along the way up I75 from Detroit to "the bridge.”*

That works just fine.

But if I set up an external folder with relative addressing and the media file to be

../../assets/motion/figs/

Nothing shows up. In fact, I cannot get MWeb to find any image on my disk!

What I want is for images to point as before:

![mac](../../assets/motion/figs/mackinac.png){:width="400px"}*Sights along the way up I75 from Detroit to "the bridge.”*

How can I do that??

**Comment by oulvhai** [comment]
No.
