### ISSUE TITLE
enhancement: 一个展示方式,像 Safari 一样,有个  show all tab 功能。

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#962]
* 一键多窗口展示文本。
* 用于同时查看多个文本。

![show all tab](https://www.macobserver.com/imgs/tmo_articles/20150528SafariTabs4.jpg?x47654)

**Comment by linfeng365** [comment]
我想要的和这个类似,
但其实**不是要**这个功能。

我不要预览,以切换。(当然,这是一个可以考虑的功能)

我**真正想要**的是,可以排列窗口。(早期 word 好像有)
比如并排最近的排4个窗口。
窗口是可以编辑的。(比如进去复制粘贴)


目的 -> **在多个文本之间编辑。**
        ->**查看多个文本**

**Comment by oulvhai** [comment]
暂时不考虑用 Show all tab 这种，应该也达不到你的需求。
在我内部优先级不高的需求中，有你这种用法。大概是：排列窗口是使用 Magnet 这种 软件实现，然后 MWeb 可以打开多窗口，所以只需要实现一个快速在本窗口打开文档的功能即可。比如说我在右上角打开了一个窗口，在激活这个窗口时，CMD + O 搜索打开的文档中，有一定的方式，能让打开的文档在当前这个窗口显示。

可能说得不清楚。所以暂时不考虑做，等我想明白整套交互先。
