### ISSUE TITLE
enhancement:URL Scheme 支持 tab 等搜索功能

### ISSUE THREAD

**Issue by linfeng365** [oulvhai/MWeb-issues#963]
请你参考一下 dayone 的标签方式;
```[#术语卡](dayone2://filter?tag=%E6%9C%AF%E8%AF%AD%E5%8D%A1)```

这样可以在 文章里插入 tags ,这个 tags 就是一个链接。
手写语法:
```[#术语卡](mweblib//filter?tag=术语卡)```

**Comment by oulvhai** [comment]
此功能已计划，具体发布时间就未定了。
