### ISSUE TITLE
文档库搜索快捷键可设为非全局

### ISSUE THREAD

**Issue by cn-src** [oulvhai/MWeb-issues#967]
文档库搜索快捷键可设置为全局或非全局。

一般来说不太希望有太多的全局快捷键，常规的搜索，打开终端这些本来就是需要全局的操作，而 mweb 的文档库搜索则不一定需要全局的，更多当成使用 mweb 写作时切换或查找文件时使用则很好。全局搜索则可以通过Alfred插件提供。

之所以不太希望有太多的全局快捷键，是因为对于开发者来说 IDE 的快捷键已经很多了，想要找到一个方便使用又不冲突的快捷键已经没几个了，因此更希望除非有必要，还是尽可能不使用全局快捷键。

**Comment by randomatom** [comment]
可不设置全局快捷键。
默认是 cmd + O。

**Comment by cn-src** [comment]
这倒是，谢谢。不过很多快捷键不能自定义倒是挺纠结的。:sweat_smile:
