### ISSUE TITLE
进入全屏幕后，command+8 的快捷键无效，无法调用“弹跳窗”

### ISSUE THREAD

**Issue by mrLuyao** [oulvhai/MWeb-issues#97]
进入全屏幕后，command+8 的快捷键无效，无法调用“弹跳窗”。导致无法在全屏幕状态下，用键盘实现标题之间的转跳。

ps：另外希望作者能像Ulysses那样详细写一下入门的介绍，这个快捷键在MWeb自带的文章里就没有介绍。很多功能都不会用，需要用户一个一个查，效率很低。

**Comment by oulvhai** [comment]
Bug 已确认，另外感谢建议，其实新版网站和帮助重制已在执行了。
