### ISSUE TITLE
调整三栏的第二栏的宽度时程序崩溃

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#971]
刚开始每次都崩溃。用了一段时间之后就不崩溃了。

我想是不是和cell的加载有关？没加载完的时候（比如屏幕下方还没显示的）调整就会崩。加载完了就不崩了？

3.1.1 试用版

**Comment by oulvhai** [comment]
未能重现，如果能重现再开此 issues

**Comment by owenzhao** [comment]
复现方法。

1.  复制MWeb3的文档库到下载文件夹
2. 打开MWeb
3. 更改文档库 -> 选择已有设置的文档库 到下载文件夹中的文档库
4. 更改成功后，MWeb会重新加载内容，并且默认的分支是所有文章。我的所有文章有186条。
5. 这时拖动，应用就会立即崩溃。

版本：MWeb 3.1.2。

之所以选择更改文档库，是因为我认为这个是某种缓冲机制造成的。所以才会在新指定文档库之后，出现问题。

过一段时间，缓冲完成了。这个问题就消失了。

**Comment by oulvhai** [comment]
按以下步骤测试，未能重现

1. 直接更改文档库到 iCloud Drive 中（这是我 2.x 版的文档库，笔记数 530 条），拖动时第二栏第一栏都测试了，没问题。
2. 复制我 3.x 用的文档库到 下载文件夹，更改文档库到这个位置，再测试拖动，没问题。
3. 更改回我原来的，再测试拖动，也没问题。

**Comment by owenzhao** [comment]
那算了。等macOS Mojave正式发布，或者你什么时候装它了再试吧。也可能和系统有关系。

**Comment by oulvhai** [comment]
呃，你一直是在说 Mojave 呀。。抱歉。。 的确没装。
