### ISSUE TITLE
添加图床内按钮间歇性失效问题

### ISSUE THREAD

**Issue by marsxxl** [oulvhai/MWeb-issues#972]
如下图所示，鼠标点击“保持上传”这一行时，出现间歇性的失效，取消选中不成功，尤其在点击文字选择取消的时候，点击前面小框框成功率高得多

系统版本：10.13.5 正式版
MWeb 版本：3.1.1 正式版

![图床](https://ws4.sinaimg.cn/large/006tNc79ly1fsxlpcz01gj30rg0m8n1o.jpg)

**Comment by oulvhai** [comment]
好像无法重现？

**Comment by marsxxl** [comment]
我在 3.1.2 上反复测试了下，暂时没发现问题了
