### ISSUE TITLE
已下载3.0，老用户反馈

### ISSUE THREAD

**Issue by iHTCboy** [oulvhai/MWeb-issues#973]
唯一不足：
1、整体的界面和图标、文字都变的大三分之一，显示的难看，希望做的小一些，像以前那边，文字还有图片太大，导致显示不全。
2、以前在标题就能重命名，现在只能在左侧栏选择，希望在标签栏也加一下重命名的快捷二级栏（写博文经常改名字，特别是草稿）

其它暂时没有要求，另作为第3版，希望UI上也有所改变，特别是主题，已经1年多没有看到新的了，加油！支持！

**Comment by itren** [comment]
文件夹的图标为啥从蓝色的改成了白色的，以后可以自定义吗？还是觉得Mac下面的蓝色文件夹图标好看。

**Comment by oulvhai** [comment]
1. 看看就习惯了，我当初也是这样想，后来觉得 3 好看点。
2. 重命名之后考虑加个快捷键，然后，图标自定义有在计划内。

**Comment by iHTCboy** [comment]
@oulvhai  还有删除的快捷键，不喜欢没有文章时自动创建无标题的占位文章。
