### ISSUE TITLE
3.0 吐槽 —— 老用户反馈

### ISSUE THREAD

**Issue by chenzz** [oulvhai/MWeb-issues#974]
1. 右侧导航栏不能常驻了，很不方便
2. 快速搜索框，只能搜索部分日志 —— 我有两篇日志“工作日志”和“工作问题”，搜索“工作问题”能搜到，搜索“工作日志”搜索不到
3. 快速搜索框，搜索时，希望能“标题包含关键字”的日志排在前面
4. https://github.com/tianhao/alfred-mweb-workflow 变成以外部模式打开文档了，原本是以Libray Mode打开文档的！

相关截图：
![image](https://user-images.githubusercontent.com/5676311/42264311-dee18d0a-7fa2-11e8-933d-e40efcb9fc64.png)

**Comment by crper** [comment]
这个大版本更新...浪费💰.....买了之后才发现..连typora这种所见即所得的模式都没有;

无语...这就是酝酿了一年多的重量级更新?

**Comment by addozhang** [comment]
同感, 从使用中没感觉到多大的提升. 
侧边栏不能停留很不方便, 有什么原因丢弃了之前的设计, 改变了老用户的习惯.

**Comment by oulvhai** [comment]
1. 关于导航我另开了一个： https://github.com/oulvhai/MWeb-issues/issues/991 
2. 搜索新版本优化了一下，还会继续。
3. 下个版本修正。

**Comment by itren** [comment]
导航栏我用的不多，但是外部模式下为啥没了搜索。
![mweb](https://user-images.githubusercontent.com/10252344/42406513-d0e16794-81db-11e8-8738-2e7039e80c23.jpg)

**Comment by oulvhai** [comment]
@ITGrocery CMD + O

**Comment by fmewtwo** [comment]
刚刚60大洋买了mweb3， 刚设置完，还没有细细使用，暂先不提新问题， 咱 #700 这个问题是不是先提前支持下，我就觉得这个功能简直就是必不可少的， 看文章时通过关键字定位，我还得切换到编辑模式下找好了，然后再切换到预览模式下凭借着记忆去滚动到那个位置:thumbsdown:

**Comment by oulvhai** [comment]
@crper MWeb 没有做 typora 这种模式的计划，也从没有说过要做呀。这个需求一开始我就否决了，如果你听到 MWeb 要支持 typora 模式，肯定不是我说的。

@1412kid 现在正在检起来一堆 issue 慢慢优化 😂，我之前还说要做 Win 版，果然高估了自己。

**Comment by addozhang** [comment]
@oulvhai 其实之前2.0用的挺好的, 一直感觉如果能支持所见即所得的模式就完美了. 不知道其他人如何, 3.0里我最希望看到的是所见即所得. 相信也是很多人无法放弃Typora的原因吧. 如果多了这个更能, 我觉得会有更多人愿意买单吧.

说个身边的例子, 6月初推荐同事买了2.0的. 他上手就放弃了, 又转回Typora了. 😂

**Comment by oulvhai** [comment]
@addozhang 虽然是这样，但是还是会保留我的坚持，反正一个软件也不可能满足所有需求的。再说了，有多的选择和竟争不是很好么，虽然 Typora 还没收费。。

**Comment by randomatom** [comment]
作为个人开发者精力有限，需要取舍。Typora 这么强大的所见即所得，工作量很大，不建议。

MWeb的优势不在于强大的编辑功能，在于内容发布，以及知识管理等等。
先把以上两方向做好，就会有很多人离不开了。

**Comment by crper** [comment]
@randomatom  [marktext](https://github.com/marktext/marktext)了解下, 这个项目才出来多久?

**Comment by addozhang** [comment]
@crper cool, 6k+ ⭐️

**Comment by oulvhai** [comment]
@crper @addozhang 这个厉害了，感觉如果多几个人开坑，直接在这个项目上做开发，很容易搞些东西出来呀。编辑器都有了，其它东西只是时间问题而已。

**Comment by addozhang** [comment]
@oulvhai Typora目前还是beta免费, 没有开源. 所见即所得可以参考下marktext吧, 感觉不会有太大难度(不是macos开发, 逃...)

收费软件是不是更要满足用户的需求, 我看所见即所得的需求还是很大的.

**Comment by oulvhai** [comment]
@addozhang marktext 和 typora 都是 Javascript 工具链，我这是 objc 和 AppKit 工具链，不知道那年才能合得起来。。

**Comment by chenzz** [comment]
@addozhang @oulvhai JavaScript 的解析器一定要考虑性能啊
Typora打开一篇稍微长点文章能卡七八秒，这个是我放弃Typora的主要原因之一

**Comment by oulvhai** [comment]
@chenzz 性能上的确是个问题。原生的都还有很多得优化呢，感觉好多需要花精力，这也是我一开始就否决的原因。

**Comment by crper** [comment]
什么时候支持VIM模式? 类似作业部落 https://www.zybuluo.com/mdeditor

**Comment by oulvhai** [comment]
@crper VIM 模式暂时不考虑支持。感谢建议。

除了 1 之外，2，3，4 都应该修正了。先关。

**Comment by hesj** [comment]
> @crper MWeb 没有做 typora 这种模式的计划，也从没有说过要做呀。这个需求一开始我就否决了，如果你听到 MWeb 要支持 typora 模式，肯定不是我说的。
> 
> @1412kid 现在正在检起来一堆 issue 慢慢优化 😂，我之前还说要做 Win 版，果然高估了自己。

 typora 这种模式，所见即所得 ，应该很多人觉得挺好的。。希望支持哈。
