### ISSUE TITLE
附件及附件预览问题及建议

### ISSUE THREAD

**Issue by xunuo** [oulvhai/MWeb-issues#975]
为表示支持，已购买最新版本。

新版本能在外部模式里面显示文件夹里面的附件了，但是图片不能方便的预览，能否有个视图或者双击在tab中预览呢？还有能否邮件点击附件菜单里面增加复制路径（绝对或相对路径可选），或者直接邮件菜单里有一个插入的选项，可以重复插入，当然我还有个愿望，就是能够自动清理在文章中没用到的附件，谢谢 :)

![image](https://user-images.githubusercontent.com/698455/42264935-c8a1a872-7f7a-11e8-8509-371c3039ba15.png)

**Comment by oulvhai** [comment]
预览目前调用系统预览了。
