### ISSUE TITLE
很多功能点了没有反应，一点就弹出错框

### ISSUE THREAD

**Issue by inRush** [oulvhai/MWeb-issues#979]
新建文档不行，外部模式没有，添加分类，新增标签也没用，一点就然出现错误框

**Comment by inRush** [comment]
MWeb：3.1.1版本
Mac：10.13.4

**Comment by inRush** [comment]
App Store 安装的 3.1.0 版本也不行

**Comment by inRush** [comment]
![image](https://user-images.githubusercontent.com/27626752/42304344-5614ed94-8058-11e8-9216-f87807cd1f20.png)
导入文档到文档库里，在finder里面显示已经导入有文件了，但是报错，新建也是，新建一个文件，在finder里面能看见有新增，但是在mweb里面没有显示

**Comment by inRush** [comment]
mweb3，出现占用cpu过高的情况。写完文档以后，一直放着在那儿，无缘无故占用cpu很高

**Comment by oulvhai** [comment]
你的文档库难道有问题了？ 感觉是 mainlib.db 没了。邮件联系我： coderforart@gmail.com
