### ISSUE TITLE
使用MWweb高级版遇到的2个问题

### ISSUE THREAD

**Issue by 919695** [oulvhai/MWeb-issues#98]
1、无法修改生成静态网站文件的位置
2、针对文章设置是否page页面后，再生成网站会崩溃

**Comment by 919695** [comment]
我的系统版本是OSX 10.11.2 (15C50)

**Comment by oulvhai** [comment]
1. 生成位置可以在菜单：偏好设置 - 通用设置里 修改
2. 可否详细说说 设置是否为 page 后的 崩溃的情况？我这边测试不出来。

**Comment by 919695** [comment]
1. 我有找到设置位置，但是无法输入和修改路径。
2. 就是我点击一篇文章右上角的设置按钮 然后勾选了是否为PAGE 再回到目录菜单点清理并重新生成网站，然后程序直接闪退了，你的系统是否和我版本一样？

**Comment by oulvhai** [comment]
1. 只能点 Save As 按钮。 权限原因，必须点 Save As MWeb 才能获得那个文件夹的写入权限。
2. 我在 10.9 ~ 10.11 都测试过，无法重现。如果可以的话，可否把闪退的详细发到 coderforart+233[at]gmail.com，也可以用 软件的 Help 菜单的  Send Feedback 功能。

**Comment by 919695** [comment]
第一个问题得到了解决，感谢。
第二个问题我现在无法重现了，我估计是只有一篇文章的时候设置为单页再生成就会崩溃，因为我当时是这种情况操作的。

**Comment by oulvhai** [comment]
非常感谢！
