### ISSUE TITLE
下载了试用版，然后去买了App Store的版本，再也无法新建文档了，新增文档库也不行

### ISSUE THREAD

**Issue by ljcoder2015** [oulvhai/MWeb-issues#980]
下载了试用版，然后去买了App Store的版本，再也无法新建文档了，新增文档库也不行。
MWeb 3 版本

**Comment by oulvhai** [comment]
可以试试以下办法：

1. 把文档库复制到另外的位置
2. 在偏好设置 - 文档库 - 修改文档库位置 - 选择现有文档库，选择这个位置。

如果还有问题，请邮件联系我： coderforart@gmail.com
