### ISSUE TITLE
只有一个分类时点击编辑器上方修改分类导致崩溃等问题

### ISSUE THREAD

**Issue by guader** [oulvhai/MWeb-issues#982]
只有一个默认分类MWeb，点击编辑器上方长按钮会直接崩溃，屡试不爽。
偏好设置界面调整字体及字体大小等参数，有时编辑器内容会消失无法看到效果，重新点击编辑器恢复。
偏好设置调整主题时，有时主题会错乱，不能正常显示，重启恢复。
今天刚买的，有点失望。

**Comment by oulvhai** [comment]
感觉你跟我用的不同一软件 😂
如果最新版本还有问题，邮件联系我： coderforart@gmail.com
