### ISSUE TITLE
建议 MWeb3 安装时，保留或者读取老版本的偏好设置

### ISSUE THREAD

**Issue by supernova16** [oulvhai/MWeb-issues#985]
虽然看过简介，觉得视觉也没怎么优化，安装上后还是崩溃了（心理崩溃）现在只想用回老版本，找回我的偏好设置。

应该有很多人都是覆盖安装的，考虑到这种情况，一些偏好设置应该替用户保留。

**Comment by supernova16** [comment]
最爱的右侧导航栏也没了，在我看来这真的是原先老版本一个亮点，我一直把 mweb 当作自己的 wiki 资料库使用，固定的导航栏在这一点上很大地提高了效率。

不要为了所谓的视觉优化而优化。

不太礼貌的老用户哔哔

**Comment by oulvhai** [comment]
大纲反馈在这里  https://github.com/oulvhai/MWeb-issues/issues/991 

目前可以导出发布服务，另外的就没有什么偏好设置了吧。有也不好导出。
