### ISSUE TITLE
搜索功能不可用：结果空白

### ISSUE THREAD

**Issue by islandx** [oulvhai/MWeb-issues#986]
macOS  10.12.6
MWeb 3.1.0(419)  App Store版本

总文档数为43， 总大小1.3MB，
不管是文档列表上方的搜索窗口，还是 cmd + O 呼出来搜索窗口， 搜索任意字符串，搜索结果都是空的，请问该如何处理？

**Comment by oulvhai** [comment]
把文档库保存在 Documents 下的新文件夹内应该会没问题了。
