### ISSUE TITLE
预览网站和打开终端希望可以使用其他的浏览器和终端

### ISSUE THREAD

**Issue by J3n5en** [oulvhai/MWeb-issues#987]
预览网站和打开终端希望可以使用其他的浏览器和终端
默认的浏览器是chrome终端是iterm2
不过还是唤起了safari和terminal。。。希望可以唤起系统默认或者可设置

**Comment by oulvhai** [comment]
主要是我用 chrome 开有时好像不能正确工作，多数不行。
另外的就是无法判定用户是否有装 iterm2 。
