### ISSUE TITLE
同一文档有多分类时文档计数错误

### ISSUE THREAD

**Issue by J3n5en** [oulvhai/MWeb-issues#988]
![image](https://user-images.githubusercontent.com/10610925/42359491-c95408be-8114-11e8-8074-153a0558da47.png)

实际上只有20多个文档，有些文档具有多分类，造成计数错误

**Comment by marsxxl** [comment]
计数问题挺普遍的，我录了个小视频，很明显
[计数bug](https://d.pr/v/fijqx8)

**Comment by oulvhai** [comment]
目前是采用折中的办法，兼顾性能，也就是分类的统计仅用计算一次，但是不太准确。如果用准确方式，需要每个分类计算一次。差别还是蛮大的。
