### ISSUE TITLE
三栏时，中间栏标题格式问题

### ISSUE THREAD

**Issue by enel1jk** [oulvhai/MWeb-issues#99]
![14519586554895](https://cloud.githubusercontent.com/assets/3055794/12105679/ef441382-b391-11e5-8511-0e9dc08eb299.jpg)

**Comment by enel1jk** [comment]
中间栏不要显示链接吧

**Comment by oulvhai** [comment]
这其实是直接原文显示的。

**Comment by enel1jk** [comment]
嗯，很明显。
不过中间栏最主要就是要看下标题而已吧，按理说不该显示出链接吧，虽然没什么大碍。:)
