### ISSUE TITLE
MWeb 3 右侧导航栏（大纲视图）讨论

### ISSUE THREAD

**Issue by oulvhai** [oulvhai/MWeb-issues#991]
3.x 版考虑到导航栏一般不大会用，实际上我也用得非常少。所以改成浮动加 拖拽固定的方式，浮动方式满足 80% 用户需求，固定方式满足 20% 用户。
最近接到几个用户反馈说 2.x 版的处理比较好。这里讨论一下。

**Comment by addozhang** [comment]
选择2.x的处理

**Comment by linfeng365** [comment]
我只使用大纲实现光标跳转功能的。
其它没太注意。

**Comment by randomatom** [comment]
个人这个功能用的比较多，习惯开大纲，有助于对全局的把控。
建议可以做两种模式：
1. 「固定模式」，类似2.x
2. 「浮动模式」，类似3.x
两个模式可以通过 确认框 切换。

**Comment by menduo** [comment]
2.x +1

**Comment by pukguy** [comment]
2.x

**Comment by chenzz** [comment]
2.x +1

**Comment by hedame** [comment]
2.x +1

**Comment by oulvhai** [comment]
目前已经没有用户反馈这个问题了，好像真的是比较少人用。。。 这个我目前还是没想到两边都满足的方案（除了两种都支持）。

**Comment by addozhang** [comment]
@oulvhai 这能叫少么 看上面全是选2.x的. 不能在大纲视图上加个checkbox, 让用户选择是浮动还是固定?__

**Comment by oulvhai** [comment]
@addozhang 是说我收到的啦，当然，上面我肯定是有看到的。加个 checkbox 是两种都支持的办法。

**Comment by xwang-cb** [comment]
@oulvhai 我感觉`浮动加 拖拽固定的方式`就可以，只要有的选，我不挑食。我现在比较困惑的是，编辑区的内容和预览区的内容不同步，并排显示的时候，两边的内容不同步，累死了

------
在郁闷之中浏览菜单，做各种尝试。
发现一个好玩的地方。猜@oulvhai可能自己习惯使用 Cmd+R(切换预览/编辑器)的。我之前是习惯用Cmd+4的方式(编辑器 & 预览视图)，可能因为之前用马克飞象养成的习惯吧。感觉Cmd+R 可能更简洁好用。

但是，在编辑器或者预览视图，点击文档大纲，同一个内容，界面显示的套路尽然是不一样的啊！
- 如果是在编辑器，点击文档大纲的某个内容，界面会把这个内容显示在屏幕的当中位置
- 如果是在预览视图，同样点击这个内容，界面则把这个内容显示屏幕开头
@oulvhai 确定是要这么干么？

**Comment by oulvhai** [comment]
@xwang-cb 这还真不是我故意的，我其实是没优化，也就是说，浏览器（预览）习惯是在最顶，编辑器是习惯在合适位置（估计）。不过这点也能发现也是够仔细了，我用这么久都没注意。

**Comment by oulvhai** [comment]
@all 
在下个版本计划满足两种方式，默认浮动，右上角加个按钮，点了之后可以选择是固定在编辑器左边或者右边。

这个固定有一点跟 2.x 版本不一样，就是：
2.x 每一个文档的目录视图是独立控制是否显示的，但是 3.x 版本会是所有文档统一的，就像是 三栏、二栏 那样。

**Comment by addozhang** [comment]
`2.x 每一个文档的目录视图是独立控制是否显示的，但是 3.x 版本会是所有文档统一的，就像是 三栏、二栏 那样。`

这个确实应该, 没必要每个文档独立.

**Comment by chenzz** [comment]
@ALL
在下个版本计划满足两种方式，默认浮动，右上角加个按钮，点了之后可以选择是固定在编辑器左边或者右边。

----

OMG 总算有支持计划了，你之前说“目前已经没有用户反馈这个问题了，好像真的是比较少人用。。。”，我还以为你打算放弃这个功能了。

要知道，如果你做的不好，只有1%老用户才会来吐槽，剩下99%的用户直接选择其他产品去了
所以请重视老用户的诉求吧

**Comment by oulvhai** [comment]
3.1.6 版已增加此功能，先关。
