### ISSUE TITLE
国内版印象笔记发布

### ISSUE THREAD

**Issue by imfuxiao** [oulvhai/MWeb-issues#992]
![jietu20180707-120633](https://user-images.githubusercontent.com/6482586/42406636-346d1af4-81de-11e8-8303-1c3b7a7807db.jpg)

**Comment by oulvhai** [comment]
`<pangu` 变成 &lt;pangu 就可以了。或者是用 \`<pangu\` 包起来。

**Comment by imfuxiao** [comment]
谢谢, 已解决, 看来是md中标签的问题
