### ISSUE TITLE
升级到 3.1.2 版本之后，打开外部模式卡死

### ISSUE THREAD

**Issue by samwei12** [oulvhai/MWeb-issues#995]
系统版本：
macOS: 10.13.5

**Comment by oulvhai** [comment]
可否提供多一点信息？ 或者直接发一张你外部模式的截图也好，我 好重现。

**Comment by samwei12** [comment]
持续了大概半小时的样子，后面打开突然可以了。。看上去像是死循环了。
我堆栈发你邮件吧
邮箱留一个

**Comment by oulvhai** [comment]
邮件： coderforart@gmail.com

**Comment by oulvhai** [comment]
堆栈 收到了，不过看完没什么收获。 看看我是否能重现了，目前也是在用 10.13
