### ISSUE TITLE
关于MWeb 3中只能使用单页css进行编辑器预览的疑问

### ISSUE THREAD

**Issue by owenzhao** [oulvhai/MWeb-issues#998]
我用MWeb的主要目的，就是通过它编辑Markdown文本，然后生成网页并上传到我自己的网站。

之前在2的时候，我修改好一个网站的模版，就可以在预览中直接预览到对应的外观，这是很方便的。

但是在3中，网站的模版，是不能在编辑器中预览的，只能生成本地网站再预览。这变麻烦了。如果想本地预览，就必须再制作一个单页的模版。

且不说我会不会把网站模版，变成一个单页的。（其实是不会-.=||）单是需要同步维护两个类似的内容，就已经很麻烦了啊。MWeb 3是出于什么考虑才取消了这个原本很好用很方便的功能呢？

**Comment by oulvhai** [comment]
主要是这个功能非常少人用，然后会给后期的功能扩展带来麻烦，所以才简单点。 
MWeb 3 正在把一些功能简化，会减去一些非常少人用的功能和进一步优化多人用的功能。如果想要在 MWeb 预览中也使用 网站模板的样式，可以做网站模板时直接把 文档的 CSS 都下在 .markdown-body 下。这样网站模板的 CSS 就可以直接丢进自定义预览样式用了。

**Comment by owenzhao** [comment]
我的网站的主题，是基于octopress主题修改的。它的css文件是screen.css。与MWeb-Foundation-Book主题不同，后者主题是由docs.css等四个css构成。其中docs.css中，我找到了你说的.markdown-body 。

那么下面我应该如何该呢？是octopress太旧才造成的不同吗？需要等你先更新为包含.markdown-body的？

**Comment by oulvhai** [comment]
需要不需要包含 .markdown-body 是看情况，如果预览样式是由静态博客修改来的，因为中间定义样式比较多，所以可以由 .markdown-body 重新定义文章部分。否则的话， 怎么方便怎么来。
然后基于原有的 预览样式改成 .markdown-body 方式，也是非常方便。

**Comment by owenzhao** [comment]
好吧。我再请教最后一个问题就好。

我之前网站模式，可以修改代码预览的主题，因为我主要做苹果方面的开发，所以将主题选的是Xcode风格的。

网站设置是在header.html中将第29行改为
`<link href="asset/highlightjs/styles/xcode.css" media="screen, projection" rel="stylesheet" type="text/css">`

目前预览的主题已经不是这样的了，用的是PrismJS的。但是直接复制粘贴过来可以吗？我对比了一下，好像也有不一致的地方。这样就很麻烦了。有简化的步骤吗？

**Comment by oulvhai** [comment]
不会很麻烦的，你参考一下 MWeb 3.x 带的预览样式，代码高亮的 CSS 都是在最后，很容易看出来。然后直接 复制文本过去即可。 至于 asset/highlightjs/styles/xcode.css ，直接拿掉。或者你只是单单的复制到 asset/highlightjs/styles/xcode.css 这个文件也是可以。
